### ISSUE TITLE
conflicting gold paths in biosample and study

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#10]
Currently, both biosample and study include slots for the five GOLD path fields (ecosystem, ecosystem_category, ecosystem_type, ecosystem_subtype, specific_ecosystem):
- [in biosample](https://github.com/microbiomedata/nmdc-schema/blob/88ba05666f71739c7946818a92629977dd3c5682/src/schema/nmdc.yaml#L433)
- [in study](https://github.com/microbiomedata/nmdc-schema/blob/88ba05666f71739c7946818a92629977dd3c5682/src/schema/nmdc.yaml#L473)

This is an issue because it's not clear if all biosamples must have the same values as the study, if the biosample values "override" the "default" study values, etc.

It would be better to (a) have them exclusively either in study or in biosample, or (b) to name them differently so as to clarify, e.g. prefix the slots in study with "default_", "assumed_", etc.

@cmungall @dehays

**Comment by dehays** [comment]
I think they should be removed from study.  @wdduncan - I am assuming that GOLD is associating them with both and that is how we have them on both NMDC study and biosample.  With our current (very small) set of studies I believe there is probably correspondence but as soon as a study has multiple sampling events / sites this may not be true.  I am not seeing the value of keeping them on study. (Studies have samples collected from environments. )

**Comment by dehays** [comment]
@cmungall @wdduncan  If you agree - can we make this change to study slots

**Comment by wdduncan** [comment]
I agree, but perhaps we should check with Reddy and see if the GOLD paths at the study level are important?

**Comment by wdduncan** [comment]
Adding @tbkreddy to the conversation.

**Comment by TBKReddy** [comment]
Ecosytem classification paths between Study and Biosample doesn't present any conflict as such.

> This is an issue because it's not clear if all biosamples must have the same values as the study, '

No. Studies with a broad scope may have the least common denominator but individual Biosmaples will have more specific classification assigned to them. 
 
> if the biosample values "override" the "default" study values, etc.
No they don't. If there is a big study with samples from a variety of environments. The study classification may stop at a level to broadly represent all samples. 

For example this study https://gold.jgi.doe.gov/study?id=Gs0047590 shows host associated -> microbial, the top two levels. If you look at the Biosamples under this study they list individual more specific classification terms. 

> 
> It would be better to (a) have them exclusively either in study or in biosample, or (b) to name them differently so as to clarify, e.g. prefix the slots in study with "default_", "assumed_", etc.

You need to have these specifically on each Biosample to have them annotated. 
You can consider not having these at all on the study and instead rely on the values from the underlying Biosmaples to come up with a common denominator or a set of classification terms and use those either to display on the study or provide a search mechanism. If you prefer you can definitely go without having these defined on the Study.

**Comment by cmungall** [comment]
I can't speak to GOLD I see no problem with capturing environment at the level of study and sample, and with the values being consistent but different

 - There may be a study that looks at the affect of salinity of lakes on microbiome community, where individual samples vary with regards to broad class of lakes and water medium and even broader biome
 - There may be a study that looks at different soil samples across a long transect with very different soil properties along some gradient

The samples environments should be consistent with study environments (formally: the ENVO terms should be subsumed in the isa-partof graph)

There is a lot of value in capturing study environment before samples are collected. We should also capture which mixs variables are being studied. See:

https://docs.google.com/document/d/1fKv4XJ1HTm3XoS_E2NnKGCiZOpJwZnZwRcxUnNNYfiQ/edit

**Comment by wdduncan** [comment]
We have decided to keep them.

**Comment by turbomam** [comment]
@dwinston I share your concern about unconstrained relationships between the biosample and study GOLD path elements, but will defer to the guidance from @TBKReddy and @cmungall
