### ISSUE TITLE
Add RNA library permissible values to `LibraryTypeEnum` for `LibraryPreparation`'s `library_type` slot

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1000]
Not urgent since it is not needed for NEON but we need a slot to capture the type of RNA library since this is needed input for Class  MetatranscriptomeActivity 

Proposed slot rna_seq_type

Propose enum for range with enumerations of 
"Stranded RNA-seq, R1 is forward, R2 is reversed", "Stranded RNA-seq, R2 is forward, R1 is reversed", "non-stranded RNA-seq"

**Comment by turbomam** [comment]
OK. The permissible values for the enumeration should be very succinct, preferably a single word or something_snake_cased.

Class [PermissibleValue](https://linkml.io/linkml-model/docs/PermissibleValue/) takes most of the annotations as other LinkML meta classes

If we can find OBO foundry terms for those concepts, we should assign the term CURIEs to the `meaning` slot.

**Comment by mslarae13** [comment]
Low priority. Mark can add this enum. Will need review. 
If not completed next sprint will not be included in berk roll out.

**Comment by turbomam** [comment]
@aclum I just rewrote your title, but then thought that maybe I don't really know what you want.

Can we just add permissible values to the existing `LibraryTypeEnum`, or do you really feel like a new slot is required? I see that you are suggesting a new slot called `rna_seq_type`. Does that mean that you would want to have something liek this?

**Comment by aclum** [comment]
I would prefer this as a separate slot since we may not have this information or we'll have to infer it from a combination of institution+processing date.

**Comment by aclum** [comment]
@turbomam  do you have time work on this ticket this sprint?

**Comment by mslarae13** [comment]
re-iding needs to re-process metaT data. File type enum for metaT isn't sorted out.
Adding support for metaT allowed in soft freeze. 
TBD, specific to 1 data type, so impacts shouldn't be huge.

**Comment by aclum** [comment]
@turbomam  do you have time to work on this next sprint?

**Comment by aclum** [comment]
Options for permissible values if the library is stranded:
[Sense Orientation](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C63550)
[Antisense Orientation] (https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C63551)

Is NCIT an acceptable ontology?

I couldn't find ontology terms but the literature seems to just use 'non-stranded'.

Library preparation references:
 https://www.azenta.com/blog/stranded-versus-non-stranded-rna-seq
 https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1876-7

**Comment by aclum** [comment]
@turbomam  let me know which modeling of example data you prefer and/or other suggestions.
https://github.com/microbiomedata/nmdc-schema/pull/2113
