### ISSUE TITLE
AnalysisTypeEnum missing permissible values for NEON

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#1006]
There are some additional analysis types recorded in the NEON study - ’marker gene’ and ’marker gene and metagenomics’

These values are currently not allowed as per all the permissible values enumerated in the [AnalysisTypeEnum](https://microbiomedata.github.io/nmdc-schema/AnalysisTypeEnum/). This needs to be modified if we're going to capture sequenceAnalysisType for all the biosamples from NEON.

**Comment by aclum** [comment]
@sujaypatil96 this information should come from mms_metagenomeSequencing, all these records are of type 'metagenomics', not the mms_metagenomeDnaExtraction
