### ISSUE TITLE
Add type on class `PlannedProcess`

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#1027]
Children of class [PlannedProcess](https://microbiomedata.github.io/nmdc-schema/PlannedProcess/) (Pooling, Extraction, LibraryPreparation) are being used extensively in the NEON metadata ingest pipeline to create instances of above mentioned processes.

It is useful to know the _type_ of instances being created, like how we indicate for _Biosamples_ that they are of type `nmdc:Biosample`. Similarly, it is useful to annotate instances of PlannedProcess objects (and their children) with type as well. For example, Pooling process instances will have type `nmdc:Pooling`, Extraction process instances will be of type `nmdc:Extraction` and so forth. This is useful redundancy to have, because it helps while writing queries against the database.

So we are requesting a modeling change where you assert the slot [type](https://microbiomedata.github.io/nmdc-schema/type/) on PlannedProcess, which will carry over into its child classes as well.

**Comment by turbomam** [comment]
OK. What should the range be? There are type values in the data already that are nmdc-schema class URIs, enumerate values, or free text string. My preference is for an enumeration in this case, but maybe we can make stub classes in the future.

**Comment by sujaypatil96** [comment]
Related to #1030

**Comment by kheal** [comment]
`type` is now a slot on `NamedThing` which is the parent class of `PlannedProcess` on Berkeley fork.
