### ISSUE TITLE
make schema MORE modular

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1028]
I have a PR for making the schema less modular: only nmdc.yaml and the imported mixs.yaml

In this case, I am mainly breaking out the Biosample class out into its own module. That required some modification to other files, too, like moving some classes tho core.yaml and some slots to basic_slots.yaml.

**Comment by mslarae13** [comment]
@turbomam is this issue still relevant? 

I see you had a PR and closed it. I am currently looking through issues to see if anything already exists about adding clarity & documentation on when slots or classes belong in nmdc.yaml vs basic_slots vs core vs the user facility .yaml files.

Came across this one. Seems similar?

**Comment by kheal** [comment]
Duplicated issue with https://github.com/microbiomedata/nmdc-schema/issues/1769 .  Closing this issue in favor of more fully fleshed out issue (not to suggest it had been addressed).

**Comment by mslarae13** [comment]
@kheal FYI, next to the close button, there's a drop down arrow & has the option to chance Close as not planned which includes duplicated :)
