### ISSUE TITLE
change sample_mass to input_mass

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1031]
Per the metadata meeting last week add slot `sample_mass` to Class ProcessedSample

cc @mslarae13 @brynnz22 @bmeluch

**Comment by mslarae13** [comment]
Question.. ProcessedSample ... could that use Class: MaterialSamplingActivity

slot 'amount_collected' ?

**Comment by aclum** [comment]
Seems reasonable to me

**Comment by brynnz22** [comment]
@aclum @mslarae13 remind me, are we also removing `sample_mass` from the Extraction class? So this would require:

- [ ] TBD - removing `sample_mass` from `Extraction` class
- [ ] Adding `sample_mass` to `ProcessedSample` class
- [ ] Changing the range of `sample_mass` to `MaterialSamplingActivity`. It looks like the `sample_mass` slot is only currently being used in the `Extraction` class, so this should not impact any existing data.

**Comment by aclum** [comment]
I thought we'd decided to leave sample_mass on class extraction. This will impact existing metadata. @sujaypatil96  is using this slot for the NEON samples and i dont want to change things at this point w/ESA deadlines so this would require a subsequent data migration

**Comment by brynnz22** [comment]
So are we also adding `sample_mass` to `ProcessedSample`? Not moving it from `Extraction`?

**Comment by mslarae13** [comment]
Don't remove sample_mass. We can add it to other classes.

Changing it would require a data migration. 

Mark - sample_mass in a process class like extraction isn't ideal. Why?
- input_mass is more appropriate as it's a process.... 
- **Decision:** remove sample_mass from Class Extraction & make it input_mass / mass_extracted (sample_mass is unclear if it was consumed or generated)
- OR ~~Mass would be on the MaterialEntity that is the input for a Class Extraction~~

We just made this slot (sample_mass) for Class Extraction  

- [ ] Schema update, schema sync, API update
- [ ] Update NEON assets mapping
- [ ] New slot mass_extracted (Montana to do: look for ontology & complete template for adding a new slot
- [ ] Evaluate addition to parent classes

**Comment by mslarae13** [comment]
No good ontology term that I can find. Lots of terms that meet our definition requirements but nothing with a good process tree.

I suggest ...
slot name: sample mass used
slot : input_mass
description: Total mass of sample used in activity
alias:
-https://www.ebi.ac.uk/ols4/ontologies/ms/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000004  

- https://www.ebi.ac.uk/ols4/ontologies/afo/classes/http%253A%252F%252Fpurl.allotrope.org%252Fontologies%252Fresult%2523AFR_0001982 

required = F
structure = value unit

**Comment by aclum** [comment]
That is fine with me

**Comment by brynnz22** [comment]
Great. It looks like we can use `input_mass` for processes and something like `samp_size` for material entities, which already exists in the schema. We can always add `samp_size` to `ProceessedSample` in the future if we need to.
