### ISSUE TITLE
"21T Agilent" appears twice in Instrument Name search on Data Portal aka `instrument_name` from schema

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1033]
![Screen Shot 2023-03-30 at 12 14 16 PM](https://user-images.githubusercontent.com/44581429/228940390-da0fd24f-07ee-4041-8250-d6763e6b3d85.png)

Why is 21T there twice? Is there a difference? It is confusing having it there twice

Criteri for completion
- [x] Determine what/why there's two 21T 
- [ ] Reconcile them if they're the same, elaborate/add clarification if they are different

**Comment by turbomam** [comment]
```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select 
?o (count(?s) as ?count)
where { 
	?s nmdc:instrument_name ?o .
}
group by ?o
order by ?o
```

| ?o                      | ?count |
|-------------------------|-------:|
| 12T_FTICR_B             | 1649   |
| 15T_FTICR               | 30     |
| 21T Agilent             | 50     |
| 21T_Agilent             | 414    |
| Agilent_GC_MS_01        | 34     |
| Illumina HiSeq          | 81     |
| Illumina HiSeq 2500     | 1      |
| Illumina HiSeq 2500-1TB | 45     |
| Illumina NextSeq550     | 1392   |
| Illumina NovaSeq        | 140    |
| Illumina NovaSeq S4     | 1089   |
| QExactHF03              | 19     |
| QExactP02               | 33     |
| VOrbiETD04              | 154    |

**Comment by kheal** [comment]
This has been resolved on Berkeley fork with the use of the Instrument class.  `instrument_name` is no longer a valid slot
