### ISSUE TITLE
all classes should have a required type-designating slot, with range CURIe and `designates_type` = True

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1048]
make these assertions as high in the class hierarchy as possible

**Comment by turbomam** [comment]
may need to restructure hierarchy

**Comment by turbomam** [comment]
also review any nmdc-schema (not MIxs) slots whose name includes the word 'type'

**Comment by turbomam** [comment]
This may decrease the number of `..._set` slots required for class `Database` and therefore the number of MongoDB collections.

But that would require a review of code that infers the type of something based on the collection that it came from.

**Comment by aclum** [comment]
overlap with  #1030

**Comment by mslarae13** [comment]
@turbomam  is this still in progress or is it done?

**Comment by mslarae13** [comment]
@turbomam status update?

**Comment by turbomam** [comment]
> @turbomam status update?

It's merged into the main branch of berkeley-schema-fy24
