### ISSUE TITLE
Update database migration script for schema releases

### ISSUE THREAD

**Issue by Shalsh23** [microbiomedata/nmdc-schema#1059]
Old procedural/imperative migration script is [here](https://github.com/microbiomedata/nmdc-schema/blob/main/nmdc_schema/mongodb_direct_to_nmdc_Database_file.py ). This is triggered by `make dump-validate-report-mongodb` from `project.Makefile`.

We want something more declarative with actions that are specific to version N to N+1 migrations.

**Comment by turbomam** [comment]
DO you want me to walk you through this, so we can add it to the documentation?

**Comment by eecavanna** [comment]
Closing because we no longer use that `mongodb_direct_to_nmdc_Database_file.py` file (also, it doesn't exist in the `nmdc-schema` repo anymore).
