### ISSUE TITLE
add DMP ID to reference data management plan

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#108]
Need to add capability for the schema to reference a data management plan (DMP). Ways I can see to do this:

1. Use a simple slot (e.g., `data management plan doi`) to reference the DMP document.
2. Create a `data management plan` attribute and `data management plan value` class. The `data management value` class would reuse the `doi` slot (already existing). 

I have slight preference for (2) b/c it allows for more information to be easily attached the `data management plan value`.

cc @dehays @cmungall @emileyfadrosh

**Comment by emileyfadrosh** [comment]
Great, thank you @wdduncan. I do not have a preference for either option, and this can be considered medium- to lower-priority compared to other tasks as I do not anticipate research teams submitting data management plans until we ramp up the engagement activities (October). Hope that helps and thanks for adding this in. 

@mar-rudolph FYI ^

**Comment by mar-rudolph** [comment]
@wdduncan Do these options take into account the possibility of a [DMP ID](https://github.com/CDLUC3/dmptool/wiki/DMP-IDs-and-Networked-Data-Management-Plans-(maDMPs))? We are hoping to have all DMPs in the portal be associated the with a DMP ID

**Comment by wdduncan** [comment]
@mar-rudolph Is the `DMP-ID` different than the `doi`? If so and capturing it is important, then I should create an object to hold DMPs (i.e., proposal (2) above).

**Comment by mar-rudolph** [comment]
@wdduncan They are the same thing. Here's an [example](https://dmphub.cdlib.org/dmps/doi:10.48321/D17G67) and here's a [presentation](https://docs.google.com/presentation/d/1NrnFn3feMloZpHsugeamW8RlZJyqaLiTMeqolTGgKU4/edit#slide=id.p4) that talks about the DMP ID that might be helpful.

**Comment by wdduncan** [comment]
Are you wanting to search DMPs using the `data management plan doi` field or `DMP ID` field?

**Comment by mar-rudolph** [comment]
Let's do DMP ID since that's CDL's terminology and will be the primary minter of those IDs

**Comment by wdduncan** [comment]
Thanks. Can you work with Set or Emily to determine which sprint this needs to be implemented in?

**Comment by mar-rudolph** [comment]
Yes, no problem! I'm setting up a discussion between Maria (DMPTool admin who has created these IDs), Mark, and I. Would it be useful to include you?

**Comment by wdduncan** [comment]
Yes. You can include me :)

**Comment by aclum** [comment]
@emileyfadrosh  is this still needed?

**Comment by emileyfadrosh** [comment]
I would be nice, how hard is it?

**Comment by aclum** [comment]
This may not be too difficult with @brynnz22  remodeling of dois. @lamccue  @mslarae13  Can you discuss this at the next study page refresh meeting?

**Comment by lamccue** [comment]
I don't understand the purpose or use case?

**Comment by emileyfadrosh** [comment]
The original plan was to support adding data management plan DOIs from users who have DOIs for their DMPs. Marisa had provided the rationale and details here: https://microbiomedata.org/data-management/ 

While most projects we are dealing with do not have DMP DOIs, we do have the Island Microbiome project from the GSC where the team created this DMP: https://doi.org/10.48321/D1Z60Q. Since we are planning to support this project, I think it would be important to include this as a new slot associated with a study. Please let me know if you need additional information and happy to discuss at the next schema meeting.

**Comment by brynnz22** [comment]
Yes, this sounds pretty easy to implement. We can add a `data management plan` enumeration to `doi_cateogry`.

**Comment by mslarae13** [comment]
We'll do it. Add to next Sprint for @brynnz22

**Comment by brynnz22** [comment]
`data_managment_plan_doi` has been added as a `permissible_value` for `DoiCategoryEnum`. I also added `gsc` as a `permissible_value` for `DoiProviderEnum`.
