### ISSUE TITLE
Update valid examples in submission portal for water content

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1083]
During the nmdc workshop today we found that people entering water content there is a bug where not all of the example data works.

Values that end in percentage (75%  or 75 %) do not validate, values that end in text (0.75 g water/g dry soil) does validate.

<img width="1551" alt="Screenshot 2023-08-24 at 9 01 29 AM" src="https://github.com/microbiomedata/submission-schema/assets/8196591/1dd7c3cd-a814-4b72-be04-14d85ce4ae69">

**Comment by aclum** [comment]
I moved this ticket from a submission-schema issue  to a nmdc-schema issue since the help menu in submission schema is is being pulled from nmdc-schema so we need to update at the source.

**Comment by aclum** [comment]
@turbomam I need some help figuring out what happened here. I made a pull request (https://github.com/microbiomedata/nmdc-schema/pull/1084) which was approved and not merged and when I check the current nmdc-schema documentation (v7.8.0) all of the examples, both valid and invalid, for water content are gone
https://microbiomedata.github.io/nmdc-schema/water_content/

cc @mslarae13 @pkalita-lbl 

![Image](https://github.com/microbiomedata/nmdc-schema/assets/8196591/a3ae001a-6ca2-4de7-b2c7-fa55f8c14f7e)

**Comment by mslarae13** [comment]
Should examples be at global or specific biosample? If it's at  specific biosample type, it'll have to go in the submission schema.

**Comment by aclum** [comment]
@mslarae13 are there any biosample types where specifying just a percent is valid? That is what was removed as examples of valid data.

**Comment by mslarae13** [comment]
Where just a percent is valid as in no other way to measure moisture? I doubt it, but I can't say I'm 100% sure on that as I'm not an expert on the other sample types.

That said, if I'm understanding your message, yes, the #% should be removed.

**Comment by aclum** [comment]
Okay, so we'll leave this as a change in nmdc-schema for now and make changes as needed if it comes up again.

**Comment by turbomam** [comment]
has the work for this issue been completed?

**Comment by mslarae13** [comment]
Yes, just need to update subport prod. Whick @pkalita-lbl  is aware of.

**Comment by mslarae13** [comment]
@pkalita-lbl  I feel like we have done an update to the submission portal since this issue was 'resolved' but it looks like they are still invalid?

**Comment by pkalita-lbl** [comment]
It's entirely possible that although several `nmdc-server` updates have been deployed, none of those updates incremented the `submission-schema` dependency. I will figure out what the situation is and what needs to be done next week.

**Comment by pkalita-lbl** [comment]
It looks like the necessary changes were made in `nmdc-schema`. However, `submission-schema` unnecessarily overrides the `water_content` examples back to the old, incorrect ones. Task for myself to remove the override: https://github.com/microbiomedata/issues/issues/541
