### ISSUE TITLE
Update Study class to allow for Consortia

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1097]
For the study refresh squad, we need to update the Study class to allow for consortia. After discussion with @mslarae13 and @lamccue, we decided to try:

- [ ] ~Changing the name of the `Study` class to `ResearchIniative`~
- [x] Add a slot called something along the lines of `study_category` with `enums` of `research_study` and `consortium`
- [x] Add the slot `part_of` to the Study class to take an identifier of another study or consortium to connect a child study/consortium to a parent study/consortium
- [x] Update the description of study to account for consortium
- [x] Create study_set sample data yaml file(s) to test this.
- [ ] ~Change references to `Study` class in NMDC repo with `ResearchInitiatve`~
- [ ] ~Change `Database` slot `study_set` to `research_initiative_set`~
- [ ] ~Do we change the slot `study_image` to `initiative_image`?~

**Comment by brynnz22** [comment]
Waiting to change `study_set` slot to `research_initiative_slot` along with changing the rest of the study references until we decide to go this route.

**Comment by turbomam** [comment]
@brynnz22 if the stuck-though list items in the first comment on this thread are in a "won't do" status, then maybe you could close this issue!

**Comment by brynnz22** [comment]
It looks like it already is closed? I wonder why it popped up.
