### ISSUE TITLE
conflicting principal_investigator_name

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#11]
`principal_investigator_name` is a slot in both [Study](https://github.com/microbiomedata/nmdc-schema/blob/eb0da4efe9b9796b3677ac5e776e767d81ad66b0/src/schema/nmdc.yaml#L478) and [OmicsProcessing](https://github.com/microbiomedata/nmdc-schema/blob/eb0da4efe9b9796b3677ac5e776e767d81ad66b0/src/schema/nmdc.yaml#L519).

The issue is similar to #10: must an omics processing's PI be the same as for the study? Does one "override" the other in a given context? Again, it would be better to (a) have it exclusively either in study or in omics processing (I'm guessing study makes more sense), or (b) to name them differently so as to clarify, e.g. "study PI" vs "processing PI".

@dehays @cmungall

**Comment by dehays** [comment]
I noticed this yesterday - I think we should remove principle_investigator_name from omics_processing.  As you (@dwinston ) point out - there would be value if they could ever be different, but I do not believe that we need to handle that case now. In NMDC for now, studies have PIs and omics_processing are part of studies.  Supporting multiple level of PIs seems YAGNI

FYI - I think this might be coming from JGI's Integrated Tracking System - where there is a proposal PI and potentially set of Co PIs.  Then there is a Sequencing Project PI which is usually the same, but could potentially be different (sometimes happens on larger proposals).

**Comment by dwinston** [comment]
Great. See #16. Yeah, I think we could always add e.g. a multivalued `investigators` slot (non-exclusive to "principal" investigators) to classes like `omics processing`.

**Comment by wdduncan** [comment]
Adding @tbkreddy to the conversation.

**Comment by wdduncan** [comment]
On the call today, we decided to retain both.
