### ISSUE TITLE
Identify what slots should be locked/ un-editable

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1107]
For / from JGI. Updates to NMDC submission schema

**Comment by mslarae13** [comment]
**Slots to lock**
dna_seq_project
rna_seq_project
dna_samp_id
rna_samp_id
rna_seq_project_pi
dna_seq_project_pi
dna_project_contact
rna_project_contact
proposal_rna
proposal_dna
rna_seq_project_name
dna_seq_project_name


**To do: Check if this is the sample name users send to JGI PM to get the excel file & the project & sample ID**
rna_seq_project_name
dna_seq_project_name

**Comment by mslarae13** [comment]
@pkalita-lbl  does the 'lock these slots' happen in the NMDC schema, or submission-schema?

**Comment by pkalita-lbl** [comment]
If it's in any schema it would be in `submission-schema` but I'm not even totally convinced yet that encoding it in the schema (as opposed to a custom code in the submission portal) is the right way to go.

**Comment by mslarae13** [comment]
@pkalita-lbl  with the splitting of the RNA and DNA interface, can we update these slots to just be seq_project_name and remove the DNA/RNA designation.. since now the same slot can appear in the different interfaces. Do we need to worry about how the information entered is captured in the database?

So, Sample 1 = DNA_1 & RNA_1 .. both DNA and RNA have a seq_project_name ...

**Comment by mslarae13** [comment]
container type should not be locked and needs to be completed via the metadata

**Comment by mslarae13** [comment]
closing this issue, but would still appreciate a response from @pkalita-lbl on my previous comment

**Comment by pkalita-lbl** [comment]
We can't drop the `dna_` or `rna_` prefixes from the slot names because ultimately they trace back to the `Biosample` class in the main schema (not sure if that's going to change in upcoming schema refactoring or not). We can change the slot titles though so that it reads, for example, "Seq project ID" instead of "DNA seq project ID" or "RNA seq project ID" in the interface if you think that's more clear. But the underlying slot name will remain the same.

**Comment by mslarae13** [comment]
@pkalita-lbl yes, now. Technically the dna name is the processed sample. And we should fix how the submission schema elements map back to the more complex main-schema.
