### ISSUE TITLE
Expand NMDC to support GLBRC

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1110]
In working with Adina, it's been identified that there are some data as metadata slots that should be added to the NMDC schema to support this project. 

Some of the slots below are already in NMDC schema, but aren't in the plant-associated package? need to confirm

_In NMDC, add alias_
- [x] Wind_Speed_Mean
- atmospheric_data = Measurement of atmospheric data; can include multiple data (example give, wind speed;9 knots
- wind_speed =Speed of wind measured at the time of sampling
- [x] Wind_Direction_Mean (wind_direction)
- Wind direction is the direction from which a wind originates
- north or west, not specific direction
- [ ] Solar_Radiation (?)
-   solar_irradiance = The amount of solar energy that arrives at a specific area of a surface during a specific time interval
    title (kilowatts per square meter per day, ergs per square centimeter per second)
- [ ] Air_temp_mean (season_temp or annual_temp)
- Or average of the day? A: yes, day of sampling
- [ ] RH 
- humidity = Amount of water vapour in the air, at the time of sampling
- [ ] AH (abs_air_humidity)
- abs_air_humidity = Actual mass of water vapor - mh20 - present in the air water vapor mixture (gram per gram, kilogram per kilogram, kilogram, pound)
- [ ] nitrogen_percent
- % of ?... Specific form?
- [ ] carbon_percent
- % of ?... Specific form?
- [ ] carbon_per_nitrogen
- Is this microbial biomass? C:N ratio?
- [ ] mass_per_leaf_g (host_dry_mass)
- unclear?
- [ ] PAR = photosynthetic active radiation (photon_flux)
- description needed
- [ ] barometric_pressure, Air_Pressure
- of the day of sampling? A: yes
- barometric_pressure = Force per unit area exerted against a surface by the weight of air above that surface
- [ ] height_mean_cm (host_height)?
- Is this height of the plant? A: average height of plants in the plot

_In NMDC, but measurement was on the SOIL. NOT Plant_
- [ ] pH
- [ ] P_ppm (tot_phosp)
- Is this total P? A: total P, Bray-Kurtz-P1 phosphorous in plant-associated bulk soil
- [ ] K_ppm (potassium)
- Is this total K? A: total K, Ammonium acetate extractable potassium in plant-associated bulk soil
- [ ] Ca_ppm (calcium)
- Is this total Ca? A: total Ca, Ammonium acetate extractable calcium in plant-associated bulk soil
- [ ] Mg_ppm (magnesium)
- Is this total Mg? A: total Mg, Ammonium acetate extractable magnesium in plant-associated bulk soil
- [ ] organic_matter   (org_matter)
- Total organic matter? How is this measured? A: Loss on ignition method, unit is % (combustion)
- [ ] NO3N_ppm   (nitrate)
- total nitrate? Or total nitrate N? A: Total soil nitrate-nitrogen (e.g. the nitrogen portion of total nitrate in a sample) , LaChat method. Measured in plant-associated bulk soil
- [ ] NH4_ppm  (ammonium)
- total ammonium? total ammonium N? A: Total soil ammonium-nitrogen (e.g. the nitrogen portion of total ammonium in a sample), LaChat method. Measured in plant-associated bulk soil
- [ ] soil_moisture_percent ( water_content?)
- Are these soil or plants? A: soil
- [ ] soil_temp_10cm
- Temperature of the soil at 10cm depth on the day of sampling? A: yes

_not in NMDC schema_
- [x] #1221
- [x] #1222
- mg dry mass / total mass
- leaf dry matter content. Ontology term? 
- [x] #1216
- of the day of sampling? A: yes
- [x] #1219
- of the day of sampling? A: yes
- [ ] precipitation   (annual_precpt or   season_precpt)
- precip on the day of sampling. Need a specific slot

_Terms that will be added to Biosample, but should discuss putting on Site_

- [ ] Agronomic logs and phenology terms need to be at the site level. Some terms added to the plants should be modeled to the site - pending schema refactoring.
- [ ] precipitation   (annual_precpt or   season_precpt)
- [ ] Wind_Speed_Mean
- [ ] Wind_Direction_Mean (wind_direction)
- [ ] Solar_Radiation (?)
- [ ] Air_temp_mean (season_temp or annual_temp)
- [ ] RH 
- [ ] AH (abs_air_humidity)

**phenotypic evaluation of plants?**
- [ ] date_phenology_assessed
- ?
- [ ] phenology_emergence
- ? true/false?
- [ ] phenology_leaves_full_size
- ? true/false?
- [ ] phenology_herbivore_damage
- ? true/false?
- [ ] phenology_open_flowers
- ? true/false?
- [ ] phenology_ripe_seeds
- ? true/false?
- [ ] phenology_leaf_wilting
- ? true/false?
- [ ] phenology_canopy_closed
- ? true/false?
- [ ] phenology_senescence
- ? true/false?
- [ ] phenology_full_leaf_loss
- ? true/false?

**Comment by mslarae13** [comment]
@turbomam misx.yaml has no separation of what environmental extension are associated with which slots, correct?

That's only done at the submissions schema, correct?

**Comment by turbomam** [comment]
Well, there are a couple of mixs.yaml files. [The one in the nmdc-schema repo](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml) does not make that connection. It's just a collection of terms, which are associated with the monolithic [Biosample](https://microbiomedata.github.io/nmdc-schema/Biosample/) class and the [OmicsProcessing](https://microbiomedata.github.io/nmdc-schema/OmicsProcessing/) class in nmdc.yaml.

But the [previous collection of MIxS YAML file**s** does](https://github.com/GenomicsStandardsConsortium/mixs/blob/8062dac79dc9cb11f875266258044dc75675331b/model/schema/soil.yaml#L15)

And so does the [6.2 release candidate](https://github.com/GenomicsStandardsConsortium/mixs6.2_release_candidate/blob/f42c84f417bfdb9779e5dfbfd5d38c5ab5782864/generated-schema/mixs_6_2_rc.yaml#L24024)

But you'll see that those two LinkML versions do it in slightly different ways. We could make all of that more transparent if necessary.

**Comment by turbomam** [comment]
And yes, the [submission schema does it too](https://github.com/microbiomedata/submission-schema/blob/29f7b27249af7af618b60386a87341310e99e4a1/src/nmdc_submission_schema/schema/nmdc_submission_schema.yaml#L38852).

**Comment by mslarae13** [comment]
@turbomam 
why are some descriptions in ' X ' but some aren't? 
see tot_phosp

**Comment by mslarae13** [comment]
> why are some descriptions in single quotes but some aren't?

If a phrase has a : in it, Mark writes it in single quotes because : can get messed up.

Need to decide when are single quotes required? Should we just use them all the time? Putting single quotes around is the safer action.

**Comment by bmeluch** [comment]
Checked the descriptions of all the "In NMDC schema, add to plant-associated" terms for sample type exclusivity. Only "tot_nitro" would exclude plants: 

`name: tot_nitro
...
description: 'Total nitrogen concentration of water samples, calculated by: total
  nitrogen = total dissolved nitrogen + particulate nitrogen. Can also be measured
  without filtering, reported as nitrogen'
...
domain_of:
- HydrocarbonResourcesCores
- HydrocarbonResourcesFluidsSwabs
- WastewaterSludge
- Water`

**Comment by turbomam** [comment]
@bmeluch @mslarae13 and friends:
how would you feel about 
- starting a new schema module for this
- attaching the new slots to a new class, like `GlbrcSample`

We could continue to use `GlbrcSample` as a mixin, or migrate the slots onto `Biosample`. But I hope our efforts in December will leave us with a smaller, more modular `Biosample` overall.

**Comment by mslarae13** [comment]
@turbomam  are you suggesting a GLBRC yaml file that NMDC schema references for these? Like we do with [MIXS](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml) and [EMSL](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/portal/emsl.yaml) and [JGI](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/portal/jgi_metagenomics.yaml)

**Comment by mslarae13** [comment]
@turbomam  how would you like alias' added to existing slots? They don't need to be curies, right? But I want to be able to attribute that this is what this term is called in GLBRC.

**Comment by turbomam** [comment]
Yes, I am _suggesting_ that strategy. In the cases you mentioned, we define slots in those separate YAML modules and then assign them to `Biosample` in nmdc.yaml.

But I have raised the general question to our team: do we want more or fewer YAML modules. At one point, @mslarae13, I think you found the multiple modules difficult to search through. Have you become more comfortable with "find-in-files" in PyCharm or some other tool? I think the PyCharm functionality can be accessed with shift-command-f. @mbthornton-lbl has confirmed that he finds the practice of separate, thematic modules helpful.

I am really concerned about the number of slots we are adding onto Biosample. @mbthornton-lbl has opened an issue to propose a refactoring. I don't know if we can or should work on that before, during or after our December meeting in Berkeley.

**Comment by turbomam** [comment]
Aliases can be assigned to a schema element with attribution with

**Comment by mslarae13** [comment]
I'm ok with separate organized files. I can figure it out. I just want to make sure we're making the right decision for the right reasons. We'll make a GLBRC yaml to capture the new slots & can merge it in depending on the decision.

**Comment by mslarae13** [comment]
Will the BRCs capture this information consistently? Are these slots specific to this study?

**Comment by mslarae13** [comment]
For now, pull in the submission and pause on mapping & additional/ new metadata fields until we meet. 
Ingest the mapped metadata & skip schema mapping for now until . Provide a spreadsheet with a column for the GLBRC term and the schema term.

**Comment by aclum** [comment]
Can this be closed?

**Comment by mslarae13** [comment]
@aclum I think you were right to close this one. In short, it was determined that BRCs aren't consistent so adding mapping for every project is not best practice.
