### ISSUE TITLE
start making a list of schema element names that we want to change

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1120]
This is always a costly action because it requires coordination between the editors of the `nmdc-schema` and possibly the `submision-schema`; the API maintainers; the `nmdc-server` maintainers 

But if it adds a lot of clarity, let's plan a bunch to do at the same time.
- https://github.com/microbiomedata/nmdc-schema/pull/1098
- https://github.com/microbiomedata/nmdc-schema/issues/93

**Comment by kheal** [comment]
Closing this.  The particular issues raised have been closed and several additional class names have been changed in the berkeley fork.
