### ISSUE TITLE
Add gold_analysis_project_identifiers and (new) jgi_analysis_project_identifiers to WorkflowChain

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1123]
In reviewing some things for the napa compliance squad I realized there is not a generic external_identifiers slot. For example all that exists on Class: MetagenomeAssembly is insdc_assembly_identifiers. JGI/GOLD and IMG have identifiers that are a direct or broad mapping. For example, [img_identifiers](/https://microbiomedata.github.io/nmdc-schema/img_identifiers/) which are currently on Class Biosample, a more appropriate mapping is https://microbiomedata.github.io/nmdc-schema/MetagenomeAnnotationActivity/ and https://microbiomedata.github.io/nmdc-schema/MagsAnalysisActivity/

Currently the workflows team uses the GOLD analysis project identifiers (Ga*) to name the directories when Ingesting the JGI workflow data, I'd like somewhere to store this in the schema so we can link back to what GOLD identifier generated the data. Currently I have to provide a table offline that maps the gold sequencing project, listed in the omics_processing_set record as https://microbiomedata.github.io/nmdc-schema/gold_sequencing_project_identifiers/ to GOLD analysis project identifiers which currently don't have a designated slot.

**Comment by mslarae13** [comment]
Some of this should go in workflow chain

Maybe!

**Comment by mslarae13** [comment]
@mbthornton-lbl these slots are coming off Class:WorkflowExecution and will ONLY be on Class:WorkflowChain. Correct?

**Comment by mbthornton-lbl** [comment]
Correct

**Comment by aclum** [comment]
Outstanding todo is to add [mg_identifiers](https://github.com/https://microbiomedata.github.io/nmdc-schema/img_identifiers/) to MetagenomeAnnotation and MagsAnalysis

**Comment by mslarae13** [comment]
The Pr with both identifiers has been merged in.
A separate PR should be made for img_identifiers.

**Comment by aclum** [comment]
Linked PR addresses img_identifiers in WorkflowExeuction subclasses.
