### ISSUE TITLE
`MetaproteomicsAnalysisActivity` uses slot `used` with non-monotonic `range` of `Instrument`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1127]
I suspect that this is an exemplar of a broad pattern

**Comment by turbomam** [comment]
non-monotonic means that something deeper into inheritance has a rule that is more liberal than it's ancestors. 

will provide examples

**Comment by turbomam** [comment]
I think the OWL representation of the schema in the triple-store doesn't do a good job of illustrating this. Maybe the RDF representation would

But for now, Schema View traversals or linkml2sheets will be most helpful

**Comment by turbomam** [comment]
Globally, the range of https://microbiomedata.github.io/nmdc-schema/used/ is `string`

```python
from linkml_runtime import SchemaView

schema_file = "../src/schema/nmdc.yaml"

schema_view = SchemaView(schema_file)

schema_classes = schema_view.all_classes()

for ck, _ in schema_classes.items():
    induced_slots = schema_view.class_induced_slots(ck)
    for induced_slot in induced_slots:
        if induced_slot.name == 'used':
            print(f"In class {ck}, slot used has range  {induced_slot.range}")
```

- **In class MetaproteomicsAnalysisActivity, slot used has range  Instrument**
- In class Activity, slot used has range  string
- In class MagsAnalysisActivity, slot used has range  string
- In class MetabolomicsAnalysisActivity, slot used has range  string
- In class MetagenomeAnnotationActivity, slot used has range  string
- In class MetagenomeAssembly, slot used has range  string
- In class MetagenomeSequencingActivity, slot used has range  string
- In class MetatranscriptomeActivity, slot used has range  string
- In class MetatranscriptomeAnnotationActivity, slot used has range  string
- In class MetatranscriptomeAssembly, slot used has range  string
- In class NomAnalysisActivity, slot used has range  string
- In class ReadBasedTaxonomyAnalysisActivity, slot used has range  string
- In class ReadQcAnalysisActivity, slot used has range  string
- In class WorkflowExecutionActivity, slot used has range  string

**Comment by turbomam** [comment]
Only `NomAnalysisActivity` and `MetabolomicsAnalysisActivity` have used `used` in the data so far, and they have adhered to the string range.

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select
?t (count(?s) as ?scount)
where {
    ?s a ?t ;
       nmdc:used ?o
}
group by ?t
```

**Comment by turbomam** [comment]
@SamuelPurvine the "Instrument name" filter on the DataPortal is populated from the values of `instrument_name`, so that functionality won't be effected by the suggested retirement of class `Instrument` or the normalization of slot `used`

**Comment by SamuelPurvine** [comment]
Purrfect :) Yeah, I actually have no idea even where "used" is being used in the MetaproteomicsAnalysisActivity. I can't find it in our json files, so I'm not sure how it's creeping into the system, let alone having been set to instrument instead of string. I see that NOMAnalysisActivity uses "used", and it is set to what would resolve as a string (example: "21T_Agilent"), which is of course an instrument_name, but Metaproteomics isn't currently doing that... I don't think? Are there examples where Metaproteomics has a value for "used"?
