### ISSUE TITLE
Establish connection of metabolomic MaterialProcessing to metabolomic data objects

### ISSUE THREAD

**Issue by anastasiyaprymolenna** [microbiomedata/nmdc-schema#1128]
1000 soils biosamples

**Comment by anastasiyaprymolenna** [comment]
The 1000 soils data uses a microbial biomass method “Chloroform fumigation direct extraction”

**Comment by ssarrafan** [comment]
Is this still "in progress"?  I don't see any updates since September so I'm changing to backlog.

**Comment by kheal** [comment]
This is complete on Berkeley fork via the `DataGeneration` subclass of `MassSpectrometry`
