### ISSUE TITLE
Add NER routine for suggesting biome terms based on package + sample description for fao_soil_class or other mixs controlled field of relevance to NMDC

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#113]
Part of larger issue: https://github.com/microbiomedata/nmdc-metadata/issues/330

**Comment by ssarrafan** [comment]
@turbomam should this issue be closed, moved to the backlog or moved to the October sprint?

**Comment by turbomam** [comment]
I would say move to October. This approach would really enrich sample metadata, and I can do it. I just haven't gotten to it yet.

**Comment by ssarrafan** [comment]
@turbomam should this issue be closed, moved to the backlog or moved to the November sprint?

**Comment by turbomam** [comment]
move to November sprint please

**Comment by ssarrafan** [comment]
@emileyfadrosh @turbomam would you prefer if I move this to December or to the backlog?

**Comment by ssarrafan** [comment]
Moving this to the December sprint based on the lower priority discussed at the mid-sprint review.

**Comment by turbomam** [comment]
I won't be able to work on this before GSP

**Comment by ssarrafan** [comment]
> 

Thanks for the update @turbomam.  I can move it to March for now.

**Comment by ssarrafan** [comment]
@turbomam said to continue this for April

**Comment by turbomam** [comment]
I thought DataGood might get to this, but I think that's less likely now. 

I have started this related https://github.com/microbiomedata/sample-annotator/pull/65 which should be applciable to the FAO class cleanup but not necessarily the predction part.

Actually, that PR will be a general refactoring of all of my previous work on string to term lookups with BioPortal and OLS.

**Comment by turbomam** [comment]
@ssarrafan: this will not be complete in time for April 22nd release

**Comment by ssarrafan** [comment]
@turbomam will remove this from this sprint and add the backlog label. Let me know if you prefer to move this to May.

**Comment by ssarrafan** [comment]
@turbomam should this still be open in the backlog?  Or can this one be closed? 
FYI @mslarae13

**Comment by mslarae13** [comment]
Can we get some more context on what exactly this issue was for?

What is NER?

'based on package + sample description' : what sample description?

**Comment by ssarrafan** [comment]
PR done, no updates in a year, I'm closing this issue. FYI @mslarae13 @turbomam
