### ISSUE TITLE
ongoing assessment of prefixes and expansions

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1130]
For example, 

```json
      "emsl": "http://example.org/emsl_biosample_in_mongodb/",
      "emsl_biosample_uuid_like": "http://example.org/emsl_biosample_uuid_like/",
```

**Comment by turbomam** [comment]
There are some problematic prefixes in our MongoDB data. My comment above and https://github.com/microbiomedata/nmdc-schema/labels/prefix-issues in general focus on expansions that I created to account for 
- `emsl`, which is used as a prefix in the `id`s of instances from multiple different classes
- `UUID`, which is used as a prefix for many things that are mentioned by id

My arbitrary expansions are problematic, but the underlying prefixes are the root of that problem.

@mbthornton-lbl has made the case for retaining all legacy identifier values, especially in the list-type [alternative_identifiers](https://microbiomedata.github.io/nmdc-schema/external_database_identifiers/) slots. Can we get a rough sense of whether the `emsl:` and `UUID:` identifiers are really present in any linkable systems? 

I am slightly uncomfortable with the `emsl:` identifiers, because even if they are technically resolvable, we probably won't know how to resolve them, because `emsl` can only be mapped to one expansion.

I am more uncomfortable with the `UUID:` identifiers. If we assert an expansion for that prefix, then we won't ever be able to use it for anything else. Even worse, the `UUID:` identifiers currently in MongoDB aren't even real UUIDs.

Semantic prefixes are supposed to aid in understanding and finding data, and the `emls` and `UUID` prefixes don't do either of those things for our current MongoDB contents.

**Comment by aclum** [comment]
We've said previously that identifiers are not required to be resolvable so wanted to check if that is still acceptable.

**Class Biosample, emsl prefix**
example `emsl:2f71038a-5dd1-11ec-bf63-0242ac130002`
It is my understanding from the emsl folks that for Class Biosample the samples with either emsl in slot `id` or uuid in `emsl_biosample_identifiers` are only held in comment fields internally within emsl.  
Records that start with emsl that are currently populated in slot id do all appear to be valid uuids and we can update the prefix when we do the re-iding work. cc @mslarae13 
TODO- decide on case for uuid prefix
**Class Biosample, uuid prefix**
example `UUID:BLAN-CB-B-a59c1a9c-e301-4f88-aff4-cf8f072d9cbc`
The records currently in mongo prod that are in slot emsl_biosample_identifiers that have a uuid prefix that are not uuid compliant all come from a single study, 1000 soils. There are 134 records, the can be found with a search on collection biosample_set with {'part_of':'nmdc:sty-11-28tm5d36'} These are not being addressed by the re-id squad b/c slot id for these records are napa compliant. If we want to fix this as work outside of this squad we could 1) assign it a different prefix 2)work with emsl to get the ids on their end updated and then update ours.  I'll defer to you to how high a priority this should be, I think in other tickets you've documented that this requires workarounds for rdf conversion. We could do option 1 until option 2 is addressed.
**Class OmicsProcessing**
example `emsl:747997`
The emsl prefixes used in Class OmicsProcessing are meaningful and have their own field and correspond to  datafile in (EMSL Data Management System), is unique to each datafile, and is/was used to serve as the ID for a datafile in the EMSL generated workflows. It is my understanding that this is the most important external ID to retain.
**Class DataObject**
example `emsl:output_747997`
emsl prefixes used in Class DataObject are used for raw omics data, so slot has_output for Class DataObject

We could make separate schema prefix based on class (ie emsl.biosample, emsl.omics,emsl.dobj) but imo there isn't a big rush to do this as the ids are not resolvable currently and won't be anytime soon so could be done in a separate pass after the omics records and data objects are updated to napa style ids.

**Comment by turbomam** [comment]
Thanks for that very clear and informative comment, @aclum 

Yes, we did agree that CURIe identifiers in nmdc-schema data aren't required to resolve. But that doesn't mean that we shouldn't support future resolution. That's hard to do when the prefixes are very general like `emsl`. It implies that EMSL would, in the future, has a single resolver or gateway for all types of things NMDC cares about.

**Comment by turbomam** [comment]
PS MongoDB also has  `id`s that lack a prefix. I'll look for some examples. I'm not sure whether they are `id` assertions or `id` mentions.

The [migration-recursion](https://github.com/microbiomedata/nmdc-schema/blob/9e4c58099b2fe064b6b08d3e24cfaf36458cbefb/project.Makefile#L465-L471) script takes a `--salvage-prefix` argument, I I have been using `nmdc` as the value for a while. But in discussion with @brynnz22, I think we should use something else, like something obviously silly, or the [generic](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L75) prefix already, which already has an expansion in the schema.

**Comment by turbomam** [comment]
@aclum and @mslarae13 @brynnz22 

As part of #1139, [I have updated the special prefix handling](https://github.com/microbiomedata/nmdc-schema/pull/1292/files):
- "emsl:" in the data is left as-is and gets the placeholder expansion "http://example.org/emsl_in_mongodb/"
- values in the data that are supposed to be CURIes but lack a prefix are assigned the "generic:" prefix, which expands to "https://example.org/generic/". In the past, I forced the "nmdc:" prefix, but I thought that "generic:" would make it easier to spot those cases.
- During the RDF conversion only
  - "UUID:" in the data is overwritten with "emsl_uuid_like" and gets the placeholder expansion "http://example.org/emsl_uuid_like/"

**Comment by aclum** [comment]
@turbomam I request we make no changes to existing prefixes in mongo, changes to prefix expansions are okay, until after the re-iding is complete as this may impact people's re-iding code. Any legacy identifier with slot id that is a legacy identifier will get a proper id shortly. Any changes made after dumping data from mongo for RDF conversion is okay as well.

**Comment by turbomam** [comment]
@aclum I guess I have violated your reasonable request by adding "nmdc:" or "generic:" prefixes to un-prefixed legacy identifiers, and that has been fed back into MongoDB. I'm thinking about how to lessen the impact of that now. It will be easy for anything with the "generic:" prefix but harder for the other case.

@eecavanna @Shalsh23 @brynnz22 I'll need to do some brainstorming with you.

**Comment by turbomam** [comment]
After updating GraphDB with the 2023-11-06 prod MongoDB contents that were run though the migration to schema v9.0.4, I ran this SPARQL query:

```sparql
select 
distinct ?s
where {
    graph <mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017> {
        ?s ?p ?o .
    }
    filter(isuri(?s))
}
order by ?s
```

and then processed the output like this:

```shell
cat query-result.tsv | \
egrep -v 'https://w3id.org/nmdc/[a-f0-9]{32}' | \
grep -v http://example.org/emsl_in_mongodb/ | \
grep -v http://example.org/jgi/ | \
grep -v http://purl.obolibrary.org/obo/CHEBI_ | \
grep -v http://purl.obolibrary.org/obo/ENVO_ | \
grep -v http://purl.obolibrary.org/obo/FMA_ | \
grep -v http://purl.obolibrary.org/obo/NCBITaxon_ | \
grep -v http://purl.obolibrary.org/obo/PO_ | \
grep -v http://purl.obolibrary.org/obo/UBERON_ | \
grep -v https://app.geosamples.org/sample/igsn/ | \
grep -v https://bioregistry.io/gold: | \
grep -v https://example.org/generic/ | \
grep -v https://w3id.org/nmdc/bsm- | \
grep -v https://w3id.org/nmdc/dobj- | \
grep -v https://w3id.org/nmdc/extrp- | \
grep -v https://w3id.org/nmdc/frsite- | \
grep -v https://w3id.org/nmdc/libprp- | \
grep -v https://w3id.org/nmdc/omprc- | \
grep -v https://w3id.org/nmdc/poolp- | \
grep -v https://w3id.org/nmdc/procsm- | \
grep -v https://w3id.org/nmdc/sty- | \
grep -v https://w3id.org/nmdc/wfmag- | \
grep -v https://w3id.org/nmdc/wfmgan- | \
grep -v https://w3id.org/nmdc/wfmgas- | \
grep -v https://w3id.org/nmdc/wfmsa- | \
grep -v https://w3id.org/nmdc/wfnom- | \
grep -v https://w3id.org/nmdc/wfrbt- | \
grep -v https://w3id.org/nmdc/wfrqc-
```

that just returned 
> ?s

I.e. the header of the SAPRQL output.

**Comment by turbomam** [comment]
The http://example.org/emsl_in_mongodb/ URIs map to MongoDB `id`s like

- [emsl:771493](https://api.microbiomedata.org/nmdcschema/ids/emsl%3A771493)
- [emsl:output_448392](https://api.microbiomedata.org/nmdcschema/ids/emsl%3Aoutput_448392)
- [emsl:63ca517c-6647-11eb-ae93-0242ac130002](https://api.microbiomedata.org/nmdcschema/ids/emsl%3A63ca517c-6647-11eb-ae93-0242ac130002)


Including those,  all of the NMDC-assigned `id`s come from namespaces that we have all agreed on except for 

- https://w3id.org/nmdc/[a-f0-9]{32}
- https://example.org/generic/

**Comment by turbomam** [comment]
The un-prefixed `id`s that were coerced to use "generic:" in my last local migration are still in MongoDB in their un-prefixed state.

i.e. [60e6fc9e49af89de1ba8999f](https://api.microbiomedata.org/nmdcschema/ids/60e6fc9e49af89de1ba8999f) is now  [generic:60e6fc9e49af89de1ba8999f](http://3.236.215.220:7200/resource?uri=https:%2F%2Fexample.org%2Fgeneric%2F60e6fc9e49af89de1ba8999f&role=subject) in GraphDB only.

**Comment by turbomam** [comment]
That leaves `/^https://w3id.org/nmdc/[a-f0-9]{32}/$` entities like  [nmdc:fffbb7b52a4886755df429e22a152427](https://api.microbiomedata.org/nmdcschema/ids/nmdc%3Afffbb7b52a4886755df429e22a152427),  which was probably just `fffbb7b52a4886755df429e22a152427` in MongoDB before I started contributing to migrations.

**Comment by turbomam** [comment]
## Examples

- http://example.org/emsl_in_mongodb/359131
  - nmdc:84e7cc65714c446b90b5565caadc9777 nmdc:was_informed_by emsl:359131
- http://example.org/emsl_in_mongodb/output_359131
  - nmdc:84e7cc65714c446b90b5565caadc9777 nmdc:has_input emsl:output_359131
- http://example.org/emsl_uuid_like/ANZA-CB-B-6bc68e7d-7383-4bbe-9789-2f897ab426ca
  - nmdc:bsm-11-yj9yav68 nmdc:emsl_biosample_identifiers emsl_uuid_like:ANZA-CB-B-6bc68e7d-7383-4bbe-9789-2f897ab426ca
- **http://purl.obolibrary.org/obo/CHEBI_** nmdc:metabolite_quantified
- http://purl.obolibrary.org/obo/CHEBI_10072
- http://purl.obolibrary.org/obo/CHEBI_None
- https://bioregistry.io/biosample:SAMEA7723902
  - gold:Gb0240115 nmdc:insdc_biosample_identifiers https://bioregistry.io/biosample:SAMEA7723902
- https://bioregistry.io/cas:100-02-7 nmdc:alternative_identifiers
- https://bioregistry.io/doi:10.1002/ppp.2200 nmdc:doi_value
- https://bioregistry.io/gnps.task:4b848c342a4f4abc871bdf8a09a60807
  - nmdc:sty-11-r2h77870 nmdc:gnps_task_identifiers gnps.task:4b848c342a4f4abc871bdf8a09a60807
- https://bioregistry.io/gold:Gb0150237 gold:Gp0208359 | nmdc:has_input | gold:Gb0150237
  - nmdc:498a1b67f0b35bc4f059a5de7d5ddb49 nmdc:was_informed_by gold:Gp0061273
- https://bioregistry.io/img.taxon:3300006022
  - gold:Gb0115838 nmdc:alternative_identifiers https://bioregistry.io/img.taxon:3300006022
- https://bioregistry.io/jgi.proposal:507130
- https://bioregistry.io/kegg:C00009
- https://example.org/generic/None
- https://example.org/generic/nmdc_mta00292
- https://w3id.org/nmdc/001877624064be7578cec0f0ab28579e
- https://w3id.org/nmdc/dobj-11-1fkqcg08
- https://w3id.org/nmdc/e010d3fc3561dd35c12b3b9f4345099d
- https://w3id.org/nmdc/mga00098
- https://w3id.org/nmdc/sty-11-2zhqs261

**Comment by aclum** [comment]
Per a conversation with @SamuelPurvine  wrt the EMSL prefixes
the proposal is for data object alternative identifiers

emsl.dms= new prefix for emsl Data Management System identifiers, not currently resolvable to use example.org as prefix expansion
my_emsl = new prefix for resolvable raw data links from EMSL, prefix to expand to https://release.my.emsl.pnnl.gov/release_data/
'emsl' prefix for omics records would be removed in favor of emsl.dms and my_emsl links on the data_object_set records
'emsl' prefix used in biosample_set records - TBD. We could leave these for now as they'd be the only collection with this prefix which addresses some of Mark's concerns. Alternative would be to update the prefix to emsl.biosample.

@lamccue @mslarae13  please provide input. LMK if this can go on the metadata meeting agenda for this week. We'd like to at least get the prefixes for the data objects sorted out so they can be done correctly for the re-iding work.

**Comment by aclum** [comment]
new proposal 
use my_emsl, add this to the schema. 

deal with the other issues at a later time.
