### ISSUE TITLE
there are documents in MongoDB that share `id`s and therefore get collapsed in RDF

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1131]
- Activities
- DataObjects

**Comment by turbomam** [comment]
This time of re-id'ing is a great time to deal with this

**Comment by turbomam** [comment]
# Activities

_[query-result.csv](https://github.com/microbiomedata/nmdc-schema/files/12692283/query-result.csv)_

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select
distinct ?s (group_concat(distinct ?tname) as ?tnames)
where
{
    graph <mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017> {
        ?s a ?t , ?t1 , ?t2 .
        filter (?t1 != ?t2)  
        bind(strafter(str(?t), "https://w3id.org/nmdc/") as ?tname)
    }
}
group by ?s
```

**Comment by turbomam** [comment]
## OmicsProcessing

I don't see any `OmicsProcessing`s that have more than one input. Was that a pattern that we were concerned about @aclum 

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select 
?OP (count(distinct ?input) as ?input_count)
where { 
	?OP a nmdc:OmicsProcessing ;
     nmdc:has_input ?input
}
group by ?OP
order by desc(count(distinct ?input))
```

**Comment by aclum** [comment]
Yes, multiple outputs are acceptable. 
The issue we were discussing yesterday was w/ the md5sum used for data objects, so that would be duplicates in has_output of the WorkflowExecutionActivity subclasses. see https://github.com/microbiomedata/issues/issues/431

Things we need to check for are
- [ ] slot id collisions within collections (I don't think runtime API allows this so I'd expect the answer to be none)
- [ ] slot id collisions between collections, you've documented that above 
- [ ] identifier reference slots (ie part_of, was_generated_by, has_input, etc) which reference an identifier that does not exist, see https://github.com/microbiomedata/issues/issues/278

**Comment by aclum** [comment]
For WorkflowExecutionActivity subclasses that use the same id across collections, of which there are 570 ids, I think this is okay since they'll get new unique ids when we re-id.

**Comment by aclum** [comment]
For identifier reference slots (ie part_of, was_generated_by, has_input, etc) which reference an identifier that does not exist we found the following problems
- workflow execution activities that use part_of where the value doesn't exist, these will be replaced with re-iding/reprocessing
- data objects being referenced by has_input or has_output which don't exist
- Workflow execution activities with was_informed_by where the omics_processing_set_record does not exist. On the sequencing side these will be either reparied or removed, on the EMSL side Sam/Yuri will determine if records will be repaired or deleted.
- MetagenomeSequencingActivity with has_input of None.  These will be dealt with separately, see https://github.com/microbiomedata/nmdc-schema/issues/1141

**Comment by aclum** [comment]
Backlogging this issue since we have done all the checking but won't be able to confirm that everything has been resolved until QA on the re-iding process.

**Comment by aclum** [comment]
this should be resolved now, all documents should have a unique ID. @turbomam  do you have a way of confirming this with RDF?

**Comment by turbomam** [comment]
@aclum 

For

```sparql
select 
?s (count(distinct ?o) as ?count)
where { 
	?s a ?o .
    filter(isuri(?s))
    filter(isuri(?o))
}
group by ?s
order by desc(count(distinct ?o))
```

in `nmdc-graph-2024-08-20`

All instances/entities/documents only have one `rdf:type` assigned now. That's not a perfect query, due to the inconsistent use of the `type` slot in nmdc-schema (as opposed to berkeley-schema-fy24), but I believe that query was sensitive to the shared `id`s in the past.

**Comment by turbomam** [comment]
The same query, with `<https://w3id.org/nmdc/type>` as the predicate (and no `filter(isuri(?o))`), also doesn't find any instances with more than one type assignment.

**Comment by turbomam** [comment]
Same for `<https://w3id.org/nmdc/designated_class>`
