### ISSUE TITLE
The expansions of ad-hoc `emsl` prefixes erroneously imply that they are only for `Biosample`s

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1139]
> I did notice the 2558 DataObjects and 1236 OmicsProcessings that use the under-specified "emsl" prefix, 
> its a bit confusing to look at these as SPARQL query output since they are of other types. 
> Not a big priority but if you could update the prefix extension for `emsl` to something more generic it would be clearer. 
> These prefixes will stay on as alternative identifiers after the re-iding.

_Originally posted by @aclum in https://github.com/microbiomedata/nmdc-schema/issues/1117#issuecomment-1736156360_

**Comment by turbomam** [comment]
```json
"emsl": "http://example.org/emsl_biosample_in_mongodb/",
"emsl_biosample_uuid_like": "http://example.org/emsl_biosample_uuid_like/",
```

**Comment by turbomam** [comment]
@aclum  do you think I should act on this? Won't it  be moot once the Napa compliance squad is complete?

**Comment by aclum** [comment]
This will not be moot as emsl will still be used as a prefix for alternative identifier slots. However, I would like to wait until re-iding is complete so we don't have additional diversions in IDs b/w the napa mongo instance and prod mongo. We already have a divergence about the case for the gold prefix.

**Comment by mslarae13** [comment]
Please don't act on this just yet. We need to check with the EMSL NEXUS team before we go making EMSL curies... but that meeting keeps getting cancelled.. 

Also see my comment in the other issue about how to handle 'emsl:'

**Comment by turbomam** [comment]
@mslarae13 what's the other issue that we should be looking at?

**Comment by turbomam** [comment]
Sine we're taking about right an wrong here:

**Comment by aclum** [comment]
@mslarae13 to clarify we'd just have internal prefixes. We decided several months ago not to register curies on behalf of other organizations.

**Comment by mslarae13** [comment]
@aclum  @turbomam 

"internal prefixes" what does this mean? Thought they all had to be resolvable curies?

**Comment by aclum** [comment]
It is preferable but not required that curies are resolvable. We have some in the schema already that 'resolve' to example.org which is what Mark is using as a dummy prefix expansion.

**Comment by turbomam** [comment]
Have either of you ahd a chance to look through https://github.com/microbiomedata/nmdc-schema/blob/main/src/docs/prefixes_curies_ids_mappings_etc.md ?

If you think it's unclear or disagree with any of the points, please consider making a PR

**Comment by aclum** [comment]
Your md file looks mostly good to me it isn't clear what you are trying to say in section [use bioregistry, not identifiers.org, BUT](https://github.com/microbiomedata/nmdc-schema/blob/main/src/docs/prefixes_curies_ids_mappings_etc.md#use-bioregistry-not-identifiersorg-but) and the ones below seem to be just notes.

**Comment by aclum** [comment]
related to #1130
