### ISSUE TITLE
schema support for unhappy paths for OmicsProcessing

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1144]
This came up as part of NEON squad discussions.

Use case:
In the case where there are two sequencing runs that need to get analyzed together, either from a single library or two libraries of the same type, how would we populate date for those? The first run was 2017-12-12 and the second instrument run was 2018-02-13 in the example from NEON. I'd argue it is not appropriate to list 2017-12-12  as start_date and 2018-02-13 as end_date b/c the instrument doesn't run for a year, it runs for ~29 hours once on 2017-12-12, then another run of about ~29 hours again on 2018-02-13. 
Proposed solution from @turbomam:
allowing OmicsProcessing's to have parts. Each part would have a start_date  and a end_date  for a period of time time in which there aren't any prolonged downtimes. We would need to think though whether the child OPs would have their own outputs, or whether only the parent OP would have outputs.

Further discussion over zoom was to allow child OP use the has_output slot to be explicit.

Depending on how this is implemented it would require code changes to the data portal and/or workflow automation to avoid duplicate counting/analysis.

@cmungall  to weigh in on proposed solution
cc @shreddd  @mslarae13

**Comment by aclum** [comment]
@cmungall  please review and comment.

**Comment by mslarae13** [comment]
Would like to get to this!! TBD if we'll get to it

**Comment by mslarae13** [comment]
@aclum  @brynnz22 will merging the linked PR complete this?

**Comment by brynnz22** [comment]
Yes!

**Comment by mslarae13** [comment]
Alicia to review and confirm parthood is modeled in the right direction
