### ISSUE TITLE
allow https://release.my.emsl.pnnl.gov/release_data paths as `alternative_identifiers` for `DataObject`s

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1151]
see
- https://microbiomedata.github.io/nmdc-schema/DataObject/
- https://microbiomedata.github.io/nmdc-schema/alternative_identifiers/

`alternative_identifiers` has a https://microbiomedata.github.io/nmdc-schema/Uriorcurie/ range, so will require defining a prefix like

```yaml
myemsl: https://release.my.emsl.pnnl.gov/release_data/
```

**Comment by aclum** [comment]
related to #1130

**Comment by aclum** [comment]
This was implemented as "my_emsl": "https://release.my.emsl.pnnl.gov/released_data/" in the schema and is being used as a curie prefix in slot alternative_identifier on Class DataObject.
