### ISSUE TITLE
pass a mongodb filter to `nmdc_schema/mongo_dump_api_emph.py`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1160]
as called in project.Makefile as

```make
local/mongo_as_unvalidated_nmdc_database.yaml:
	date
	time $(RUN) pure-export \
```

this will be tricky... it probably won't be safe or reasonable to apply the same filter to all collections

**Comment by turbomam** [comment]
request by @aclum

**Comment by turbomam** [comment]
workaround: user manually dumps the data that they are interested in with https://api-dev.microbiomedata.org/docs#/metadata/list_from_collection_nmdcschema__collection_name__get

and the we convert the MongoDB list-oriented format to LinkML keyed format with the data harmonizer/linkml format conversion tools from submission-schema

**Comment by aclum** [comment]
@mbthornton-lbl @turbomam do we need this or can it be closed in favor of Michael's extract-study code?

**Comment by aclum** [comment]
Closing in favor of extract-study and mongo queries.
