### ISSUE TITLE
move `src/data/valid/SampleOperation_comprehensive.yaml` from `issue-907-metabolink-mergeprep`  into `src/data/uncertain`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1165]
> Additional properties are not allowed ('aliquot_list', 'analytestorage_list', 'extraction_list', 'mixing_list', 'operation_type', 'phaseseparation_list', 'reaction_list', 'subsampling_list' were unexpected) in $

@anastasiyaprymolenna @JamesTessmer

**Comment by kheal** [comment]
This branch no longer exists, closing.
