### ISSUE TITLE
get branch `issue-907-metabolink-mergeprep` to build

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1166]
Pull requests must always be left in a state where the build process works.

I guess there is an exception: if the person who last edited the branch gets stuck, it's OK to push a branch that has one failure point, as along as other contributors are alerted.

Ideally feature branches like `issue-907-metabolink-mergeprep` should stay current with `main`, especially after a release (like 8.0.0)

- [x] #1163 
- [x] #1164
- [x] #1165

**Comment by turbomam** [comment]
build works up until example running now

```shell
poetry run linkml-run-examples \
        --schema project/nmdc_schema_generated.yaml \
        --input-directory src/data/valid \
        --counter-example-input-directory src/data/invalid \
        --output-directory examples/output > examples/output/README.md
```

**Comment by turbomam** [comment]
> ValueError: Example src/data/valid/SampleOperation_filter_clean_up.yaml failed validation:
> Additional properties are not allowed ('aliquot_list', 'analytestorage_list', 'extraction_list', 'filtration_list', 'mixing_list', 'operation_type', 'phaseseparation_list', 'subsampling_list' were unexpected) in $

**Comment by turbomam** [comment]
I will be moving all "broken" examples files into `src/data/uncertain`

**Comment by turbomam** [comment]
Wouldn't it be funny if the only problem with most of the example data files was that they weren't following the naming convention! In order to learn the convention, one has to either 
- look it up in the LinkML documentation
- follow the naming style used by the existing examples: 
  - {CLASS_NAME}-description.yaml, not {CLASS_NAME}_description.yaml

**Comment by turbomam** [comment]
trying 

```shell
mv src/data/valid/SampleOperation_OrganicMatterExtraction.yaml src/data/valid/SampleOperation-OrganicMatterExtraction.yaml
```

**Comment by kheal** [comment]
This branch no longer exists, closing.
