### ISSUE TITLE
Document the purpose and usage of the `Dockerfile`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1167]
There is a `Dockerfile` in the root folder of the repo. It contains:

```dockerfile
FROM python:3.9

ADD . /src/

RUN \
    pip install poetry && \
    cd /src && poetry install 
```

Other than in the name of that file, I don't see any occurrences to the string "`docker`" in the repo.

I recommend documenting the file somewhere in the repo.

**Comment by eecavanna** [comment]
Based on the contents of the `Dockerfile`, I think it can be used to create an environment that contains the dependencies of `nmdc-schema`. With that in mind, I'll try using the file and report back.

**Comment by eecavanna** [comment]
Here's some documentation I came up with after experimenting with the file:

---

## Development

This repository contains a `Dockerfile` you can use to run a container in which all the dependencies of `nmdc-schema` are present.

### Usage

You can build the container by issuing the following command in the root folder of the repo:

```shell
# Build a Docker image based upon the Dockerfile in the current folder.
docker build -t nmdc-schema .
```

Once the container has been built, you can run it with:

```shell
# Instantiate the Docker image as a container, mount the current folder within it,
# set the working directory inside the container to `/src`, attach your terminal
# to the container's STDIN, STDOUT, and STDERR streams, run `bash` within the
# container, and delete the container as soon as `bash` stops running.
docker run --name nmdc-schema --rm -it -v "$(pwd):/src" -w /src nmdc-schema /bin/bash
```

Alternatively, once the container has been built, you can run a specific shell command in it:

```shell
docker run --name nmdc-schema --rm -it -v "$(pwd):/src" -w /src nmdc-schema /bin/bash -c "hostname; whoami"
```

**Comment by eecavanna** [comment]
On second thought, I don't think the container contains all the dependencies of `nmdc-schema`. For example, it doesn't have `yq` installed.

Based on that new information, I think the `Dockerfile` is a remnant of an unfinished attempt to create a Docker-based development environment for `nmdc-schema`.

I want there to be a Docker-based development environment for `nmdc-schema`. I'll try adding to the `Dockerfile` with that in mind.

**Comment by eecavanna** [comment]
Here's a `Dockerfile` I wrote that installs pandoc, yq, and Apache Jena (in addition to Poetry).

```dockerfile
FROM python:3.9

WORKDIR /src

# Download and install pandoc.
RUN apt update && \
    apt install -y \
      pandoc

# Download and install yq.
# Reference: https://github.com/mikefarah/yq#install
RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

# Download and install Apache Jena.
# Reference: https://sparrowflights.blogspot.com/2012/12/how-to-install-jena-command-line-tools.html
RUN wget -P /downloads/tmp "https://dlcdn.apache.org/jena/binaries/apache-jena-4.9.0.zip"
RUN unzip /downloads/tmp/apache-jena-4.9.0.zip -d /downloads/apache-jena
ENV JENAROOT="/downloads/apache-jena/apache-jena-4.9.0"
ENV PATH="$JENAROOT/bin:$PATH"

ADD . /src/

RUN pip install poetry
RUN poetry install 

CMD ["echo", "Hello and goodbye."]
```

**Comment by turbomam** [comment]
Do you imagine that people would use the container interactively, by gaining access to it's shell? Or add more commands to the Dockerfile, like `make squeaky-clean all test validate-filtered-request-all make-rdf` ?

**Comment by turbomam** [comment]
Could we use a wrapper like this r[un.sh from the Environment Ontology](https://github.com/EnvironmentOntology/envo/blob/master/src/envo/run.sh)?

**Comment by turbomam** [comment]
And let's make sure we have an idea of the motivating use cases for running nmdc-schema code
- in a local Poetry environment, where the system's owner is responsible for installing all system dependencies
- in a [GitHub action](https://github.com/microbiomedata/nmdc-schema/tree/main/.github/workflows)
- in a Docker container

**Comment by eecavanna** [comment]
I imagine people using it either (a) interactively (via `$ docker run -it ... bash`); or (b) via `docker run ... some-command`, where they specify the single command they want to run within it.

**Comment by eecavanna** [comment]
I plan to use Docker Compose to "wrap" the volume-mounting commands and anything else that would otherwise be manually specified via `$ docker run ...`; as opposed to using a custom wrapper/shell script.

**Comment by eecavanna** [comment]
My motivation is to be able to run various `make` commands specified in the repo, without installing the repo's dependencies on my local machine. I haven't been considering GitHub Actions.

**Comment by eecavanna** [comment]
I'm also open to submitting the Dockerfile to the upstream LinkML cookie-cutter repo, but I'm not prepared to discuss that with its maintainers since I'm not familiar with the cookie-cutter repo except that it was used to create this repo.
