### ISSUE TITLE
Make target `setup` fails (file `RELEASE_NOTES_v7.7.2_to_v7.7.7.md` is missing)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1168]
When I ran `$ make setup`, it ran for several minutes, then showed an error saying a file was missing:

```shell
# (...truncated...)
INFO:root:Importing portal/mixs_inspired as portal/mixs_inspired from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing portal/jgi_metatranscriptomics as portal/jgi_metatranscriptomics from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing portal/jgi_metagenomics as portal/jgi_metagenomics from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing portal/emsl as portal/emsl from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing mixs as mixs from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing annotation as annotation from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Could not find schema.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find class.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find slot.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find enum.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find type.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find subset.md.jinja2 in src/doc-templates - falling back to default
None
git init
Reinitialized existing Git repository in /src/.git/
git add \
        *.md \
        .cruft.json \
        .github \
        .gitignore \
        CODE_OF_CONDUCT.md \
        CONTRIBUTING.md \
        LICENSE \
        MAINTAINERS.md \
        Makefile \
        README.md \
        RELEASE_NOTES_v7.7.2_to_v7.7.7.md \
        about.yaml \
        assets \
        images \
        mkdocs.yml \
        nmdc_schema \
        notebooks \
        poetry.lock \
        project.Makefile \
        project/ \
        pyproject.toml \
        src/ \
        tests \
        utils
fatal: pathspec 'RELEASE_NOTES_v7.7.2_to_v7.7.7.md' did not match any files
make: *** [Makefile:167: git-add] Error 128
```

I think the `git-add` target in the Makefile is out-of-date (see line 178 below).

https://github.com/microbiomedata/nmdc-schema/blob/03bcd93cebc5987b9694fbba1427880ed86ca8e3/Makefile#L166-L167

https://github.com/microbiomedata/nmdc-schema/blob/03bcd93cebc5987b9694fbba1427880ed86ca8e3/Makefile#L168-L177

https://github.com/microbiomedata/nmdc-schema/blob/03bcd93cebc5987b9694fbba1427880ed86ca8e3/Makefile#L178-L191

https://github.com/microbiomedata/nmdc-schema/blob/03bcd93cebc5987b9694fbba1427880ed86ca8e3/Makefile#L190-L191

**Comment by eecavanna** [comment]
I edited the `Makefile` as follows, and then re-ran `$ make setup`.

```diff
- 		RELEASE_NOTES_v7.7.2_to_v7.7.7.md \
+ 		CHANGELOG.md \
```

It failed this time, too, but with a different error message:

```shell
INFO:root:Importing mixs as mixs from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Importing annotation as annotation from source src/schema/nmdc.yaml; base_dir=src/schema
INFO:root:Could not find schema.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find class.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find slot.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find enum.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find type.md.jinja2 in src/doc-templates - falling back to default
INFO:root:Could not find subset.md.jinja2 in src/doc-templates - falling back to default
None
git init
Reinitialized existing Git repository in /src/.git/
git add \
        *.md \
        .cruft.json \
        .github \
        .gitignore \
        CODE_OF_CONDUCT.md \
        CONTRIBUTING.md \
        LICENSE \
        MAINTAINERS.md \
        Makefile \
        README.md \
        CHANGELOG.md \
        about.yaml \
        assets \
        images \
        mkdocs.yml \
        nmdc_schema \
        notebooks \
        poetry.lock \
        project.Makefile \
        project/ \
        pyproject.toml \
        src/ \
        tests \
        utils
The following paths are ignored by one of your .gitignore files:
project
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
make: *** [Makefile:167: git-add] Error 1
```

**Comment by eecavanna** [comment]
I added the `-f` flag to the `git add` command in the `Makefile`'s `git-add` target. Then, I re-ran `$ make setup`.

This time, I got this error:

```shell
git add  project/jsonldcontext  project/jsonschema  project/owl  project/python  project/rdf
fatal: pathspec 'project/jsonldcontext' did not match any files
make: *** [Makefile:168: git-add] Error 128
```

Screenshot:

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/574a0e7a-053e-4f81-aa77-83b55a6bd6a9)

**Comment by eecavanna** [comment]
I updated the `PROJECT_FOLDERS` list in the `Makefile` as follows:

```diff
- PROJECT_FOLDERS = jsonldcontext jsonschema owl python rdf
+ PROJECT_FOLDERS = jsonld jsonschema owl 
```

That's based on what I see in the file tree:
![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/3a449c1d-ee4b-4e29-907c-699eb27ad8ff)

With that in place, I re-ran `$ make setup` again.

This time, I got the following error message again (albeit for a different line than before), since the `project` folder is listed in the `.gitignore` file:

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/889d8fc2-8cc9-45e6-8069-2db8826ee772)

So, I added `-f` to this `git add` command as well.

```diff
- 	git add $(patsubst %, project/%, $(PROJECT_FOLDERS))
+	git add -f $(patsubst %, project/%, $(PROJECT_FOLDERS))
```

With that in place, I re-ran `$ make setup` again. This time, I got an error related to my Git configuration.

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/e64737e1-cb15-4d27-a1f9-f20c6eee47df)

**Comment by eecavanna** [comment]
I ran the following command to set my Git username and email address (for the Git client _within the Docker container_):

```shell
$ git config --global user.email "user@example.com" && \
  git config --global user.name "Fake name"
```

Then, I re-ran `$ make setup`. This time, it seemed to me to run without issue. 🏁 

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/bdfd2dca-2b89-4b20-8e76-c6baa756fe44)

**Comment by eecavanna** [comment]
In summary, here's a Git diff showing all the changes I made to the `Makefile` to get `$ make setup` to work:

```diff
diff --git a/Makefile b/Makefile
index c99389ddd..9d23ee8ea 100644
--- a/Makefile
+++ b/Makefile
@@ -159,12 +159,12 @@ mkd-%:
        $(MKDOCS) $*
 
 # keep these in sync between PROJECT_FOLDERS and the includes/excludes for gen-project and test-schema
-PROJECT_FOLDERS = jsonldcontext jsonschema owl python rdf
+PROJECT_FOLDERS = jsonld jsonschema owl
 git-init-add: git-init git-add git-commit git-status
 git-init:
        git init
 git-add: .cruft.json
-       git add \
+       git add -f \
                *.md \
                .cruft.json \
                .github \
@@ -175,7 +175,7 @@ git-add: .cruft.json
                MAINTAINERS.md \
                Makefile \
                README.md \
-               RELEASE_NOTES_v7.7.2_to_v7.7.7.md \
+               CHANGELOG.md \
                about.yaml \
                assets \
                images \
@@ -189,7 +189,7 @@ git-add: .cruft.json
                src/ \
                tests \
                utils
-       git add $(patsubst %, project/%, $(PROJECT_FOLDERS))
+       git add -f $(patsubst %, project/%, $(PROJECT_FOLDERS))
 
 git-commit:
        git commit -m 'Initial commit' -a
```

I also ran this set of commands:

```shell
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your name"
```

CC: @turbomam

**Comment by turbomam** [comment]
Thanks.

Let's discuss this in Monterey. 

`setup` is not intended to be run on a regular basis. That should be documented more clearly. And it doesn't mean that we should leave it in a broken state.

We inherited it from the [LinkML cookiecutter](https://github.com/linkml/linkml-project-cookiecutter), and I would like to follow that more closely, not less closely.

**Comment by turbomam** [comment]
@mbthornton-lbl pointed out that the Makefile ASCII menu encourages

**Comment by turbomam** [comment]
Actually, almost nobody should be running any of those options suggested in the Makefile `help` target

**Comment by turbomam** [comment]
Normally "we" try to avoid editing the `Makefile` because that can be updated though the cookiecutter infrastructure, but this won't be the first time it happens. Ideally we would make it easier to track the templated parts of the `Makefile` from the customized parts.

Customized targets are supposed to go in `project.Makefile`, which is `include`d into `Makefile`
