### ISSUE TITLE
Is there something called an umbrella study?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1170]
Besides the 'umbrella project' alias on `Study`, which implies that either a `research_study` or a `consortium` could reasonably be called an 'umbrella project'.

in conclusion, nothing is defined as an umbrella project, and nothing says that the differentiating factor of an umbrella project is that it has Study parts.

**Comment by brynnz22** [comment]
I think we could add this to the slot usage of the slot definition of `part_of` for the `Study` class. I think right now the definition says "parent study or consortium".

**Comment by aclum** [comment]
Is this resolved?

**Comment by mslarae13** [comment]
I think this is done. @brynnz22 can we close?

**Comment by brynnz22** [comment]
Yes I will close now.

**Comment by turbomam** [comment]
Thanks for keeping an eye on this.

So how can I find things that are umbrella studies? I'm wiling to use any search strategy over MongoDB, or in the DataPortal, or whatever.

**Comment by brynnz22** [comment]
@turbomam You would search for studies that have `part_of`. The value is the study id for an umbrella study/consortium.
