### ISSUE TITLE
Merge SubSampling and Extraction classes, with data that illustrates the relationship, into nmdc-schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1198]
Update this issue with other people who will be consulted like
Consulted:
- @mslarae13 (will attend the meeting)
- @cmungall 
- @sujaypatil96 

Add SubSampling and Extraction class activities to the schema. Update what @JamesTessmer  & @anastasiyaprymolenna  have created & address @turbomam 's concerns with the modeling.

Completion criteria:
- The 2 classes will be added 
- Valid and invalid data will be added for test. 
- Classes modeling and examples will be updated

**Comment by mslarae13** [comment]
I wish GitHub tracked WHO updated another persons comment or issue description. But @turbomam  I tried to add some more context. Does that sound good?

**Comment by turbomam** [comment]
yes thank you @mslarae13

**Comment by anastasiyaprymolenna** [comment]
@mslarae13 The slot "extractant" needs to be reviewed. Could you fill in where you are defining this from?

**Comment by mslarae13** [comment]
@anastasiyaprymolenna  do you still need me to look at extractant?
