### ISSUE TITLE
attribute value should be abstract, doi should be something concrete

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#12]
Whereas [named thing](https://github.com/microbiomedata/nmdc-schema/blob/eb0da4efe9b9796b3677ac5e776e767d81ad66b0/src/schema/core.yaml#L76) is abstract, [attribute value](https://github.com/microbiomedata/nmdc-schema/blob/eb0da4efe9b9796b3677ac5e776e767d81ad66b0/src/schema/core.yaml#L85) is not abstract. However, [doi](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L1116) is the only slot in the NMDC schema with a range of attribute value, rather than a range that is_a attribute value such as [text value](https://github.com/microbiomedata/nmdc-schema/blob/eb0da4efe9b9796b3677ac5e776e767d81ad66b0/src/schema/core.yaml#L135). I recommend that attribute value be made `abstract: true` and that the range of doi be made `text value` or another concretion of `attribute value`.

**Comment by turbomam** [comment]
`doi` will imminently be migrated to various `...dois` 

This is still a good issue to review

- #1039

**Comment by turbomam** [comment]
Nothing is asserted to be an instance of `AttributeValue`, so I support the idea of making it `abstract`.

https://graphdb-dev.microbiomedata.org/resource?uri=https:%2F%2Fw3id.org%2Fnmdc%2FAttributeValue&role=object
