### ISSUE TITLE
Add pattern validation of NMDC `id` mentions (in addition to `id` assertions)

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1207]
cc @aclum

**Comment by turbomam** [comment]
start wiht any inbound or outbound relationship including
- Study
- BioSample
- OmicsProcessing

**Comment by turbomam** [comment]
I don't think LinkML does anything like this by default.

**Comment by turbomam** [comment]
@aclum has a report of inter-class relationships that we worked on together, but I just whipped this up too:

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select
?p ?ot (count(?b) as ?bcount)
where {
    graph <mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017> {
        ?b a nmdc:Biosample ;
           ?p ?o .
        ?o a ?ot .
    } minus 
    {
        ?o a ?vt .
        ?vt rdfs:subClassOf* nmdc:AttributeValue
    }
}
group by ?p ?ot
```

**Comment by turbomam** [comment]
There are some patterns like this in the data, **from an RDF perspective**:
- `Biosample` 
  - `collected_from` some `FieldResearchSite`
  - `gold_biosample_identifiers` some `Biosample`  **probably unintentional**
- `Study`
  - `qualifiedAssociation` some `Association` for credit associations
  - `gold_study_identifiers` some `Study`  **probably unintentional**
- `OmicsProcessing`
  - `part_of` some `Study`
  - `gold_sequencing_project_idnetifiers` some `OmicsProcessing`   **probably unintentional**
  - `has_input` some `Biosample`
  - `has_input` some `ProcessedSample`
  - `has_output` some `DataObject`

**Comment by turbomam** [comment]
Having added most of the pattern constrainst on slots that mention things with `id`s, but not ahving updated any of the example data files:

**Comment by aclum** [comment]
@turbomam  I don't understand your 'probably unintentional' comment about the gold slots. Do you mean that the values in id and gold_study_identifiers can be the same? This will be resolved with re-iding.

**Comment by turbomam** [comment]
> Do you mean that the values in id and gold_study_identifiers can be the same? This will be resolved with re-iding.

Yes, that's what I meant. I'll update those annotations.

**Comment by turbomam** [comment]
`Study`'s `slot_usage` on `structured_pattern.syntax` for `id`: 
- "{id_nmdc_prefix}:sty-{id_shoulder}-{id_blade}{id_version}{id_locus}"

----

-   id_nmdc_prefix: "^(nmdc)"
-   id_shoulder: "([0-9][a-z]{0,6}[0-9])"
-   id_blade: "([A-Za-z0-9]{1,})"
-   id_version: "(\\.[A-Za-z0-9]{1,})*"
-   id_locus: "(_[A-Za-z0-9_\\.-]+)?$"

**Comment by turbomam** [comment]
- [ ] Finish issue by constraining `OmicsProcessing`'s `has_input` mentions to allow `Biosample`s and `ProcessedSamples`

**Comment by aclum** [comment]
@turbomam  do you want to work off of this ticket or #1212 , they are redundant as far as I can tell.

**Comment by aclum** [comment]
We need a pattern constraints on was_informed_by, has_calibration, was_generated_by

**Comment by sierra-moxon** [comment]
@turbomam - this is planned for discussion today at metadata call -- the idea was a structured_pattern in slot_usage for ids (plus support in linkml JSONSchema generator for this construct) and range constraints.  The other "fix" to make this the uniform way of doing this, is to "fix" the OWL generator to use the range constraint and not the structured_pattern.

**Comment by aclum** [comment]
This was resolved by https://github.com/microbiomedata/nmdc-schema/pull/1994
