### ISSUE TITLE
continue Napa pattern constraints on `id` mentions

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1212]
- [x] #1215

see also
- https://github.com/microbiomedata/nmdc-schema/pull/1209

**Comment by turbomam** [comment]
@aclum I merged #1209 but didn't finish the `OmicsProcessing` `has_input` constraints 

Then there will be more work along these lines for other classes that should only mention Napa `id`s

I'm mentioning this to you because my merge of #1209 apparently marked something as complete on some project boards

**Comment by turbomam** [comment]
run as necessary as updating example data:

```shell
poetry run linkml-run-examples \
        --schema project/nmdc_schema_generated.yaml \
        --input-directory src/data/valid \
        --counter-example-input-directory src/data/invalid \
        --output-directory examples/output > examples/output/README.md
```

**Comment by aclum** [comment]
We need `id` mentions checked on the following Classes:
Biosample
OmicsProcessing
WorkflowExecutionAcitvity subclasses
DataObjects

**Comment by aclum** [comment]
@turbomam Is there an update on this?

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint. Adding backlog label.

**Comment by aclum** [comment]
this is done for part_of and has_input for OmicsProcessing. Needed for was_informed_by for WorkflowExeuctionActivity. also check that has_inputs and has_outputs for WorkflowExeuctionActivity have a range of DataObject with the napa data object pattern.
