### ISSUE TITLE
Add air_temp_max slot for GLBRC support

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-schema#1216]
Update NMDC schema to include this slot for GLBRC data

At a broader level, we should revisit how air_temp_max/min/average relate to [air_temp](https://microbiomedata.github.io/nmdc-schema/air_temp/)

**Comment by turbomam** [comment]
Great, I'm glad to see concrete examples of GLBRC and NMDC working together

@bmeluch 
- do you have a provisional definition for `air_temp_max`? 
- what classes would use it?
- Is it important to retain that name in order to have interoperability with GLBRC?

**Comment by bmeluch** [comment]
Their definition is "Max temperature on day of sampling, at 10 m height"
It's going to be added to Biosample, I'm not sure about the exact name but I would think it either needs to keep the exact name or have "air_temp_max" as an alias so their data can be added easily?
I'm working through a super issue of GLBRC terms so there will be more issues for adding similar slots shortly

**Comment by bmeluch** [comment]
Closing as not planned, parent issue https://github.com/microbiomedata/nmdc-schema/issues/1110 was closed because we decided it was not best practice to try and add mapping to support every BRC project.
