### ISSUE TITLE
have teams of people associated with studies

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#122]
@pvangay would like to distinguish between the "team" of the study and the co-principal investigators.

![image](https://user-images.githubusercontent.com/3186638/130700461-9bd97d2a-9055-4410-821d-1348ac673ad0.png)

This could be done on the kitware side by having special rules about how members are displayed based on their roles. 

@turbomam can a person have more than one role?

cc @cmungall @dehays

**Comment by ssarrafan** [comment]
@turbomam will you have bandwidth to work on this in September?  

@pvangay @wdduncan

**Comment by ssarrafan** [comment]
NMDC-server#434 is dependent on this issue being completed

**Comment by wdduncan** [comment]
@ssarrafan I think we can do this in September.

**Comment by wdduncan** [comment]
We have added a [has credit associations](https://microbiomedata.github.io/nmdc-schema/has_credit_associations/) slot/relationship to link a study with the team of researchers. 
I think this suits your needs. I am closing this ticket for now. We can reopen if this solution doesn't work.
