### ISSUE TITLE
Add lime_index slot for GLBRC support

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-schema#1221]
Add to Biosample class
GLBRC definition is "an indicator of the reserve or potential acidity in soil and is used to determine the quantity of lime needed to correct the pH of an acid soil. Aka buffer pH or buffer index"

Related to [lbc_thirty](https://microbiomedata.github.io/nmdc-schema/lbc_thirty/) and [lbceq](https://microbiomedata.github.io/nmdc-schema/lbceq/) but not the same measurement.

**Comment by turbomam** [comment]
@bmeluch would you please provide some documentation about **how** the proposed `lime_index` slot is different from both `lbc_thirty` and `lbceq`?

If it is reasonably possible to convert between any of those phenomena, I propose that we don't add another slot but rather provide annotations on the existing slots about how to do the conversion. 

If this slot is in support of one project, and the data are not going to be ingested from the DataPortal, then this could be a good case to illustrate nmdc tooling that ingests data with labels different from our slot names.

**Comment by mslarae13** [comment]
lime index description will be "an indicator of the reserve or potential acidity in soil and is used to determine the quantity of lime needed to correct the pH of an acid soil. Aka buffer pH or buffer index"

lbc_thirty is bioscales specific, if I rememeber and defined as "lime buffer capacity, determined after 30 minute incubation" I'm not sure it's the same thing? I can ask Adina.

lbceq description is lime buffer capacity, determined at equilibrium after 5 day incubation. 

These are really specific with incubation time. I don't think these are the same.

**Comment by bmeluch** [comment]
Closing as not planned, parent issue https://github.com/microbiomedata/nmdc-schema/issues/1110 was closed because we decided it was not best practice to try and add mapping to support every BRC project.
