### ISSUE TITLE
`Study` nmdc:sty-11-hdd4bf83 is lacking a `study_category` value

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1223]
Whose responsible for fixing this kind of thing?

How did it make it past nmdc-runtime validation?

**Comment by turbomam** [comment]
```json
{
  "description": "Identify metabolic pathways in the microbiota that are linked to colonization resistance against Candida",
  "principal_investigator": {
    "email": "ajbaumler@ucdavis.edu",
    "name": "Andreas Baumler",
    "orcid": "0000-0001-9152-7809"
  },
  "title": "Colonization resistance against Candida",
  "websites": [
    "https://health.ucdavis.edu/medmicro/faculty/baumler/"
  ],
  "name": "Colonization resistance against Candida",
  "has_credit_associations": [
    {
      "applies_to_person": {
        "name": "Andrew Tritt",
        "orcid": "0000-0002-1617-449X"
      },
      "applied_roles": [
        "Data curation"
      ]
    },
    {
      "applies_to_person": {
        "name": "Connor Tiffany",
        "orcid": "0000-0001-8188-7720"
      },
      "applied_roles": [
        "Formal Analysis"
      ]
    },
    {
      "applies_to_person": {
        "name": "Hannah Pritkin Savage",
        "orcid": "\t0000-0002-1057-7239"
      },
      "applied_roles": [
        "Investigation",
        "Formal Analysis"
      ]
    },
    {
      "applies_to_person": {
        "name": "Krystle Lynn Reagan",
        "orcid": "0000-0003-3426-6352"
      },
      "applied_roles": [
        "Investigation"
      ]
    }
  ],
  "id": "nmdc:sty-11-hdd4bf83"
}
```

**Comment by turbomam** [comment]
see
- https://github.com/microbiomedata/nmdc-runtime/issues/315

**Comment by brynnz22** [comment]
@turbomam I tried to submit a change sheet for this and the changesheets submit endpoint will not load for me, will it load for you? https://api.microbiomedata.org/docs#/metadata/submit_changesheet_metadata_changesheets_submit_post

**Comment by turbomam** [comment]
When I click on that link you provided, a page does appear, but maybe that's not helpful feedback. I have only done change sheets once or twice. What's the most helpful tub for me to try?

**Comment by brynnz22** [comment]
Just go to the changesheet submit endpoint in the API Gui and click "Try It out" and let me know if it doesn't freeze and seems to be working.

**Comment by brynnz22** [comment]
Yes, that's what happens to me too - the page freezing.

Hmm... I'm not sure, I've never tried. I'm not sure how to do it either. Do you know?

**Comment by turbomam** [comment]
https://github.com/microbiomedata/nmdc-runtime/issues/337

**Comment by mslarae13** [comment]
@brynnz22 can you look at this. Did this get resolved?

**Comment by brynnz22** [comment]
It looks like its got a `study_category` of `research_study`. I am going to close this.
