### ISSUE TITLE
add study image urls

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#123]
@pvangay wishes to have images associated with studies. E.g.:

![image](https://user-images.githubusercontent.com/3186638/130700798-d6b9ad8f-67be-4ea5-b226-aefd6504104d.png)

further discuss is needed.

cc @cmungall @dehays @turbomam

**Comment by wdduncan** [comment]
A description may need to be associated with the image. So, we may need to add an `image` class with slots `url` and `description` (note: `description` is already a slot with all `named thing`).

**Comment by ssarrafan** [comment]
NMDC-server#434 is dependent on this issue being completed.

@wdduncan do you have bandwidth for this issue in September? 
@pvangay 
@emileyfadrosh

**Comment by cmungall** [comment]
Can we flesh out requirements more:

 - one image per study or multiple?
 - are the images in order and do they need to be inlined with the text?
 - do the images have their own metadata and/or captions associated with them? e.g license. It sounds like there is a requirement for caption/description
 - is the size already normalized, or do they need to be accompanied by information about how to scale them on the site?
 - do the images need to be stored or will they be published separately and included via URL (strongly recommend the latter)

Either way I think @wdduncan's suggested schema extension is sensible. I would not inherit named thing though. Just make a new class `image` with slots: url, description as you suggest. We can add more fields later.

The schema changes here are simple. The harder part is the dataflow. How does this get into our system? Do we need to coordinate with @mslarae13 to get into the spreadsheets and then with @turbomam to ingest? Do they get ETL's from GOLD? Or should we author the study metadata directly as a yaml file in GitHub?

**Comment by pvangay** [comment]
@cmungall my 2 cents:
- 1 (or more - nice to have) images per study, each with their own caption/description
- order may matter
- does including by URL prevent the user from scaling themselves?

**Comment by ssarrafan** [comment]
@cmungall @wdduncan should this issue be closed, moved to the backlog or moved to the October sprint?

**Comment by wdduncan** [comment]
@ssarrafan Please move to October sprint. Thanks!

**Comment by ssarrafan** [comment]
@pvangay Bill reported that he needed more information from you to proceed with this issue.  Can you please follow up with @wdduncan?
