### ISSUE TITLE
check if json schema is regenerated in github action

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#124]
When a PR is merged, need to check if the json schema is regenerated by github action.

cc @cmungall

**Comment by wdduncan** [comment]
@cmungall a json schema is generated during the [github actions ](https://github.com/microbiomedata/nmdc-schema/blob/8a47e5d18ab47145983f18021dcb5ebba135de52/.github/workflows/check-pull-request.yaml#L50) that checks the pull request.

Can this ticket be closed?

**Comment by turbomam** [comment]
`project/jsonschema/nmdc.schema.json`

- #682
