### ISSUE TITLE
Plan for the role of LinkML rules in nmdc-schema and assess their fitness for purpose

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1243]
@pkalita-lbl and @brynnz22 how are you coming along with this proposed LinkMLrule (excuse my loose terminology)

> DOI values should generally require attribution to an authority, except publication DOIs (because there's an unreasonable number of authorities/publishers)

@brynnz22, is there any issue that tracks that particular addition to the schema?

If the two of you make progress with this, would you please check/improve my [incomplete tube/plate/well rule](https://github.com/microbiomedata/nmdc-schema/blob/3ea79afe459fe5501cdd5735ac0e930082544688/src/schema/nmdc.yaml#L350-L400)?
- #919

**Comment by brynnz22** [comment]
@turbomam it looks like your rules work as they should!

**Comment by pkalita-lbl** [comment]
I'm not sure this issue is serving any purpose. Closing.
