### ISSUE TITLE
nmdc-schema contributions should START with an issue and a PR. Draft PRs are fine!

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1244]
_nmdc-schema has had a problem with stale branches for a while. I appreciate the new contributors who have asked me about that! So I have been closing stale branches, if I'm the owner, or after discussion with some other owner. This review process is much easier for everyone involved if the branches are tied to issues and PRs._

**TL;DR: If you `push` an nmdc-schema branch to the cloud, please make sure that it is tied to an issue and a pull request**

Draft pull request are great for indicating that the work isn't intended for formal review yet

### References
- https://github.blog/2019-02-14-introducing-draft-pull-requests/
- https://berkeleybop.github.io/best_practice/#git-and-github

**Comment by kheal** [comment]
This is well documented here: https://github.com/microbiomedata/nmdc-schema/blob/2f7797be782e5b7124b2588bc6b312e903ea0a1b/MAINTAINERS.md?plain=1#L15
