### ISSUE TITLE
id-based configs and data (eg for migrations) should go in one, standardized assets/misc file

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1249]
not embedded in code

**Comment by eecavanna** [comment]
@turbomam suggested the data reside in a YAML file as opposed to a "code" file (i.e. a Python data structure).

If we move to a more hierarchical file free structure (as proposed in https://github.com/microbiomedata/nmdc-schema/issues/1250), the YAML file could reside in that somewhere (TBD).

**Comment by eecavanna** [comment]
Related to storing data used by transformation functions: https://github.com/microbiomedata/nmdc-schema/issues/1310

**Comment by eecavanna** [comment]
Closing because all migrators (at least since the migration squad was created) that do id-based migration retrieve their data from data files and not from variables in the migrator modules.
