### ISSUE TITLE
Move each migration class into its own module in a `migrations` folder

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1250]
Current file tree structure:

```shell
nmdc_schema/
  migration_recursion.py  # <-- contains all migration classes
  ...
```

Here's the file tree structure I propose:

```shell
nmdc_schema/
  migration_recursion.py
  migrators/
    __init__.py
    MigratorBase.py
    Migrator_7_8_0_to_8_0_0.py
    Migrator_8_0_0_to_8_1_0.py
    ...
```

@turbomam, @brynnz22, and I discussed this topic on October 27, 2023, and we agreed to move forward with (at least, roughly) this structure. I will make a PR containing this restructuring (once there's some migration downtime) and tag @turbomam and @brynnz22 in it for review.

**Comment by eecavanna** [comment]
Note: Some migrations reference data files. For example:
- https://github.com/microbiomedata/nmdc-schema/pull/1208/files#diff-e59e5c5787da889a611cbf193a0748d67682e0132b45966fbcb8559b3e058589R332

**Comment by ssarrafan** [comment]
Moving to next sprint due to recent comment.  @eecavanna let me know if this is not actively being worked on. Thanks!

**Comment by eecavanna** [comment]
Related: https://github.com/microbiomedata/nmdc-schema/issues/1310
