### ISSUE TITLE
make slots for Class FunctionalAnnotationAggMember required

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1252]
I think all slots for this Class should be required. For the data portal to be able to have the kegg search work properly they need to know the term id, count, and what WorkflowExecutionActivity it was derived from.
slots in question are 
- metagenome_annotation_id
- gene_function_id
- count

These slots are currently all optional.
@naglepuff  @scanon please comment.

**Comment by naglepuff** [comment]
Sounds good to me

**Comment by ssarrafan** [comment]
@aclum this is not assigned to anyone, and no updates since Oct so I'm removing from the sprint and adding the backlog label. 

Please assign and add to new sprint if it's an active issue.

**Comment by aclum** [comment]
This is in review, it mixed in with a pull request (https://github.com/microbiomedata/nmdc-schema/pull/1309) that is failing tests that needs to be debugged which addresses related issue https://github.com/microbiomedata/nmdc-schema/issues/1253. Its fine to leave this in the backlog for now since I'm not sure we'll get the related issues resolved this sprint.

**Comment by aclum** [comment]
We uncoupled the two issues. The PR to address just this issue should get merged in today.
