### ISSUE TITLE
`src/data/invalid/Study-include-abstract.yaml` is not a Study example, it is a Database example

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1274]
In order to be tested by `linkml-run-examples`, the first hyphen-separated token in a data file's name must the the verbatim name of the class it instantiates.

The first token of the filename in `src/data/invalid/Study-include-abstract.yaml` is "Study", but the file instantiates a `Database`. One piece of evidence for this is that the outermost key is `study_set`, a slot that only applies to class `Database`

Since the file is in the `src/data/invalid` path, it's not obvious that this is a problem. But we should fix this anyway, for the principle of limiting each invalid data file to one error, which is the inclusion of a `abstract` in this case.

**Comment by brynnz22** [comment]
I fixed this and created a PR for your review!
