### ISSUE TITLE
Latest GitHub Release is `9.0.0` while latest PyPI Release is `9.0.2`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1276]
I am pointing this out because I expected each PyPI Release to have a corresponding GitHub Release (with the same version identifier).

GitHub Releases: https://github.com/microbiomedata/nmdc-schema/releases

PyPI Releases: https://pypi.org/project/nmdc-schema/#history

**Comment by eecavanna** [comment]
On PyPI, I see a mismatch between the version number shown in the header area, and the version number shown on a badge.

<img width="930" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/9c885a46-3eef-46fc-9a64-7f66b4845ca9">

**Comment by turbomam** [comment]
Thanks. I think we've had that problem before. Do you know a solution?

**Comment by eecavanna** [comment]
Not off the top of my head. I'm not familiar with that badge. I'll look into it real quick right now and see if I see any clues. My guess is that the two areas get the information from two different places (i.e. two sources of truth); OR that they get them from the same place, but at different times (e.g. "at build time" and "at publish time" or something like that). I'll look now and report back.

**Comment by eecavanna** [comment]
The `fury.io` website has a manual badge generator. It does see that the current version is 9.0.4.

<img width="974" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/dc8bc352-61eb-489a-8de9-cda142319929">

Based on that, I think some kind of caching is at play here. I don't know at what level, though.

**Comment by eecavanna** [comment]
The original issue has been fixed.

<img width="490" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/b77263f6-556b-4c28-a45e-84cbb28c2f49">

I'll close this one and open a separate one about the badge. Sorry!

**Comment by eecavanna** [comment]
I created an issue specific to the badge behavior, here: https://github.com/microbiomedata/nmdc-schema/issues/1290
