### ISSUE TITLE
`has_input` and `has_output` are multivalued, so their names should be pluralized

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1284]
see also
- #923 

cc @mslarae13 @anastasiyaprymolenna @corilo

**Comment by aclum** [comment]
We intentially as part of the neon work deprecated the plural versions of these slots. I recall this was b/c it is best practice to name slots singular even if the values are a list. I don't care either way as long as we don't have both. What is the linkml recommendation here? We should try and be consistent, slot names should either be singular or plural, not a mix

**Comment by eecavanna** [comment]
When I first came across these slot names, I expected their values to be a single Boolean value; i.e. `has_outputs: true` (as in, "yes, this does have outputs"). I was surprised to learn they contain lists of ids of outputs. I wonder whether consumers would find the slots more intuitive if they were named `input_ids` and `output_ids`, or `inputs` and `outputs`. I don't know the background of their names and may be missing something.

**Comment by aclum** [comment]
@cmungall  what is the best practice here wrt singular vs plural slot names?

**Comment by mslarae13** [comment]
I just wanna add that there's some other slots I'd like us to evaluate. IMO, we should always use has_input and has_output. I have no opinion or knowledge of best practice for plural or not..

But, I'd like to see the following removed / replaced with has_input/output

Consistency for was_generated_by or has_output or is_output … etc (ex:[FunctionalAnnotation](https://microbiomedata.github.io/nmdc-schema/FunctionalAnnotation/))
https://microbiomedata.github.io/nmdc-schema/DissolvingActivity/ + material_input and material_output

**Comment by cmungall** [comment]
Plural is better for multi valued for all new slots. Note this policy this
can conflict if slots are brought in from another standard so there may be
inconsistency.

**Comment by mslarae13** [comment]
So, plural when it's IS multivalued or a list. 0..*
Singular when the range is single value , 0..1 ...

**Comment by aclum** [comment]
Per the metadata meeting today we are leaving these slots as they are. As Chris mentions going forward new slots should be plural if they are multivalued. Closing this issue.
