### ISSUE TITLE
Badge (hosted by `badge.fury.io`) temporarily shows different version number than PyPI header

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1290]
The header on PyPI shows a different version number (`9.0.4`) than the badge on the README (`9.0.2`).

Screenshot of PyPI:

<img width="1043" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/a7e75240-5e51-4f49-a4aa-2389bc71b950">

Screenshot of GitHub:

<img width="741" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/2cab0cd3-db9b-4532-917c-4a0ba9e450a7">

---

Here's the line of code in `README.md` that produces the badge:

https://github.com/microbiomedata/nmdc-schema/blob/f5339a8f4e967fc8a78845da869722b7d042f5d4/README.md?plain=1#L8

When I visit `https://badge.fury.io/py/nmdc-schema.svg` in my web browser, I am redirected to here:

```clean
https://d25lcipzij17d.cloudfront.net/badge.svg?id=py&r=r&ts=1683906897&type=6e&v=9.0.4&x2=0
```

---

The `fury.io` website has a badge URL generator (I assume this is where the URL came from). On the badge preview on that website, the version number does appear as 9.0.4.

![](https://user-images.githubusercontent.com/134325062/280428892-dc8bc352-61eb-489a-8de9-cda142319929.png)

---

I suspect the root cause is related to caching in the web browser.

**Comment by turbomam** [comment]
I agree that it is a cache issue. I propose we close the issue.

**Comment by eecavanna** [comment]
There are a couple things I want to try first before closing the issue.

1. Append a query string to the URL that is unique to each release; e.g. `https://badge.fury.io/py/nmdc-schema.svg?unique_str=20231104`. 
    - This is a technique web developers can use for website assets that get frequently updated (e.g. CSS files during development), in order to force the web browser to fetch the latest version from the web server
2. Report the issue to the third-party that hosts the badge (i.e. that performs the HTTP 302 redirect shown below) in case they can change the way they do the redirect so that it doesn't get cached by web browsers
    - <img width="664" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/946c5dc6-ee19-489c-9b1f-053d723c24a4">

I'll assign the issue to myself and try those things next time a new version of `nmdc-schema` gets published to PyPI. I would try them now, but the issue seems to have resolved itself (for my web browser) sometime within the last 17 hours.

<img width="964" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/28e11f4c-869b-467f-bb78-7e36b3f3d328">

**Comment by eecavanna** [comment]
Hmm... the issue is still happening:

See:

- https://pypi.org/project/nmdc-schema/
- https://github.com/microbiomedata/nmdc-schema

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/52b8d5dd-b480-4ea8-b074-19b18148c3ea)

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/7077b434-475a-4fbc-9553-55e4dc133aa7)

I am wondering whether the badge is counterproductive, since it does not always show the correct schema version.

**Comment by eecavanna** [comment]
> 1. Append a query string to the URL that is unique to each release; e.g. https://badge.fury.io/py/nmdc-schema.svg?unique_str=20231104.
>    - This is a technique web developers can use for website assets that get frequently updated (e.g. CSS files during development), in order to force the web browser to fetch the latest version from the web server

When I visited `https://badge.fury.io/py/nmdc-schema.svg`, I saw "9.3.2". Then, when I visited `https://badge.fury.io/py/nmdc-schema.svg?foo=bar`, I saw "10.0.0". I'll open a PR in which the URL contains a query string (an arbitrary one) and see how that works over time. I don't want people to have to update that query string for each release (I'd rather remove the badge altogether, than require that).
