### ISSUE TITLE
populate GraphDB from https://api-napa.microbiomedata.org/

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1302]
@aclum what collections do you want to include?

**Comment by turbomam** [comment]
@eecavanna did the dump around September 28th

See Slack thread: https://nmdc-group.slack.com/archives/C05RNEJAV38/p1695864234712159

**Comment by turbomam** [comment]
https://pypi.org/project/nmdc-schema/#history

**Comment by turbomam** [comment]
https://pypi.org/project/nmdc-schema/8.0.0/ from September 21st?

**Comment by turbomam** [comment]
try https://github.com/microbiomedata/nmdc-schema/blob/v8.0.0/nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml

**Comment by turbomam** [comment]
> ✗ Additional properties are not allowed ('sample_mass' was unexpected) in $.extraction_set[0]

https://raw.githubusercontent.com/microbiomedata/nmdc-schema/v7.8.0/nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml ???

**Comment by aclum** [comment]
study_set,biosample_set, omics_processing, subclasses of WorkflowExecutionActivity, data_object_set. extraction_set records are not needed since those only existed after napa-style ids

**Comment by turbomam** [comment]
@aclum please confirm and **see my notes**

## Yes migrate

- biosample_set
- data_object_set
- omics_processing_set
- study_set
- all collections for the subclasses of [WorkflowExecutionActivity](https://microbiomedata.github.io/nmdc-schema/WorkflowExecutionActivity/), 

## No, dumping not required

- functional_annotation_agg **(MAM: I didn't have any plans in general to dump, migrate, validate or convert this becasue it is so large)**
- extraction_set (not needed since it only existed after napa-style ids)

**Comment by turbomam** [comment]
validating against v7.8.0 also fails due to illegal upper-case GOLD: prefixes

**Comment by aclum** [comment]
I thought I fixed all the gold uppercasing in an ad hoc fashion. Do you have an example record. I can fix.

**Comment by turbomam** [comment]
## Finishing thought about collections to be migrated:

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select distinct ?database_slot
where {
    graph <https://w3id.org/nmdc/nmdc> {
        ?mixin <http://www.w3.org/2000/01/rdf-schema#domain> <https://w3id.org/nmdc/Database> .
        ?database_slot <http://www.w3.org/2000/01/rdf-schema#subPropertyOf> ?mixin .
        ?database_slot <http://www.w3.org/2000/01/rdf-schema#range> ?slot_range .
        ?slot_range <http://www.w3.org/2000/01/rdf-schema#subClassOf> nmdc:WorkflowExecutionActivity .
    }
    graph <mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017> {
        ?x ?database_slot ?z .
    }
}
order by ?database_slot
```

?database_slot
--
<https://w3id.org/nmdc/mags_activity_set>
<https://w3id.org/nmdc/metabolomics_analysis_activity_set>
<https://w3id.org/nmdc/metagenome_annotation_activity_set>
<https://w3id.org/nmdc/metagenome_assembly_set>
<https://w3id.org/nmdc/metagenome_sequencing_activity_set>
<https://w3id.org/nmdc/metatranscriptome_activity_set>
<https://w3id.org/nmdc/nom_analysis_activity_set>
<https://w3id.org/nmdc/read_based_taxonomy_analysis_activity_set>
<https://w3id.org/nmdc/read_qc_analysis_activity_set>

**Comment by turbomam** [comment]
> I thought I fixed all the gold uppercasing in an ad hoc fashion. Do you have an example record. I can fix.

regenerating validation log now

**Comment by turbomam** [comment]
## Explicitly excluding these routinely-dumped collections
_These are small, so including them wouldn't take much longer or make the output files much larger._

```shell
--selected-collections extraction_set \
--selected-collections field_research_site_set \
--selected-collections library_preparation_set \
--selected-collections pooling_set \
--selected-collections processed_sample_set \
```

**Comment by turbomam** [comment]
@aclum yes, you did correct all GenomesOnLine Database prefixes to  "gold:", in accordance with the more recent schema releases.

But nmdc-schema v7.8.0 (which otherwise matches the frozen Napa MongoDB) expected the following slots to use the following patterns
- `gold_biosample_identifiers`: '^GOLD:Gb[0-9]+$'
- `gold_sequencing_project_identifiers`: '^GOLD:Gp[0-9]+$'
- `gold_study_identifiers`: '^GOLD:Gs[0-9]+$'

I think I can do a quick and dirty fix for this.

**Comment by turbomam** [comment]
Fixed and validated. Will be available in GraphDB tomorrow.

**Comment by aclum** [comment]
thanks @turbomam

**Comment by turbomam** [comment]
I put the Napa squad's MongoDB contents into a separate GraphDB repository (which is like a Postgres database? or schema?) called **napa-graph**. You will need to select that from the repository pull-down on the top right of most GraphDB pages

![image](https://github.com/microbiomedata/nmdc-schema/assets/25185273/32cbbdd0-03b4-4c08-a68b-2f14cd6036d1)

Here are the currently populated named graphs:

- https://api-dev.microbiomedata.org (data)
- https://w3id.org/nmdc/nmdc (schema)

If that new name for the data graph is disruptive, then we can temporarily change it. The old data named graph was based on the MongoDB connection string ([mongodb://mongo-loadbalancer.nmdc.production.svc.spin.nersc.gov:27017](http://3.236.215.220:7200/resource?uri=mongodb%3A%2F%2Fmongo-loadbalancer.nmdc.production.svc.spin.nersc.gov%3A27017&role=context)). Some systems and tools I like have been complaining about that so I would prefer to use the API's URL instead.

**Comment by turbomam** [comment]
See also
- https://github.com/microbiomedata/nmdc-schema/issues/1303#issuecomment-1801982834

**Comment by aclum** [comment]
re-iding is done, we can close this.
