### ISSUE TITLE
Transformation function raises `FileNotFoundError` regarding data YAML file

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1310]
### Summary

While running a transformation function named `fix_award_dois` from within a Python notebook that `import`s the containing Python class from the `nmdc-schema` Python package on PyPI, Python raised a `FileNotFoundError` exception because it couldn't find a file at the path specified.

### Screenshot

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/863f3fa2-8a94-474e-a8e1-50f5e2529eb7)

### Related snippets

Invocation of `load_yaml_file` function:

https://github.com/microbiomedata/nmdc-schema/blob/918056b61508b2094433abb15fbb0e1578fd014f/nmdc_schema/migration_recursion.py#L332-L333

Definition of `load_yaml_file` function:

https://github.com/microbiomedata/nmdc-schema/blob/918056b61508b2094433abb15fbb0e1578fd014f/nmdc_schema/migration_recursion.py#L90-L94

### Proposal

Reference the file in a way that works regardless of where the function is being invoked.

Suggestion (untested):

```diff
+ from importlib import resources

# ...

 def load_yaml_file(filename): 
     """Loads a YAML file into a Python dict.""" 
-    with open(filename, "r") as f: 
+    with resources.open(filename, "r") as f: 
        data = yaml.safe_load(f) 
     return data 
```

Docs:
- Official: https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources
- Official: https://docs.python.org/3/library/importlib.resources.abc.html#importlib.resources.abc.Traversable.open
- Third-party: https://dev.to/bowmanjd/easily-load-non-python-data-files-from-a-python-package-2e8g

**Comment by eecavanna** [comment]
As a workaround for the current migration, I can download the referenced file from the `nmdc-schema` GitHub repo and put it at the path `assets/misc/study_dois_changes.yaml` relative to the Python notebook.

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/477a7707-509f-4ee7-9ac9-a74834a9cf00)

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/4268904f-ce19-4c35-8c12-d6ef55735067)

**Comment by turbomam** [comment]
Thanks @eecavanna 

@brynnz22 would be it be OK for me to change the assignee to you?

**Comment by eecavanna** [comment]
The issue is still present, and will come into play again the next time code that imports the `nmdc-schema` Python package calls the `load_yaml_function` (or calls something that calls that function). That's because that function uses Python's `open()` function with a relative path, which is relative to the current working directory.

Python docs about `open()`: https://docs.python.org/3/library/functions.html#open

**Comment by eecavanna** [comment]
For future reference: I found this code in the `nmdc-schema` repo (while working on something else). Maybe the same approach (i.e. way of getting the contents of a file) can be used in this case.

https://github.com/microbiomedata/nmdc-schema/blob/387ed3be408a87f9da6df590e43953fc55665138/nmdc_schema/nmdc_data.py#L28
