### ISSUE TITLE
Two transformation functions do not return the transformed dictionary

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1311]
### Summary

While running a transformation function named `remove_doi_slots` from within a Python notebook that `import`s the containing Python class from the `nmdc-schema` Python package on PyPI, Python raised an `AttributeError` exception because a value of `None` doesn't have an attribute named `get`.

### Screenshot

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/69b95587-4d1a-425d-8cb4-1729b8d1a2c5)

### Related snippets

This is where the exception was raised:

https://github.com/microbiomedata/nmdc-schema/blob/918056b61508b2094433abb15fbb0e1578fd014f/nmdc_schema/migration_recursion.py#L382-L384

These two transformation functions don't return the transformed dictionary (i.e. they implicitly return `None` since they don't have `return` statements):

https://github.com/microbiomedata/nmdc-schema/blob/918056b61508b2094433abb15fbb0e1578fd014f/nmdc_schema/migration_recursion.py#L316-L327

https://github.com/microbiomedata/nmdc-schema/blob/918056b61508b2094433abb15fbb0e1578fd014f/nmdc_schema/migration_recursion.py#L368-L376

As a result, transformation functions "further down the pipeline" won't receive a dictionary as input.

### Proposal

End each transformation function with:

```py
return study
```

**Comment by eecavanna** [comment]
As a short-term workaround, in the notebook, I ignored the return values after confirming (by reviewing the source code) all the transformation functions modify the dictionary "in place."

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/ed117904-5d8a-4613-b5aa-771d36a0db1c)

I created the following PR which contains the permanent fix: https://github.com/microbiomedata/nmdc-schema/pull/1312

**Comment by turbomam** [comment]
Thanks @eecavanna 

@brynnz22 would be it be OK for me to remove myself as an assignee and just leave you?

**Comment by brynnz22** [comment]
@turbomam Yes! I just approved the PR. I think you already changed it? Or @eecavanna did. Thanks for the quick fix. Sorry about this.
