### ISSUE TITLE
Hyperlink on `nmdc-schema` documentation website leads to `404 Not Found` error page

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1317]
The hyperlink is in the "See Also" section of this page: https://microbiomedata.github.io/nmdc-schema/ExternalIdentifier/

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/3074ac82-503a-4505-858e-b00ce601ff47)

The hyperlink points to this URL: https://microbiomedata.github.io/nmdc-schema/identifiers.html

The URL leads to a 404 error page.

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/297872fe-3c33-4450-b348-96cfcce34d3b)

**Comment by turbomam** [comment]
@sujaypatil96 can you please develop a strategy that will automatically check all links on LinkML documentation pages as part of the build process?

**Comment by eecavanna** [comment]
For reference, here's a link to some info about how link-checking is performed in the `NMDC_Documentation` repo:

https://github.com/microbiomedata/NMDC_documentation#link-checking
