### ISSUE TITLE
Add Filtration and Phase Separation classes

### ISSUE THREAD

**Issue by JamesTessmer** [microbiomedata/nmdc-schema#1325]
Adding the FiltrationProcess and PhaseSeparationProcess classes (and supporting slots) for metabolomics analysis.
Included are the supporting classes ConditioningValue and ModifierValue.

**Comment by JamesTessmer** [comment]
See these:
PR: https://github.com/microbiomedata/nmdc-schema/pull/1326
Branch: [1325-add-filtration-and-phase-separation-classes](https://github.com/microbiomedata/nmdc-schema/tree/1325-add-filtration-and-phase-separation-classes)

**Comment by turbomam** [comment]
@JamesTessmer please provide the exact names of the classes in https://github.com/microbiomedata/nmdc-schema/pull/1326 that are relelvant to this issue.
