### ISSUE TITLE
Create example data for MaterialProcessing Subclasses

### ISSUE THREAD

**Issue by anastasiyaprymolenna** [microbiomedata/nmdc-schema#1328]
A running issue until all MaterialProcessing Subclasses have an example data set committed for them:

- [x] SubsamplingProcess
- [x] MixingProcess
- [x] FiltrationProcess
- [x] ~Phase~ChromatographicSeparationProcess
~- [ ] AcidificationProcess~
~- [ ] AnalyteStorage~
- [x] Extraction
~- [ ] ReactionActivity~
~- [ ] SievingProcess~
~- [ ] SampleDrying~
~- [ ] DerivatizationProcess~
- [x] Chemical~Reaction~ConversionProcess
~- [ ] PhMeasuringProcess~
- [x] DissolvingProcess

**Comment by turbomam** [comment]
Thanks @anastasiyaprymolenna . Please provide the name of the example data file for each of those classes that you have checked off as complete.

**Comment by anastasiyaprymolenna** [comment]
branch for committing to https://github.com/microbiomedata/nmdc-schema/tree/1328-create-example-data-for-materialprocessing-subclasses

**Comment by anastasiyaprymolenna** [comment]
Subsampling https://github.com/microbiomedata/nmdc-schema/blob/1328-create-example-data-for-materialprocessing-subclasses/src/data/valid/MixingProcess-Biosample-input.yaml

**Comment by anastasiyaprymolenna** [comment]
Mixing  https://github.com/microbiomedata/nmdc-schema/blob/1328-create-example-data-for-materialprocessing-subclasses/src/data/valid/MixingProcess-Biosample-input.yaml

**Comment by anastasiyaprymolenna** [comment]
Filtration:
Valid: https://github.com/microbiomedata/nmdc-schema/blob/1328-create-example-data-for-materialprocessing-subclasses/src/data/valid/FiltrationProcess-Biosample-input.yaml
Invalid: https://github.com/microbiomedata/nmdc-schema/blob/1328-create-example-data-for-materialprocessing-subclasses/src/data/invalid/FiltrationProcess-Biosample-input.yaml

**Comment by anastasiyaprymolenna** [comment]
PhaseSeparation:
https://github.com/microbiomedata/nmdc-schema/blob/1328-create-example-data-for-materialprocessing-subclasses/src/data/valid/PhaseSeparationProcess-Biosample-input.yaml

**Comment by anastasiyaprymolenna** [comment]
Filtration and Phase separation need to be reviewed and updated when the models are finalized, this example data will not currently validate

**Comment by anastasiyaprymolenna** [comment]
Extraction examples
https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Extraction-NEON.yaml 
https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Extraction-metabolomics.yaml
https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Extraction-proteomics.yaml

**Comment by mslarae13** [comment]
@anastasiyaprymolenna @JamesTessmer do we have a status update? Can any more of these be checked off?
What is feasible to get done for the berk roll out?

**Comment by anastasiyaprymolenna** [comment]
DissolvingProcess valid:
https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/DissolvingProcess-minimal.yaml

ChemicalConversionProcess
https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/ChemicalConversionProcess-minimal.yaml
https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/ChemicalConversionProcess-digest.yaml

StorageProcess
https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/StorageProcess-minimal.yaml

**Comment by anastasiyaprymolenna** [comment]
@mslarae13 Since opening the issue we have removed the need for some classes, so I crossed those out, but the rest of the new `MaterialProcessing` subclasses all have data examples created for them. I will close this issue.
