### ISSUE TITLE
elaborate on `description` of `emsl_project_identifiers`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1329]
The `description`s for slots in `src/schema/external_identifiers.yaml` aren't completely consistent when it comes to level of detail, but there are some good examples in there, like 

- `jgi_portal_study_identifiers`: Identifiers that link a NMDC study to a website hosting raw and analyzed data for a JGI proposal. The suffix of the curie can used to query the GOLD API and is interoperable with an award DOI from OSTI and a GOLD study identifier.
- `gnps_task_identifiers`: identifiers that link a NMDC study to a web-based report about metabolomics analysis progress and results

Let's update the `description` of `emsl_project_identifiers` so that it's more similar to the descriptions above.

Medium importance. Low urgency.

**Comment by mslarae13** [comment]
current description is `an identifier that links to an EMSL user facility project`

Not sure how much more elaborate we really want it to be... I would say at most we make it

`Identifiers that link a NMDC study to associated EMSL user facility projects and the project information page"

Not sure how else to describe https://www.emsl.pnnl.gov/project/60141

@lamccue thoughts?

**Comment by lamccue** [comment]
Agree @mslarae13 , keeping this simple would be preferred.  Here is my suggestion.

"Identifiers that link a NMDC study to the EMSL user facility website hosting the project description of an EMSL user project"
