### ISSUE TITLE
delete all instrument/device classes and start over, distinguishing between named/anonymous

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1331]
pass this off to @anastasiyaprymolenna

**Comment by turbomam** [comment]
add in data generation vs preparation after this

**Comment by brynnz22** [comment]
Here is a metadata schema a working group for RDA developed that might be useful for inspiration and the "I" in FAIR. I was hoping they might have a controlled vocabulary for instrument type, but it does not look like it
