### ISSUE TITLE
expanded use of quality_control_report

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1333]
We have a need to indicate pass/fail for some of the WorkflowExecutionActivity subclasses. We already made quality_control_report but that currently only has Extraction as an applicable class. I would like to expand this slot to other PlannedProcess and WorkflowExecutionActivity classes. 

I would also like to expand the slots on Class [QualityControlReport](https://microbiomedata.github.io/nmdc-schema/QualityControlReport/). The current slots are 'status' and 'name'. JGI has a concept of failure_what failure_where, populated with controlled vocabulary. 
ie 
failure_where failure_what
Sequencing	substandard run output
PMO                 assembly size below min threshold
multiple_failure_modes Sequencing_qPCR error;Sequencing_no data produced

We could model something similar where failure_where has a range of Activity or PlannedProcess classes (soon to be only PlannedProcess after the Dec schema refactor)

I'll open a draft pull request with some example data.

**Comment by aclum** [comment]
FYI @Michal-Babins @hubin-keio @mslarae13 @anastasiyaprymolenna @scanon @turbomam @sujaypatil96

**Comment by ssarrafan** [comment]
@aclum appears to be active. I'll move to the next sprint but please remove if it's not being worked on.

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint, adding backlog label. Please update or add to next sprint if still active.

**Comment by aclum** [comment]
This is in progress this week. Ive updated the modeling and need help from Brynn on the linkml rules, then the migration code needs to be written. This will likely span into January.

**Comment by aclum** [comment]
Brynn and Patrick confirmed there is a bug in the linkml rules, see https://github.com/linkml/linkml/issues/1524. Patrick said he'd try and work on this on Friday. Will pause on this until January. Targeting a solution by the end of the first sprint in January so this can make it into the January end of month release.

**Comment by aclum** [comment]
To get the value_presence rules to work correctly I had to update linkml to 1.6.6 on Patrick's recommendation, then Patrick helped identify an issue where rules don't inherit to subclasses. Patrick will make a ticket for the linkml issue, this should be released in early January. Workaround would be to copy rules to each subclass but leaving for now since the next update to runtime would be end of January.

**Comment by aclum** [comment]
Patrick fixed the rules in linkml, i've updated the schema to use linkml 1.6.8 which made the linkml rules inheritance work as expected. Now the build passes.

@mbthornton-lbl  we need a small bit of migration code to move quality_control_report.status to qc_status in the extraction_set collection. See example data in https://github.com/microbiomedata/nmdc-schema/blob/1427-try-to-fix-qc-report-pr-1334-in-new-branch/src/data/valid/Database-ReadQcAnalysisActivity-quality_fail.yaml. Please work off of branch 1427-try-to-fix-qc-report-pr-1334-in-new-branch which already as a draft PR https://github.com/microbiomedata/nmdc-schema/pull/1428

**Comment by aclum** [comment]
Mark is reviewing the PR now. Hope to have this merged by EOD.
