### ISSUE TITLE
Add slots / update NMDC schema for sample types for EMSL submission

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1335]
New slots to be added to NMDC schema. 

- [x] microbiomedata/nmdc-schema#1336
- [x] #1337
- [x] #1338

See https://github.com/microbiomedata/submission-schema/issues/158 for slots to be added to submission portal interfaces

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint. Adding backlog label.

**Comment by bmeluch** [comment]
YAY they're all ticked off! @turbomam do you know what NMDC schema release number is likely to include these three slots, so I can reference that number as I incorporate them into the submission schema?

**Comment by bmeluch** [comment]
Incorporated into schema release 10.0.0, closing issue, thank you so much :)
