### ISSUE TITLE
Add slot: host_disease_stat

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-schema#1336]
"[host_disease_stat](https://genomicsstandardsconsortium.github.io/mixs/0000031/)" is listed in the MIxS "Plant-Associated" extension but I could not find it in the NMDC schema documentation or [mixs.yaml](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml), is there a reason it did not get imported? 

host_disease_stat
List of diseases with which the host has been diagnosed; can include multiple diagnoses. The value of the field depends on host; for humans the terms should be chosen from the DO (Human Disease Ontology) at https://www.disease-ontology.org/, non-human host diseases are free text
Expected_value: disease name or Disease Ontology term

This is an EMSL metadata field, adding to the schema to support EMSL users in the submission portal.

**Comment by bmeluch** [comment]
@turbomam @mslarae13 any guidance or thoughts on this slot/importing this slot from MIxS?

**Comment by turbomam** [comment]
There is a long complicated story about how MIxS terms have been imported into the nmdc-schema, and that's about to change with 
- https://github.com/microbiomedata/nmdc-schema/pull/1386

For now, I have tied this issue to a branch, which will turn into a PR very shortly. It imports the definition of `host_disease_stat` into src/schema/mixs.yaml and makes `host_disease_stat` available to the `Biosample` class.

**Comment by turbomam** [comment]
https://github.com/microbiomedata/nmdc-schema/pull/1408/files

**Comment by bmeluch** [comment]
Thank you @turbomam for context + dealing with the complicated import issue!
