### ISSUE TITLE
Add slots: infiltration_1 / infiltration_2 / infiltration_notes

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-schema#1338]
infiltration_1	
infiltration time 1
Description: Amount of time it takes to accomplish the first infiltration activity

infiltration_2	
infiltration time 2
Description: Amount of time it takes to accomplish the second infiltration activity

infiltration_notes
infiltration notes
Description: Provide any details, issues, or context needed to understand the infiltration activity

These are EMSL metadata fields, adding to the schema to support EMSL users in the submission portal.
All new slots or expanded extension associations will be communicated back to GSC.

**Comment by turbomam** [comment]
Would it be OK to use the following names:

- infiltration_time_1
- infiltration_time_2
- infiltration_notes

The EMSL preferred names could be aliases

These terms should have see_also assertions that point to documentation bout why there would be a first and second infiltration

**Comment by turbomam** [comment]
Also, could we model with with a single `multivalued` `inflitraions` slot?

**Comment by bmeluch** [comment]
As far as we can tell from 
* submitting and retrieving a test biosample JSON with multivalued slots in the dev API
* using the flag "list_elements_ordered: true"
* discussing YAML, JSON, and Python data structure specifications with the team
multivalued slots will retain their order. Moving ahead with creating "infiltrations" as an ordered multivalued slot.

**Comment by mslarae13** [comment]
@bmeluch I'm not sure what syntax we landed on for these terms, but we'd like it to be HH:MM:SS

**Comment by mslarae13** [comment]
@ssarrafan I added this to the sprint. It's been in progress and was delayed waiting for a review on the PR.
