### ISSUE TITLE
group class for workflow execution activities

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#134]
@cmungall @scanon 

@dehays and I came up with the following proposal for grouping together metagenome and metatranscriptome workflows.

First create a high-level `biological analysis` class:
```
biological analysis:
    slots:
      - has part
 ```

Next, inherit from this high-level class for the metagenome, metatranscriptome (and other potential needs):
```
metagenome analysis:
    is_a: biological analysis
    slot_usage:
      has part:
        range: metagenome activity ### CREATE THIS CLASS

  metatranscriptome analysis:
    is_a: biological analysis
    slot_usage:
      has part:
        range: metatranscriptome activity ### CREATE THIS CLASS
```
The `### CREATE THIS CLASS` comments mean that these classes are not in data model yet.

**Comment by dehays** [comment]
Example from Shane: /global/cfs/cdirs/m3408/ficus/pipeline_products/nmdc:mga0s317

**Comment by dehays** [comment]
`{
  "has_input": [], 
  "part_of": "nmdc:mga0s317", 
  "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1", 
  "has_output": [], 
  "was_informed_by": "gold:Gp0213371", 
  "id": "nmdc:mga0s317", 
  "execution_resource": "NERSC-Cori", 
  "name": "Metagenome Analysis Activity for nmdc:mga0s317", 
  "started_at_time": "2021-08-05T14:48:51+00:00", 
  "type": "nmdc:metagenomeAnalysisActivity", 
  "ended_at_time": "2021-08-20T19:18:04+00:00"
}`

`{
  "has_input": [
    "nmdc:22afa3d49b73eaec2e9787a6b88fbdc3"
  ], 
  "part_of": "nmdc:mga0s317", 
  "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1", 
  "has_output": [
    "nmdc:f107af0a000ec0b90e157fc09473c337", 
    "nmdc:71528f677698dd6657ea7ddcc3105184"
  ], 
  "was_informed_by": "gold:Gp0213371", 
  "input_read_count": 102766230, 
  "output_read_bases": 15235297055, 
  "id": "nmdc:e78b28249268b5341cdb42c9c3c468d6", 
  "execution_resource": "NERSC-Cori", 
  "input_read_bases": 15517700730, 
  "name": "QA Activity for nmdc:mga0s317", 
  "output_read_count": 101660590, 
  "started_at_time": "2021-08-05T14:48:51+00:00", 
  "type": "nmdc:qaActivity", 
  "ended_at_time": "2021-08-20T19:18:04+00:00"
}
`

**Comment by ssarrafan** [comment]
Should this issue be added to the November sprint? @wdduncan @dehays

**Comment by ssarrafan** [comment]
Per @wdduncan re-assigning to @sujaypatil96  and moving to the March sprint but please let me know if this is not a priority and we can move it to the backlog
FYI @cmungall @turbomam 

Note from Bill:
HI Set. Here is an update:
https://github.com/microbiomedata/nmdc-schema/issues/134
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-runtime/issues/89
I updated the comment on this. I should be able to get the change sheet edit done before I leave.
https://github.com/microbiomedata/nmdc-schema/issues/195
I am working with Sujay on this. I should be able to close before the week’s end.
https://github.com/microbiomedata/nmdc-runtime/issues/46
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-server/issues/555
This is a lot of conversation in this thread. But, it looks like Mark has taken this one over.

**Comment by ssarrafan** [comment]
Removing from sprint and adding backlog label per @sujaypatil96

**Comment by turbomam** [comment]
Hasn't this been addressed with the [WorkflowExecutionActivity](https://microbiomedata.github.io/nmdc-schema/WorkflowExecutionActivity/)  parent class?

**Comment by aclum** [comment]
@turbomam  I agree, let's close and we can revisit later if it becomes a problem.
