### ISSUE TITLE
new rule: WorkflowExecutionActivity must have either some outputs OR a quality control report with status failed 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1349]
In other words, the `has_output` required `slots_usage`  would be commented out and a `recommended` annotation would be added

cc @mbthornton-lbl @Michal-Babins @aclum

**Comment by turbomam** [comment]
See the [Doi rules](https://github.com/microbiomedata/nmdc-schema/blob/0b9a115d18c83ffd8489690663a0016d2e32dcfe/src/schema/nmdc.yaml#L1370-L1396) for inspiration.

**Comment by turbomam** [comment]
https://linkml.io/linkml/schemas/advanced.html#rules

**Comment by brynnz22** [comment]
@aclum did you want me to add this rule for you? If so, which branch should I work off of?

**Comment by turbomam** [comment]
Another solution to all of this is saying that a failed WEAs does have some `DataObject` as its output... and add the QC report slots either globally to `DataObject`, or to a QcReport subclass of `DataObject`

**Comment by aclum** [comment]
@brynnz22  please add to this branch if you have time https://github.com/microbiomedata/nmdc-schema/tree/1333-expanded-use-of-quality_control_report

**Comment by aclum** [comment]
related to #1333

**Comment by brynnz22** [comment]
@aclum I added the rule. This will need to be tested once the rest of the schema changes are in place, but I believe this is what it would look like. I am guessing you will be adding `quality_control_report` as a slot on `WorkflowExecutionActivity`?

**Comment by turbomam** [comment]
Can we add the full matrix of examples?
- valid
  - with outputs and with a valid/successful QC report
  - lacking output, with a failed QC report
- invalid
  - lacking output but with a valid/successful QC report
  - with outputs but with a failed QC report
- *I don't know*
  -  with outputs and lacking any QC report
  -  lacking outputs and lacking any QC report

**Comment by brynnz22** [comment]
rule will require a linkml feature request. Request here: https://github.com/linkml/linkml/issues/1751

**Comment by brynnz22** [comment]
@aclum should we close this issue since it can't be done right now?

**Comment by ssarrafan** [comment]
New rule has been added by Brynn.  If there are any next steps please open new GH issues and link back to this issue.

**Comment by aclum** [comment]
Just a clarification, this was canceled not completed due to linkml limitations.
