### ISSUE TITLE
resolution of `nmdc`-prefixed schema element, JSON data objects and DataPortal pages

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1359]
possible duplicate issue

- list resolvers
  - [bioregistry](https://bioregistry.io/registry/nmdc)
  - [w3id via .htaccess](https://github.com/perma-id/w3id.org/blob/master/nmdc/.htaccess)
  - [identifiers.org](https://registry.identifiers.org/registry/nmdc)/miriam
- list endpoints/destinations 
  - [nmdc-schema documentation pages on GH pages](https://microbiomedata.github.io/nmdc-schema/Biosample/)
  - [DataPortal representations of selected Class' instances, like Study and Biosample](https://data.microbiomedata.org/details/study/nmdc:sty-11-28tm5d36)
  - [nmdc-runtime document id endpoint](https://api.microbiomedata.org/nmdcschema/ids/nmdc:sty-11-28tm5d36)

**Comment by turbomam** [comment]
_prefer_ not to use DRS for getting objects (multiple steps?)

**Comment by turbomam** [comment]
nmdc.yaml says

```yaml
  nmdc: https://w3id.org/nmdc/
```
working schema element resolution:
- nmdc:Biosample -> https://w3id.org/nmdc/Biosample -> https://microbiomedata.github.io/nmdc-schema/Biosample/
woprking endpoint ofr a data object:

https://api.microbiomedata.org/nmdcschema/ids/nmdc:sty-11-28tm5d36

not to be confused with https://api.microbiomedata.org/nmdcschema/ids/nmdc:sty-11-28tm5d36

**Comment by turbomam** [comment]
see also
- https://github.com/identifiers-org/identifiers-org.github.io/issues/233

**Comment by turbomam** [comment]
https://api-dev.microbiomedata.org/docs#/objects/get_object_info_objects__object_id__get

`/objects/{object_id}`

> Resolution strategy:
> 
>     if object_id.startswith("sty"): # nmdc:Study typecode then try https://data.microbiomedata.org/details/study/nmdc:{object_id}
>     if object_id.startswith("bsm"): # nmdc:Biosample typecode then try https://data.microbiomedata.org/details/sample/nmdc:{object_id}
>     if object_id.startswith some known typecode then try https://api.microbiomedata.org/nmdcschema/ids/nmdc:{object_id}
>     try https://w3id.org/nmdc/{object_id}
>     try mdb.objects.find_one({"id": object_id})

**Comment by dwinston** [comment]
related: https://github.com/microbiomedata/nmdc-server/issues/1058

**Comment by dwinston** [comment]
this should be close-able once https://github.com/microbiomedata/nmdc-runtime/pull/405 is merged and released.

**Comment by sujaypatil96** [comment]
Related issue:
* https://github.com/microbiomedata/nmdc-schema/issues/1611
