### ISSUE TITLE
Remove static page Table of Identifier Typecodes for each Class (`src/docs/typecode_table.md`)

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#1360]
The static web documentation page titled: _Typecodes per class_ (that can be found here: [Table of Identifier Typecodes for each Class](https://microbiomedata.github.io/nmdc-schema/typecode_table/)) is currently out-of-date (and can go out of date very easily as and when there are updates to the schema). Therefore it is important to have a dynamic way of maintaining a list of all the typecodes and their corresponding classes. 

There is now an endpoint in the NMDC runtime: `/nmdcschema/typecodes` (https://api.microbiomedata.org/docs#/metadata/get_nmdc_schema_typecodes_nmdcschema_typecodes_get) which returns a list of all the typecodes and their classes.

Make a note about the usage of this endpoint somewhere on the [Identifiers in NMDC](https://microbiomedata.github.io/nmdc-schema/identifiers/) page and remove [Table of Identifier Typecodes for each Class](https://microbiomedata.github.io/nmdc-schema/typecode_table/)

**Comment by turbomam** [comment]
https://api-dev.microbiomedata.org/docs#/metadata/get_nmdc_schema_typecodes_nmdcschema_typecodes_get
