### ISSUE TITLE
Data harmonizer templates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#137]
Test data harmonizer as a tool for curating data

**Comment by ssarrafan** [comment]
@turbomam can we close this issue?  Maybe with a link to the latest templates/repo?

**Comment by turbomam** [comment]
- Here are the templates: https://github.com/turbomam/DataHarmonizer/tree/master/template
- From this repo: https://github.com/turbomam/DataHarmonizer
- Based on this code: https://github.com/microbiomedata/nmdc-metadata/blob/issue-375/notebooks/build_dh_mixs_templates.ipynb

Remaining to do:
- add columns based on input from @mslarae13. 
    - Set analysis results at https://github.com/microbiomedata/nmdc-metadata/blob/issue-398/notebooks/soil_slot_column_analysis_curated.json. 
    - Resolving this may require requesting new terms or requesting new package/slot associations from MIxS.
- move this work into a https://github.com/microbiomedata repo

**Comment by ssarrafan** [comment]
I will close this one then and create a new issue for October related to adding columns based on input from Montana.
