### ISSUE TITLE
`napa_compliance` branch: Format source code using `black`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1381]
Several NMDC projects (e.g. `nmdc-schema`, `nmdc-runtime`) depend upon a code formatter called [`black`](https://pypi.org/project/black/) to force their source code to adhere to some formatting rules.

Here are some examples of what it does:

- Surround equals signs with whitespace when used for assignment, but not when used for kwargs:

```diff
- person=fn(thing = "foo", other_thing= "bar")
+ person = fn(thing="foo", other_thing="bar")
```

- Ensure indentation length is consistent throughout the file:

```diff
  for item in items:
-   if condition is True:
+     if condition is True:
-    do_something(item)
+         do_something(item)
```

Here's how someone could install and run it on the source code files introduced in the [napa_compliance](https://github.com/microbiomedata/nmdc-schema/tree/napa_compliance) branch:

```shell
# Install it.
pip install black

# Run it.
python -m black nmdc_schema/connect_napa_mongo.py
python -m black nmdc_schema/metab_id_refactor.py
python -m black nmdc_schema/napa_study_biosample_omics_migration.py
python -m black nmdc_schema/runtime_api_operations.py

# Commit the result.
git add .
git commit -m "Format source code using black"
git push
```

**Comment by eecavanna** [comment]
I'll fix this and tag @aclum in a PR.

**Comment by aclum** [comment]
I think we can close this, I just merged the PR.

**Comment by eecavanna** [comment]
I agree. I'll close it now. Thanks for merging the PR!
