### ISSUE TITLE
remove stray whitespace at the end of `MixingProcess`'s description

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1409]
It appears that there is a whitespace after 

> more homogeneous state.

Because of that, Markdown italics can't be applied to the description on https://microbiomedata.github.io/nmdc-schema/MixingProcess/

@sujaypatil96 do you have anything to add to this?

**Comment by JamesTessmer** [comment]
Is the best way to resolve this to just do a small PR? or is there a more efficient way?

**Comment by turbomam** [comment]
if you know how to do a drive-by PR in a branch, you can do that from the GitHub web interface. I can walk you through that if you want.

Otherwise, yes, just use the standard issue -> branch -> PR flow.

**Comment by JamesTessmer** [comment]
Made the change, created PR https://github.com/microbiomedata/nmdc-schema/pull/1416
