### ISSUE TITLE
empty strings and empty lists are not acceptable in example data files

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1415]
@aclum can you please help me identify who "owns" these tests? Or who I should consult with? I did the last edits :-(

```shell
grep -r "''" src/data/
```

- src/data/valid/Database-with-MetagenomeSequencingActivity.yaml:    git_url: ''
- src/data/valid/MetagenomeSequencingActivity-from-metagenome_seequencing_activity_json.yaml:git_url: ''
- src/data/problem/uncertain/MetagenomeSequencingActivity-bad_id.yaml:git_url: ''
- src/data/invalid/MetagenomeSequencingActivity-no_parthood.yaml:git_url: ''

**Comment by turbomam** [comment]
most of the `git_url` values in the tests don't really look like GitHUb URLs

```shell
grep -r git_url src/data/
```

- src/data/valid/Database-mags-activities.yaml:    git_url: https://img.jgi.doe.gov
- src/data/valid/Database-mags-activities.yaml:    git_url: https://img.jgi.doe.gov
- src/data/valid/Database-metagenome-assembly.yaml:    git_url: https://github.com/microbiomedata/metaAssembly/releases/tag/1.0.0
- src/data/valid/Database-metagenome-assembly.yaml:    git_url: https://github.com/microbiomedata/metaAssembly/releases/tag/1.0.0
- src/data/valid/Database-metagenome-assembly.yaml:    git_url: https://github.com/microbiomedata/metaAssembly/releases/tag/1.0.0
- src/data/valid/Database-neon_Biosample_to_DataObject_NEON.yaml:  git_url: https://github.com/microbiomedata/ReadsQC
- src/data/valid/ReadQcAnalysisActivity-1.yaml:git_url: git_url1
- src/data/valid/Database-MetabolomicsAnalysisActivity-1.yaml:    git_url: https://example.org/WorkflowExecutionActivity
- src/data/valid/Database-with-MetagenomeSequencingActivity.yaml:    git_url: ''
- src/data/valid/Database-nom_analysis_activity_set.yaml:    git_url: xxx
- src/data/valid/MetabolomicsAnalysisActivity-1.yaml:git_url: https://example.org/WorkflowExecutionActivity
- src/data/valid/MetagenomeSequencingActivity-from-metagenome_seequencing_activity_json.yaml:git_url: ''
- src/data/valid/Database-neon_Biosample_to_DataObject_NEON.json:      "git_url": "https://github.com/microbiomedata/ReadsQC",
- src/data/problem/uncertain/Database-nom_analysis_activity_set-non-string-ended_at_time.yaml:    git_url: xxx
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-img_mg_annotation_objects.yaml:  git_url: https://img.jgi.doe.gov
- src/data/problem/uncertain/Database-nom_analysis_activity_set-invalid-string-ended_at_time.yaml:    git_url: xxx
- src/data/problem/uncertain/MetagenomeSequencingActivity-bad_id.yaml:git_url: ''
- src/data/invalid/MetagenomeSequencingActivity-no_parthood.yaml:git_url: ''

**Comment by aclum** [comment]
I think you createed the first two based on the commit history. Just a note that MetagenomeSequencingActivity exists but is effectively depricated since it is redundant/overlapping with OmicsProcessing.
aside from src/data/invalid/MetagenomeSequencingActivity-no_parthood.yaml having legacy ids it looks valid to me. part_of is not required for WorkflowExuectionActivity subclasses..

**Comment by aclum** [comment]
What is the expected/desired behavior for MetagenomeSequencingActivity-bad_id.yaml?

**Comment by kheal** [comment]
None of the example files listed exist in Berkeley fork.  All existing examples with git_url in Berkeley fork have complete git_url slots.
