### ISSUE TITLE
remove or refactor `nucleic_acid_concentration` slot

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1439]
It's not used in MongoDB. It's range is asserted to be `InstrumentValue`, which doesn't make any sense. `InstrumentValue` is also going to be removed.

It was a `see_also` for the following slots
- `dna_concentration` _in `src/schema/portal/jgi_metagenomics.yaml`_
- `rna_concentration` _in `src/schema/portal/jgi_metatranscriptomics.yaml`_

It was associated with class `ProcessedSample` _in `src/schema/core.yaml`_

It is commented out as a slot on a ProcessedSample in the following. In these cases, it illustrates a hybrid `QuantityValue`/`InstrumentValue` structure
- _src/data/problem/uncertain/Database-analytical_sample-extract-exhaustive.yaml_
- _src/data/valid/Database-processed_sample-extract-exhaustive.yaml_

`assets/misc/neon_nmdc_term_mapping.tsv` also suggests that it be used in the `QuantityValue`/`InstrumentValue` style in support of NEON's `nucleicAcidConcentration` and `nucleicAcidQuantMethod`

cc @aclum @mslarae13

**Comment by mslarae13** [comment]
So we did this before we had 'JGI MT Interface' and 'JGI MG Interface' in the submission schema. I agree, we make nucleic_acid_conc (and do the same for all the other rna & dna shared slots) .... and then have slot usage for the MT and MG interfaces as necessary. 

@pkalita-lbl  fyi
