### ISSUE TITLE
when to use `used` vs `instrument_name` vs `instrument_used`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1446]
This should all be simplified with a minimal number of slots that allow a process to assert what technology was employed, as either a permissible value from an enumeration **or** an instance of a class (with or without identifier?) that can encapsulate details like vendor, model, location, etc.

- `Activity` instances can use the `used` slot with a `string` range. Update to enumeration?
- `OmicsProcessing` instances can use the `instrument_name` slot with a `string` range, to be updated to an enumeration
- `FiltrationProcess` and `MixingProcess` instances can use the `instrument_used` slot with an `AnonymousInstrument` range. This slot name and range should probably be refactored. Note that a better range might be a `any_of` union that also includes `DataGeneratingInstrument`

cc @anastasiyaprymolenna

**Comment by aclum** [comment]
We decided the following 
- [ ] a new class `Instrument `with slots (look through existing slots)
something like
id, name, vendor, model 

- [ ] new multivalued slot `instrument_used` on classes `MaterialProcessing`, `DataGeneration` with a Range of class `Instrument` 
- [ ] remove instrument_name

**Comment by aclum** [comment]
related to https://github.com/microbiomedata/nmdc-schema/issues/1528

**Comment by aclum** [comment]
for now use a range of an enumeration with permissible values for instrument mode  and instrument vendor.
