### ISSUE TITLE
reintroduce `nucleic_acid_concentration` 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1453]
see also:
- https://github.com/microbiomedata/nmdc-schema/pull/1441

In the domain of a `ProcessedSample` (and/or `Biosample`?)

It seems like there is a desire to capture both the concentration and the method by which the concentration was determined.

There are lots of ways to model this. I think the following has a good balance of encapsulation, re-usability and simplicity.

- `ProcessedSample` has a `has_analyate_info` relationship with zero or more `AnalyteInfo` instances
- `AnalyteInfo` would have an `analyte_category` relationship with one enumerated value like 'DNA', 'RNA', etc
- `AnalyteInfo` would have an `instrument_name` or `used` etc. relationship with one enumerated value like `UV absorption`, `fluorescence`, etc.
- `AnalyteInfo` would have a `nucleic_acid_concentration` relationship with one `QuantityValue`

**Comment by aclum** [comment]
Not a priority for modeling, closing and will reopen if needed.
