### ISSUE TITLE
Simplify migrator modules and their usage

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1456]
I propose the following things be done (I'm planning to do them):

- [x] 1. Don't assume transformation functions modify the dictionary _in place_
- [x] 2. Name every migrator class `Migrator` instead of `Migrator_from_...`
- [x] 3. Make `agenda` be a "private" variable (i.e. `_agenda`)

Details:

### 1. Don't assume transformation functions modify the dictionary _in place_

In `migration_recursion.py`, capture the dictionary returned by the transformer and pass that to the next transformer. The fact that the existing transformers all happen to migrate the input dictionary in place is a coincidence. They could just as well make a copy of the input dictionary and return a distinct dictionary.

https://github.com/microbiomedata/nmdc-schema/blob/d1593296fbb0e296e86fa4f8c8d3be7fe63b2b01/nmdc_schema/migration_recursion.py#L178

### 2. Name every migrator class `Migrator` instead of `Migrator_from_...`

The current naming convention has the same suffix in both the module name and the class name. The module name alone will be sufficient to know what schema versions the migrator class _within it_ deals with. Python's import system allows for `import`ers to designate an alias for an imported thing (e.g. `import thing as my_thing`). 

This will simplify the "class-finding" code in `migration_recursion.py` (the class name would always be `Migrator`):

https://github.com/microbiomedata/nmdc-schema/blob/d1593296fbb0e296e86fa4f8c8d3be7fe63b2b01/nmdc_schema/migration_recursion.py#L107-L110

It will also further reduce (by one) the number of lines an `nmdc-runtime` developer would have to edit when making a migration notebook based off an existing one.

### 3. Make `agenda` be a "private" variable (i.e. `_agenda`)

I do not want anyone/anything to update it during runtime. It's gotta remain an instance variable, though, since it may reference instance methods.

### 4. (Deferred) Update `migration_recursion.py` to, optionally, determine the latest migration class dynamically

Currently, when introducing a new migrator class to `nmdc-schema` the author of that class has to update the `migration_recursion.py` CLI options in a Makefile so that that new migrator class is referenced within them. I want there to be a CLI option that is something like `--use-latest-migrator`, which will always find the latest migrator class (so the class author doesn't have to update the Makefile).

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint, adding backlog label. Please update or add to next sprint if still active.

**Comment by eecavanna** [comment]
Still active. PR is in review.

**Comment by ssarrafan** [comment]
> Still active. PR is in review.

ok I will move it to the current sprint @eecavanna

**Comment by eecavanna** [comment]
I opened a [PR](https://github.com/microbiomedata/nmdc-runtime/pull/425) in `nmdc-runtime` that has the corresponding changes there (i.e. it imports a class named `Migrator`). I'm holding off on merging it until the changes in this PR (this one in `nmdc-schema`) have been published to PyPI (e.g. some time in January).
