### ISSUE TITLE
`in_subset` slot should be used as `multivalued` throughout

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1464]
see https://linkml.io/linkml-model/latest/docs/in_subset/

In some cases, the Python Dataclasses data loader silently repairs singe-valued/multi-valued mismatches, but we shouldn't count on that, because we might change to a Pydantic data loader in the future.

please change the 

`in_subset: data_portal_subset` lines to

```yaml
in_subset:
  - data_portal_subset
```

**Comment by brynnz22** [comment]
I'll do this next sprint!

**Comment by turbomam** [comment]
This search shows all in_subset assertions in the schema. I'm including the line after the beginning of the assertion to emphasize whether the list notation is being used properly.

```shell
grep -A 1 -r 'in_subset:' src/schema/
```

# BAD SCALAR  FORMATTING

src/schema/basic_classes.yaml:    in_subset: data_portal_subset
src/schema/basic_classes.yaml-    examples:
--
src/schema/basic_slots.yaml:    in_subset: data_portal_subset
src/schema/basic_slots.yaml-    range: uriorcurie
--
src/schema/basic_slots.yaml:    in_subset: data_portal_subset
src/schema/basic_slots.yaml-    examples:
--
src/schema/basic_slots.yaml:    in_subset: data_portal_subset
src/schema/basic_slots.yaml-    examples:


## OK

src/schema/basic_classes.yaml:    in_subset:
src/schema/basic_classes.yaml-      - sample subset
--
src/schema/basic_classes.yaml:    in_subset:
src/schema/basic_classes.yaml-      - data object subset
--
src/schema/basic_classes.yaml:    in_subset:
src/schema/basic_classes.yaml-      - sample subset
--
src/schema/basic_classes.yaml:    in_subset:
src/schema/basic_classes.yaml-      - workflow subset

src/schema/core.yaml:    in_subset:
src/schema/core.yaml-      - workflow subset
--
src/schema/core.yaml:    in_subset:
src/schema/core.yaml-      - sample subset
--
src/schema/core.yaml:    in_subset:
src/schema/core.yaml-      - mixs extension
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
--
src/schema/workflow_execution_activity.yaml:    in_subset:
src/schema/workflow_execution_activity.yaml-      - workflow subset
