### ISSUE TITLE
(IN PROGRESS) 2023-12 Schema Refactoring Priorities

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1466]
A super issue to capture all the changes to be made. These issues are at the Class level & should be broken down as necessary.

- [x] #1513
- [x]  #1547
- [x] #1514
- [x] #1518
- [x] Create Class:DataGeneration  
- [x] #1549
- [x] #1552 
- [x] #1551 
~- [ ] Reroute all subclasses of Activity to become subclasses of WorkflowExecution~
~- [ ] Incorporation of QC for PlannedProcesses~
- [x] #1525
- [x] Move OmicsProcessing sub classes 
- [x] #1557
- [x] Change omics_type to omics_target or ? and change to Enum
- [x] #1521
- [x] #1123 
- [x] #1144 
- [x] #251 
- [x] #1519
- [x] Create subclass of MaterialProcessing Class:DissolvingProcess 
- [x] Move DissolvingActivity to be a PlannedProcess
~- [ ] Create subclass of MaterialProcessing Class:Acidification~ -- Captured in reaction
- [x] #1524
- [x] Deprecate chimera_check slot
- [x] #1528
- [x] #1529
- [x] #1530 
- [x] ~#1531~
- [x] #1532
- [x] ~#1533~
- [x] #1570
- [x] #1536
- [x] #1537
- [x] #1548
- [x] #1550
- [x] #1556
- [x] #1564
- [x] #1566
- [x] #1048 
- [x] #1562 
- [x] Make Class:InstrumentData (not class, data_category slot on Class:DataObject)
- [x] Make Class:ProcessedData (not class, data_category slot on Class:DataObject)
- [x] #1581
- [x] #1560
- [x] #1666
- [x] #1681
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1736
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1762
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1777
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1779
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1831

Low priority
- [ ] Remove all references to OmicsProcessing

Did not get to
- [ ] #1727
- [x] #1725
- [x] Remove 'type' from slots, change to _category or ??
-- Review library_type and determine if it should be part of the 1st RC, or do it in a future RC
- [x] #1030 
- [x] #1027 
- [ ] #1000 
- [x] #984 
- [ ] Add sequencing instruments to the enums
-- Updating enums is easy, can skip for initial RC and will visit later
- [X] refactor MetaboliteQuantifiaction (changed the name, MetaboliteIdentification)
- [x] #1580
- [ ] Update dna and rna concentration slots to be just nucleic acid concentration (or more general?, peptide?)
-- Issues created, not a task for berk. Currently assigned to a class that does go to mongo. 
- [ ] review instrument_name_enum in basic_slots.yaml
-- Updating enums is easy, can skip for initial RC and will visit later
- [x] #1606
- [x] update data_object_type to not use type

**Comment by turbomam** [comment]
thanks, @mslarae13 

how does this relate to 
- https://github.com/microbiomedata/nmdc-schema/issues/1237

**Comment by mslarae13** [comment]
@turbomam that is the list of proposed updates. This is the list of things we are definitely doing & prioritizing.

**Comment by brynnz22** [comment]
- [ ] remove `part_of` slot from `WorkflowExecutionActivity`

**Comment by mslarae13** [comment]
Stretch Goals / Things to keep in mind when these changes are merged into main

- [ ] Reaction vs ReactionProcess. what is the right terminology here & which should be updated.
- [ ] Determine a parent class for PeptideQuantification, ProteinQuantification, etc?
- [ ]

**Comment by mslarae13** [comment]
ProtocolExecution vs PlannedProcess and finding the data for the user. User / data discovery is required to know if they want an execution or planned process and that's a problem.  I will connect / make a broader issue for this 

In progress

**Comment by mslarae13** [comment]
For InstrumentVendorEnum and InstrumentModelEnum we will investigate the ability to make it more generalizable list of these models and vendors so NMDC is not required to keep an extensive and constant updated list.

@lamccue @corilo @SamuelPurvine @cmungall

**Comment by brynnz22** [comment]
See list of migration scripts in progress: https://github.com/microbiomedata/nmdc-schema/issues/1607

**Comment by mslarae13** [comment]
Are there really no additional slots to be compelted for Class:Pooling ? Currently, only the inherited slots at part of this class
@anastasiyaprymolenna @aclum (anything from NEON we missed?)

`
Pooling:
    class_uri: nmdc:Pooling
    is_a: MaterialProcessing
    description: physical combination of several instances of like material.
    slots:
    exact_mappings:
      - OBI:0600016
    slot_usage:
      has_input:
        minimum_cardinality: 2
      has_output:
        minimum_cardinality: 1
        maximum_cardinality: 1
      id:
        required: true
        structured_pattern:
          syntax: "{id_nmdc_prefix}:poolp-{id_shoulder}-{id_blade}{id_version}{id_locus}"
          interpolated: true
`

**Comment by brynnz22** [comment]
After talking with @aclum this issue needs to be completed https://github.com/microbiomedata/nmdc-schema/issues/1617 (allowing omprc typcodes on subclasses of DataGeneration) so that this migration: https://github.com/microbiomedata/berkeley-schema-fy24/pull/29 (move has_calibration to MassSpectrometry) can happen.

**Comment by aclum** [comment]
@mslarae13  not really for pooling. These are the fields NEON has for the pooling table
uid,domainID,siteID,plotID,namedLocation,startDate,collectDate,eventID,samplingProtocolVersion,genomicsPooledIDList,genomicsSampleID,genomicsSampleCode,sampleCondition,processedBy,remarks,genomicsDataQF

**Comment by aclum** [comment]
unchecking #1537 b/c we need to evaluatate if we can  repair referential integrity (not all omics_processing_set records have has_output populated or if we need to leave was_informed by. Simplest thing is to leave was_informed_by for now.

**Comment by mslarae13** [comment]
Some work from https://github.com/microbiomedata/nmdc-schema/issues/1752 will be done in the berkeley fork in a new branch. That will be a long running branch that we will NOT merge back into the berkeley fork.

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/nmdc-schema/issues/1760
