### ISSUE TITLE
Build and Deploy Static Mkdocs Documentation vs openpyxl

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#148]
https://github.com/microbiomedata/nmdc-schema/actions/runs/1257938882

> An error occurred while installing openpyxl==3.0.8; python_version >= '3.6' --hash=sha256:4f2770348c029ce9433316ced8f91ed37d2a605e654f8bfdc93a3524561a8ce2 --hash=sha256:52150a09b660fe444af7abe2592b156c14e324526b1968a57705525547317a7f! Will try again.
Installing initially failed dependencies...
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement openpyxl==3.0.8 (from versions: 1.1.0, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.1, 1.6.2, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.4, 2.4.5, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.10, 2.5.11, 2.5.12, 2.5.14, 2.6.0a1, 2.6.0b1, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for openpyxl==3.0.8
ERROR: Couldn't install package: openpyxl

**Comment by wdduncan** [comment]
@turbomam @cmungall Closing this issue. I assume adding openpyxl fixed the issue.
