### ISSUE TITLE
`pure-export` should handle empty `selected-collections`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1485]
> ```
> Attempting to get 0 documents from nmdcschema/activity_set in pages of 200000.
> warning: 400 Client Error: Bad Request for url: https://api.microbiomedata.org/nmdcschema/activity_set?max_page_size=200000
> warning: FastAPI request to nmdcschema/activity_set appears to have failed. Trying as a PyMongo query.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/gitrepos/nmdc-schema/nmdc_schema/mongo_dump_api_emph.py", line 354, in cli
>     direct_data_all = nmdc_pymongo_client.get_docs_from_pymongo(current_collection, max_docs)
> UnboundLocalError: local variable 'nmdc_pymongo_client' referenced before assignment
> ```

**Comment by eecavanna** [comment]
When I visit the URL in the error message...

```
https://api.microbiomedata.org/nmdcschema/activity_set?max_page_size=200000
```

...I get the following response:

```json
{
  "detail": "Collection name must be one of {'pooling_set', 'metagenome_annotation_activity_set', 'extraction_set', 'read_based_taxonomy_analysis_activity_set', 'field_research_site_set', 'metabolomics_analysis_activity_set', 'planned_process_set', 'study_set', 'collecting_biosamples_from_site_set', 'mags_activity_set', 'data_object_set', 'metagenome_sequencing_activity_set', 'functional_annotation_agg', 'read_qc_analysis_activity_set', 'library_preparation_set', 'metagenome_assembly_set', 'biosample_set', 'nom_analysis_activity_set', 'metaproteomics_analysis_activity_set', 'omics_processing_set', 'material_sample_set', 'metatranscriptome_activity_set', 'processed_sample_set'}"
}
```

I don't see `activity_set` in the list. I wanted to point this out as the Issue name says "empty" (maybe based upon the first line of the error message, which says "0 documents"), while the HTTP request suggests to me something like "unrecognized".
