### ISSUE TITLE
`slot_usage` for `emsl_project_identifier` in `Study` has been commented out for a while. Should we reactivate it or remove it completely?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1490]
``` yaml
# emsl_project_identifier:
#  description: The EMSL project ID that relates to the NMDC submitted study
```

**Comment by mslarae13** [comment]
see https://github.com/microbiomedata/nmdc-schema/issues/1329

see https://github.com/microbiomedata/nmdc-schema/issues/927 

I believe this is the slot we agreed the [emsl.project:60141](https://bioregistry.io/reference/emsl.project:60141) identifier should go (related identifier) and it should resolve to https://www.emsl.pnnl.gov/project/60141

**Comment by mslarae13** [comment]
I'm closing this in favor of the above 2 issues. This slot should not be commented out.
