### ISSUE TITLE
if a domain is asserted for a slot, it should be displayed on the documentation page for that slot

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1494]
this is not the case for the [object_set](https://microbiomedata.github.io/nmdc-schema/object_set/) mixin

**Comment by sujaypatil96** [comment]
We added a column to the mixin usage table called 'domain'. Can you check if that satisfies the requirement for this issue?

**Comment by turbomam** [comment]
I am withdrawing my requests for asserting or displaying domains.
