### ISSUE TITLE
Modify `slot_usage` for `source_mat_id` in `Biosample`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1498]
@mslarae13 thanks for reviewing
- https://github.com/microbiomedata/nmdc-schema/pull/1449

You raised [one comment that I didn't understand how to address](https://github.com/microbiomedata/nmdc-schema/pull/1449#discussion_r1412591554)

I'm going to merge the PR now but we can revisit this whenever you want

**Comment by mslarae13** [comment]
Oh! My comment was just if the things we put in 'todo' should be in 'notes' so it doesn't show up in the documentation.. we talked about it a bit at the metabolink meeting today... I made this issue for @sujaypatil96  so it might be moot.

https://github.com/microbiomedata/nmdc-schema/issues/1495

**Comment by turbomam** [comment]
see
- #1898

**Comment by kheal** [comment]
Resolved by opening #1495
