### ISSUE TITLE
DRAFT: replace problematic "Solution" and "compound" modeling with  "Fluid" and "name"

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1508]
A Fluid class would be supportive of GC and LC.

The choice of a `compound`/`name`slot decision will depend on how we link form external reference knowledge about substances to processes that use the substances.

**Comment by anastasiyaprymolenna** [comment]
Will we be able to preserve the structure that allows multiple solution (or fluid) components that make up the "solution"?

**Comment by kheal** [comment]
Solution class has been replaced with `substances_used` and `PortionofSubstance` slot/class in berkeley schema.
