### ISSUE TITLE
Create MaterialProcessing class

### ISSUE THREAD

**Issue by anastasiyaprymolenna** [microbiomedata/nmdc-schema#1512]
See also: https://github.com/microbiomedata/nmdc-schema/issues/1466

Create the MaterialProcessing class to replace BiosampleProcessing

Removing BiosampleProcessing will be in a separate issue to follow this one.

**Comment by JamesTessmer** [comment]
see https://github.com/microbiomedata/berkeley-schema-fy24/tree/make-materialprocessing for working branch

**Comment by mslarae13** [comment]
For schema refactor https://github.com/microbiomedata/berkeley-schema-fy24/pull/1

**Comment by mslarae13** [comment]
Closing in favor of schema refactor issues
