### ISSUE TITLE
Identify slots to migrate off of DataGeneration (formerly Omicsprocessing)

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1516]
Review slots on DataGeneration and determine which slots belong on other classes.

**Comment by kheal** [comment]
@bmeluch - did you address this on the berkeley fork?  If so, can you link the PR here?

**Comment by bmeluch** [comment]
I think so! https://github.com/microbiomedata/berkeley-schema-fy24/pull/104
