### ISSUE TITLE
Remove the `Reaction` class, unused

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1521]
What is the use of Reaction vs ReactionParticipant?
How does this compare to or be used by a ReactionProcess for MaterialProcess

**Comment by turbomam** [comment]
You might be able to get some sense of that by looking at the GraphDB visual graph. Or I can explain later.

I think the essense of `Reaction` is that it is part of a `Pathway`... mostly a cellular biology concept, not a laboratory procedure concept.

**Comment by mslarae13** [comment]
Reaction to BiochemicalReaction @turbomam

**Comment by mslarae13** [comment]
@turbomam  do you think you can make the change of Class:Reaction to Class:BiochemicalReaction by the end of the week?

**Comment by mslarae13** [comment]
@turbomam I started a branch to do this change... https://github.com/microbiomedata/berkeley-schema-fy24/tree/1521-reaction-changeto-biochemicalreaction ... but I don't think it's as simple as renaming the class. 

I see `Reaction` in nmdc_materialized_patterns.yaml . can you take a look at this.

**Comment by turbomam** [comment]
thanks. can I work in the branch you started?

**Comment by mslarae13** [comment]
@turbomam definitely! :)

**Comment by turbomam** [comment]
I think this URL suggests that there isn't any difference between the main branch of the berkeley-schema-fy24 repo and the 1521-reaction-changeto-biochemicalreaction branch, but sometimes I misinterpret these kinds of things

**Comment by turbomam** [comment]
I just did a whole-word, case-sensitive find and replace of Reaction with BiochemicalReaction in src/schema.

`make squeaky-clean all test` is running now.

After that I'll locally regenerate the documentation and make sure it looks reasonable.

**Comment by turbomam** [comment]
OK, that all looked good to me. I have a PR for you to review:
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/64

Let me know if you want me to show you the new documentation before reviewing. Or you can generate it on your own with `make squeaky-clean all testdoc` in the `berkeley-schema-fy24`'s `1521-reaction-changeto-biochemicalreaction` branch.

**Comment by mslarae13** [comment]
Metabolic was too restrictive. This is a small part of all biochemical reactions.
Differentiate a chemical conversion process in a lab from a reaction or pathway that is owned by a gene. 
Suggestion, ReactionConcept.
Remove this until we're ready to use it and then evaluate the Class name?

**Comment by turbomam** [comment]
I think it would be good to have examples of when "metabolic is too restrictive" and to focus very clearly on the task of differentiating two things:
- reactions that a scientist might do in a laboratory (ChemicalConversionProcess)
- reactions that a gene, cell or sample is capable, such that one of those might be annotated with the reaction, traditionally as part of a pathway.

Yes, I will delete for now.

**Comment by mslarae13** [comment]
Update: still open. Reaction class was created for things like metacyte reactions. There's currently no path for using it. Just get rid of it.

**Comment by mslarae13** [comment]
@turbomam I thought I saw something where you were working on this? Is this in progress now?

**Comment by mslarae13** [comment]
@turbomam update? is this done?

**Comment by turbomam** [comment]
`Reaction` is no longer present as a class in berkeley-schema-fy24
