### ISSUE TITLE
Create subclass of MaterialProcessing Class:ReactionProcess

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1524]
Reviewing classes 
Reaction vs ReactionActivity vs ReactionParticipant

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/tree/make-ReactionProcess

**Comment by mslarae13** [comment]
relates to https://github.com/microbiomedata/nmdc-schema/issues/1521

**Comment by mslarae13** [comment]
* ChemicalConversionProcess

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/45

added to make acidification

**Comment by kheal** [comment]
@anastasiyaprymolenna This is completed on Berkeley fork, right?  If so, can you link PR?
