### ISSUE TITLE
Create / redistribute OmicsProcessing & slots

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1525]
- [x] deprecate chimera_check
- [x] #1535
- [x] #1540
- [x] #1541
- [x] #1543
- [ ] ~remove [principal_investigator](https://microbiomedata.github.io/nmdc-schema/principal_investigator/) from OmicsProcessing (DataGeneration)~
- [x] deprecate [samp_vol_we_dna_ext](https://microbiomedata.github.io/nmdc-schema/samp_vol_we_dna_ext/) & confirm the [input_mass](https://microbiomedata.github.io/nmdc-schema/input_mass/) exisiting slot satisfies
- [x] move [seq_meth](https://microbiomedata.github.io/nmdc-schema/seq_meth/) to Class:NucleotideSequecingClass
- [x] Remove seq_meth from OmicsProcessing (DataGeneration)
- [x] move [seq_quality_check](https://microbiomedata.github.io/nmdc-schema/seq_quality_check/) to 
- [x] remove classes that were added to LibraryPreparation from Biosample
- [x] remove classes that were added to LibraryPreparation from DataGeneration

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/tree/1525-add-slots-to-MaterialProcessing-classes-that-were-on-OmicsProcessing

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/42

**Comment by mslarae13** [comment]
@aclum to follow up on PI, merging the rest of the changes now.

**Comment by aclum** [comment]
@mslarae13 I did confirm that JGI provides PI at the sequencing project level in the GOLD projects API endpoint so the best mapping to NMDC classes is to leave this on DataGeneration. An alternative would be to put this on Biosample but would require more graph traversal. The use case for JGI having this slot and for NMDC to keep it is studies will multiple PIs like GROW where more granular resolution is needed.
