### ISSUE TITLE
Remove slot `used` from WorkflowExecution 

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1528]
Remove the `used` slot (refers to instrument _**used**_ to generate data)

Steps:
- Update LinkML model
- update examples / counter-examples

**Comment by mslarae13** [comment]
slot 'used' should not be on WorkflowExecution.

Some of the EMSL workflow records have used and it provides an instrument name.

It should NOT be on WorkflowExecution subclasses

It should ONLY be on DataGeneration. 
Migration to remove the data required.
