### ISSUE TITLE
Remove slow `part_of` from WorkflowExecution

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1530]
WorkflowExecution primarily relies on `informed_by` and `part_of` is not meaningful

Steps:

- Modify WorkflowExecution Class to remove slot
- Update data examples and counterexamples

**Comment by turbomam** [comment]
what does the qualifier "slow" mean in this RP title?

**Comment by mslarae13** [comment]
Cancelling. We need this now!
