### ISSUE TITLE
remove `was_informed_by` from `WorkflowExecution`

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1537]
Remove `was_informed_by` `WorkflowChain` will be the new grouping class to group all of the workflows together.

After `WorkflowChain` class is created and migration has ocurred.

**Comment by mslarae13** [comment]
we decided to keep this, didn't we @brynnz22

**Comment by brynnz22** [comment]
No, we are removing it from `WorkflowExecutionActivity`, but adding it to `WorkflowChain`

**Comment by mslarae13** [comment]
Migrate and fix ingest code (GOLD ingest pipeline) so it will make data objects. 
Move it from workflow execution activity to the chan. 
Will need to double check that there's no integrity issues. 

This is done, but during implementation and checks we will need to do a close check that we don't lose any records.
