### ISSUE TITLE
File `src/schema/nmdc.yaml` contains recurring typo (`byt`)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1553]
There's a recurring typo in `src/schema/nmdc.yaml`:

The word `by` is misspelled as `byt`.

For example:

https://github.com/microbiomedata/nmdc-schema/blob/7a8b423d132015117cbbadc069222718dd92bc2b/src/schema/nmdc.yaml#L2643

It occurs 25 times:

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/a5f83ba5-9d61-4e49-9ef5-bb97f8a05a29)

**Comment by eecavanna** [comment]
These (comment) typos still exist in the latest version of the schema.

https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L2686

Not urgent, in my opinion. I'm cleaning up/updating Issues I've been involved with.

**Comment by kheal** [comment]
Fixed on Berkeley fork.

**Comment by eecavanna** [comment]
Thank you!
