### ISSUE TITLE
Make execution_resource on WorkflowExecution into an enum

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1556]
Create enumeration for execution resource on Workflow Execution

**Comment by mslarae13** [comment]
@mbthornton-lbl can you add a description to this slot? https://microbiomedata.github.io/berkeley-schema-fy24/execution_resource/

**Comment by mslarae13** [comment]
Description added. Done.

**Comment by mslarae13** [comment]
done https://github.com/microbiomedata/berkeley-schema-fy24/pull/63
