### ISSUE TITLE
workflow_execution_activity should not have reciprocal dependencies with nmdc.yaml

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#1574]
(this issue refers to main on the berkeley fork)

 - workflow_execution_activity is imported by nmdc, yet it also depends on analyte_category which is defined in nmdc
 - core.file_size_bytes declares a domain of DataObject, which is defined in nmdc

**Comment by kheal** [comment]
This is fixed on Berkeley fork.
