### ISSUE TITLE
Add descriptions to ProteolyticEnzymeEnum

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1580]

**Comment by mslarae13** [comment]
relates to https://github.com/microbiomedata/berkeley-schema-fy24/pull/37

**Comment by mslarae13** [comment]
@SamuelPurvine and Montana will work on this one.

**Comment by SamuelPurvine** [comment]
https://microbiomedata.github.io/berkeley-schema-fy24/ProteolyticEnzymeEnum/

trypsin	
chymotrypsin	
lys_c	
lys_n	
glu_c	
arg_c	
asp_n	
alphalp

**Comment by SamuelPurvine** [comment]
Descripti0ons:
trypsin	- A serine protease that hydrolyzes the C-terminus of arginine and lysine
chymotrypsin - A serine protease that hydrolyzes the C-terminus of tryptophan, leucine, tyrosine, and phenylalanine
lys_c - A serine protease that hydrolyzes the C-terminus lysine
lys_n - A metalloendopeptidase that hydrolyzes the C-terminus lysine
glu_c - A serine protease that hydrolyzes the C-terminus of aspartic acid or glutamic acid
arg_c - A cystein protease that hydrolyzes the C-terminus of arginine and occasionally lysine	
asp_n - A zinc metalloendopeptidase that hydrolyzes the N-terminus aspardic acid
alphalp - A serine protease that hydrolyzes the C-terminus of threonine, alanine, serine, and valine

**Comment by lamccue** [comment]
added edits to descriptions:
trypsin - A serine protease that hydrolyzes peptide bonds at the C-terminus of arginine and lysine
chymotrypsin - A serine protease that hydrolyzes peptide bonds at the C-terminus of tryptophan, leucine, tyrosine, and phenylalanine
lys_c - A serine protease that hydrolyzes peptide, ester, and amide bonds at the C-terminus of lysine
lys_n - A metalloendopeptidase that hydrolyzes peptide bonds at the C-terminus of lysine
glu_c - A serine protease that hydrolyzes peptide and ester bonds at the C-terminus of aspartic acid or glutamic acid
arg_c - A cysteine protease that hydrolyzes peptide, ester, and amide bonds at the C-terminus of arginine and with lower efficiency, lysine
asp_n - A zinc metalloendopeptidase that hydrolyzes peptide bonds at the N-terminus of aspartic acid
alphalp - A serine protease that hydrolyzes peptide bonds at the C-terminus of threonine, alanine, serine, and valine

**Comment by anastasiyaprymolenna** [comment]
from Metadata meeting: add `meaning:` with terms from ontologies for each permissible value with a description

**Comment by SamuelPurvine** [comment]
Or perhaps I'm misunderstanding, and what's being looked for is something like:
_trypsin:
text: trypsin
description: A serine protease that hydrolyzes peptide bonds at the C-terminus of arginine and lysine
meaning: MS_1001251
aliases:_

And the descriptive nature of the ontology link isn't as important as which source is preferred, in this case https://www.ebi.ac.uk/ols4/ontologies/ms, as it is most closely related to the science area in question?

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/102
