### ISSUE TITLE
Re-add OmicsProcessing typecode as a valid regex for DataGeneration

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1581]
This is needed to support existing napa style ids for class DataGeneration, formerly known as OmIcsProcessing

**Comment by mslarae13** [comment]
@aclum this is for re-iding... but we're going to keep it when we merge the fork right, we won't re- re-ID things...

**Comment by aclum** [comment]
This is so we don't have to re-id currently napa compliant DataGeneration (formerly OmicsProcessing records) just because we've changed the class names.
