### ISSUE TITLE
What does the `see_also` of 'C01033' mean in the definition of `ChemicalConversionProcess` ?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1585]
At the very least, this requires a prefix

This format is reminiscent of a NCIT or KEGG term. Those are just-barely acceptable namespaces for nmdc-schema mappings. Let's try to find a mapping from OBI, schema.org or Wikidata

What should the `see_also` relationship be interpreted as? Could a [SKOS](https://www.w3.org/2004/02/skos/)-inspired [LinkML mapping](https://linkml.io/linkml-model/latest/docs/mappings/) be used instead?

**Comment by kheal** [comment]
This is no longer in the definition of `ChemicalConversionProcess` on berkeley branch.  Closing issue.
