### ISSUE TITLE
the `slot_usage` of `part_of` in `classes.WorkflowExecution` should not have `multivalued: false` (berkeley schema)

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1587]
the change from the global `multivalued: true` definition of `part_of` to  `multivalued: false` is non-monotonic

@cmungall can you please remind us where the current documentation about non-monotonic consequences is in the LinkML documentation?

**Comment by mbthornton-lbl** [comment]
Duplicates 
#1583

**Comment by turbomam** [comment]
see
- #1898
