### ISSUE TITLE
Please replace `AFO:/process#AFP_0000112` mapping for `DissolvingProcess` in berkeley schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1589]
AFO is a problematic ontology, both in terms of it's URI syntax and it's upper hierarchy

You will notice that it's not defined in [nmdc.yaml's prefixes block](https://github.com/microbiomedata/nmdc-schema/blob/c4186e295c7db2c957ce3cac5e62cc69167afce1/src/schema/nmdc.yaml#L35-L99)

Is there any reason we can't use [CHMO:0002773](https://www.ebi.ac.uk/ols4/ontologies/chmo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHMO_0002773) ?

**Comment by turbomam** [comment]
@turbomam  to double check and then close

**Comment by anastasiyaprymolenna** [comment]
this related issue has been closed https://github.com/microbiomedata/nmdc-schema/issues/1626 to resolve this open issue. can close.
