### ISSUE TITLE
Document which version of Apache Jena is required

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1603]
The repository contains a few reference to Apache Jena. Specifically:

https://github.com/microbiomedata/nmdc-schema/blob/c4186e295c7db2c957ce3cac5e62cc69167afce1/README.md?plain=1#L42

https://github.com/microbiomedata/nmdc-schema/blob/c4186e295c7db2c957ce3cac5e62cc69167afce1/MAINTAINERS.md?plain=1#L9

https://github.com/microbiomedata/nmdc-schema/blob/c4186e295c7db2c957ce3cac5e62cc69167afce1/project.Makefile#L3

https://github.com/microbiomedata/nmdc-schema/blob/c4186e295c7db2c957ce3cac5e62cc69167afce1/.github/workflows/migration.yaml#L26

From that information, I have not been able to determine which version of Apache Jena is required. There are several versions of Apache Jena available. Is there a minimum compatible version?

I think all the past versions are available here:

- https://archive.apache.org/dist/jena/binaries/

I think the latest major version is 4.

**Comment by eecavanna** [comment]
I have version 4.9.0 installed in my (Docker-based) local `nmdc-schema` development environment. I don't know how to tell whether it's adequate or not (I don't know what commands or `make` targets use it).

**Comment by eecavanna** [comment]
As a starting point, I think knowing the specific version(s) the primary contributors use would be helpful to me and to future contributors. That could be documented in the README or contributor guide.

For example:

"We use version x.y.z and we recommend you use that, too."

**Comment by turbomam** [comment]
This is a good issue. Thanks @eecavanna .

I haven't determined a minimum version for Jena. I will give this some thought.

**Comment by turbomam** [comment]
https://archive.apache.org/dist/jena/binaries/

**Comment by eecavanna** [comment]
Thanks, @turbomam. To summarize: you have been using 4.8.0, I have been using 4.9.0, and there is a 4.10.0 available.

Based on that, I recommend adding the following note to `MAINTAINERS.md`:

```diff
  - ...
  - Some optional components use the Java-based [ROBOT](http://robot.obolibrary.org/), which might be replaced with Jena arq
  - [Jena riot]([url](https://www.bobdc.com/blog/jenagems/#rsparql)) is also a part of the MongoDB dumping, repairing and validation workflow, if the user wishes to generate and validate RDF/TTL.

+ The maintainer of this repository uses Apache Jena version 4.8.0, specifically, which you can [download here](https://archive.apache.org/dist/jena/binaries/).

  ## Making changes to the NMDC Schema
  ...
```

I think new contributors will find that note helpful when deciding which version of Apache Jena they will install.

Do you want me to open a PR with that change?

**Comment by turbomam** [comment]
yes please!
