### ISSUE TITLE
Make a list of Mongo queries people find difficult to write

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1604]
There are some NMDC information retrieval tasks that do not seem intuitive.

Let's collect some use cases that call out 
- what the task is
  - list the input knowledge and the output knowledge, like getting the identifiers for all `Biosample`s that are `part_of` a given `Study`
- who the intended audience is
  - NMDC team members
  - workflows
  - external users

Possible solutions:
- fancy pure-MongoDB queries over the existing collections
- ad-hoc Python scripts that integrate results form multiple queries
- MongoDB views
- SPARQL
- existing API endpoints
- new API endpoints

**Comment by turbomam** [comment]
I added some people who might have some thoughts on this to the issue assignees, but please add or remove others if necessary.

**Comment by brynnz22** [comment]
@turbomam here is a mongo query I wrote for one of the notebooks to go from biosample to a data object: https://github.com/microbiomedata/notebook_hackathons/blob/soil-contig-tax/taxonomic_dist_by_soil_layer/python/mongodb_query.txt.js

**Comment by aclum** [comment]
@turbomam  see https://github.com/microbiomedata/nmdc-runtime/issues/355
My preference would be consolidate tickets, no preference which repo we work out of.

**Comment by PeopleMakeCulture** [comment]
@dwinston and I have been collecting examples of difficult queries in https://github.com/microbiomedata/nmdc-runtime/issues/355

**Comment by mslarae13** [comment]
I'm going to close this issue. @brynnz22 @turbomam please copy your comments to the existing issue in runtime.
