### ISSUE TITLE
Implement migrators for all Berkeley schema changes (meta-issue)

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1607]
Below is a list (in the order they should be executed) of the migration PRs to account for the schema changes in Berkeley:

1. [Migrator_from_X_to_PR23: Update the values for `execution_resource` to match the newly created enumeration permissible values](https://github.com/microbiomedata/berkeley-schema-fy24/pull/59/files) 

2. [Migrator_from_X_to_PR4: Remove `omics_type` and create `analyte_category` on `OmicsProcessing` class and update values to match enum](https://github.com/microbiomedata/berkeley-schema-fy24/pull/62) 

     - Should occur **BEFORE** `OmicsProcessing` becomes `DataGeneration`

3. [Migrator_from_X_to_PR53: Move `part_of` values to `associated_studies` on `OmicsProcessing` and `Biosample` classes](https://github.com/microbiomedata/berkeley-schema-fy24/pull/78) 
     - Should occur **BEFORE** `OmicsProcessing` becomes `DataGeneration`. 

4.  [Migrator_from_X_to_PR21: Move `relevant_protocols` to `protocol_link` for studies and remove `relevant_protocols` slot](https://github.com/microbiomedata/berkeley-schema-fy24/pull/76)

5. [Migrator_from_X_to_PR129: change `metabolite_quantified` and `has_metabolite_quantification` slot names](https://github.com/microbiomedata/berkeley-schema-fy24/pull/129)
   - Should occur **BEFORE** `MetabolomicsAnalysisActivity` becomes `MetabolomicsAnalysis`

6. [Migrator_from_X_to_PR31: Remove used slot from `WorkflowExecution` subclasses](https://github.com/microbiomedata/berkeley-schema-fy24/pull/139)
   - Needs to occur **BEFORE** collection name changes as it refers to old collection names
   - Neds to occur **BEFORE** the instrument_set migrator happens because this migrator compares the values in the 'used' slot to the values in the 'instrument_name' slot (that is removed in that migrator)
   - Needs to occur **BEFORE** workflow chain migrator because that migrator removes the `was_informed_by` slot from the `WorkflowExecution`s which this migrator references.

7. [Migrator_from_X_to_PR9: populate `workflow_chain_set` and remove `was_informed_by` from `WorkflowExectuion` subclasses and populate `part_of on subclass with workflow chain `id`](https://github.com/microbiomedata/berkeley-schema-fy24/pull/127)
   - Should occur **BEFORE** collection name changes as this migrator refers to `omics_processing_set` and `WorkflowExecution` subclasses with "Activity" in the name.
   - Shoul occur **AFTER** `omics_type` becomes `analyte_category`

8. [Migrator_from_X_to_PR19_and_PR70: `instrument_set` update to `instrument_used` from `instrument_name`](https://github.com/microbiomedata/berkeley-schema-fy24/pull/119)
   - Should occur **BEFORE** collection name changes as this migrator refers to `omics_processing_set`

9. [Migrator_from_X_to_PR2_and_PR24: change MongoDb collection names](https://github.com/microbiomedata/berkeley-schema-fy24/pull/91)
    - This includes changing `omics_processing_set` to `data_generation_set` and the workflow execution set names

10.  [Migrator_from_X_to_PR10: Add the `type` slot to every class instance](https://github.com/microbiomedata/berkeley-schema-fy24/pull/66) (calls the new collection names. 
     - This will need to happen **AFTER** the classes are renamed. E.g. this migration calls the `data_generation_set` instead of the `omics_processing_set`)
     - This PR was also updated to account for new inlined classes: https://github.com/microbiomedata/berkeley-schema-fy24/pull/103

11. [Migrator_from_X_to_PR3: Fix type slot to specify subclass for DataGeneration subclasses](https://github.com/microbiomedata/berkeley-schema-fy24/pull/92)
     - This needs to happen **AFTER** the following migrations:
          - X_to_PR4 (changing `omics_type` to `analyte_category` and updating values to enum)
          - X_to_PR2_and_PR24 (changing collection names, esp. `omics_processing_set` to `data_generation_set`)
          - X_to_PR10 (adding type slot to all instances as this migrator will just make all `type:DataGeneration` and not take into account the subclasses (e.g. `type:NucleotideSequencing`, and `type:MassSpectrometry`)

- ~[Update collection names that changed (all `WorkflowExecution(Activity)` subclass collections and `omics_processing_set` to `data_generation_set`. ](https://github.com/microbiomedata/berkeley-schema-fy24/pull/60) (needs to be refactored to account for cross-collection/database level migrations)~ 
     - This PR was closed because Eric implemented adapters to make changes to the whole database.

**Comment by turbomam** [comment]
this is great! would you be willing to update it with the name of the migrator that will execute each of the steps? (without requiring the user to hover over them)

**Comment by turbomam** [comment]
As of now, I have them ordered like this in my `project.Makefile`

```
	time $(RUN) migration-recursion \
		--migrator-name migrator_from_9_3_to_9_4 \
		--migrator-name migrator_from_X_to_PR10 \
		--migrator-name migrator_from_X_to_PR4 \
		--migrator-name migrator_from_X_to_PR53 \
```

**Comment by brynnz22** [comment]
@turbomam I added the names of the migrators. I am thinking the `migrator_from_X_to_PR10` should go at the bottom of the list. It does not really matter now, but when we write the migration for `OmicsProcessing` to become `DataGeneration`, migrator for PR10 will need to come after that because it refers to `DataGeneration`. But we can move those around in the `project.makefile` later. The list in this issue can be the source of ground truth for the order of the migrations should be performed.

**Comment by ssarrafan** [comment]
@brynnz22 should this remain active for the next sprint?

**Comment by eecavanna** [comment]
Hi @ssarrafan, I think we'll still be working on this next sprint. For example, once the `main` branch of the `nmdc-schema` repo gets merged into the `main` branch of the `berkeley-schema-fy24` repo (which I assume will happen during the next sprint), we will update each of the migrators referenced in this ticket to use some new so-called "adapter" code that would become available as a result of that merge.

**Comment by eecavanna** [comment]
I think we'll still be working on this next sprint. The migration framework still does not allow migrators to mint IDs (or obtain minted IDs) during a migration, which is blocking the completion of this "meta" ticket. I'll move this to the next sprint now.

**Comment by ssarrafan** [comment]
checked with @eecavanna and moving to next sprint

**Comment by eecavanna** [comment]
I renamed this "meta-issue" so its name says "meta-issue" and so it is a verb.

**Comment by brynnz22** [comment]
@anastasiyaprymolenna when you are finished with writing the migrator that removes the `used` slot from `WorkflowExecution` can you add edit the big comment above to add that migrator in the write order? It needs to come before 7. Changing `instrument_name` to `instrument_used`

**Comment by ssarrafan** [comment]
@brynnz22 @eecavanna any update on this?  Should it be moved to the backlog or next sprint?

**Comment by brynnz22** [comment]
We are done writing the migrators. I think we can probably close this issue, unless @eecavanna wants to keep it open for the rest of the implementation steps? But I think eric created a separate issue for those here: https://github.com/microbiomedata/nmdc-schema/issues/1983

**Comment by eecavanna** [comment]
Hi @brynnz22 and @ssarrafan, I'm OK with this "meta-issue" being closed. I will continue to refer to its description when I am putting migrators in order (so I can run them in the order in which they were designed to be run), but I can do that while it's closed.

**Comment by ssarrafan** [comment]
Thanks @brynnz22 and @eecavanna and also for giving me the joy of clicking the close button.  ;)
