### ISSUE TITLE
check Napa identifier compliance for (old) "Stegen" study gold:Gs0114663

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1608]
The `project.Makefile` in the main branch already has some code that illustrates making filtered downloads from specified collections from a specified MongoDB server. It will need to be enhanced to use more complex, multi-collection filtering (for which there aren't any API endpoints yet)

```make
# user is responsible for providing pre-tested, properly escaped, filtered https://api-napa.microbiomedata.org/docs#/metadata requests
# todo: explicitly running this through the python interpreter emits less logging
assets/filtered-api-requests/filtered-request-result.yaml:
	$(RUN) build-datafile-from-api-requests \
		--output-file $@ \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/study_set?filter=%7B%22id%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999" \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/biosample_set?filter=%7B%22part_of%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999" \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/omics_processing_set?filter=%7B%22part_of%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999"
```

**Comment by turbomam** [comment]
use shcema v7.8.0

**Comment by turbomam** [comment]
new Study id: `nmdc:sty-11-aygzgv51`

why isn';t thi working? 

```
https://api-napa.microbiomedata.org/studies?filter=gold_study_identifiers%3A%27gold%3AGs0114663%27&per_page=25

**Comment by turbomam** [comment]
```make
# user is responsible for providing pre-tested, properly escaped, filtered https://api-napa.microbiomedata.org/docs#/metadata requests
# todo: explicitly running this through the python interpreter emits less logging
assets/filtered-api-requests/filtered-request-result.yaml:
	$(RUN) build-datafile-from-api-requests \
		--output-file $@ \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/study_set?filter=%7B%22id%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999" \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/biosample_set?filter=%7B%22part_of%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999" \
		--api-url "https://api-napa.microbiomedata.org/nmdcschema/omics_processing_set?filter=%7B%22part_of%22%3A%22nmdc%3Asty-11-aygzgv51%22%7D&max_page_size=999999"
```

**Comment by turbomam** [comment]
https://api-napa.microbiomedata.org/studies?filter=id%3Agold%3AGs0110138&per_page=25

**Comment by turbomam** [comment]
todo:
- add more pattern slot_usages
  - #1212 
  - preferable for LinkML to check identifier patterns without this workaround
  - may need to apply some of these rules to an older schema or filter out expected errors
- @mbthornton-lbl write a tool to fetch records that are related to some entity though multiple collections (looping solution)

**Comment by mbthornton-lbl** [comment]
Related Issue:
#1609

**Comment by turbomam** [comment]
@brynnz22 wrote a guide for using the find and metadata endpoints in the nmdc -runtime API: 

https://github.com/microbiomedata/NMDC_documentation/blob/main/docs/howto_guides/api_gui.md

**Comment by aclum** [comment]
work happened on this last sprint, this sprint @mbthornton-lbl  will expand to check records with legacy ids. Everything validates with linkml-validate for the records that have updated identifiers.

**Comment by aclum** [comment]
@mbthornton-lbl did you want to move this ticket over to the next sprint or are you working off of a different ticket to include records that haven't been re-ided yet.

**Comment by mbthornton-lbl** [comment]
@aclum I will move this to the next sprint - I have been able to extract the Stegen study, including following `was_informed_by` gold seq project identifiers / alternative identifiers.  The extracted results show the Old ientries still in place. I need to check if the `delete-records` tools was run or not

**Comment by ssarrafan** [comment]
@mbthornton-lbl doesn't appear to be active in the last 2 weeks.  Can you remove from the sprint if you're not working on it.

**Comment by mbthornton-lbl** [comment]
Update Results:

- ran `extract-study` on nmdc:sty-11-aygzgv51
- ran linkml-validate on the resulting yaml data

No validation errors related to metagenomic data

Errors for metabolomic and NOM
4 Types of Errors
```
[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] Additional properties are not allowed ('alternative_identifier' was unexpected) in /data_object_set/1127


[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] 'id' is a required property in /data_object_set/1195
[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] 'name' is a required property in /data_object_set/1195
[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] 'description' is a required property in /data_object_set/1195

[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] ['nmdc:omprc-11-s1vt0h44'] is not of type 'string' in /metabolomics_analysis_activity_set/7/was_informed_by

[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] ['nmdc:omprc-11-dz40jm83'] is not of type 'string' in /nom_analysis_activity_set/23/was_informed_by
```

**Comment by mbthornton-lbl** [comment]
Unable to convert to RDF with lonkml-convert:
ValueError: File "nmdc:sty-11-aygzgv51.yaml", line 12852, col 5:  Unknown argument: alternative_identifier = [['emsl:output_499451']]

**Comment by aclum** [comment]
we went over these errors in our 1x1, I've slacked Yuri about the alternative_identifiers slot missing the 's' and that was_informed_by should be a string, not an array. The id, name, and description errors are b/c the data objects don't exist. Yuri has been provided a list of how to remap these since this is not an issue in prod.

**Comment by mbthornton-lbl** [comment]
`linkml-validate` results: No issues found
`linkml-convert to RDF datastore complete

**Comment by mbthornton-lbl** [comment]
Reviewed with @turbomam - complete
