### ISSUE TITLE
Implement tool to extract all related data entities for a Study

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1609]
Starting from a Study ID, implement a tool that will extract related Entities and produce a YAML output.

**Comment by turbomam** [comment]
please put the code in `nmdc_schema` or `src/scripts/python`

**Comment by turbomam** [comment]
@mbthornton-lbl can you give an example of a transaction that you will be working on? Like "find all DataObjects that were the output of a MetagenomeAnnotationActivity whose input was a DataObject that was the output of an OmicsProcessing whose input was  Biosample that was part of Study gold:Gs0114663" ?
