### ISSUE TITLE
what's a Study that doesn't have many Biosamples

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1614]
see also
- https://github.com/microbiomedata/nmdc-schema/pull/1612
defaults to nmdc:sty-11-aygzgv51, which is new in the Napa MongoDB

**Comment by turbomam** [comment]
```SPARQL
PREFIX nmdc: <https://w3id.org/nmdc/>
PREFIX dcterms: <http://purl.org/dc/terms/>
select ?s (count(?b) as ?bcount) where { 
	?b a nmdc:Biosample ;
    dcterms:isPartOf ?s .
    ?s a nmdc:Study .
}
group by ?s
order by desc(count(?b))
```

**Comment by turbomam** [comment]
| ?s                                      | ?bcount |
|-----------------------------------------|--------:|
| <https://w3id.org/nmdc/sty-11-34xj1150> | 5003    |
| <https://w3id.org/nmdc/sty-11-5bgrvr62> | 471     |
| <https://w3id.org/nmdc/sty-11-5tgfr349> | 430     |
| <https://w3id.org/nmdc/sty-11-r2h77870> | 416     |
| <https://w3id.org/nmdc/sty-11-db67n062> | 241     |
| <https://w3id.org/nmdc/sty-11-8xdqsn54> | 207     |
| <https://w3id.org/nmdc/sty-11-28tm5d36> | 134     |
| <https://bioregistry.io/gold:Gs0128850> | 105     |
| <https://bioregistry.io/gold:Gs0110138> | 100     |
| <https://w3id.org/nmdc/sty-11-t91cwb40> | 95      |
| <https://bioregistry.io/gold:Gs0114663> | 85      |
| <https://bioregistry.io/gold:Gs0154244> | 80      |
| <https://w3id.org/nmdc/sty-11-hdd4bf83> | 61      |
| <https://bioregistry.io/gold:Gs0110119> | 60      |
| <https://bioregistry.io/gold:Gs0135149> | 53      |
| <https://bioregistry.io/gold:Gs0103573> | 30      |
| <https://bioregistry.io/gold:Gs0114675> | 23      |

**Comment by turbomam** [comment]
It doesn't seem like many of those are available in the Napa MongoDB

```shell
export NAPA_BASE_URL=https://api-napa.microbiomedata.org/ ; export NAPA_USERNAME=mam ; export NAPA_PASSWORD=<SECRET> ; poetry run get-study-related-records \
	--api_base NAPA \
	extract-study \
	--study_id nmdc:sty-11-hdd4bf83 \
	--yaml_out
```

> ```
> Extracting study nmdc:sty-11-hdd4bf83 from the NMDC database.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/mark/gitrepos/nmdc-schema/src/scripts/nmdc_database_tools.py", line 182, in extract_study
>     study_response = api_client.request("GET", f"studies/{study_id}")
>   File "/home/mark/gitrepos/nmdc-schema/src/scripts/nmdc_database_tools.py", line 95, in request
>     rv.raise_for_status()
>   File "/home/mark/gitrepos/nmdc-schema/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api-napa.microbiomedata.org/studies/nmdc:sty-11-hdd4bf83
> make: *** [/home/mark/gitrepos/nmdc-schema/project.Makefile:586: extract-study] Error 1
> ```

**Comment by mslarae13** [comment]
parent studies might not have samples of their own. They may be in the study that has the part_of relationship. 

Do we still need this issue?

**Comment by aclum** [comment]
@turbomam  can this be closed?
