### ISSUE TITLE
Migration framework does not provide a mechanism for renaming a collection

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1623]
Related: https://github.com/microbiomedata/berkeley-schema-fy24/pull/60 (via https://github.com/microbiomedata/nmdc-schema/issues/1607)

**Comment by turbomam** [comment]
Good catch @eecavanna and @brynnz22 

I'd like to call out two important points for the benefit of those that don't already know this:
1. LinkML and the nmdc-schema don't currently know anything about "collections", at least in the MongoDB sense, where collections are aggregations of Documents and Databases are aggregations of Collections. They also don't know what agents (people or software applications) might expect to write into a MongoDB collection.
3. The nmdc-schema does know that there is a [Database](https://microbiomedata.github.io/nmdc-schema/Database/) class. By convention all of the `Database` slots like [biosample_set](https://microbiomedata.github.io/nmdc-schema/biosample_set/) are `multivalued` and `inlined_as_list`, but nothing enforces that.

It's up to our collective memory (and possibly better documentation) to draw the connection between Database slots, MongoDB collections and software that accesses the collections. Some of this is reflected in the example data files, especially [those whose name starts with 'Database'](https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Database-neon_Biosample_to_DataObject_NEON.yaml)

That leaves me wondering what a collection-renaming migration would be like. Presumably, `Database` slot would be renamed manually, and users would be told about the new collection name through announcements or documentation.

The part we could implement within code is dumping a collection and telling MongoDB to insert the same records back into a new collection, possibly using either direct MongoDB transactions, API calls or bulk file-wise operations.My recollection is that we're doing the third. Can't that already accommodate creating a new collection on the fly? I guess it wouldn't know to delete the old collection, but that could be a one-time manual interaction, couldn't it?

**Comment by ssarrafan** [comment]
I'll move to new sprint based on recent comment but please remove from sprint if not actively working on this.
