### ISSUE TITLE
`get-study-related-records` aka `src/scripts/nmdc_database_tools.py` output path not working correctly

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1633]
Fix:
- make output work as expected - default to project_root/local (excluded in .gitignore)
- remove dependencies on .env
- make api_base_url option explicit with a default to NAPA

By default, `get-study-related-records` tries to write an output and a logging file to `~/local/`. My intention was that it would go to the `local/` sub-directory in the `nmdc-schema` repo. In that case the files will be gitignored, i.e. not committed back to GitHub. Side note: it should be easy to expose them somewhere public.

Even better than that, I would prefer that `get-study-related-records` would take  `--output-file` and `--log-file` parameters. Then it would be easier/more deterministic to use the output in a subsequent validation target. The current behavior builds filenames based on the `--study_id`, which is admittedly nice in the case where many files from this process might be accumulated in the same directory.

**Comment by turbomam** [comment]
```python
@click.option("--output_dir", default="../../local/", help="Output directory.")
```

**Comment by turbomam** [comment]
Now running like

**Comment by mbthornton-lbl** [comment]
related #1634
