### ISSUE TITLE
All click options should use hyphens not underscores

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1635]
Click knows that parameters expressed with hyphens will create variables with underscores

So for `src/scripts/nmdc_database_tools.py` we would have a section like this:

```Python
@click.group()
@click.option("--api-base", default="NAPA", help="API base to use.")
@click.option("--env-file", default="../../local/.env", help="dotenv file for username, password, etc.")
@click.option("--output-dir", default="../../local/", help="Output directory.")
@click.pass_context
def cli(ctx, api_base, env_file, output_dir):

**Comment by turbomam** [comment]
Although we have other issues with suggestions for eliminating `--env-file`, using a more literal `--api-base` and specifying `--output-file` instead of `--output-dir` !

**Comment by turbomam** [comment]
see also
- #1633 
- #1634

**Comment by mbthornton-lbl** [comment]
covered by #1641
