### ISSUE TITLE
berkeley-schema-fy24 must migrate string "type" to object types consisting of the instances' class' `class_uri`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1640]
The berkeley-schema-fy24 is much stricter about the `type` slot, compared to the current nmdc-schema

Currently the [type](https://microbiomedata.github.io/nmdc-schema/type/) of a [WorkflowExecutionActivity](https://microbiomedata.github.io/nmdc-schema/WorkflowExecutionActivity/) is 

> An optional string that specifies the type object. This is used to allow for searches for different kinds of objects.

The [berkeley-schema-fy24](https://microbiomedata.github.io/berkeley-schema-fy24/type/) requires that all data instances of nmdc-schema classes must reiterate the class' `class_uri` as a CURIe.

Theoretically there should be a good example of this pattern (for some WorkflowExecution) in the [example data files directory](https://github.com/microbiomedata/nmdc-schema/tree/main/src/data/valid) already but I haven't found one yet.

cc @Michal-Babins @mslarae13

**Comment by eecavanna** [comment]
Thanks for bringing this to my attention, @turbomam. 

Was there a specific PR for this change (the change to the `type` slot)? I think knowing its URL will help us (a) name the `Migrator` module and (b) get more info if we need it.

Is creating a CURIe something that involves obtaining something from the outside world (e.g. "minting" or "registering" something) or is it just a matter of concatenating/processing various pieces of information that's already available in the Mongo document? If it's the former (i.e. involves accessing the outside world), I may add something to the "adapter" class I'm currently working on.

**Comment by turbomam** [comment]
this PR added the type slot to all classes:
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/10
  - the new definition of `type` can be seen in that PR's [src/schema/basic_slots.yaml](https://github.com/microbiomedata/berkeley-schema-fy24/pull/10/files#diff-ab7721fce565980ec31e373ca85395454afefadc992c17b7954c21f4ebb24bb1)
  - it also adds some test that check _classes_ for their inclusion of the `type` slot

**Comment by eecavanna** [comment]
##### Notes from 5/21/2024 migration squad meeting

- `type` slot in `nmdc-schema` has string range
- `type` slot in `berkeley-schema-fy24` has to be a `class_uri`
  - uses the "designates type" meta slot (https://linkml.io/linkml-model/latest/docs/designates_type/)
  - rule: all classes must assert their `class_uri`
  - rule: all classes must be able to use the `type` slot (without reasserting that capability if they inherited that capability)
  - rule: all instances must assert their own `type` value

See: https://github.com/microbiomedata/berkeley-schema-fy24/tree/main/tests
- `test_all_classes_assert_a_class_uri.py`
- `test_all_classes_can_use_type_slot.py`
- `test_inherited_slots_not_reiterated.py`

**Comment by eecavanna** [comment]
Check whether https://github.com/microbiomedata/nmdc-schema/issues/1607 encapsulates this issue.

**Comment by aclum** [comment]
@turbomam  can this be closed? I believe in berkeley all classes now have type required with a range of a curie.
