### ISSUE TITLE
Data Harmonizer - additional tasks

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#167]
- [x] add columns based on input from @mslarae13.
    - old **slot** set analysis can be found at https://github.com/microbiomedata/nmdc-metadata/blob/issue-398/notebooks/soil_slot_column_analysis_curated.json
    - [ ] #276
    - [x] new **enum** set analysis has been generated and can be found at ???
- [x] Resolving this may require requesting new terms or requesting new package/slot associations from MIxS.
- [x] move this work into a https://github.com/microbiomedata repo
- [x] finish converting @Montana Smith's Index of Terms to LinkML today. If she adds rows to her sheet to represent new attributes of biosamples, I can just rerun my code. But I should be clear that it just makes LinkML YAML at this point.
- [x] change the column headers to something like a display name, rather than a term label.
- [x] determine subset of MIxS packages to use for usability testing

See #137 for more details/background

**Comment by ssarrafan** [comment]
@turbomam can this issue be updated or closed?  If it needs to continue to November let me know and I can move it for you.

**Comment by turbomam** [comment]
The emphasis has shifted to converting Montana's [Index of Terms](https://github.com/microbiomedata/nmdc-metadata/issues/330) document to YAML so that parts of it can be incorporated into the NMDC schema as necessary. That will have to continue into November.

**Comment by cmungall** [comment]
Need JGI terms too?

**Comment by ssarrafan** [comment]
Moving this to the December sprint per @turbomam via Slack

**Comment by turbomam** [comment]
I know @mslarae13 has done a lot of work towards `Resolving this may require requesting new terms or requesting new package/slot associations from MIxS.` but I don't know if that could be considered complete.

I have completed all of my checkboxes except for routinely generating slot and enum set analyses (SNTC vs MIxS) and posting them somewhere memorable.

**Comment by ssarrafan** [comment]
@turbomam would you like me to move this issue to February to do the remaining checkboxes?

**Comment by ssarrafan** [comment]
@turbomam can this GH issue be closed at this time?  Or would you like to keep it open for March?

**Comment by ssarrafan** [comment]
Created one more issue. Closing this one.
