### ISSUE TITLE
backmerge nmdc-schema 9.4 to berkeley-schema-fy24 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1677]
9.4.* includes changes made to modeling QC information and making [FunctionalAnnotationAggMember](https://microbiomedata.github.io/nmdc-schema/FunctionalAnnotationAggMember/) slots required.
These need to get backmerged into  berkeley-schema-fy24  to minimize merge conflicts.
This also has a bump in the linkml version

**Comment by eecavanna** [comment]
Related PRs:
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/72
    - I created this PR to merge a copy of `nmdc-schema/main` (named `berkeley-schema-fy24/upstream-main-replica`) into a copy of `berkeley-schema-fy24/main` (named `berkeley-schema-fy24/berkeley-main-replica`).
    - @turbomam completed the merge. The result is in `berkeley-schema-fy24/berkeley-main-replica`.
    - This is in preparation for (effectively) merging `nmdc-schema/main` into `berkeley-schema-fy24/main`.
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/73
    - @turbomam created this PR to merge `berkeley-schema-fy24/berkeley-main-replica` into `berkeley-schema-fy24/main`, which (currently) is effectively the same as merging `nmdc-schema/main` into `berkeley-schema-fy24/main`.
    - This PR is still in review. @turbomam identified some non-Git issues involving example data files, where files labeled "invalid" validate OK, and files labeled "valid" don't validate OK. He and I posted messages on Slack on Friday afternoon, asking for our teammates' help to resolve those contradictions.
    - I expect those contradictions to get resolved next week (i.e. January 22-26) and then for the PR to be merged. Once that happens, it will be as though `nmdc-schema/main` has been merged into `berkeley-schema-fy24/main`.

I don't know what the version number of "9.4" is referring to, though. At this point, I don't know of a version "9.4" of `nmdc-schema`. Maybe that is referring to a future version that people other than me are familiar with and planning to call "9.4", specifically.
