### ISSUE TITLE
Enable `app` container to bring a Fuseki dataset (managed by `fuseki` container) online and offline

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1690]
I want to enable the `app` container to bring a Fuseki dataset (in `fuseki` container) online and offline. When a dataset is online, the `nmdc-tdb2` `make` target (which people run from within the `app` container) fails with an error saying that it could not obtain a lock on a file.

I have an idea for this, which I'll document in this issue.

CC: @turbomam

**Comment by eecavanna** [comment]
- The `app` container can access the `fuseki` container via the hostname, `fuseki`
- Fuseki has an HTTP API that includes an endpoint clients can use to bring a dataset online/offline
  - It is documented here: https://jena.apache.org/documentation/fuseki2/fuseki-server-protocol.html#active-and-offline
  - Access to that endpoint is restricted

**Comment by eecavanna** [comment]
Here's the command I expected would put the `nmdc-tdb2` dataset into an "offline" state; but it doesn't seem to me to do so:

```shell
curl --user 'admin:password' 'http://fuseki:3030/$/datasets/nmdc-tdb2?state=offline'
```

**Comment by eecavanna** [comment]
The following `curl` command seems to **work**, for putting the `nmdc-tdb2` dataset into an "offline" state!

```shell
curl -H "Authorization: Basic $(echo -n admin:password | base64)" -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'state=offline' 'http://fuseki:3030/$/datasets/nmdc-tdb2'
```

It's based on a code snippet I stumbled upon [in this `stain/jena-docker` PR from 2019](https://github.com/stain/jena-docker/pull/17/files#diff-e0d7742627ae376658fddabf19870806edc2ba1c8758075e4d3f9b8329e98f9fR50-R54).

Here's the corresponding one for putting the dataset back into an "active" state:

```shell
curl -H "Authorization: Basic $(echo -n admin:password | base64)" -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'state=active' 'http://fuseki:3030/$/datasets/nmdc-tdb2'
```

**Comment by eecavanna** [comment]
Based on what I described in the previous message, here are the two commands we can issue from the `app` container, to toggle the state of the `nmdc-tdb2` dataset between "active" and "offline":

```shell
curl --user 'admin:password' --data 'state=active' 'http://fuseki:3030/$/datasets/nmdc-tdb2'
curl --user 'admin:password' --data 'state=offline' 'http://fuseki:3030/$/datasets/nmdc-tdb2'
```

**Comment by eecavanna** [comment]
Based on what I wrote in the previous message, here's a diff for `project.Makefile`:

```diff
diff --git a/project.Makefile b/project.Makefile
index 6e65da0cc..7ac9fb0ad 100644
--- a/project.Makefile
+++ b/project.Makefile
@@ -637,10 +637,21 @@ local/nmdc-sty-11-aygzgv51-tdb: local/nmdc-schema-v8.0.0.owl.ttl local/nmdc-sty-
 # Note: We expect people to run this make target from within the `app` container.
 #
 nmdc-tdb2:
+       echo "Putting dataset into 'offline' state."
+       curl \
+               --user 'admin:password' \
+               --data 'state=offline' \
+               'http://fuseki:3030/$/datasets/nmdc-tdb2'
+       echo "Populating dataset."
        tdb2.tdbloader \
                --loc=/nmdc-schema/local/fuseki-data/databases/$@ \
                --graph=https://w3id.org/nmdc/nmdc \
                /nmdc-schema/project/owl/nmdc.owl.ttl
+       echo "Putting dataset into 'active' state."
+       curl \
+               --user 'admin:password' \
+               --data 'state=active' \
+               'http://fuseki:3030/$/datasets/nmdc-tdb2'
 
 .PHONY: filtered-status
 filtered-status:
```

FYI, @turbomam, in case you want to try this out before I work on this next.

**Comment by turbomam** [comment]
@eecavanna this is excellent. Thanks.
