### ISSUE TITLE
add a schema version on releases of NMDC schema

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-schema#17]
We discussed using semantic versioning or simply a time stamp on release versions.  Either could work, to avoid needing to define the semantics of semantic versioning (does minor or patch break ingest or only major?) we decided time stamp release versions was simplest.

With versions on the schema it becomes possible to ask what schema version the metadata store (MongoDB or Terminus) is at and what version the search application ingest and relationship schema support

**Comment by dwinston** [comment]
@wdduncan I'm familiar with the following scheme (which I used for https://github.com/polyneme/nmdc-mongo-tools):

```python
# among dev requirements
invoke
setuptools-scm
twine
```

```python
# in /setup.py

from setuptools import setup, find_packages

setup(
    packages=find_packages(),
    use_scm_version=True,
...
```

```python
# /task.py
from subprocess import run

from invoke import task


@task
def publish(c):
    completed = run(
        "git describe --tags $(git rev-list --tags --max-count=1)",
        shell=True,
        capture_output=True,
        encoding="utf-8",
    )
    vtag = completed.stdout.strip()
    major_minor, dot, patch = vtag.rpartition(".")
    vtag_new = major_minor + dot + str(int(patch) + 1)
    run(["git", "tag", vtag_new])
    run(["git", "push"])
    run(["git", "push", "--tags"])
    c.run("rm dist/*.*", warn=True)
    c.run("python setup.py sdist bdist_wheel")
    c.run("twine upload dist/*")
```

Here, `invoke publish` on the command line bumps the patch version via a git tag and pushes that to PyPI. The logic above can be refactored to use [calver](https://calver.org/) (e.g. YYYY.MM.DD).

**Comment by wdduncan** [comment]
The nmdc-schema is now versioned using pypi.
