### ISSUE TITLE
prepare for nmdc-schema v10.0.0 release

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1700]
- coordinate with @aclum @eecavanna and @mbthornton-lbl wrt whether the v9.3.0 to v9.4.0 migrator is ready to include
- update version strings in nmdc.yaml and pyproject.toml

**Comment by eecavanna** [comment]
I consider it ready.

**Comment by turbomam** [comment]
see 
- #1701 
- #1702
