### ISSUE TITLE
'Migrator' object has no attribute 'get_transformers_for'

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1701]
```shell
make local/mongo_as_nmdc_database_rdf_safe.yaml
```

aka

```shell
time poetry run migration-recursion \
                --migrator-name migrator_from_9_3_to_9_4 \
                --schema-path nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml \
                --input-path local/mongo_as_unvalidated_nmdc_database.yaml \
                --salvage-prefix generic \
                --output-path local/mongo_as_nmdc_database_rdf_safe.yaml
```

> ```
> Will use migrator: migrator_from_9_3_to_9_4
> Loading data from local/mongo_as_unvalidated_nmdc_database.yaml
> Loading schema from nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml
> {'biosample_set', 'part_of', 'has_input', 'metatranscriptome_activity_set', 'biosample_identifiers', 'alternative_identifiers', 'jgi_portal_study_identifiers', 'read_qc_analysis_activity_set', 'insdc_bioproject_identifiers', 'omics_processing_identifiers', 'nom_analysis_activity_set', 'designated_class', 'metagenome_annotation_activity_set', 'read_based_taxonomy_analysis_activity_set', 'library_preparation_set', 'gold_analysis_project_identifiers', 'encodes', 'pooling_set', 'insdc_secondary_sample_identifiers', 'img_identifiers', 'gnps_task_identifiers', 'extraction_set', 'chemical', 'subject', 'analysis_identifiers', 'data_object_set', 'mags_activity_set', 'emsl_biosample_identifiers', 'insdc_biosample_identifiers', 'metagenome_assembly_set', 'gold_sequencing_project_identifiers', 'id', 'was_informed_by', 'insdc_analysis_identifiers', 'field_research_site_set', 'gold_study_identifiers', 'study_identifiers', 'mgnify_project_identifiers', 'all_proteins', 'was_generated_by', 'metabolomics_analysis_activity_set', 'has_output', 'igsn_biosample_identifiers', 'omics_processing_set', 'study_set', 'gene_function_id', 'insdc_sra_ena_study_identifiers', 'metaproteomics_analysis_activity_set', 'metabolite_quantified', 'metagenome_sequencing_activity_set', 'emsl_project_identifiers', 'insdc_experiment_identifiers', 'planned_process_set', 'doi_value', 'activity_set', 'processed_sample_set', 'best_protein', 'metagenome_annotation_id', 'neon_biosample_identifiers', 'collecting_biosamples_from_site_set', 'external_database_identifiers', 'neon_study_identifiers', 'term', 'mgnify_analysis_identifiers', 'collected_from', 'has_part', 'gold_biosample_identifiers'}
> Fixing CURIes in biosample_set if necessary
> ---snip---
> Fixing CURIes in study_set if necessary
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/MAM/Documents/gitrepos/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/MAM/Documents/gitrepos/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/Users/MAM/Documents/gitrepos/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/MAM/Documents/gitrepos/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/MAM/Documents/gitrepos/nmdc-schema/nmdc_schema/migration_recursion.py", line 176, in main
>     transformers = migrator.get_transformers_for(collection_name=collection_name)
> AttributeError: 'Migrator' object has no attribute 'get_transformers_for'
> 
> real    6m15.233s
> user    6m7.856s
> sys     0m5.415s
> make: *** [local/mongo_as_nmdc_database_rdf_safe.yaml] Error 1
> ```

See
- https://github.com/microbiomedata/nmdc-schema/blame/86b26440311d01b2850aa0c7210930e13dc17531/nmdc_schema/migration_recursion.py#L176

**Comment by turbomam** [comment]
Also tried this:

```shell
time poetry run migration-recursion \
                --migrator-name Migrator_from_9_3_to_9_4 \
                --schema-path nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml \
                --input-path local/mongo_as_unvalidated_nmdc_database.yaml \
                --salvage-prefix generic \
                --output-path local/mongo_as_nmdc_database_rdf_safe.yaml
```

> ```
> error: ERROR: Migrator_from_9_3_to_9_4 is not a valid migrator module name. No module named 'nmdc_schema.migrators.Migrator_from_9_3_to_9_4'.
> ```

**Comment by brynnz22** [comment]
@turbomam did you try it with the upper case M? I believe it does need to be uppercase.

**Comment by turbomam** [comment]
Yes, thanks. I addressed that in the comment directly above yours. @eecavanna said we could discuss it in a few minutes.

**Comment by eecavanna** [comment]
I forgot to update this part of the module (in [PR1624](https://github.com/microbiomedata/nmdc-schema/pull/1624)) to accommodate the final structure of the `Migrator` class.

https://github.com/microbiomedata/nmdc-schema/blob/86b26440311d01b2850aa0c7210930e13dc17531/nmdc_schema/migration_recursion.py#L172-L187

I'll submit a patch today.

**Comment by eecavanna** [comment]
I'm confident this is a bug I introduced into the codebase. For now, I'll remove @aclum and @brynnz22 as assignees and keep myself there.
