### ISSUE TITLE
broken data download links

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#171]
@turbomam The download links seem broken. Here is what I get when I click on one.

![image](https://user-images.githubusercontent.com/3186638/136712863-5fefc974-7355-4726-a327-d241181545a8.png)

Would you mind updating them? ... please :)

cc @cmungall

**Comment by dwinston** [comment]
Perhaps just replace the section with a link to <https://github.com/microbiomedata/nmdc-runtime/#data-exports>?

**Comment by wdduncan** [comment]
@turbomam can you update the readme to use the [nmdc-runtime exports](https://github.com/microbiomedata/nmdc-runtime/#data-exports)?

**Comment by turbomam** [comment]
> @turbomam can you update the readme to use the [nmdc-runtime exports](https://github.com/microbiomedata/nmdc-runtime/#data-exports)?

Sorry for the delay, @Bill, I think I see a couple of ways for doing this and I'm not sure which you think is best.

- One solution is in PR #181, which you approved but I don't merge yet. I used the link https://portal.nersc.gov/project/m3408/meta/mongoexports/2021-07/ which points to a handy download index page that's sort-able by name and size, but it's static for the 2021-07 release and would have to be updated.
- @dwinston and you have mentioned using the nmdc-runtime exports at https://github.com/microbiomedata/nmdc-runtime/#data-exports
    - were you thinking we would just add a link to that section of documentation in the nmdc-schema README.md, or were you thinking that we would build something that queries the DRS API and renders and up-to-date list of downloadable files in the nmdc-schema README.md?
