### ISSUE TITLE
has_unit does not appear as a slot for QuantityValue in the online documentation ?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1724]

**Comment by sujaypatil96** [comment]
Here is the documentation page for QuantityValue: https://microbiomedata.github.io/nmdc-schema/QuantityValue/

The slots table on the above documentation page: https://microbiomedata.github.io/nmdc-schema/QuantityValue/#slots accurately shows the has_unit slot asserted on that class.

I think this issue can be closed @turbomam
