### ISSUE TITLE
Split up MetatranscriptomeActivity like metaG was

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#1725]
Create classes in berkeley-schema fork to break up [MetatranscriptomeAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAnalysis/) the same way we did MetagenomeAnalysis. 

Create sub-issues as needed.

**Comment by aclum** [comment]
I don't think we need to do this. MetaT uses the same subclasses as metagenome with the exception of counting step which uses [MetatranscriptomeAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAnalysis/)

**Comment by ssarrafan** [comment]
Closing this issue based on the last comment from @aclum 
@mslarae13 let me know if you want this to remain open
