### ISSUE TITLE
Developer documentation and `Dockerfile` contradict one another

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1739]
The [developer documentation](https://github.com/microbiomedata/nmdc-schema/blob/main/DEVELOPMENT.md) says that spinning up the Docker Compose stack will result in a Mkdocs dev-server listening for incoming requests; but that is no longer the case as of commit https://github.com/microbiomedata/nmdc-schema/commit/3a1381bd050c8a538fc29edc759b90acb4050929, in which the command that starts the Mkdocs dev-server was commented out.

https://github.com/microbiomedata/nmdc-schema/blob/3db6cff34450bfca7d48e305c1495af36606730f/Dockerfile#L67-L71

**Comment by eecavanna** [comment]
Here's the path forward I want to take:
- Debug the issues with the original command
- Reinstate the original command into the `Dockerfile`

**Comment by eecavanna** [comment]
The command `poetry install` is commented out also. That means the Python dependencies will not be installed.

**Comment by eecavanna** [comment]
Hi @ssarrafan, there's a tag I have liked on other projects, called `awaiting-response` (whether in pursuit of making a decision, gathering more information, etc.).

I think I'd prefer not having a column on the sprint board for "decisions needed". That's because it can occur at various stages of `todo` -> `in progress` -> `in review` -> `done` and I like the left-to-right flow that the current set of columns "encourages."

**Comment by eecavanna** [comment]
I don't expect us to get to this this sprint anymore, so I'll move it to the next one.

**Comment by turbomam** [comment]
Sorry for leaving things in the bad stated @eecavanna . I can help get the documentation to agree with the current implementation, or work together with you to go back to your previous implementation, as long as it works on MacOS and Linux.

**Comment by eecavanna** [comment]
Moving to next sprint as I will be out of the office tomorrow (sprint ends tomorrow).

**Comment by eecavanna** [comment]
@turbomam and I discussed this today. I will remove him as an assignee and open a PR that updates the documentation.

**Comment by eecavanna** [comment]
I opened a PR that resolves this issue: https://github.com/microbiomedata/nmdc-schema/pull/1854
