### ISSUE TITLE
`local/mongo_as_nmdc_database_rdf_safe.yaml` target in `berkeley-schema-fy24`'s `main` fails to run migration

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1755]
> ` Migrator_from_X_to_PR53 is not a valid migrator module name. No module named 'nmdc_schema.migrators.Migrator_from_X_to_PR53'.`

**Comment by turbomam** [comment]
Maybe we're missing some fixes that were added to nmdc-schema after the `nmdc-schema` -> `berkeley-schema-fy24` merge process was started?

**Comment by brynnz22** [comment]
@turbomam I think we did because the migrator for PR53 looks slightly different than the rest. I can look into it today!

**Comment by eecavanna** [comment]
Here's a link to the code that generates that error message:

https://github.com/microbiomedata/berkeley-schema-fy24/blob/06ebc00b55401100ca82c4c5a573128cb605e85d/nmdc_schema/migration_recursion.py#L119-L121
