### ISSUE TITLE
Implement migrator that populates `WorkflowExecutionActivity.has_calibration` field with a `Calibration.id` value

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1761]
Just a noting that in nmdc-schema has_calibration has a range of a string and is currently populated with either a data object identifier, "False", or "false". In the berkeley schema the range of this slot is now DataObject so records having a value of "False" or "false" prior to migration should exclude this slot.  @corilo  to confirm desired behavior and that there is not another slot that should be populated with a boolean value. I came across these when dealing with some re-iding stuff so wanted to record what I believe is the desired behavior for migration.

cc @eecavanna @brynnz22 @mslarae13 @SamuelPurvine

**Comment by brynnz22** [comment]
@aclum I am looking into this now for the migration for this. Will the data object ids that are values for `has_calibration` be changed as part of the re-iding effort? For example, the data object with `id` of `nmdc:cdee3cc8648d43fbbcfd488247ba1887` has a value of `has_calibration` of `emsl:output_499639`. This does not currently match an `id` of any data object.

**Comment by SamuelPurvine** [comment]
For those without access to DMS, output_499639 corresponds to Agilent_GC_MS_01 datafile Froze_Core_2015_N3_20_30_32_Metab, part of the Stegen effort/study, collected May 24, 2016. It was second in a series of 17 GC-MS files collected on or closely around that date. Also collected on that date, before the 17 Froz_Core_2015 samples, was GCMS_FAMEs_01_GCMS01_20160524, which I 'think' is the QC instrument run that is used to calibrate the GC retention times for metabolomics compound identifications.

This comment doesn't attempt to answer anything, just give some info about that particular emsl:output_ identifier.

**Comment by brynnz22** [comment]
@SamuelPurvine I see. Should those emsl:output_identifier have `DataObject` metadata in NMDC since `has_calibration` points to an nmdc `DataObject`. @corilo? Or is okay to just be a string that is emsl:output_identifier? If so, then it seems like the `range` of `has_calibration` should be a string or maybe a curie?

**Comment by aclum** [comment]
Yuri has to decide if he wants this slot to be a boolean or a curie. If a curie it should be populated with a data object (nmdc:dobj*). I do not recommend keeping the range as a string. 
For re-iding we are leaving the false or False values and updating any other values to a data object that exists in data_object_set.

**Comment by brynnz22** [comment]
Tagging @anastasiyaprymolenna @kheal as we are working on updating MassSpec metadata.

**Comment by kheal** [comment]
I'm closing this issue, not because it is completed but because we are taking a different approach to solve this issue during the refactoring, which is tracked here: https://github.com/microbiomedata/issues/issues/750
