### ISSUE TITLE
Migrators: Update example migrator to demonstrate cross-collection operations

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1771]
For example:
- creating a document in a collection, using values from an existing document in a different collection

**Comment by eecavanna** [comment]
This ticket will be closed once https://github.com/microbiomedata/nmdc-schema/pull/1772 (awaiting review) has been merged into `main`.

**Comment by ssarrafan** [comment]
@turbomam is this review done yet?

**Comment by ssarrafan** [comment]
@eecavanna this has been in review for a while. Since you're out can you update it and add it to the next sprint Monday if it's still an active issue.  Thanks!

I'm removing from the board.

**Comment by eecavanna** [comment]
Status (from my perspective):
- Implementation is done
- Awaiting review/merge

@turbomam, I'll check in with you about it next week. As far as I'm concerned, it can be merged in.
