### ISSUE TITLE
Document `mkd-gh-deploy` Make target used by GitHub Actions workflow

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1782]
I see the `deploy-docs.yaml` workflow runs (among other things) the command `$ make mkd-gh-deploy`.

https://github.com/microbiomedata/nmdc-schema/blob/668f56c4caa3aac226fc3ae37d3d3c2bb232ad50/.github/workflows/deploy-docs.yaml#L31

I don't see where that `make` target is defined. When I [search the repo](https://github.com/search?q=repo%3Amicrobiomedata%2Fnmdc-schema%20mkd-gh-deploy&type=code) on GitHub, I see it listed as a `make` target's _dependency_; but I don't actually see its own definition as a `make` target.

I'm creating this issue to represent the task of documenting that `make` target. I think that will make it easier for people to maintain the workflow (and update it in the future). As it exists today, I don't know where `mkd-gh-deploy` is defined and why it works.

I'm assigning it to @sujaypatil96 as I think he introduced it into the workflow via https://github.com/microbiomedata/nmdc-schema/pull/876/files.

**Comment by ssarrafan** [comment]
@sujaypatil96 will this be done this week? Or should it be moved to the next sprint?

**Comment by sujaypatil96** [comment]
@ssarrafan this needs to be moved to the next sprint.

**Comment by eecavanna** [comment]
I think I found where the `mkd-gh-deploy` target is defined.

There seems to be some kind of wildcard target defined on line 171 of the `Makefile`.

![image](https://github.com/microbiomedata/nmdc-schema/assets/134325062/5b2b4474-75be-49eb-843e-211072c3c5a1)

Since it's in the `Makefile`, I suspect it comes from the cookiecutter.

Yes, I confirmed it comes from the cookiecutter:

https://github.com/linkml/linkml-project-cookiecutter/blob/07462f015a240ff3a68f52e25df027b33b364b1b/%7B%7Bcookiecutter.project_name%7D%7D/Makefile#L202

**Comment by eecavanna** [comment]
I recommend adding a comment next to occurrences of `mkd-gh-deploy` that say what it is and where it is derived (since there is no explicit definition of it).

@sujaypatil96, are you OK with me reassigning this to myself? I have a solution in mind.

**Comment by ssarrafan** [comment]
> I recommend adding a comment next to occurrences of `mkd-gh-deploy` that say what it is and where it is dynamically defined (since there is no static definition of it).
> 
> [@sujaypatil96](https://github.com/sujaypatil96), are you OK with me reassigning this to myself? I have a solution in mind.

@eecavanna @sujaypatil96 can this be done by tomorrow?

**Comment by eecavanna** [comment]
I don't have the bandwidth to do it by tomorrow, but I'll assign it to myself and do it next sprint. I think it'll take no more than 5 minutes to document, but I don't want to context switch.

**Comment by eecavanna** [comment]
I documented this in the following PR: https://github.com/microbiomedata/nmdc-schema/pull/1853
