### ISSUE TITLE
`dictionary_adapter.py` tries to access non-existent collection

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1784]
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/gitrepos/nmdc-schema/nmdc_schema/migration_recursion.py", line 173, in main
>     migrator.upgrade()
>   File "/home/mark/gitrepos/nmdc-schema/nmdc_schema/migrators/migrator_from_9_3_to_10_0.py", line 13, in upgrade
>     self.adapter.process_each_document(
>   File "/home/mark/gitrepos/nmdc-schema/nmdc_schema/migrators/adapters/dictionary_adapter.py", line 261, in process_each_document
>     for index, original_document in enumerate(self._db[collection_name]):
> KeyError: 'extraction_set'
> 
> ```

**Comment by turbomam** [comment]
Thanks for responding. I just pulled main. How can I determine the commit hash?

**Comment by eecavanna** [comment]
I usually do it with this command, because I remember it (I think there are other commands that product it, too, in a more concise way):

```shell
$ git log -1
```

The output starts with `commit {commit_hash}` and I want to know the `{commit_hash}` part.

**Comment by turbomam** [comment]
668f56c4caa3aac226fc3ae37d3d3c2bb232ad50

**Comment by eecavanna** [comment]
Thanks for confirming. I'll take a look.

**Comment by eecavanna** [comment]
What arguments were you passing to the `migration_recursion.py` script (command)?

**Comment by turbomam** [comment]
It looks like I explicitly commented out 

```
# 		--selected-collections extraction_set \
```

from `pure-export` on January 29th, but I don't remember why.

**Comment by eecavanna** [comment]
OK, thanks. I have the same commit checked out now and am running `$ make make-rdf` to try to reproduce this.

Even though you have commented that line out, I still don't want the adapter to raise that exception. I'll look at the adapter's code while `make-rdf` is running.

**Comment by turbomam** [comment]
But I left in `		--selected-collections functional_annotation_agg \`. Maybe that's not populated and it probably has nothing to do with this issue.

**Comment by turbomam** [comment]
I'm rerunning `make-rdf` now too, but only selecting the following collections in `pure-export`:

```shell
		--selected-collections activity_set \
		--selected-collections biosample_set \
		--selected-collections study_set \
```

same error

**Comment by eecavanna** [comment]
The error is happening because the "database" being migrated doesn't have an `extraction_set` collection in it.

**Comment by eecavanna** [comment]
I'll add a check to the adapter to check that the specified collection exists in the database before trying to iterate over its contents. In the meantime, you can ensure that the collection exists in the "database" before running the migration script. I'll open a PR when done.

**Comment by turbomam** [comment]
The migrator should be able to migrate YAML files, as dictionaries, that only have selected collections. That's always worked up until today.

**Comment by turbomam** [comment]
I just ran `make-rdf` with pure-export configured like that

```shell
		--selected-collections activity_set \
		--selected-collections biosample_set \
		--selected-collections extraction_set \
		--selected-collections study_set \
```

and the migration completed. So it seems to be tolerant of some missing collection, just not `extraction_set` in this case?

**Comment by eecavanna** [comment]
I expect it to be equally intolerant, regardless of which collection is missing.

ETA 3 minutes until a PR exists.

**Comment by turbomam** [comment]
sorry for interrupting

**Comment by eecavanna** [comment]
It's OK. All the info was helpful for me. Here's a link to the PR: https://github.com/microbiomedata/nmdc-schema/pull/1785

**Comment by eecavanna** [comment]
It didn't interrupt me (I checked the issue every now and then anyway since my phone was vibrating with GitHub notifications).

**Comment by turbomam** [comment]
bzzz bzzz bzzzz
