### ISSUE TITLE
Update PR10 migrator to account for inlined classes in WorkflowExecutions

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1800]
The migrator written for the Berkeley refactoring that adds the `type` slot to every class needs to be updated to account for all inlined classes. As it is written right now it only accounts for inlined classes part of `Biosample`, `Study` and `Extraction`. It appears that there are inlined classes as part of some of the `WorkflowExecution` subclasses. This needs to be looked into and the migrator updated.

**Comment by ssarrafan** [comment]
@brynnz22 is this issue active?  Should it be moved to the next sprint?

**Comment by brynnz22** [comment]
This is closed. Sorry!
