### ISSUE TITLE
Migrators: Update framework so caller receives information about migration events

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1801]
Use case:
- A migrator renames a collection; but the script that invoked the migrator was written under the assumption that collection names are constant for the life of the script. If the script received information saying that a collection had been renamed, it could update its behavior accordingly (i.e. using the new name instead of the original one).

This topic was discussed during the February 27, 2024, instance of the migration squad meeting.

One way this could be accomplished is through the use of "callback" functions. Example of the "callback function" pattern, in general (ignoring the real structure of the `Migrator` class):
```python
# In some arbitrary script...

def replace_dict_key(old_key: str, new_key: str):
    """Replaces a dictionary key."""
    my_dict[new_key] = my_dict[old_key]
    del my_dict[old_key]

# In a hypothetical migrator...

def rename_collection(old_name: str, new_name: str, do_after_renaming: Callable = None):
    """Renames a Mongo collection, and—if a callback function was provided—invokes it."""
    db.get_collection(name=old_name).rename(new_name=new_name)

    # If a "callback" function was provided, invoke it.
    if do_after_renaming is not None:
        do_after_renaming(old_name, new_name)

# Back in that arbitrary script...

# Note: We pass `replace_dict_key` as the "callback" function.
rename_collection("square_set", "rectangle_set", replace_dict_key)
```

**Comment by ssarrafan** [comment]
@eecavanna who needs to review this?

**Comment by eecavanna** [comment]
Hi, @ssarrafan. @turbomam and I talked about this issue and the associated PR (https://github.com/microbiomedata/nmdc-schema/pull/1802) on Tuesday. Our plan was that he would re-run the usual set of tests he runs before merging a PR, and then—assuming all of those tests pass—merge it in. Based on that, I expect @turbomam will be the person reviewing it.

**Comment by ssarrafan** [comment]
Ok I'll move this to the next sprint for @turbomam to review
