### ISSUE TITLE
merge current `nmdc-schema` into `berkeley-schema-fy24`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1832]
### in `berkeley-schema-fy24`: 

```shell
git checkout main
git remote add upstream https://github.com/microbiomedata/nmdc-schema.git
git fetch upstream
git merge upstream/main
```

### start working on conflicts

`src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml` was "deleted by us"

still available at https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml

**Comment by turbomam** [comment]
```shell
make squeaky-clean all test
```

> ValueError: Example src/data/valid/Biosample-exhaustive.yaml failed validation:

So I deleted it.  Still avaialble at

https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Biosample-exhasutive.yaml

Although that won't have any type assignments and exhaustive was misspelled at one point

**Comment by turbomam** [comment]
```shell
git log -- src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml
```


> commit 0071a87202d333d8e6a6ffaa0a1002e46b0c0cab
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Sun Dec 17 22:44:38 2023 -0500
> 
>     most valids have types
>     
>     will need to add types to invalids too for 'single fault'
> 
> commit bc4b1e0a027d7c3f1497b7fcde19f3b826913fe5
> Merge: 26ea0a7d 4b65dfd7
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Sun Dec 17 18:30:33 2023 -0500
> 
>     issue complete except type not required
> 
> commit ef20d5427ddb02d64d6b3193033745ca61d01415
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Thu Dec 14 11:51:01 2023 -0500
> 
>     more examples behaving as expected
> 
> commit 164e581fc4467efffa7ffb4fba6678cb8e08be37
> Author: James Tessmer <james.tessmer@pnnl.gov>
> Date:   Wed Dec 13 14:56:50 2023 -0800
> 
>     removed references to Phenol/chloroform extraction
> 
> commit 0de4bb4ffbe8e7c1c1058f23c5d64076c57ce251
> Author: Mark Andrew Miller <MAM@lbl.gov>
> Date:   Tue Oct 24 14:35:09 2023 -0400
> 
>     id mentions pattern checking
>     
>     including updated example data
> 
> commit f060324cb1ad1c412467641c55c21a30064fd31c
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Mon Sep 18 19:03:15 2023 -0400
> 
>     always gold never GOLD
> 
> commit 0377450aceaa275599009b0b00eeb855cadb39f4
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Fri Jun 9 18:46:16 2023 -0400
> 
>     cleaned up prefixes and module id
>     
>     and other small fixes
> 
> commit ad371222d5c7840aa1d96dc8eaab4cb1e05278bd
> Merge: 7432e8e2 79a5f91a
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Fri Jun 9 15:42:38 2023 -0400
> 
>     haven't modeled types yet
> 
> commit e1178d8e23bb3e49c05611278ddea1e0d2109588
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Thu Jun 8 15:14:00 2023 -0400
> 
>     img_identifiers specification and examples
> 
> commit c749e617374d2c9b6023cb339559235b6ddf6c88
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Wed Jun 7 21:30:29 2023 -0400
> 
>     #963 plus some schema diet
> 
> commit 03f5da12a4bbcebe9b07935afdcc56e93456824a
> Author: Mark Andrew Miller <MAM@lbl.gov>
> Date:   Thu Jun 1 13:36:59 2023 -0400
> 
>     tests pass
> 
> commit 9dccf7931bbce8669d0698f01db154312932936e
> Author: Mark Andrew Miller <MAM@lbl.gov>
> Date:   Tue May 23 12:02:06 2023 -0400
> 
>     tests pass
> 
> commit 5409d29af1970282d300c17369eaece7a85e4b3d
> Author: Mark Andrew Miller <MAM@lbl.gov>
> Date:   Tue May 16 19:14:16 2023 -0400
> 
>     updated tube/plate/well ruels and example data
> 
> commit 01f1cd1b723c645ae69c84b33e6d6c238175d0af
> Author: Mark A. Miller <mamillerpa@gmail.com>
> Date:   Wed Mar 22 20:31:44 2023 -0400
> 
>     float ranges for jgi mg and mt
>     
>     schema and data
> 
> commit c4a8fb80ff15b5f8176710bc68f1ca84005eb3b1
> Author: Mark A. Miller <mamillerpa@gmail.com>
> Date:   Tue Feb 28 12:41:48 2023 -0500
> 
>     updated exhaustive/796 biosample
>     
>     refactored materialized site target but fails every other time
> 
> commit 5e55c8c3ac88d30e879e9f419fb05afb719253ce
> Author: Mark A. Miller <mamillerpa@gmail.com>
> Date:   Tue Feb 28 09:39:53 2023 -0500
> 
>     add_date expects string
> 
> commit 5ce9b2a8c394384404163d3799cc43d6e3d318fa
> Author: Mark A. Miller <mamillerpa@gmail.com>
> Date:   Mon Feb 27 11:51:11 2023 -0500
> 
>     #798 comparable exhasutive biosample data
>

**Comment by turbomam** [comment]
```shell
git log -- src/data/valid/Biosample-exhaustive.yaml
```

> commit 0071a87202d333d8e6a6ffaa0a1002e46b0c0cab
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Sun Dec 17 22:44:38 2023 -0500
> 
>     most valids have types
>     
>     will need to add types to invalids too for 'single fault'
> 
> commit bc4b1e0a027d7c3f1497b7fcde19f3b826913fe5
> Merge: 26ea0a7d 4b65dfd7
> Author: Mark A. Miller <MAM@lbl.gov>
> Date:   Sun Dec 17 18:30:33 2023 -0500
> 
>     issue complete except type not required
>

**Comment by turbomam** [comment]
```shell
poetry run linkml-run-examples \
        --schema project/nmdc_schema_generated.yaml \
        --input-directory src/data/valid \
        --counter-example-input-directory src/data/invalid \
        --output-directory examples/output > examples/output/README.md
```

all deletions required to get examples to pass

- src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml
- src/data/valid/Biosample-exhaustive.yaml
- src/data/valid/Database-biosample-exhasutive.yaml
- src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml
- src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml

**Comment by turbomam** [comment]
but the PR says that only these were deleted in the merge:
- src/data/valid/Database-biosample-exhasutive.yaml
- src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml
- src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml

**Comment by turbomam** [comment]
- https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/Database-biosample-exhasutive.yaml
- https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml
- https://github.com/microbiomedata/berkeley-schema-fy24/blob/main/src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml

**Comment by turbomam** [comment]
- https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Database-biosample-exhasutive.yaml
- https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml
- https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml

**Comment by kheal** [comment]
Closing this - we've had several merges from `nmdc_schema` into `berkeley-schema-fy24` since this issue was made.
