### ISSUE TITLE
Handle emsl:output does not match nmdc:dobj failures vs. v10.1 schema

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1833]
```
[ERROR] [./local/nmdc:sty-11-aygzgv51.yaml/0] 'emsl:output_500091' does not match '^nmdc:dobj-[0-9][a-z]{0,6}[0-9]-[A-Za-z0-9]{1,}(\\.[A-Za-z0-9]{1,})*(_[A-Za-z0-9_\\.-]+)?$' in /omics_processing_set/256/has_output/0

```

**Comment by aclum** [comment]
@picowatt this is a proteomics data object. can you make sure all the proteomics data objects are deleted.

**Comment by mbthornton-lbl** [comment]
@picowatt Is there any other data apart from the `emsl:output_` ID pattern that I need to know about when I go deleting?

**Comment by mbthornton-lbl** [comment]
Re-extracted the Stegen study and re-ran validtion:

```
 % linkml-validate -s ../../local/nmdc-schema-v10.1.1.yaml ../../local/nmdc:sty-11-aygzgv51.yaml

INFO:root:Using SchemaView with im=None
[ERROR] [../../local/nmdc:sty-11-aygzgv51.yaml/0] Additional properties are not allowed ('award_dois', 'publication_dois' were unexpected) in /study_set/0
[ERROR] [../../local/nmdc:sty-11-aygzgv51.yaml/0] 'study_category' is a required property in /study_set/0

``` 

`study_category`, `award_dois`, and `publication_dois` errors are expected here, and will be addressed by the v10 data migration process

**Comment by mbthornton-lbl** [comment]
@aclum @picowatt Based on the results of `linkml-validate` above, this ticket can be closed. There were not code changes so noPR
