### ISSUE TITLE
Deprecate, don't delete `Reaction`?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1839]
This PR deletes `Reaction` 
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/64

We should probably go though the deprecation process. Can somebody help me with that?

**Comment by mslarae13** [comment]
@cmungall @sierra-moxon I think you were going to work on the documentation and 'how to deprecate' guide for NMDC, correct?

**Comment by mslarae13** [comment]
We are deleting / deprecating this in berkeley-schema, right? Or did you do it in main? if it's done in berk, then I don't think we need to deprecate. Just delete it.
