### ISSUE TITLE
ChemicalConversionProcess class refactor

### ISSUE THREAD

**Issue by sierra-moxon** [microbiomedata/nmdc-schema#1842]

**Comment by sierra-moxon** [comment]
Notes from 3/11/24 meeting with Mark, James, Sujay, Samuel, Sierra, Anastasiya
leader: Anastasiya 
notes: Sierra (please correct/add)

We'd like to simplify modeling between reagents and solutions and catalysts.
Can we have a simple relation that covers both `has reagent` and `catalyzed by` ?
Can we have a class that combines Solution components and Reagent collection collections? 
a "role" would need to be an attribute on the use of that reagent or solution in a particular experiment (role of "buffer" role of "catalyst" etc...)

Mark showed OBI
has_input, has_output are important generic relations
Asked: should we have specificity in the model or in the values of the generic model components.
[Mark's diagram](http://3.236.215.220/graphs-visualizations?uri=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FPR_000027795&role=subject)


discussing:
https://github.com/microbiomedata/nmdc-schema/issues/1564
https://github.com/microbiomedata/nmdc-schema/issues/1741
https://github.com/microbiomedata/nmdc-schema/issues/1666

**Comment by turbomam** [comment]
completed via
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/116
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/114
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/106
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/100
