### ISSUE TITLE
Remove `has_calibration` from `WorkflowExecution` subclasses after `MassSpectrometry` change sheets

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1852]
see issue: https://github.com/microbiomedata/nmdc-schema/issues/1570

In issue linked above, discussed creating a `Calibration` class. Will need to change name of slot from `has_calibration` which implies a boolean and we are linking a `DataObject`.

This will require a migration.

**Comment by brynnz22** [comment]
After discussion with @kheal and @anastasiyaprymolenna `has_calibration` is fine the way its modeled on `ChromatographicSeparationProcess`. Calibration does not need to have its own class.

**Comment by kheal** [comment]
See update here: https://github.com/microbiomedata/nmdc-schema/issues/1918 .  After discussing limitations of only capturing the a `DataObject` with regards to calibration, we will likely make a `Calibration` class.

**Comment by kheal** [comment]
See https://github.com/microbiomedata/berkeley-schema-fy24/pull/133.

After ingestion
1. The range of `has_calibration` on `CalibrationInformation` class should  be limited to`CalibrationInformation`. 
2. The definitions for `CalibrationInformation`, `has_calibration`, `calibration_target`, `CalibrationTargetEnum`, `internal_calibration`, `calibration_standard`, `CalibrationStandardEnum`, and `calibration_object` can move from the `workflow_execution.yaml` to the a logical location of `nmdc.yaml`

**Comment by aclum** [comment]
Is this planned for after the rollout?

**Comment by kheal** [comment]
@aclum .  As part of the rollout, @brynnz22  and I will need to make changesheets for existing GC-MS metabolomics and NOM DataGeneration records to refactor the use of the 'has_calibration' slot.  After that we can remove that slot and its contents from the WorkflowExecution class.  If we remove that slot before the changesheets, we'll orphan the DataObjects that are linked through that slot.

**Comment by kheal** [comment]
Note that this is dependent on the completion of https://github.com/microbiomedata/issues/issues/750

**Comment by brynnz22** [comment]
@kheal after thining about this further, I don't think we should add the `has_calibration` in the change sheet and write a migrator to remove the slot from the `WorkflowExecution`. This allows room for a lot of human error. I think we should go with what I suggested last week. Write a migrator that moves it upstream to the `MassSpectrometry` its on, and then remove. This allows us to do checks and make sure its on the correct instance. Whereas using a change sheet then removing it in a migrator allows for possible errors of mismatching. I can write the migrator for this. I will also do the change sheet. thanks!

**Comment by kheal** [comment]
@brynnz22  Sounds reasonable.  I certainly prefer migrators over changesheets and I agree there are fewer opportunities for errors.  I'll update the https://github.com/microbiomedata/issues/issues/750 with this new plan.  Will you make a new issue (or change this issues' name/description?) to describe the migrator? I think I understand it, but I think you'll capture it more thoroughly.

**Comment by kheal** [comment]
@brynnz22 - I think this can be closed now that https://github.com/microbiomedata/nmdc-schema/pull/2235 is in, correct?
