### ISSUE TITLE
Delete bioscales legacy data objects

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1859]
There are legacy sequencing data files from studies that have been removed or re-ided but not cleaned up properly (bioscales)
After all studies have been re-id we should use this function to delete any remaining legacy sequencing raw data files in the data_object_set collection

`{id: {$not: { $regex: '^nmdc:dobj*'}},'description':'Raw sequencer read data'}`

**Comment by mbthornton-lbl** [comment]
This query find 444 documents:

```
db.getCollection("data_object_set").find(
    {id: {$not: { $regex: '^nmdc:dobj*'}},'description':'Raw sequencer read data'}
)
```

**Comment by aclum** [comment]
that is the expected number of records. Attached is info on what these records are from the JGI side. 
[20240425.legacy seq data objects.csv.csv](https://github.com/microbiomedata/nmdc-schema/files/14760768/20240425.legacy.seq.data.objects.csv.csv)

**Comment by aclum** [comment]
Confirmed fixed. This can be closed.
