### ISSUE TITLE
update example data to napa -style identifiers

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1868]
After re-iding is complete and the materialized pattern version of the schema is enforced some of the example data will fail validation because there are legacy style identifiers. We can & should fix some of this in advance.

**Comment by aclum** [comment]
@turbomam  took care of this several months ago.

**Comment by aclum** [comment]
This is fixed for IDs but not ID mentions.

**Comment by aclum** [comment]
@turbomam  not quite sure what to do here. These are hard to find out with structured_pattern enforced for IDs and ID mentions. Some of this is fixed in Berkeley.

**Comment by aclum** [comment]
I started a branch and will push my changes but we need fix issues mentioned above.

**Comment by turbomam** [comment]
Yeah, this is one of those things where the progress made in nmdc-schema and berkeley-schema-fy24 isn't totally clear

I'll 
- try to make detection of pattern constraints in the schema clearer
- provide tools for checking the examples against the various forms of the schema
    - src/schema/*.yaml
    - nmdc_schema/nmdc_materialized_patterns.yaml
    - nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml
    - nmdc_schema/nmdc_schema_merged.yaml

**Comment by aclum** [comment]
This PR addressed constraints on ID mentions which required updating all the example data to make it match. @bmeluch is separately going to review the invalid data to make sure tests fail or one and one one reason.

**Comment by aclum** [comment]
Assigning to @bmeluch  so she can update the invalid example data. I fixed a lot of this in Berkeley but not in nmdc-schema.

**Comment by bmeluch** [comment]
Being addressed in Berkeley as part of https://github.com/microbiomedata/berkeley-schema-fy24/pull/220

**Comment by aclum** [comment]
Bea's PR was merged in so I think we are good to close this out.
