### ISSUE TITLE
DataPortal can be searched for `Pathway`s and `OntologyGroup`s... does that justify leaving them in nmdc-schema?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1881]
Good question. Suggested by @mslarae13

**Comment by mslarae13** [comment]
I don't remember making this suggestion :)

**Comment by turbomam** [comment]
whops! sorry @mslarae13

**Comment by turbomam** [comment]
@bmeluch you and discussed something like this earlier this week, right? I recommend

**Comment by bmeluch** [comment]
Yes we talked about it since those classes do not appear anywhere in the example data. I guess we just have to make sure no one has been incubating any plans for them?

**Comment by turbomam** [comment]
Id there's time should we discuss this in the upcoming _NMDC Schema & Metadata_ meeting?

**Comment by bmeluch** [comment]
From 03 July Metadata/ Data Schema / Data Management Meeting: these classes were never used, we aren't modeling these at this level of granularity, put in a PR to remove them. Team will review and decide if it can be merged before or after Berkeley schema rollout.

**Comment by bmeluch** [comment]
Closing this issue, this was addressed in Berkeley, see discussion in the linked PR

**Comment by bmeluch** [comment]
It's not in a comment but in the issue history, https://github.com/microbiomedata/berkeley-schema-fy24/pull/222
