### ISSUE TITLE
update code to delete unconnected workflow activity and data objects to same logging format as Michael's deletion function

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1896]
There is code from https://github.com/microbiomedata/nmdc-schema/blob/28823618de2c17189934cdae0ca291d14fda0c08/nmdc_schema/connect_napa_mongo.py#L454 , lines 454 to 490, which based on a list of gold projects deletes workflow execution activities and data objects. These won't have a study ID b/c upstream records were never properly made. The deleted workflow records currently print to standard out but not in the same format the Michael is using and the data object deletions is not logged.

Please update to a more consistent logging to what is being done in PR https://github.com/microbiomedata/nmdc_automation/pull/83

**Comment by mbthornton-lbl** [comment]
Done in #1902
