### ISSUE TITLE
Resolve referential integrity exceptions for `nmdc:sty-11-547rwq94` Metagenome Omics Processing records

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1897]
## Referential Integrity Exception: `omics_processing_has_output_data_object`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/MBThornton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/MBThornton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

649b009773e824995934a1d3 | nmdc:omprc-11-tdt0js09 | Volcanic soil microbial communities from   Hawaii, Kilauea Volcano, USA - King27.Edge.1.3.0.2 |   | nmdc:bsm-11-bzj1ca10 | nmdc:8a9d164e1310e5b838d6ceb492f64a61 | nmdc:sty-11-547rwq94 | Metagenome | nmdc:OmicsProcessing
-- | -- | -- | -- | -- | -- | -- | -- | --
649b009773e824995934a1d3 | nmdc:omprc-11-tdt0js09 | Volcanic soil microbial communities from Hawaii, Kilauea Volcano, USA -   King27.Edge.1.3.0.2 |   | nmdc:bsm-11-bzj1ca10 | nmdc:9bd3cf378610c02776b54cc797d8c07a | nmdc:sty-11-547rwq94 | Metagenome | nmdc:OmicsProcessing
649b009773e824995934a1d3 | nmdc:omprc-11-tdt0js09 | Volcanic soil microbial communities from Hawaii, Kilauea Volcano, USA -   King27.Edge.1.3.0.2 |   | nmdc:bsm-11-bzj1ca10 | nmdc:9d5f99fba241d6bdd933ccbf405bf872 | nmdc:sty-11-547rwq94 | Metagenome | nmdc:OmicsProcessing

</body>

</html>

**Comment by aclum** [comment]
This duplicates https://github.com/microbiomedata/issues/issues/596

**Comment by aclum** [comment]
Let's drop this omics processing record for now, the schema can't handle multiple seq runs until Berkeley schema.

**Comment by aclum** [comment]
@mbthornton-lbl please close if complete.
