### ISSUE TITLE
Metabolomics Schema Updates Meta Issue

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1905]
**MaterialProcessing**

- [x] #1908
- [x] #1907
- [x] #1906
- [x] https://github.com/microbiomedata/nmdc-schema/issues/1922

DataGeneration

- [x] #1909
- [x] #1913
- [x] #1920
- [x] #1918
- [x] #1910

WorkflowExecution

- [x] ~#1911~
- [x] #1912
- [x] #1914
- [x] #1942
- [x] #1943

Future things to Consider: 
- Syringe used as container or filter in MaterialProcessing step.

**Comment by turbomam** [comment]
I haven't had a chance to discuss any of these tasks with you in person yet, and I will be at a conference on Wednesday the 17th.

Do you all feel like you understand the modeling principles that will determine how quickly your branches can be merged in (as opposed to requiring a lot of refactoring?)

I think many of the sub-tasks above should be broken down into even smaller sub-tasks. For example, for class-creation sub-task, there may be new slots. I recommend defining those slots and getting them merged as early on as possible.

**Comment by turbomam** [comment]
Why are you thinking of creating a `workflow_version` slot? How is the existing [version](https://microbiomedata.github.io/berkeley-schema-fy24/version/) slot inadequate ?

**Comment by turbomam** [comment]
If you are going to create classes for modeling configuration, please do so in the most generic possible way. We should look for other existing patterns in the schema that associate configuration, settings or objective with a process.

**Comment by turbomam** [comment]
When pointing the instance of one class to a configuration, I recommend using a generic slot like `has_configuration` over `workflow_configuration_object`

**Comment by turbomam** [comment]
What will the range of `SubsamplingProcess`' `sample_portion` slot be?

**Comment by kheal** [comment]
> Why are you thinking of creating a `workflow_version` slot? How is the existing [version](https://microbiomedata.github.io/berkeley-schema-fy24/version/) slot inadequate ?

Good call @turbomam. 
@brynnz22  I think the version slot is adequate for our use - it accepts a string so we can say "MetaMS 2.1" and similar there, unless I'm missing something.
