### ISSUE TITLE
Add `StorageProcess` class (a subclass of `MaterialProcessing` with slots like `substances_used` (already exists) and `contained_in` slot (already exists), `duration` (already exists), and `temperature` (already exists). With `input` and 'output`

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1908]

**Comment by anastasiyaprymolenna** [comment]
After the Metadata squad meeting, it was suggested that rather than creating a whole new class just to capture storage, we can add slots to capture `duration` , `temperature` , and `contained_in` to the MaterialProcessing class and then capture a storage process as just a MaterialProcessing.

**Comment by anastasiyaprymolenna** [comment]
See PR https://github.com/microbiomedata/berkeley-schema-fy24/pull/126

**Comment by anastasiyaprymolenna** [comment]
@mslarae13 @turbomam

**Comment by anastasiyaprymolenna** [comment]
https://github.com/microbiomedata/berkeley-schema-fy24/pull/126
