### ISSUE TITLE
Include distinct packages in the schema

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#191]
Currently we have a "flat" biosample class with all relevant slots listed underneath

to drive DH we want to separate slots into packages. These will follow mixs, but we will be able to extend packages to add  our own slots.

For the purposes of the portal, we will continue to roll these up to a generic biosample class

**Comment by turbomam** [comment]
@cmungall @mslarae13 @pkalita-lbl I think we have delivered this in the submission-schema. In December, I hope we can harmonize the nmdc-schema `Biosample` with the environment-specific [`DhInterface`s](https://microbiomedata.github.io/submission-schema/DhInterface/) 

Close this issue?

**Comment by pkalita-lbl** [comment]
I think this can be closed.

**Comment by mslarae13** [comment]
Agreed. Closed for submission schema. for Biosample, we've decide NOT to prioritize this separation based on extension / environment type.
