### ISSUE TITLE
Edit slot usages to accommodate multiple detection configurations for single `MassSpectrometry` instance

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1910]
`MassSpectrometry` (or however it ends up) needs some slots to be multivalued to better describe the data generation process.

These slots should be able to be multivalued (and therefore the slot names should change to be plural):

- `resolution_category`.  Rewrite definition as well - _unity_ should be _unit_ 
- `mass_analyzer`
- `mass_spectrum_collection_mode`

This is likely better addressed in a configuration class rather than the instance of the MassSpectrometryProcess

**Comment by kheal** [comment]
Dependent on #1913
