### ISSUE TITLE
Add permissible values to `FileTypeEnum` and `DataCategoryEnum` to accomodate workflow configuration `DataObject`s

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#1912]
relies on issue #1913 and #1920. We will use the new `has_configuration` slot and make it have two ranges: the new `Configuration` parent class and `DataObject`

**Comment by kheal** [comment]
@brynnz22 per discussion in https://github.com/microbiomedata/berkeley-schema-fy24/pull/130, there is a preference that workflow configurations (which will be `DataObjects`) utilize a different slot than potential `has_configuration` slot, so this PR is not dependent on https://github.com/microbiomedata/berkeley-schema-fy24/pull/130.

**Comment by brynnz22** [comment]
Sounds good. I will add it separately. Thanks!
