### ISSUE TITLE
support slot for when document was added

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#1916]
For some classes, like workflow activity records we have information about when data was processed, I would like similar information about all classes, especially Study, Biosample, OmicsProcessing, and DataObject. We are routinely asked how much data has been added to the data portal on a per quarter or annual basis and need to make this easier to get a handle on. I frequently have to go off memory or restore from backups. I believe @eecavanna  has similar experiences. I would like to discuss options either in the schema or in runtime to add information about when a document was added to a collection.

@turbomam @dwinston @PeopleMakeCulture @shreddd

**Comment by PeopleMakeCulture** [comment]
@dwinston and I can update the runtime to support analytics queries against when data was created/updated in mongo. There's a couple ways to go about this, one of which would not require updates in `nmdc-schema`. 

@aclum could you: 
1. give a sense for the urgency of the request to help us decide on the best approach? 
2. If we decide to move forward with a runtime approach that does not require a new slot to be added to the schema, could you close this issue and open one in the [runtime repo](https://github.com/microbiomedata/nmdc-runtime)?  

## Approach Options

### 1. New `created_at` attribute/slot 
One approach is to add `created_at` and `updated_at` fields for individual collections (eg Biosample, Study, etc). However this would introduce an issue with data validation if an equivalent slot is not added in the nmdc schema. 

### 2. New `ledger` collection 
A second approach is to create an append-only ledger of [datomic](https://docs.datomic.com/cloud/whatis/data-model.html) entries. This would allow for a broader range of search queries and preserve update histories. However this would add additional complexity to querying and maintenance.

**Comment by aclum** [comment]
I was able to get what I needed for the quarterly report from Eric restoring some of the backups so this isn't urgent but I would like to see this addressed this quarter.

**Comment by PeopleMakeCulture** [comment]
> I was able to get what I needed for the quarterly report from Eric restoring some of the backups so this isn't urgent but I would like to see this addressed this quarter.

Great! That should give @dwinston and me enough time to implement the more robust append-only ledger solution, pending any larger decisions from the 4/25 database discussion

**Comment by turbomam** [comment]
Good discussion. Where does this stand as a schema request?

If it is a schema request, how would the slot we're talking about relate to the `add_date` slot?

**Comment by aclum** [comment]
The plan is to discuss at the infrastructure sync today. If no schema development is needed I'll convert this to a nmdc-runtime issue.

**Comment by aclum** [comment]
RE add_date, this current pulls from GOLD so is the GOLD added date so it would be good to clarify that at some point.

**Comment by eecavanna** [comment]
> If it is a schema request, how would the slot we're talking about relate to the `add_date` slot?

Here's a link to the documentation for the `add_date` slot: https://microbiomedata.github.io/nmdc-schema/add_date/.

Here are ways that I think I'd want the slot's specification to change if it were going to be used in the way people are talking about here:
- Rename slot to not imply its value is a date alone (as opposed to a date-and-time)
- Restrict slot to only accept strings that conform to some date-and-time standard (as opposed to _any_ string)

**Comment by shreddd** [comment]
Also consider pulling from Mongo [ObjectID](https://www.mongodb.com/docs/manual/reference/method/ObjectId/) which encodes the timestamp.

**Comment by eecavanna** [comment]
I just learned about that option within the past couple days (never knew that)! There is one caveat that I think exists with that option: based on what I read, the timestamp encoded in the ObjectId indicates when the _ObjectId_ was created, not when "the [rest of the] document" was created. So, if we were to restore from a backup and not using the `--preserveUUID` flag, I _think_ the _ObjectIds_ would all describe the restoration time, not the original creation time. Note: I haven't confirmed that suspicion through testing yet—it's just something that came to mind when I was reading about the fact that the _ObjectId_ contains a timestamp.

**Comment by aclum** [comment]
ie https://steveridout.com/mongo-object-time/
Closing for now will 
db.comments.find({_id: {$gt: ObjectId("5272e0f00000000000000000")}}), where 5272e0f00000000000000000 is the target date, syntax for now.

**Comment by eecavanna** [comment]
I want to emphasize that the Mongo docs say that the timestamp embedded in the ObjectId indicates the creation time of the _ObjectId_. I think the author of that converter may be making a "logical leap" by assuming it also indicates the creation time of the [rest of the] _document_, itself. That's something I haven't tested yet—I just want to reiterate that distinction here.

<img width="585" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/0914c3bd-0ea0-4712-8c0f-a7d9d7bb330e">
