### ISSUE TITLE
generate prefixmap for nmdc 

### ISSUE THREAD

**Issue by sierra-moxon** [microbiomedata/nmdc-schema#1925]
We can generate a prefix map for all the NMDC schema prefixes currently supported with their expansions using this linkml command: 

`poetry run gen-prefix-map src/schema/nmdc.yaml` 

per @aclum's request in PR #1924

**Comment by aclum** [comment]
@sierra-moxon  is there a way to get this generated and up on the website as a markdown file or something similar? Is gen-prefix-map part of linkml or this is specific to nmdc?

**Comment by sierra-moxon** [comment]
part of linkml, we can add it to the gen-doc target and deploy the .json file that results to our documentation site (that also allows downloading of the file at a stable URL instead of a github raw URL for computational usage). 

see PR #1976
