### ISSUE TITLE
Review and test NOM re-IDing code

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#1928]

**Comment by ssarrafan** [comment]
@mbthornton-lbl will be continuing to work on this in the next sprint per Slack message. Moving over.

**Comment by mbthornton-lbl** [comment]
Upon review I am planning on re-implementing the blocks of logic for Metabolomics and NOM in the `re_id_tool.py` tool in nmdc-automation
