### ISSUE TITLE
remove depth2 and subsurface_depth2 attributes

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#193]
After ETL reflecting schema changes in #189 have been processed by Kitware, remove the  `depth2` and `subsurface_depth2` attributes. These are only in there for backwards compatibility.

Related to https://github.com/microbiomedata/nmdc-runtime/issues/44

**Comment by ssarrafan** [comment]
@wdduncan should this be added to the December sprint?

**Comment by wdduncan** [comment]
This is dependent on corridation with Kitware. If possible, it would be great to get this done before @dwinston goes on leave. Do you think that is possible?

**Comment by turbomam** [comment]
done

`depth` has sub-slots for numerical, minimum and maximum values now.
