### ISSUE TITLE
add unit tests for validation

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#194]
Currently, I am using `make validate` for testing in `nmdc-schema`. 
```
validate-%: test/data/%.json jsonschema/nmdc.schema.json
# util/validate_nmdc_json.py -i $< # example of validating data using the cli
	pipenv run jsonschema -i $< $(word 2, $^)
```

I should switch to using unit tests.

@ssarrafan can add this to the November sprint?

cc @cmungall

**Comment by ssarrafan** [comment]
> Currently, I am using `make validate` for testing in `nmdc-schema`.
> 
> ```
> validate-%: test/data/%.json jsonschema/nmdc.schema.json
> # util/validate_nmdc_json.py -i $< # example of validating data using the cli
> 	pipenv run jsonschema -i $< $(word 2, $^)
> ```
> 
> I should switch to using unit tests.
> 
> @ssarrafan can add this to the November sprint?
> 
> cc @cmungall

Hi @wdduncan. Is this issue done or does it need to go to the backlog or the next sprint?

**Comment by ssarrafan** [comment]
Moving to December per @wdduncan
