### ISSUE TITLE
Create declarative mapping file for NMDC-to-NCBI push

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#1940]
Similar to the "NCBI Postgres database column to NMDC slot names" mapping file that we have in `nmdc-schema`: https://github.com/microbiomedata/nmdc-schema/blob/main/assets/ncbi_mappings/ncbi_pg_db_field_mappings_filled.tsv already, we need another declarative mapping file that maps "NMDC slot names to all NCBI BioSample harmonized names".

The NCBI BioSample Attributes XML file can be found here: https://www.ncbi.nlm.nih.gov/biosample/docs/attributes/

The declarative mapping file, which will also be a TSV file similar to _ncbi_pg_db_field_mappings_filled.tsv_ will map NMDC schema slots (from classes Biosample, Extraction, LibraryPreparation, OmicsProcessing, DataObject) to values in the harmonized_name/synonym/title column from the above table. Since the range of some of the measurement slots in NMDC schema follow an object pattern (as opposed to scalar values in NCBI and MIxS) we need to compose the slots using the dot notation on slots.

Example:

| nmdc_schema_class | nmdc_schema_slot | nmdc_schema_slot_range | ncbi_biosample_attribute_name | static_value | ignore |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Biosample | depth | QuantityValue | depth | |

Generic handling for nested data types in NMDC schema (to compose flat NCBI BioSample field values):
* QuantityValue
  * {slot_name}.has_numeric_value {slot_name}.has_unit, or
  * ( {slot_name}.has_maximum_numeric_value - {slot_name}.has_minimum_numeric_value ) {slot_name}.has_unit, or
  * <s>{slot_name}.has_raw_value</s>
* TextValue
  * {slot_name}.has_raw_value
* TimestampValue
  * {slot_name}.has_raw_value
* ControlledTermValue
  * {slot_name}.term.name [{slot_name}.term.id] , or
  * {slot_name}.term.id, or
  * {slot_name}.term.name, or
  * <s>{slot_name}.has_raw_value</s>
* ControlledIdentifiedTermValue
  * {slot_name}.term.name [{slot_name}.term.id], or
  * <s>{slot_name}.has_raw_value</s>
* GeolocationValue
  * {slot_name}.latitude {slot_name}.longitude, or
  * <s>{slot_name}.has_raw_value</s>

_{slot_name}_ is the name of a slot in the NMDC schema.

Note: This is the first of a series of tasks that need to be completed in order to address https://github.com/microbiomedata/nmdc-runtime/issues/503

**Comment by sujaypatil96** [comment]
We will need special handling for [host_taxid](https://microbiomedata.github.io/nmdc-schema/host_taxid/) in NMDC.

Example:

```json
host_tax_id: {
  {
    "has_raw_value": "Homo sapiens [NCBITaxon:9606]",
    "term": {
      "id": "NCBITaxon:9606",
      "name": "Homo sapiens"
  }
}
```

In MIxS and NCBI, we will need to map [host_taxid](https://genomicsstandardsconsortium.github.io/mixs/0000250/) to `host_tax_id.term.id` and split it up to get only the integer part, i.e., 9606. The other term `host` will need to be retrieved from `host_tax_id.term.name`.

**Comment by turbomam** [comment]
> We will need special handling for [host_tax_id](https://microbiomedata.github.io/nmdc-schema/host_taxid/) in NMDC.

I was expecting that this would be a common pattern. Is `host_tax_id` the only place you've see it so far?

**Comment by sujaypatil96** [comment]
Yup, `host_tax_id` is the only slot I've noticed this inconsistency on so far. Perhaps you can help me look through the results of automated exact matching and see if I'm missing something? I will have a PR out soon.
