### ISSUE TITLE
move package files into nmd_schema directory

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#195]
When I originally setup the repo, I was trying to keep the artifact folders (e.g., jsonchema, python) at the top level of the repo. This means that I have copy the artifacts to the `nmdc_schema` directory when making a pypi release. Better practice seems to be to put these files in the directory where the package contents are (also allows you to use `pip install -e .` when developing).

@ssarrafan can you add this to the Nov. sprint please?

cc @cmungall

**Comment by ssarrafan** [comment]
Moving to December per @wdduncan

**Comment by ssarrafan** [comment]
@wdduncan can we close this issue?  or should it go in the backlog?

**Comment by wdduncan** [comment]
@ssarrafan can you move it to the next sprint? I'm working on it.

**Comment by ssarrafan** [comment]
Moving to March per @wdduncan who plans to close it by Friday (his last day!) 

Note from Bill:
HI Set. Here is an update:
https://github.com/microbiomedata/nmdc-schema/issues/134
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-runtime/issues/89
I updated the comment on this. I should be able to get the change sheet edit done before I leave.
https://github.com/microbiomedata/nmdc-schema/issues/195
I am working with Sujay on this. I should be able to close before the week’s end.
https://github.com/microbiomedata/nmdc-runtime/issues/46
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-server/issues/555
This is a lot of conversation in this thread. But, it looks like Mark has taken this one over.

**Comment by ssarrafan** [comment]
@cmungall @turbomam @dehays any idea if Bill finished this before he left?

**Comment by ssarrafan** [comment]
Done per @sujaypatil96 
Closing issue

**Comment by sujaypatil96** [comment]
We now have contents in the nmdc_schema directory that is referenced in the ticket body. See here: https://github.com/microbiomedata/nmdc-schema/tree/main/nmdc_schema

Poetry also tags this directory and its contents to be included in the package to be deployed to PyPI: https://github.com/microbiomedata/nmdc-schema/blob/main/pyproject.toml#L27-L29. The package has been imported in a Python environment and its elements have been tested as well.

Something that we didn't do here was updating the README. I'll update that.

CC: @ssarrafan
