### ISSUE TITLE
Merge `nmdc-schema/main` branch (base) into `berkeley-schema-fy24/main` branch (fork)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1952]
This task came out of a hackathon conversation.

**Comment by eecavanna** [comment]
There's a commit whose commit message is `backmerge` — [here](https://github.com/microbiomedata/berkeley-schema-fy24/commit/2482fd021c1ca62c1629ebe99e7957978b38947d). I don't know whether that was a merge from `nmdc-schema/main` into `berkeley-schema-fy24/main` (I don't know what "backmerge" means to the person that wrote it).

**Comment by aclum** [comment]
Everything from berkeley-schema-fy24 is now in nmdc-schema.
