### ISSUE TITLE
`Database` class has two slots named `planned_process_set`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#1955]
Here's a snippet showing this (the snippet can be scrolled vertically):

https://github.com/microbiomedata/nmdc-schema/blob/b7a8130e6dc7b4d460e34c5be0be0f1131c52341/src/schema/nmdc.yaml#L164-L186

**Comment by turbomam** [comment]
- https://github.com/microbiomedata/nmdc-schema/pull/1980
