### ISSUE TITLE
Expand permissible values on `FileTypeEnum` for Metaproteomics related files

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-schema#1958]
To capture information about the `DataObject`s that are generated as part of a `MetaproteomicsAnalysis`, we need to expand the permissible values on the `FileTypeEnum`.

@SamuelPurvine, can you and @JamesTessmer connect to make sure we add accurate values?  

Notes from meeting on 5/3/24 indicate the following as file types we need to capture
- Analysis tool parameter files
- Contaminant protein collection (fasta)
- Analysis summary

**Comment by JamesTessmer** [comment]
The PR for this (on the Berkeley schema, please ignore the previous closed PR) is [here](https://github.com/microbiomedata/berkeley-schema-fy24/pull/145)
