### ISSUE TITLE
Repair MIXS environment annotations

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#197]
MIXS environment repair annotations to the format: label1 (D1) label2 (D2)... 

On the Nov list for refactoring

**Comment by ssarrafan** [comment]
Leaving this in the current sprint based on the mid-sprint review but let me know if it should be moved to December @turbomam

**Comment by ssarrafan** [comment]
Adding the backlog label and removing from sprint per @turbomam via Slack

**Comment by wdduncan** [comment]
@ssarrafan @turbomam Should we leave this open or close it?

**Comment by ssarrafan** [comment]
@wdduncan Mark had suggested we add it to the backlog to be reprioritized. If we think it's done or not relevant I'm happy to close it.

**Comment by turbomam** [comment]
This is somewhat intertwined with the issue of how MIxS content gets merged into the NMDC schema. I can't remember the issue for that off-hand

For a short term solution, we could move the specification for these columns into @mslarae13's [mixs_modified_slots](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=770915920) tab

**Comment by wdduncan** [comment]
Is `mixs_modified_slots` at `data harmonizer` thing, a `nmdc-schema` thing, or both? We should sort this out.

Merging `mixs` content into the `nmdc-schema` is straightforward:
- the `mixs.yaml` file is updated (either manually or programmatically)
- the updated `mixs.yaml` is then incorporated into the schema

**Comment by ssarrafan** [comment]
@turbomam this issue is pretty old and we've had new versions since so closing this one out but let me know if we still need to keep this in the backlog to be worked on.
