### ISSUE TITLE
Description fields for portal search terms

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#198]
Clean/revise/add description fields in the schema for all terms in the portal search pane

Added to Nov sprint planning doc by @pvangay

**Comment by ssarrafan** [comment]
Moving this to the December sprint per discussions at mid-sprint that it's a priority but not till January release.

**Comment by pvangay** [comment]
### Portal search terms that have MIxS Descriptions
@wdduncan these should be populated from MIxS
- [ ] Latitude
- [ ] Longitude
- [ ] Depth
- [ ] Environmental biome
- [ ] Environmental feature
- [ ] Environmental material
note that the [portal envo search terms dont match the schema at the moment](https://github.com/microbiomedata/nmdc-server/issues/548)

### Portal search terms that are not in MIxS
These are drafts for now - will update when they're ready to be updated.

- PI Name: Principal Investigator responsible for leading the associated study and/or generating the dataset. _**please review @emileyfadrosh**_ 
- GOLD classification: The JGI Genomes OnLine Database ([GOLD](https://gold.jgi.doe.gov/)) five-level ecosystem classification path used to describe biosample environments. 
Level 1: Ecosystem describes biosamples using three different broadest contexts, namely environmental, engineered, and host-associated.
Level 2: Ecosystem category subdivides the ecosystem into categories, such as aquatic or terrestrial.
Level 3: Ecosystem type classifies those categories into types, such as freshwater or marine, cave, desert, soil, etc.
Level 4: Ecosystem subtype allows for additional environmental context or boundaries.
Level 5: Specific ecosystem that describes the environment that directly influences the sample or the environmental material itself. 
**_Emailed Reddy to double check this._**
- Instrument name - this seems specific to metaB and metaP. _**sent an email to @corilo @pdpiehowski @SamuelPurvine to get their input for a better description.**_

**Comment by mslarae13** [comment]
Alternative Names | Other names/titles associated with this project/dataset

Term that needs a schema definition update

**Comment by wdduncan** [comment]
- `Depth` in `mixs.yaml` now has description: Depth is defined as the vertical distance below local surface, e.g. For sediment or soil samples depth is measured from sediment or soil surface, respectively. Depth can be reported as an interval for subsurface samples
- `Latitude` and `Longitude` are not MIxS terms. Only `lat_lon` is. I can add them as slots to the schema, but it may give the impression that these are valid slots in the schema (which they are not).
- GOLD path descriptions have been added to the `nmdc.yaml` file.
- Environmental biome/feature/material are the `env_broad_scale`, `env_local_scale`, `env_medium` terms in `mixs.yaml`
