### ISSUE TITLE
Command to generate delete API requests legacy orphan data objects and functional annotation agg records

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc-schema#2011]
Implement a click command to:
- locate the orphan records
- construct deletion queries for records
- submit deletion queries to `queries:run` endpoint

**Comment by ssarrafan** [comment]
@mbthornton-lbl @aclum who needs to review this? Can it be done today?

**Comment by aclum** [comment]
We talked on slack about updating this to dumping a json that could be submitted to queries run so we should move it to the next sprint.

**Comment by aclum** [comment]
PR is still pending merging on the berkeley schema approval board but was reviewed and approved by Eric and Mark so I submitted the queries run command to prod
