### ISSUE TITLE
Remove `acquisition_category` slot and `AcquisitionCategoryEnum`

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-schema#2018]
@corilo, @SamuelPurvine et al agreed to collapse these slots for simplicity and to better match mappings as uncovered during work for https://github.com/microbiomedata/issues/issues/705

Remove `acquisition_category` slot and `AcquisitionCategoryEnum`.
Add "full-scan only" as a permissible value to `AcquisitionStrategyEnum`.
Rename Enum`AcquisitionStrategyEnum` to `MassSpectrometryAcquisitionStrategyEnum`
Rename slot `acquisition_strategy` to `mass_spectrometry_acquisition_strategy`

**Comment by mslarae13** [comment]
& update `mass_spectrometryacquisition_strategy` description from

```
description: whether spectra are dependent on or independent of any other spectra during the experiment
```

to 

```
   description: Mode of running a mass spectrometer method by which m/z ranges are selected and ions possibly fragmented
```

**Comment by mslarae13** [comment]
acquisition_strategy to mass_spectrometry_acquisition_strategy causes issues.
Will follow up with commit link where this is corrected.
