### ISSUE TITLE
nmdc-schema needs a more global mechanism for capturing ownership-like credit

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2037]
This is especially relevant to the export NCBI XML task, with contributors @sujaypatil96 @aclum @chienchi etc.

If we are submitting `Biosample` records to NCBI, we want to indicate the various people and organizations that played a role in the final result: the sequence and metadata about the sample are available in NCBI.

We might say that A obtained the sample, B did the extraction and prepared the library, C operated the sequencer and D uploaded all of that to NCBI.

Challenges:
- which standard NCBI fields can that knowledge go into? 
    - Will it require custom fields? What should we call them? Can we use terms from an OBO ontology or schema.org?
- where should we store that knowledge in MongoDB/ according to the schema?
    - I think we might be able to use a `CreditAssociation`-like mechanism on many classes in the schema.

**Comment by aclum** [comment]
Adding this to this sprint as we need to determine custom attributes for NCBI submission testing.

**Comment by sujaypatil96** [comment]
Comprehensive example from NCBI (Submission, BioProject, BioSample, SRA): https://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/submit/public-docs/sra/samples/sra.submission.bs.bp.run.xml?view=co

**Comment by sujaypatil96** [comment]
Block of XML to focus on/peek at:

```xml
<Submission>
<Description>
<Comment>BP(1.0)+BS(1.0)+SRA</Comment>
<Organization role="owner" type="institute">
<Name>Institute of Biology</Name>
<Contact email="jane.doe@domain.com">
<Name>
<First>jane</First>
<Last>doe</Last>
</Name>
</Contact>
</Organization>
<Hold release_date="2015-10-21"/>
</Description>
```

**Comment by turbomam** [comment]
- Where does "ownership" appear in the NCBI Submission Schema (or any of its constituents)? Look in the XSDs.
- which are required?
- which optional ones do we want to fill in?
- do we already have slots that capture all of that?

The NMDC schema has `has_credit_association` for Study and `processing_institution` for `PlannedProcess`. 

- Submission XSD: https://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/submit/public-docs/common/submission.xsd?view=co
- BioProject XSD: https://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/submit/public-docs/bioproject/bioproject.xsd?view=co
- BioSample XSD: https://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/submit/public-docs/biosample/biosample.xsd?view=co

**Comment by sujaypatil96** [comment]
From the Submission XSD:

```xml              
<xs:element name="Organization" minOccurs="1" maxOccurs="unbounded" type="typeOrganization">
	<xs:annotation>
		<xs:documentation>
                    Organization(s) involved into the submission.
                    One organization is the owner of submission data which is identified by  attribute "role"
                  </xs:documentation>
	</xs:annotation>
</xs:element>
```

```xml
<xs:attribute name="role" use="optional">
	<xs:annotation>
		<xs:documentation>
          Role of the ogranization in submission - owner of the data or just a participant.
          It is expected that there is one owner of the submission data.
        </xs:documentation>
	</xs:annotation>
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="owner"/>
			<xs:enumeration value="participant"/>
		</xs:restriction>
	</xs:simpleType>
</xs:attribute>
```

```xml
<xs:complexType name="typeOrganization">
```

**Comment by turbomam** [comment]
@turbomam to contact John at NCBI and check assumptions about the `Organization` and `Submitter` nodes in the NCBI submission schema

**Comment by ssarrafan** [comment]
Appears to be active. Will move to the next sprint.
@turbomam please let me know if you're not working on this issue currently.

**Comment by turbomam** [comment]
> Hi Mark,
> I've moved this conversation over to our standard helpdesk software so we can keep better track of it on our end. You can certainly enter multiple organization nodes in the xml package, but only the ‘owner’ is displayed on public pages currently. It may be possible to display other organization roles on the public pages in specified fields for them, but that would take some development work and our product teams would need to comment on whether and when it can be done.
> 
> The Submitter node is auto-populated by submission portal to match the submitting account when the submission is created. The submitting account can make updates to the submission in the future, as well as any users who are a member of the associated shared submission group.
> 
> It might help if we had a little more information about how you want NMDC and the data provider to be associated with the submission. Is your goal to maintain editorial ownership of these submissions and simply provide credit for the data provider on the public pages? Or do you want to transfer ownership to the data provider, making them the submitting account? We have an option that allows you to transfer editing privileges to another user after you create the submission. If you are interested in that, let us know and we can discuss it.
> Best,
>  
> The SRA Team
> 
> National Center for Biotechnology Information | National Library of Medicine
> National Institutes of Health, Bethesda, Maryland 20892
> Email: [SRA@ncbi.nlm.nih.gov](mailto:SRA@ncbi.nlm.nih.gov)
> 
> [Connect with NLM](https://www.nlm.nih.gov/socialmedia/): [Twitter](https://twitter.com/NLM_NIH) | [Facebook](https://www.facebook.com/nationallibraryofmedicine) | [YouTube](https://www.youtube.com/user/NLMNIH/)
> 
> 
> ****
> * PLEASE DO NOT MODIFY THE SUBJECT LINE OF THIS EMAIL WHEN RESPONDING TO ENSURE CORRECT TRACKING *
> 
> Case Information:
> Case #: CAS-1333031-N0Y0X1
> Customer Name: Alicia Clum
> Customer Email: [aclum@lbl.gov](mailto:aclum@lbl.gov)
> Case Created: 6/27/2024, 2:49:27 PM
> 
> Summary: NMDC API submission account
> 
> Details:
> From: Mark Miller <[MAM@lbl.gov](mailto:MAM@lbl.gov)>
> Sent: Tuesday, June 25, 2024 1:50 PM
> To: Alicia Clum <[aclum@lbl.gov](mailto:aclum@lbl.gov)>; Trow, Jonathan (NIH/NLM/NCBI) [C] <[jonathan.trow@nih.gov](mailto:jonathan.trow@nih.gov)>; Sujay Patil <[spatil@lbl.gov](mailto:spatil@lbl.gov)>
> Subject: Re: [EXTERNAL] Re: NCBI UIless submission procedures
> 
> Hi John. Thanks for helping NMDC think about how to optimally credit people and organizations for the work in NMDC records that we intend to submit to NCBI. Thanks Alicia for starting this conversation.
> 
> I've been one of the MIxS developers for a few years now and I would really prefer that NMDC not propagate the use of non-standardized attributes.
> 
> Sujay Patil and I have been studying the NCBI submission XSD files to understand how to map NMDC's MIxS-like terminology to tNCBI's expectations.
> 
> I suspect that we can express all of the necessary credit in all of the data structures (Biosamples, Bioprojects, SRA) by including multiple <Organization> nodes. NMDC would take the role of 'participant', not 'owner'. If I could raise an issue, I personally would ask for a richer vocabulary of roles, not a custom attribute approach.
> 
> How does that multiple participant organization solution sound?
> 
> I am also curious about a tag that I remember as <Submitter>. I got the impression that it is auto-populated with the name or email of the human logged in when the submission is actually submitted. I also got the sense that the <Submitter> node/path never makes it into the biosample_set.xml etc. Can you say more about that? Does either the 'owner' designation or the contents of the <Submitter> node determine who can edit the submission in the future?
> thanks a lot,
> Mark

**Comment by ssarrafan** [comment]
@turbomam what's the status of this?  
@sujaypatil96 @aclum

**Comment by aclum** [comment]
Let's aim to get this sorted out this sprint.

**Comment by turbomam** [comment]
We've had some good discussion on Slack but I haven't added any of that to this issue yet. We're meeting this Thursday 2024-07-25 and I will update by the end of the day.

**Comment by ssarrafan** [comment]
> We've had some good discussion on Slack but I haven't added any of that to this issue yet. We're meeting this Thursday 2024-07-25 and I will update by the end of the day.

ANy update @turbomam after the meeting yesterday?

**Comment by aclum** [comment]
@turbomam  did a nice analysis of existing custom attributes in ncbi and we will use a custom attribute of `broker name` which is a term many other submissions use.
