### ISSUE TITLE
Make `ExtractionTarget` mutlivalued to accommodate MPLEX extractions

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#2043]
`extraction_target` needs to accomodate multiple extraction targets for protocols like MPLEX and MPLEX-lite that have extraction targets of `metabolite` `lipid` and `protein`. Need to:

- [ ] change name of slot to `extraction_targets` because it is multivalued
- [ ] make `extraction_target` multivalued
- [ ] Add `lipid` to `extractionTargetEnum`
- [ ] Write migrator to accommodate the multivalued change and the slot name change.

**Comment by turbomam** [comment]
A PR has been merged for this issue. Should it still be left open?
