### ISSUE TITLE
`berkeley-schema-fy24`: Implement migrator that merges some collections

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2045]
Hi @aclum, I created this ticket to represent the task that came up during today's metadata meeting.

It sounded to me like you wanted all of the documents in one collection to be moved to another collection, and to have the first collection be deleted. Is there more to it than that (e.g. modifying fields within documents)?

**Comment by eecavanna** [comment]
Here are links to the schema documentation pages for the classes I think will be involved here.

### [PlannedProcess](https://microbiomedata.github.io/berkeley-schema-fy24/PlannedProcess/) has these child classes:

- [CollectingBiosamplesFromSite](https://microbiomedata.github.io/berkeley-schema-fy24/CollectingBiosamplesFromSite/) - has no child classes
- [ProtocolExecution](https://microbiomedata.github.io/berkeley-schema-fy24/ProtocolExecution/) - has no child classes
- [StorageProcess](https://microbiomedata.github.io/berkeley-schema-fy24/StorageProcess/) - has no child classes
- [MaterialProcessing](https://microbiomedata.github.io/berkeley-schema-fy24/MaterialProcessing/)
- [DataGeneration](https://microbiomedata.github.io/berkeley-schema-fy24/DataGeneration/)
- [WorkflowChain](https://microbiomedata.github.io/berkeley-schema-fy24/WorkflowChain/) - has no child classes
- [WorkflowExecution](https://microbiomedata.github.io/berkeley-schema-fy24/WorkflowExecution/)

#### [MaterialProcessing](https://microbiomedata.github.io/berkeley-schema-fy24/MaterialProcessing/) has these child classes:

- [Pooling](https://microbiomedata.github.io/berkeley-schema-fy24/Pooling/)
- [Extraction](https://microbiomedata.github.io/berkeley-schema-fy24/Extraction/)
- [LibraryPreparation](https://microbiomedata.github.io/berkeley-schema-fy24/LibraryPreparation/)
- [SubSamplingProcess](https://microbiomedata.github.io/berkeley-schema-fy24/SubSamplingProcess/)
- [MixingProcess](https://microbiomedata.github.io/berkeley-schema-fy24/MixingProcess/)
- [FiltrationProcess](https://microbiomedata.github.io/berkeley-schema-fy24/FiltrationProcess/)
- [ChromatographicSeparationProcess](https://microbiomedata.github.io/berkeley-schema-fy24/ChromatographicSeparationProcess/)
- [DissolvingProcess](https://microbiomedata.github.io/berkeley-schema-fy24/DissolvingProcess/)
- [ChemicalConversionProcess](https://microbiomedata.github.io/berkeley-schema-fy24/ChemicalConversionProcess/)

#### [DataGeneration](https://microbiomedata.github.io/berkeley-schema-fy24/DataGeneration/) has these child classes:

- [NucleotideSequencing](https://microbiomedata.github.io/berkeley-schema-fy24/NucleotideSequencing/)
- [MassSpectrometry](https://microbiomedata.github.io/berkeley-schema-fy24/MassSpectrometry/)

#### [WorkflowExecution](https://microbiomedata.github.io/berkeley-schema-fy24/WorkflowExecution/) has these child classes:

- [MetagenomeAnnotation](https://microbiomedata.github.io/berkeley-schema-fy24/MetagenomeAnnotation/)
- [MetagenomeAssembly](https://microbiomedata.github.io/berkeley-schema-fy24/MetagenomeAssembly/)
- [MetatranscriptomeAssembly](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAssembly/)
- [MetatranscriptomeAnnotation](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAnnotation/)
- [MetatranscriptomeAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAnalysis/)
- [MagsAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MagsAnalysis/)
- [MetagenomeSequencing](https://microbiomedata.github.io/berkeley-schema-fy24/MetagenomeSequencing/)
- [ReadQcAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/ReadQcAnalysis/)
- [ReadBasedTaxonomyAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/ReadBasedTaxonomyAnalysis/)
- [MetabolomicsAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetabolomicsAnalysis/)
- [MetaproteomicsAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetaproteomicsAnalysis/)
- [NomAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/NomAnalysis/)

**Comment by eecavanna** [comment]
In terms of existing adapter methods, here's what I expect this migrator to do for each of those child classes (written here in pseudocode):
```py
# Move all documents from the "pooling_set" collection into the "material_processing_set" collection,
# then delete the "pooling_set" collection.
self.adapter.do_for_each_document(
    collection_name="pooling_set", 
    action=lambda document: self.adapter.insert_document(collection="material_processing_set", document=document)
)
self.adapter.delete_collection(collection_name="pooling_set")
```

**Comment by aclum** [comment]
DataGeneration subclasses are already in a combined collection so there no action there. All existing collections from children of MaterialProcessing should combined to a new collection called material_processing_set, same for WorkflowExecution.  Im assuming you want to put this migrator at the end in which case you use commit id https://github.com/microbiomedata/berkeley-schema-fy24/commit/ca304e47916f9ff2825dcd854a7a936dfdd5b07f to determine what the starting Database slot names are. If this is running earlier you may need to use nmdc-schema Database slot names. Note that some of these subclasses never had a collection in mongo so the code should be able to handle that.

**Comment by eecavanna** [comment]
Thanks! That was very helpful to me. I'm operating under the assumption that this will run _after_ all migrators that have been implemented so far, so I'll refer to that commit you linked to.

**Comment by eecavanna** [comment]
I implemented this migrator. It's in this PR: https://github.com/microbiomedata/berkeley-schema-fy24/pull/196
