### ISSUE TITLE
backmerge issue with ID mention pattern constraints on WorkflowExecution

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2053]
I discovered today that there is some example data in Database-interleaved.yaml where the has_input/has_output values are accepting md5sum style identifiers. When I check https://microbiomedata.github.io/berkeley-schema-fy24/WorkflowExecution/ there are not slot usage constaints for has_input, has_output, or was_informed_by. The same is not true for PlannedProcess subclasses so not sure what happened but we should review ID mentions in general in berkeley-schema-fy24 to make sure other Classes were merged correctly.

**Comment by turbomam** [comment]
Can `WorkflowExecutions` be `informed_by`?

**Comment by turbomam** [comment]
I'm not going to finish this today

- https://github.com/microbiomedata/nmdc-schema/pull/2054

**Comment by aclum** [comment]
No, we moved was_informed_by from WorkflowExecution to WorkflowChain.
