### ISSUE TITLE
Delete Class WorkflowChain in Berkeley schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2063]
In the schema meeting today we decided to remove WorkflowChain in favor of a single mongo collection for all WorkflowExecution documents.
- Delete WorkflowChain, this will be remodeled later to more closely match ProtocolExecution, see #2060 
- move was_informed_by back on WorkflowExecution
- update valid and invalid data

**Comment by eecavanna** [comment]
I think this is the PR that goes along with this issue. PR: https://github.com/microbiomedata/berkeley-schema-fy24/pull/206

**Comment by aclum** [comment]
@eecavanna  that is corrects
