### ISSUE TITLE
Publish schema to PyPI via GitHub Release `v10.5.4`

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2069]
We need a release of nmdc_schema so we can update runtime and test  ahead of the monthly release on June 24

cc @pkalita-lbl 

Target completion: Monday June 17

**Comment by eecavanna** [comment]
@turbomam finished this today.

<img width="849" alt="image" src="https://github.com/microbiomedata/nmdc-schema/assets/134325062/cff3930c-9712-45f7-ad61-54f16ce3ed33">

> https://pypi.org/project/nmdc-schema/
