### ISSUE TITLE
replace uses of `nmdc_schema_merged.yaml` with `nmdc_schema/nmdc_materialized_patterns.yaml`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2095]
We are committing to `nmdc_schema/nmdc_materialized_patterns.yaml` as our default schema file

`nmdc_schema/nmdc_schema_merged.yaml` doesn't serve any other purpose now and just adds confusion

**Comment by mslarae13** [comment]
@turbomam can you say more about what "committing to nmdc_schema/nmdc_materialized_patterns.yaml as our default schema file" means? ... specifically what does "default schema file" mean?

**Comment by turbomam** [comment]
> @turbomam can you say more about what "committing to nmdc_schema/nmdc_materialized_patterns.yaml as our default schema file" means? ... specifically what does "default schema file" mean?

Excellent questions @mslarae13 

I meant that any process that loads a YAML representation of the schema should load `nmdc_schema/nmdc_materialized_patterns.yaml`. I guess there could be exceptions, but I can't think of any right now.

I am proposing that we think of `src/schema/nmdc.yaml` etc as really being source files that we edit, and that that the derived `nmdc_schema/nmdc_materialized_patterns.yaml` is the only YAML schema artifact that we would ever consume computationally. That ensures that the materialized `structured_patterns` are applied in all downstream validation activities.

https://github.com/microbiomedata/nmdc-schema/pull/2099 eliminates the creation of `nmdc_schema/merged.yaml`and any use of it internally to the `nmdc-schema` repo. #2094 does the same thing for `nmdc_schema/nmdc_schema_accepting_legacy_ids.yaml`. Once they are merged, I hope we will all have a shared understanding of the uses for the remaining schema files, `src/schema/nmdc.yaml` and `nmdc_schema/nmdc_materialized_patterns.yaml`

**Comment by ssarrafan** [comment]
PR appears to be approved/reviewed. Montana's question answered. Can this be closed @turbomam?
