### ISSUE TITLE
`berkeley-schema-fy24`: Update `part_16` migrator to include `metatranscriptome_expression_analysis_set` collection

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2124]
There is a "Berkeley" migrator that moves all documents from the "child collections" of `workflow_execution_set`, into the `workflow_execution_set` collection. Here's a link to it:

- [partials/migrator_from_10_2_0_to_11_0_0_part_16.py](https://github.com/microbiomedata/berkeley-schema-fy24/blob/f4d2b4c0ca36891b48d84b938733eac8320b71a7/nmdc_schema/migrators/partials/migrator_from_10_2_0_to_11_0_0/migrator_from_10_2_0_to_11_0_0_part_16.py#L35C1-L48C11)

The task here is to add `metatranscriptome_expression_analysis_set` to the list of names of collections that the migrator considers to be a "child collection" of `workflow_execution_set`.

This issue came out of this PR: 
- https://github.com/microbiomedata/nmdc-schema/pull/2117#issuecomment-2231621723

**Comment by ssarrafan** [comment]
PR approved by 4 team members. Eric is out. Will move to next sprint.
