### ISSUE TITLE
document the fact that working on a PR template is the only case in which PRs don't require review

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#2126]
see
- https://github.com/microbiomedata/nmdc-schema/blob/main/.github/PULL_REQUEST_TEMPALTE/pull_request_template.md

**Comment by eecavanna** [comment]
Note: The path to the PR template will be changed once PR #2128 gets merged in (that PR gets rid of the `PULL_REQUEST_TEMPALTE` directory and moves the PR template to the `.github` directory).
