### ISSUE TITLE
`berkeley`: Fix range for `has_calibration` slot

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-schema#2139]
Follow up tasks from https://github.com/microbiomedata/berkeley-schema-fy24/pull/133.

This work is dependent on the completion of https://github.com/microbiomedata/issues/issues/750

- [x] The range of has_calibration should be limited to `CalibrationInformation`.
- [x] The definitions for `CalibrationInformation`, `has_calibration`, `calibration_target`, `CalibrationTargetEnum`, `internal_calibration`, `calibration_standard`, `CalibrationStandardEnum`, and `calibration_object` can move from the workflow_execution.yaml to the a logical location of nmdc.yaml
- [x] Remove `has_calibration` from `NomAnalysis` and `MetabolomicsAnalysis`

**Comment by kheal** [comment]
@brynnz22 Here are the schema changes needed to the `has_calibration` slot alongside the migrator we discussed.

**Comment by brynnz22** [comment]
I added another bullet point to remove `has_calibration` from `NomAnalysis` and `MetabolomicsAnalysis`

**Comment by kheal** [comment]
@brynnz22 - I think this can be closed now that https://github.com/microbiomedata/nmdc-schema/pull/2235 is in, correct?

**Comment by brynnz22** [comment]
Yes, thanks. Closing!
