### ISSUE TITLE
`berkeley-schema-fy24`: JSON Schema and YAML schema files are missing from `nmdc_schema` directory

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2150]
#### Background

In PR https://github.com/microbiomedata/berkeley-schema-fy24/pull/229/files, the files `nmdc.schema.json`, `nmdc_materialized_patterns.yaml`, and `nmdc_materialized_patterns.schema.json` were deleted from the `nmdc_schema` directory (that is on the `berkeley-schema-fy24` fork).

#### Task

Assuming those files (by some name) still exist somewhere in the repo file tree; this task is to document their new locations; for example, in the repository's `README.md` file. In the off chance that those files were deleted unintentionally, the task is—instead—to restore them.

**Comment by turbomam** [comment]
Quick note for now:

When I start a backmerge, there's usually about 20 files marked with conflicts by git. Running `make squeaky-clean` deletes most of them, and they can all be recreated with `make squeaky-clean all` if I remember.

Same thing for `poetry.lock`. If there's a conflict, I delete it and hopefully remember to `poetry lock` before giving myself credit for completing the backmerge.

I started a backmerge yesterday and have pushed it in a state where there's still ~ 6 conflicts in `nmdc.yaml`. 

- https://github.com/microbiomedata/nmdc-schema/pull/2149

I think getting to that point was pretty easy, so I could close that PR start over again, going though the whole process with you @eecavanna  or @aclum @pkalita-lbl @sierra-moxon @sujaypatil96 @mslarae13.

**Comment by turbomam** [comment]
I will fix these missing files now.

**Comment by turbomam** [comment]
```shell
git add nmdc_schema/*json nmdc_schema/*yaml
```

> The following paths are ignored by one of your .gitignore files:
> nmdc_schema/nmdc.schema.json
> nmdc_schema/nmdc_materialized_patterns.schema.json
> nmdc_schema/nmdc_materialized_patterns.yaml
> hint: Use -f if you really want to add them.
> hint: Turn this message off by running
> hint: "git config advice.addIgnoredFile false"

I'm going to force add them for now, but I guess we should do some `.gitignore` grooming.

**Comment by aclum** [comment]
Are there still conflicts in `nmdc.yaml`? the linked PR indicates not.

**Comment by ssarrafan** [comment]
It's relatively new comment so I'll move to new sprint.  @turbomam  let me know if you're not working on this.
