### ISSUE TITLE
`berkeley` breakdown AnalyteCategoryEnum into types allowable for NucleotideSequencing and MassSpectrometry

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2154]
Not required before the rollout but at some point we should break down AnalyteCategoryEnum into enumerations specific to subcategories. At present it would be valid to have  analyte_category populated with nom for class NucleotideSequencing

cc @mslarae13

**Comment by kheal** [comment]
We can add rule on the MassSpectrometry and NucleotideSequencing subclasses to specify acceptable PVs for the `analyte_category` slot.  Although `analyte_category` is only currently used on `DataGeneration` I think we'd need to rename that slot if we wanted to use separate Enums (and then migrate).

**Comment by kheal** [comment]
@samobermiller - please add titles to the PVs in AnalyteCategoryEnum at this same time.  See discussion in https://github.com/microbiomedata/nmdc-server/issues/1326 for why.

**Comment by aclum** [comment]
See linked PR, blocked on subsetting permissible values

**Comment by aclum** [comment]
Awaiting review.
