### ISSUE TITLE
`berkeley-schema-fy24`: Restore missing derived files (e.g. `nmdc_schema/nmdc_materialized_patterns.yaml`)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2176]
This is a recurrence of https://github.com/microbiomedata/nmdc-schema/issues/2150

**Comment by ssarrafan** [comment]
This was added to the sprint which ends today. I'm moving this to the next sprint.  @turbomam @eecavanna

**Comment by ssarrafan** [comment]
This one also hasn't been touched in 2 weeks
Removing from sprint, adding backlog label
@turbomam @eecavanna

**Comment by mslarae13** [comment]
@eecavanna resolved this issue for the most recent release.
@turbomam thing to sort out is these derived files shouldn't need to be created manually. 
Requesting help to decide if this needs tweeks.
@eecavanna . didn't need tweeks last time and is in favor of closing this issue.

**Comment by eecavanna** [comment]
When I did that most recent release of `berkeley-schema-fy24`, I did not have to include any special options to `$ git add` when adding the derived files. The derived files are not currently listed in `.gitignore`. So, I don't expect this issue to recur (in that fork). Closing.
