### ISSUE TITLE
Read the Docs Missing Figure

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#218]
The read the docs is missing figures in the Metadata Standards Documentation chapter

https://microbiomedata.github.io/nmdc-schema/Metadata_Documentation_Overview/

Can we locate these figures and fix this?

**Comment by wdduncan** [comment]
Still isn't fixed ... need to reopen.

**Comment by wdduncan** [comment]
Images have been restored for [Metadata_Documentation_Overview/](https://microbiomedata.github.io/nmdc-schema/Metadata_Documentation_Overview/)

![image](https://user-images.githubusercontent.com/3186638/147290917-2fee7af7-0f38-41ae-b1a0-ad7b32790946.png)
