### ISSUE TITLE
`berkeley-schema` - `type` slot requirement on `Protocol` class requires a migrator

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-schema#2180]
In the Berkeley schema, the slot `type` on the `Protocol` class is required.

We need a migrator to implement this.

**Comment by turbomam** [comment]
Nice work. Ideally we would have some root migrator that always ensures that all documents written into a berkeley-schema-fy24 MongoDB would have a type, along with types for all nested instances.
