### ISSUE TITLE
`berkeley`: Incorporate `refscan` graphs into schema documentation

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2188]
Idea: Use GitHub Actions to install `refscan` from PyPI, run it on the latest schema, and store the resulting HTML file in the right place in the schema docs so that it appears on the deployed schema docs website.

Emphasis: This does not involve adding any more "derived files" to the repo. The docs are built by GHA.

Limitation: `refscan` only works with the Berkeley schema (due to `refscan`'s dependence upon the `type` field, which is only "reliable" in the Berkeley schema).

During today's NMDC sync, people seemed to me to want this to be a public-facing diagram and some of them seemed to me to be in favor of it living in the schema repo (in this case, it would start out in the `berkeley-schema-fy24` repo and only appear in the `nmdc-schema` repo once the fork gets merged into the base). Needs buy-in from @turbomam, specifically, as lead maintainer of the repo.

Currently, graphs are hosted at this improvised URL: https://portal.nersc.gov/project/m3408/refscan/

**Comment by turbomam** [comment]
I support adding the refgraphs to the nmdc-schema documentation. I will probably have some suggestions for brief documentation that could go along with it.

**Comment by eecavanna** [comment]
>I support adding the refgraphs to the nmdc-schema documentation.

Thanks, @turbomam. I'll try to make this happen next sprint.

>I will probably have some suggestions for brief documentation that could go along with it.

Sounds good to me.

**Comment by eecavanna** [comment]
I've prototyped this in `berkeley-schema-fy24` PR https://github.com/microbiomedata/berkeley-schema-fy24/pull/265.

**Comment by ssarrafan** [comment]
@turbomam @sujaypatil96 can you provide feedback on PR https://github.com/microbiomedata/berkeley-schema-fy24/pull/265 please? 

@eecavanna I'm guessing this is on hold till after the Berkeley rollout correct?  Can we move this to next sprint?

**Comment by eecavanna** [comment]
Yes, next sprint, please. We did decide to hold off on merging this until after the Berkeley Schema Roll Out (even if the PR has been reviewed/approved before then).

**Comment by eecavanna** [comment]
This has been implemented in https://github.com/microbiomedata/nmdc-schema/pull/2198 and I am ready for it to be merged in.

**Comment by eecavanna** [comment]
Part of this has been re-implemented (more granularly) in PR #2240.

**Comment by eecavanna** [comment]
Closing this ticket in favor of the following two, newer, more narrowly-scoped tickets:
- #2240 
- #2242
