### ISSUE TITLE
Change Instrument name from `GC-MS` to `Agilent GC-MS (2009)`

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-schema#2208]
After Berekely Roll out, a change sheet needs to be submitted changing the instrument name to be more descriptive. @aclum

**Comment by bmeluch** [comment]
Changesheet applied in dev and prod
[instrument_name_gcms.txt](https://github.com/user-attachments/files/17441115/instrument_name_gcms.txt)

**Comment by brynnz22** [comment]
Thanks so much @bmeluch
