### ISSUE TITLE
MagBin.members_id should be multivalued

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2222]
MagBin.members_id is currently a string but should be multivalued. It is a list of the contigs which make up a bin.

**Comment by turbomam** [comment]
agreed

I'm looking though our metadata now

see also
- https://github.com/microbiomedata/nmdc-schema/issues/2221

**Comment by turbomam** [comment]
I just removed myself as the assignee from 
- #2221

**Comment by aclum** [comment]
sorry for the duplicate tickets, i didn't see yours. This is the proposed hotfix branch
https://github.com/microbiomedata/nmdc-schema/tree/hotfix-issue-2222

If you agree please make a patched release for that branch @turbomam
