### ISSUE TITLE
Add inter-collection diagram generated by refscan to schema documentation

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2240]
This is a more narrowly-focused spin-off from https://github.com/microbiomedata/nmdc-schema/issues/2188.

- [x] Add an inter-collection diagram (dynamically generated based upon the current schema files)
- [x] Add an explanatory web page that links to the diagram
- [x] Add a sidebar link that points to that web page

**Comment by eecavanna** [comment]
This has been implemented in PR #2241.

**Comment by ssarrafan** [comment]
@eecavanna is this done?  Is the final at https://microbiomedata.github.io/nmdc-schema/visualizations/collection-graph.html?

**Comment by eecavanna** [comment]
Yes, this is done. Yers, that is the long-term URL of the graph (that graph gets regenerated whenever the documentation site gets regenerated, but it is always at that URL).
