### ISSUE TITLE
Migrations: Implement adapter method `copy_value_from_field_to_field_in_each_document`

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-schema#2259]
Adapter method signature:

```py
def copy_value_from_field_to_field_in_each_document(
    self,
    collection_name: str,
    source_field_name: str,
    destination_field_name: str,
) -> None:
    r"""
    For each document in the collection that has the source field,
    copy the value of the source field into the destination field,
    creating the destination field if it doesn't already exist.
    If the document lacks the source field, do nothing.
    """
    pass
```

Mongo query:

```js
db.getCollection("things").updateMany({
    {"foo": {$exists: true}},   // for each document that has a `foo` field,
    [{"$set": {"bar": "$foo"}}] // populate its `bar` field with the value in that `foo` field
});
```

**Comment by eecavanna** [comment]
Hi @kheal and @brynnz22, I'm planning to implement the adapter method described above. I wanted to know whether you find its signature (i.e. name and parameters) to be intuitive. I plan to implement it as described above unless I hear of any concerns.

Note: Separately, I'm planning to implement an adapter method that can be used to _delete_ a field from each document in the collection. Using the above adapter method and this _delete_ one, together, a migrator author will be able to effectively rename a field (which is being done in a different way [here](https://github.com/microbiomedata/nmdc-schema/blob/a5c3f4e7fe221b01d24151e536bfe00cbeb3ac19/nmdc_schema/migrators/partials/migrator_from_11_0_3_to_11_1_0/migrator_from_11_0_3_to_11_1_0_part_2.py#L31)).

**Comment by brynnz22** [comment]
Yeah this makes sense to me! And would be very helpful

**Comment by kheal** [comment]
This looks great.

**Comment by eecavanna** [comment]
Thanks! I have opened a PR and designated both of you as reviewers.

I'm going to jump straight into implementing a second adapter method—`delete_field_from_each_document`—now (in a different PR). I'll tag you as reviewers there, too (ETA is 1 hour). In case you prefer waiting until the second PR exists before doing any reviewing, that would work for me.
