### ISSUE TITLE
in_manifest metamodelcore.py issues

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#2274]
nmdc_automation had some issues with DataObject records in dev which had in_manifest populated. These records were modifed via changesheets which passed validation and also pass linkml-validate but have an error from linkml_runtime/utils/metamodelcore.py

Testing was done in dev using https://github.com/microbiomedata/issues/issues/948 (note @eecavanna  has subsequently modified this data in dev to unblock @mbthornton-lbl). 

Corresponding nmdc_automation issue is https://github.com/microbiomedata/nmdc_automation/issues/303

I will make some invalid data which *should* fail based on but does not currently.

**Comment by aclum** [comment]
cc @bmeluch @samobermiller @kheal

**Comment by aclum** [comment]
see example data (src/data/invalid/DataObject-in_manifest-invalid.yaml) in linked development branch

**Comment by aclum** [comment]
I think this is because we are missing a pattern constraint on in_manifest on DataObject.

**Comment by kheal** [comment]
@aclum  - I think you're right. I should have added that as part of #2230.

**Comment by aclum** [comment]
@kheal  I've testing locally & will have a PR review request coming shortly.

**Comment by aclum** [comment]
planning on merging this in after the metadata meeting today.
