### ISSUE TITLE
GOLD Path term desciption still "TODO"

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#231]
- ecosystem
- ecosystem_category
- ecosystem_subtype
- ecosystem_type
- specific_ecosystem

**Comment by turbomam** [comment]
in `src/schema/nmdc.yaml`

**Comment by cmungall** [comment]
You can also include see_also links to

 - https://gold.jgi.doe.gov/ecosystem_classification
 - https://pubmed.ncbi.nlm.nih.gov/20653767/

**Comment by turbomam** [comment]
https://microbiomedata.github.io/nmdc-schema/ecosystem/
