### ISSUE TITLE
Discuss which NMDC biosample slots to use for NMDC DataHarmonizer

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#235]
https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit#gid=1974870456

**Comment by wdduncan** [comment]
tagging @mslarae13 in this ticket.

**Comment by turbomam** [comment]
This is ongoing and has made great progress. This issue is not required as a reminder anymore.
