### ISSUE TITLE
add slot relating biosample to study

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#25]
Currently, biosamples are related to biosamples via omics processing. I.e.:
```
(biosample) <-- has input -- (omics process) -- part of --> (study)
```
It would be useful to have a slot that directly related biosamples to studies.

**Comment by wdduncan** [comment]
For now, let's use `part of`, but we need to add sanity checks to verify the data.

**Comment by ssarrafan** [comment]
I'm moving to the May sprint per Bill and adding Small label for effort.
