### ISSUE TITLE
remove stray omics_type slot

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#250]
In `nmdc.yaml`, there seems to be a stay `omics_type` slot that is not associated with any class:
```
 omics_type:
    range: string
```
This is not that same of the `omics type` slot that **is used** for `omics processing`:
```
omics type:
    range: controlled term value 
    description: >-
      The type of omics data
    examples:
      - value: metatranscriptome
      - value: metagenome
 ```

cc @turbomam @sujaypatil96 @cmungall @dehays

**Comment by brynnz22** [comment]
@turbomam can this be marked as closed and finished? I looked at the nmdc.yaml file and all I see is [omics_type](https://github.com/microbiomedata/nmdc-schema/blob/8b5d1d10957d04c647991e8d66a02f9e3bee971e/src/schema/nmdc.yaml#L2459). I do not see any such `omics type` slot described above?

**Comment by turbomam** [comment]
Yes, thank you!
