### ISSUE TITLE
restrict range of omics type

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#251]
The current range of `omics type` is a `controlled term value`. However, we don't do any validation of the values. 

Currently, the values used are:
```
'Lipidomics',
'Metabolomics',
'Metagenome',
'Metatranscriptome',
'Organic Matter Characterization',
'Proteomics'
```
Should we make these enums?

cc @dehays @cmungall @turbomam @SamuelPurvine @sujaypatil96

**Comment by turbomam** [comment]
The name of the relevant terms have been updated, but the question remains valid

- https://microbiomedata.github.io/nmdc-schema/omics_type/
- https://microbiomedata.github.io/nmdc-schema/ControlledTermValue/

**Comment by turbomam** [comment]
The term `id` slot is almost never getting populated.  `omics_type` is being used as if it was a cumbersome string slot.

```sparql
PREFIX nmdc: <https://w3id.org/nmdc/>
select 
?op ?oo (count(?s) as ?scount)
where { 
	?s nmdc:omics_type ?o .
    ?o ?op ?oo .
}
group by ?op ?oo
```

?op | ?oo | ?scount
-- | -- | --
nmdc:has_raw_value | Organic Matter Characterization | 2143
nmdc:has_raw_value | Metagenome | 1650
nmdc:has_raw_value | metagenome | 1473
nmdc:has_raw_value | Lipidomics | 154
nmdc:has_raw_value | Metatranscriptome | 111
nmdc:has_raw_value | Proteomics | 52
nmdc:has_raw_value | Metabolomics | 34
nmdc:term | NCBITaxon:256318 | 87
rdf:type | nmdc:ControlledTermValue | 5617

**Comment by mslarae13** [comment]
Done with update & addition of new enums
