### ISSUE TITLE
short term: programmatically tag the origin of MIxS terms when imported into NMDC schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#252]
CC @cmungall @wdduncan 

[Sample MIxS term in NMDC shema](https://github.com/microbiomedata/nmdc-schema/blob/b7e656664e39ec6d528c8a0ebd66636842bc6560/src/schema/mixs.yaml#L147-L159)

see also https://github.com/microbiomedata/nmdc-server/issues/555

especially the discussion of MIxS' lat_lon field

**Comment by turbomam** [comment]
CC @cmungall @wdduncan 

see also ...

**Comment by turbomam** [comment]
Implement with `conforms_to` or `annotations`?

semantics too loose?
- in_subset
- see_also

probably not
- quick and dirty parse of slot_uri, from_schema, imported_from, exact_mappings etc.
- owner (deprecated)

**Comment by wdduncan** [comment]
tagging @mslarae13

**Comment by cmungall** [comment]
I think in_subset is good

**Comment by turbomam** [comment]
I implemented with with `source: http://w3id.org/mixs/terms` in [`mixs.yaml`](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml)

When creating the Bioscales tempalte, we found that the LinkML `source` attribute conflicts with a reserved `source` annotation in DataHarmonizer, so this might not be a good long term solution.

**Comment by turbomam** [comment]
[What are DataHarmonizer's reserved field names](https://github.com/cidgoh/DataHarmonizer/issues/313)

**Comment by turbomam** [comment]
> Just checking, does this relate to the discussion we had yesterday about "annotating" the NMDC schema slots with "where they came from"?

@mslarae13 @ssarrafan 

Yes, but I'm not convinced I did it in a sustainable way, or that I used the most appropriate LinkML slot to make the annotations. Will look into it more in the beginning of August.

**Comment by ssarrafan** [comment]
> > Just checking, does this relate to the discussion we had yesterday about "annotating" the NMDC schema slots with "where they came from"?
> 
> @mslarae13 @ssarrafan
> 
> Yes, but I'm not convinced I did it in a sustainable way, or that I used the most appropriate LinkML slot to make the annotations. Will look into it more in the beginning of August.

I'm tempted to tag this as interim fix and close it but will move it to August for you @turbomam. FYI @mslarae13

**Comment by mslarae13** [comment]
> > > Just checking, does this relate to the discussion we had yesterday about "annotating" the NMDC schema slots with "where they came from"?
> > 
> > 
> > @mslarae13 @ssarrafan
> > Yes, but I'm not convinced I did it in a sustainable way, or that I used the most appropriate LinkML slot to make the annotations. Will look into it more in the beginning of August.
> 
> I'm tempted to tag this as interim fix and close it but will move it to August for you @turbomam. FYI @mslarae13

@ssarrafan  I agree interim fix. Can we get a ticket started for the "preferred solution" per Mark's comment

**Comment by ssarrafan** [comment]
@sujaypatil96 @turbomam can this interim fix issue be closed?  

I'm moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by ssarrafan** [comment]
@turbomam @sujaypatil96 I'm going to assume this is not going to get done and closing it. If you think you'll have time to work on it let me know or re-open.
