### ISSUE TITLE
Align concept of study/project between NMDC and EMSL

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#26]
We should make sure the NMDC modeling of studies in the schema matches what is in EMSL

We have aligned this with GOLD but we should also make the mapping more explicit

For reference, this is the documentation page for the study class in our schema

https://microbiomedata.github.io/nmdc-metadata/docs/Study

Auto-generated UML diagram (not so useful IMO):

![image](https://user-images.githubusercontent.com/50745/98297846-e8a3ad00-1f69-11eb-9e35-c337af903da2.png)

@lamccue - who is the best PNNL point person? Mark B?

**Comment by lamccue** [comment]
@cmungall Mark B is still does not yet have permission to return to work (from Customs & Immigration). Hopeful that he can return next month, but in the meantime, Dave Millard is probably in the best position to speak to this.

**Comment by wdduncan** [comment]
Decision for now: leave the schema flexible. E.g., studies can be parts of studies, which can be parts of other studies, etc.

This will hopefully allow us to meet different organizational needs.

**Comment by aclum** [comment]
@lamccue  are you okay with closing this in favor of the work that is happening in the study refresh squad [#study](https://github.com/microbiomedata/issues/issues/342)

**Comment by lamccue** [comment]
yes, we should close this issue, thanks @aclum
