### ISSUE TITLE
Missing file type enums in nmdc.yaml

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc-schema#266]
The following files do not have an entry with description in the enums:

```
crt.gff
genemark.gff
prodigal.gff
trna.gff 
rfam_misc_bind_misc_feature_regulatory.gff
rfam_rrna.gff
rfam_ncrna_tmrna.gff
ko_ec.gff 
```

For generating objects we are following the File Type and Descriptor to fill out the fields. The following entries are not present for annotation.

**Comment by scanon** [comment]
In addition we will be adding at least two other new files.

product tsv
crispr output

Maybe @emileyfadrosh can suggest names for these.

**Comment by wdduncan** [comment]
If possible, it is good to have short descriptions too.
