### ISSUE TITLE
Add ability to link studies or make umbrella studies

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#27]
At JGI we have many cases where there are multiple proposals that span a long-term “study” (e.g., a large, multi-year SFA project that involves many hundreds of samples). 

Also need to add mappings for concepts of studies across different systems

**Comment by wdduncan** [comment]
see #26

**Comment by cmungall** [comment]
proposal:

 * Add a parent_study field to study, with range Study
 * Add a type field, with an enum, which may have values:
     * umbrella project
     * individual study
     * ...?

**Comment by turbomam** [comment]
Implementation (the outer two bullets are probably exclusive):
- add a Class to model consortia? `Consortium`
  - add a slot to a `Biosample` or a `Study` to assert what consortium it is `part_of`
- add a Boolean slot to `Study` to say it is a consortium

@aclum @mslarae13 @lamccue 

We have been talking about about this recently, haven't we? @eecavanna and I thought we should rejuvenate this issue! Look how old it is!

**Comment by mslarae13** [comment]
@turbomam  @eecavanna  we plan to discuss this today

This is an issue surrounding the umbrella projects but that's different from the consortiums. We'll discuss the differences between the 3 classes (study, umbrella project, and consortium) today and how we want to / can handle them in the schema.

**Comment by turbomam** [comment]
Does the addition of [study_category](https://microbiomedata.github.io/nmdc-schema/study_category/) to the schema close this issue?

**Comment by lamccue** [comment]
Yes, I think it does.
