### ISSUE TITLE
Update NMDC schema docs to use `gen-doc` instead of `gen-markdown`

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#278]
Currently, the nmdc schema docs are being built using the `gen-markdown` utility provided by linkml instead of the newer documentation utility `gen-doc`.

An example of documentation built by `gen-doc` is the MIxS docs: https://genomicsstandardsconsortium.github.io/mixs/

**Comment by ssarrafan** [comment]
@sujaypatil96 what is the status of this issue?  Are you still actively working on it? Do you expect to finish this week?

@turbomam FYI

**Comment by ssarrafan** [comment]
@sujaypatil96 moving this to the backlog. Let me know if it should be assigned to someone else. 
FYI @cmungall

**Comment by turbomam** [comment]
Keep all of the existing content like YUML diagrams

**Comment by turbomam** [comment]
Be careful about the search experience

**Comment by ssarrafan** [comment]
@sujaypatil96 Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by turbomam** [comment]
Updates/status questions:
- see also 
  - https://github.com/microbiomedata/mixs/issues/44
  - https://github.com/microbiomedata/mixs/issues/42
  - https://github.com/microbiomedata/mixs/issues/39
- Will we be adding mermaid diagrams?

**Comment by ssarrafan** [comment]
Moving to July sprint per @sujaypatil96

**Comment by ssarrafan** [comment]
@sujaypatil96 indicated this is in the works, almost done, and to move to August sprint

**Comment by ssarrafan** [comment]
@sujaypatil96 is this done?  
I'm moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by sujaypatil96** [comment]
@ssarrafan: could you please close this issue? It's done.

**Comment by ssarrafan** [comment]
> @ssarrafan: could you please close this issue? It's done.

Yay!

**Comment by ssarrafan** [comment]
Done!
