### ISSUE TITLE
increase specificity of has_input relationship on omics_processing

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-schema#28]
The need here is driven from metabolomics and metaproteomics where @corilo would like to be able to specify the input as one of:

sample
blank
QC

**Comment by ssarrafan** [comment]
@corilo I'm removing David and Bill from this issue.  Let me know if this is something we should put in the backlog, break down into smaller chunks, or re-assign.  I'm so glad you're still here.

**Comment by turbomam** [comment]
It looks to me like the range of `OmicsProcessing.has_input` is as wide open as possible right now: `NamedThing`. 

See https://microbiomedata.github.io/nmdc-schema/OmicsProcessing/#induced

I would actually like to constrain this more now.

We have a `Biosample` class, but no classes for modelling blanks or QC samples. That doesn't sound totally unreasonable to me, but I do wonder if we would want to store the results of blank or QC runs in MongoDB.

**Comment by aclum** [comment]
@anastasiyaprymolenna  @corilo is this going to be addressed in the metabolomics squad?
