### ISSUE TITLE
Display hints requested for "NCBI BioProject Title" and "Data Types", but those aren't accessible from the study class

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#288]
See #267 and [SubmissionPortal_TermUpdates](https://docs.google.com/spreadsheets/d/1T31B5gbRgS6vuK_lIg0ZLpIyafByWhlvE2hfcCy-c4k/edit#gid=0&range=15:17) 

I have [added display hint annotations to the NMDC schema](https://github.com/microbiomedata/nmdc-schema/pull/287) for most of the rows in the `SubmissionPortal_TermUpdates` sheet. In those cases, I have provided jq paths to the hints.

However, I don't see anything [related to studies in the schema](https://github.com/microbiomedata/nmdc-schema/blob/issue-267-disp-hints/assets/study_indiced_slots.yaml) that correlates strongly with "bioproject title" or "data type"

I guess you could argue that [alternative titles](https://microbiomedata.github.io/nmdc-schema/alternative_titles/#slot-alternative-titles) could be used for "bioproject title", but the semantics are pretty weak.

Also, why would somebody enter a title when it could be looked up from the accession?

For "Data Types", is that supposed to correlate with [analysis_type](https://docs.google.com/spreadsheets/d/1WkftrJV548wO5Oh1L-K6N1BNU03btRUm2D7jvlHc7Uc/edit#gid=0&range=70:70) from our DataHarmonizer interface? I don't think that term is defined in either the NMDC or MIxS schemas yet.

**Comment by turbomam** [comment]
rather hinting about how to enter something, not hinting on how to display it

tooltips

**Comment by turbomam** [comment]
could column A or B be an actual DOM path? or anything verifiable?

**Comment by turbomam** [comment]
why are different tooltips for PI and Contrib ORCiD

box around PI fields?

then could have tooltip on principal investigator slot

**Comment by ssarrafan** [comment]
I'm going to move this one to April as it appears to be in process.  I will remove @mslarae13 as an assignee.

**Comment by turbomam** [comment]
@dehays provided some useful feedback about other classes that could receive this information, esp. 'Data Types'. Omics processing?

- [ ] I don't think we should add a display hint for 'NCBI BioProject Title' or even include that on the study submission pages at all. It should be looked up in NCBI based on the BioProject ID/accession (which should also be verified

I have also started to think of representing the DOM location for each display hint annotation, so that an external lookup table wouldn't be required. If we did this, @subdavis, what kind of notation would you want me to use? In Chrome's developer console, there are a couple of different copy as options.

**Comment by turbomam** [comment]
I don't expect to close this before April 28th or possible even the month's end.

**Comment by ssarrafan** [comment]
> I don't expect to close this before April 28th or possible even the month's end.

would you like me to move this to May or put it back in the backlog?  @turbomam

**Comment by ssarrafan** [comment]
@turbomam I will move this to May but if it should go in the backlog let me know and we can remove it from the May sprint

**Comment by ssarrafan** [comment]
Moving to June sprint per @turbomam on stand up

**Comment by turbomam** [comment]
We need better overall alignment between the labels used on the Submission Portal form elements, the field names returned by the API, and the real slots names defined by the NMDC Schema.

Then, we need to determine what element in the NMDC Schema should bear the display hints annotations, and what that formally corresponds to in the Portal's DOM. (@subdavis ?)

There's no reason for a submitter to enter `NCBI BioProject Title` in the Submission Portal. It can be looked up from the NCBI BioProject Accession, either during entry into the Submission Portal, or in the downstream metadata repair service (e.g. [`get_metadata_submissions.py`](https://github.com/microbiomedata/sample-annotator/blob/1a83d09a1d487eeba4cccf6fa080deb0e82ee3bf/sample_annotator/clients/nmdc/get_metadata_submissions.py)). Then there's no chance of typographic errors.

**Comment by turbomam** [comment]
Thanks, @subdavis

I would clarify that the use case for the first bullet point is validating soemthing like an NCBI BioProject accession (like XXX). I'll think about other use cases for validation and lookup.

In-portal validation and lookup would be very valuable, but maybe we should move those two ideas to a separate issue like #354 ?

My intent for this issue was to document the fact that there are elements on the study portion of the submission forms that don't relate directly to any slot or class in the schema, which makes it hard to assert what display hint goes where.

I'll be providing more documentation on this soon. @subdavis are you coming to the NMDC Sync meeting this afternoon?

**Comment by ssarrafan** [comment]
I'll move to July but let me know if it's not high priority so I can move it to the backlog.

**Comment by ssarrafan** [comment]
@turbomam @cmungall based on the meeting today with Kitwware does it make sense to move this to August or to backlog? Or would you like me to keep it in for July?

**Comment by mslarae13** [comment]
> @ssarrafan : the schema still doesn't authoritatively say what display hint goes where on the NMDC portals, and I don't think the portals are getting their hints from the schema either. This needs work.

I think this needs to be another / separate ticket if there isn't already one.

**Comment by ssarrafan** [comment]
> > @ssarrafan : the schema still doesn't authoritatively say what display hint goes where on the NMDC portals, and I don't think the portals are getting their hints from the schema either. This needs work.
> 
> I think this needs to be another / separate ticket if there isn't already one.

@mslarae13 @turbomam so the idea is to close this issue and open a new one for the proper fix? interim fix label?

**Comment by ssarrafan** [comment]
I'll close this and tag it with interim fix.  When you're ready to work on the change we can add another ticket.  @mslarae13 @turbomam
