### ISSUE TITLE
Transform EMP study & biosample records from GOLD API for ingest

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#294]
Description: The GOLD team is working to import the relevant set of soil metagenome and amplicon data from the EMP500 study hosted at NCBI (https://www.ncbi.nlm.nih.gov/bioproject/PRJEB42019). A list of biosamples was sent to the GOLD team on March 21. GOLD currently hosts the study information here: https://gold.jgi.doe.gov/study?id=Gs0154244 -- Reddy will notify us via email when the data is available in GOLD. What is needed for import into the mongoDB:

1. use GOLD API (details here: https://docs.google.com/document/d/1PgrFYmc7AU7Kd5Dtg-xbpAyC6ZcLw4ChFwg3bHV1JQg/edit)
2. ensure terms map appropriately to the currently NMDC data schema
3. Emiley will provide additional study information through this ticket (eg, study fields like ORCiD that are not in GOLD)
4. work with Donny to import metadata into mongoDB & validate

**Comment by turbomam** [comment]
Should I continue with https://github.com/microbiomedata/nmdc-emp500 ?

**Comment by ssarrafan** [comment]
@emileyfadrosh @dwinston tagging you since you're mentioned in this ticket

**Comment by dwinston** [comment]
@sujaypatil96 info on API endpoint for validating metadata: https://api.dev.microbiomedata.org/docs#/metadata/validate_json_metadata_json_validate_post

**Comment by cmungall** [comment]
we'll use this:

https://github.com/microbiomedata/sample-annotator/blob/main/sample_annotator/clients/gold_client.py

example code:

https://github.com/microbiomedata/sample-annotator/blob/main/tests/test_gold.py

**Comment by turbomam** [comment]
These fields are available to populate in the NMDC mongodb bisoample_set collection. Some mapping to GOLD fields names may be required.

- add_date
- alternative_identifiers
- collection_date
- community
- depth.has_numeric_value
- depth
- depth.has_unit
- depth2.has_numeric_value
- depth2
- depth2.has_unit
- description
- ecosystem
- ecosystem_category
- ecosystem_subtype
- ecosystem_type
- env_broad_scale
- env_local_scale
- env_medium
- geo_loc_name
- GOLD_sample_identifiers
- habitat
- host_name
- id
- identifier
- INSDC_biosample_identifiers
- lat_lon
- lat_lon.latitude
- lat_lon.longitude
- location
- mod_date
- name
- ncbi_taxonomy_name
- nitrate
- nitrate.has_unit
- part_of
- salinity
- sample_collection_site
- specific_ecosystem
- temp.has_numeric_value
- temp
- temp.has_unit
- type

The https://github.com/microbiomedata/nmdc-emp500 repo has tools for obtaining all of the metadata fields the the EMP500 people sued when submitting to NCBI, but I really think the mongodb fields are most important for the GOLD API alignment.

**Comment by ssarrafan** [comment]
@sujaypatil96 do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by ssarrafan** [comment]
I'm considering this issue closed. @sujaypatil96 you can re-open if you disagree. Thank you
