### ISSUE TITLE
update README on main page

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#3]
cc @jbeezley @turbomam

**Comment by turbomam** [comment]
Borrow from https://github.com/microbiomedata/nmdc-metadata/blob/master/README.md !

Not ETL code

**Comment by turbomam** [comment]
Updated branch name from `mam-readme` to `issue-3-update-README`

Anybody who has a `mam-readme` branch checked out needs to do

```Bash
git branch -m mam-readme issue-3-update-README
git fetch origin
git branch -u origin/issue-3-update-README issue-3-update-README
```

**Comment by wdduncan** [comment]
Thanks Mark.  
BTW, the branch name only needs to match the issue number, e.g. `issue-3`. You don't need to have the `update-README`, although it is nice to have that too :)

**Comment by turbomam** [comment]
I pushed a clean but minimal README.

- It doesn't include any editing or building instructions. 
- I took out any mentions of artifact formats if I don't think we're routinely making them, like OWL, GraphQL, etc.

Did I go overboard in cleaning it up?

**Comment by turbomam** [comment]
This may be irrelevant due to other changes to the README since June 2021
