### ISSUE TITLE
Metatranscriptiome workflow activities were incorrectly labelled

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-schema#30]
The activities were labelled "metagenome" and this was corrected manually in the portal, but I believe this should be fixed upstream in the metadata to get rid of this naming hack.

**Comment by wdduncan** [comment]
@scanon just to confirm, you need the class/type `MetatranscriptomeAnnotationActivity`. Right?  

I the schema file it will be `metatranscriptome annotation activity`.

**Comment by dehays** [comment]
We need to differentiate metagenome analysis from metagenome analysis in two places.

Currently there are nmdc:MetagenomeAnnotation and nmdc:MetagenomeAssembly

To the schema we need to add nmdc:MetatranscriptomeAnnotation and nmdc:MetatranscriptomeAssembly and @scanon would need to modify how the type is set in metadata to use these two new analysis types.
