### ISSUE TITLE
Remove pipenv related files?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#306]
- Pipfile
- Pipfile.lock
- environment.sh
- requirements.txt
- setup.py

Also read through Makefile

**Comment by turbomam** [comment]
see branch issue-306-no-pipenv

**Comment by turbomam** [comment]
```shell
grep -i pipenv .github/workflows/*
```
> %

----

```shell
grep poetry .github/workflows/*
```

> .github/workflows/build-deploy-documentation.yaml:      #          install & configure poetry
.github/workflows/build-deploy-documentation.yaml:        uses: snok/install-poetry@v1.3
.github/workflows/build-deploy-documentation.yaml:        id: cached-poetry-dependencies
.github/workflows/build-deploy-documentation.yaml:          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
.github/workflows/build-deploy-documentation.yaml:        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
.github/workflows/build-deploy-documentation.yaml:        run: poetry install --no-interaction --no-root     
.github/workflows/check-pull-request.yaml:    #          install & configure poetry
.github/workflows/check-pull-request.yaml:      uses: snok/install-poetry@v1.3
.github/workflows/check-pull-request.yaml:      id: cached-poetry-dependencies
.github/workflows/check-pull-request.yaml:        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
.github/workflows/check-pull-request.yaml:      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
.github/workflows/check-pull-request.yaml:      run: poetry install --no-interaction --no-root
.github/workflows/pypi-publish.yml:      uses: snok/install-poetry@v1.1.6
.github/workflows/pypi-publish.yml:        poetry version $(git describe --tags --abbrev=0)
.github/workflows/pypi-publish.yml:        poetry build

**Comment by sujaypatil96** [comment]
Looks like the setup.py file is still in the core repo?
