### ISSUE TITLE
Model Stan's Bioscales elements/nutrients terms here

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#311]
Were originally requested in MIxS: https://github.com/GenomicsStandardsConsortium/mixs/issues?q=is%3Aissue+author%3AStantonMartin

Some have been implemented in MIxS already. Questions remain for the others.

[Copy of GA lab Data 11_17_2020 (1).xlsx](https://github.com/microbiomedata/nmdc-schema/files/8730598/Copy.of.GA.lab.Data.11_17_2020.1.xlsx) illustrates some additional new terms required for Bioscales

CC @StantonMartin

**Comment by turbomam** [comment]
[carbon terms for Bioscales (plus errors) #7](https://github.com/microbiomedata/mixs/issues/7)

**Comment by ssarrafan** [comment]
@turbomam reported this morning that this issue is done. Closing issue.
