### ISSUE TITLE
Where do NMDC DataHarmonizer submissions go once the SUBMIT button is clicked?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#312]

**Comment by turbomam** [comment]
Thanks. How can I retrieve them?

**Comment by dwinston** [comment]
Oh, hmm, I interpreted this issue as one of proposed implementation. i.e. "where *may* NMDC DataHarmonizer submissions go?" I do not know where they currently go. @subdavis would know (you could also spelunk in the nmdc-server repo code).

**Comment by dehays** [comment]
They get saved in postgres in the submission_metadata table as unconstrained json on the metadata_submission field which is postgres jsonb. (like a JSON CLOB type).  

That table also has author_orcid, created, and status fields.

**Comment by turbomam** [comment]
OK, then I'm going to want read access on NMDC Postgres, and all of the SPIN middleware or whatever

**Comment by dehays** [comment]
@turbomam Rather than running a shell within a container in Spin/Rancher - would suggest you might use the API endpoints that Kitware provided.  Specifically: https://data.dev.microbiomedata.org/docs in the metadata_submission section.

**Comment by subdavis** [comment]
You can get the submissions from here: https://data.dev.microbiomedata.org/docs#/metadata_submission/list_submissions_api_metadata_submission_get

**Comment by turbomam** [comment]
Do in need credentials for this?

**Comment by subdavis** [comment]
You need to be authenticated with your Orcid on https://data.microbiomedata.org/ (or dev)

A bit more documentation here: https://github.com/microbiomedata/nmdc-server/wiki/Search-API-Docs

**Comment by turbomam** [comment]
Great. That does work in the browser. I don't see how to authenticate and use the API programmatically yet, but I ahven't read the documentation links you've shared meticulously.

**Comment by turbomam** [comment]
They go immediately into the submission_metadata table in "Kitware's" Postgres table, and yes, the API access seems to meet all of my needs.
