### ISSUE TITLE
create a user submitted ID field

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#328]
The user submitted ID field could follow the spirit of other external ID fields like INDC identifier(s?)

The existing id field, inherited from named thing, should be populated with IDs minted by https://api.dev.microbiomedata.org/docs#/identifiers

**Comment by turbomam** [comment]
https://api.dev.microbiomedata.org/docs#/identifiers

**Comment by mslarae13** [comment]
I thought we decided we were removing the 'identifiers' slot?
id vs identifier is too confusing.

**Comment by turbomam** [comment]
OK. Given the mongodb -> schema 7 migration @mslarae13 I and I have been doing, it looks like `source_mat_id` will serve the purpose I was looking for. Maybe we can clarify the slot descriptions to differentiate between the NMDC-minted identifier in `id` and `source_mat_id`

**Comment by turbomam** [comment]
Good progress. We could always improve the guidance to submitters.
