### ISSUE TITLE
Update and improve identifiers

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#330]
Identifiers, GUIDs, sample names, alternative IDs, 

The use of these fields and their definitions needs re-worked with possible addition of new terms. 

- [x] #369
- [x] #370
- [x] #371

**Comment by turbomam** [comment]
See [NMDC Biosample Slots selected cols](https://docs.google.com/spreadsheets/d/1eJAa-FExSls3YZrsVVA2NjDIGRm68FsEh00ma8rgbyw/edit#gid=916732144). Will provide more documentation soon.

**Comment by ssarrafan** [comment]
@mslarae13 would you like me to create 3 separate GH issues for this based on the three tasks above?  Update and improve seems to be too vague to be able to accomplish/close an issue.

**Comment by mslarae13** [comment]
@ssarrafan  I agree & think this would make it easier to plan

**Comment by ssarrafan** [comment]
> @ssarrafan I agree & think this would make it easier to plan

Ok I've created 3 separate issues related to this. I moved the first one to the August sprint and have not assigned the other two to a sprint yet. Let me know how you want to schedule them and if someone else should be assigned.  I'll move this overall issue to August so we can figure it out.

**Comment by mslarae13** [comment]
Related to https://github.com/microbiomedata/nmdc-schema/issues/369

**Comment by ssarrafan** [comment]
@mslarae13 moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by mslarae13** [comment]
See also
https://github.com/microbiomedata/nmdc-schema/issues/401#issuecomment-1234641862
&
https://github.com/microbiomedata/nmdc-schema/issues/369#issuecomment-1234630202

**Comment by ssarrafan** [comment]
Checked in with @turbomam and moving this to the squad sprint.  @mslarae13 let me know if you're not planning to work on this the rest of this month.

**Comment by mslarae13** [comment]
Can this get added to the deinococcus squad board? @ssarrafan

**Comment by ssarrafan** [comment]
Sure @mslarae13. I'll remove it from the current sprint and add it to the deino squad board until you're ready to work on it again then we can add it to the next sprint.  

FYI @turbomam

**Comment by mslarae13** [comment]
Oh, no.. it can be in the upcoming sprint. I'll be working on it. It's just a task that rounds out the work I'm doing in the squad and it wasn't on the board. Sorry for the confusion @ssarrafan

**Comment by ssarrafan** [comment]
> Oh, no.. it can be in the upcoming sprint. I'll be working on it. It's just a task that rounds out the work I'm doing in the squad and it wasn't on the board. Sorry for the confusion @ssarrafan

Ah ok no problem. I've added to the new sprint.

**Comment by mslarae13** [comment]
See https://github.com/microbiomedata/nmdc-schema/pull/491

**Comment by ssarrafan** [comment]
Moving to next sprint to allow for review. @mslarae13

**Comment by ssarrafan** [comment]
@mslarae13 has this one been reviewed yet? Can it be closed?

**Comment by mslarae13** [comment]
Still some identifier work being done, but requested additions have been made for this ticket : https://github.com/microbiomedata/nmdc-schema/pull/491
