### ISSUE TITLE
Low number of EMP 500 sample in data portal

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#331]
@cmungall and I looked at for EMP 500 samples in the data portal on Friday. We [found 80](https://data.dev.microbiomedata.org/?q=ChgIABABGAMiECJnb2xkOkdzMDE1NDI0NCIKFAgAEAIYAiIMIk1ldGFnZW5vbWUi).

NCBI Biosample says that there are [1024 samples.](https://www.ncbi.nlm.nih.gov/bioproject/686344)

I am not an expert on the EMP studies, but this did seem like a big discrepancy to me.

I think I have heard one or more person say that many of the EMP 500 samples didn't meet some of our suitability criteria. @hubin-keio ? @Michal-Babins ? @sujaypatil96, since you obtained the biosample metadata from GOLD, do you have any insight into this?

I get the sense that there have been many separate studies in the Earth Microbiome Project initiative. Is it possible that we loaded the wrong one?

I am doing some more research in our SQLite version of NCBI's biosample_set now. That's available from https://portal.nersc.gov/project/m3513/biosample/biosample_basex.db.gz

CC @emileyfadrosh

**Comment by turbomam** [comment]
This should probably be moved to a different repo

**Comment by turbomam** [comment]
@sujaypatil96 remembers @dehays saying that there were only 80 *soil* samples

**Comment by sujaypatil96** [comment]
The ETL pipeline only pulled out data for the 80 soil samples from the EMP500 study that are in the GOLD database. To see a list of the 80 samples: https://github.com/microbiomedata/sample-annotator/blob/main/sample_annotator/clients/nmdc/input/soil_ids.txt

**Comment by turbomam** [comment]
It would be interesting to review how the ~ 80 samples were identified as coming from a soil environment, but the count of useful EMP500 soil samples is not in dispute anymore.
