### ISSUE TITLE
Model relationship between semantic ID shoulder and entity type in schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#333]
I will elaborate later today

CC @cmungall @emileyfadrosh @dwinston @mslarae13

**Comment by mslarae13** [comment]
@turbomam  I think this has to do with the ID miniting task @pkalita-lbl  is working on right?

**Comment by turbomam** [comment]
id minting with typecodes and indicators of the minting authority has been released, at least on the dev version of the NMDC runtime API.
