### ISSUE TITLE
biosample class definitions are so large that YUML URIs are rejected

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#344]
https://microbiomedata.github.io/nmdc-schema/Biosample/#class-biosample is trying to generate a YUML diagram from this URL:

https://yuml.me/diagram/nofunky;dir:TB/class/[TimestampValue],[TextValue],[QuantityValue],[OmicsProcessing],[NamedThing],[GeolocationValue],[Database],[ControlledTermValue],[BiosampleProcessing],[QuantityValue]%3Clbceq%200..1-++[Biosample|type:string%20%3F;tot_nitro_cont_meth:string%20%3F;water_cont_soil_meth:string%20%3F;ecosystem:string%20%3F;ecosystem_category:string%20%3F;ecosystem_type:string%20%3F;ecosystem_subtype:string%20%3F;specific_ecosystem:string%20%3F;add_date:string%20%3F;community:string%20%3F;habitat:string%20%3F;host_name:string%20%3F;identifier:string%20%3F;location:string%20%3F;mod_date:string%20%3F;ncbi_taxonomy_name:string%20%3F;proport_woa_temperature:string%20%3F;salinity_category:string%20%3F;sample_collection_site:string%20%3F;soluble_iron_micromol:string%20%3F;GOLD_sample_identifiers:external_identifier%20*;INSDC_biosample_identifiers:external_identifier%20*;INSDC_secondary_sample_identifiers:external_identifier%20*;micro_biomass_meth:string%20%3F;samp_collec_method:string%20%3F;soil_texture_meth:string%20%3F;dna_absorb1:string%20%3F;dna_absorb2:string%20%3F;dna_collect_site:string%20%3F;dna_concentration:string%20%3F;dna_cont_type:dna_cont_type_enum%20%3F;dna_cont_well:string%20%3F;dna_container_ID:string%20%3F;dna_dnase:dna_dnase_enum%20%3F;dna_isolate_meth:string%20%3F;dna_organisms:string%20%3F;dna_project_contact:string%20%3F;dna_samp_ID:string%20%3F;dna_sample_format:dna_sample_format_enum%20%3F;dna_sample_name:string%20%3F;dna_seq_project:string%20%3F;dna_seq_project_PI:string%20%3F;dna_seq_project_name:string%20%3F;dna_volume:string%20%3F;proposal_dna:string%20%3F;dnase_rna:dnase_rna_enum%20%3F;proposal_rna:string%20%3F;rna_absorb1:string%20%3F;rna_absorb2:string%20%3F;rna_collect_site:string%20%3F;rna_concentration:string%20%3F;rna_cont_type:rna_cont_type_enum%20%3F;rna_cont_well:string%20%3F;rna_container_ID:string%20%3F;rna_isolate_meth:string%20%3F;rna_organisms:string%20%3F;rna_project_contact:string%20%3F;rna_samp_ID:string%20%3F;rna_sample_format:rna_sample_format_enum%20%3F;rna_sample_name:string%20%3F;rna_seq_project:string%20%3F;rna_seq_project_PI:string%20%3F;rna_seq_project_name:string%20%3F;rna_volume:string%20%3F;collection_date_inc:string%20%3F;collection_time:string%20%3F;collection_time_inc:string%20%3F;experimental_factor_other:string%20%3F;filter_method:string%20%3F;isotope_exposure:string%20%3F;micro_biomass_C_meth:string%20%3F;micro_biomass_N_meth:string%20%3F;microbial_biomass_C:string%20%3F;microbial_biomass_N:string%20%3F;non_microb_biomass:string%20%3F;non_microb_biomass_method:string%20%3F;org_nitro_method:string%20%3F;other_treatment:string%20%3F;start_date_inc:string%20%3F;start_time_inc:string%20%3F;EMSL_store_temp:string%20%3F;project_ID:string%20%3F;replicate_number:string%20%3F;sample_shipped:string%20%3F;sample_type:sample_type_enum%20%3F;technical_reps:string%20%3F;analysis_type:analysis_type_enum%20*;sample_link:string%20%3F;id(i):string;name(i):string%20%3F;description(i):string%20%3F;alternative_identifiers(i):string%20*],[QuantityValue]%3Clbc_thirty%200..1-++[Biosample],[QuantityValue]%3Cnitrite%20nitrogen%200..1-++[Biosample],[QuantityValue]%3Cnitrate%20nitrogen%200..1-++[Biosample],[QuantityValue]%3Cammonium%20nitrogen%200..1-++[Biosample],[QuantityValue]%3Cmanganese%200..1-++[Biosample],[QuantityValue]%3Czinc%200..1-++[Biosample],[QuantityValue]%3Cwatering_regm%200..1-++[Biosample],[TextValue]%3Csource_mat_id%200..1-++[Biosample],[QuantityValue]%3Csoil_text_measure%200..1-++[Biosample],[QuantityValue]%3Csamp_size%200..1-++[Biosample],[TextValue]%3Crel_to_oxygen%200..1-++[Biosample],[QuantityValue]%3Cphosphate%200..1-++[Biosample],[QuantityValue]%3Clight_regm%200..1-++[Biosample],[QuantityValue]%3Chumidity_regm%200..1-++[Biosample],[ControlledTermValue]%3Cgrowth_facil%200..1-++[Biosample],[QuantityValue]%3Cgaseous_environment%200..1-++[Biosample],[ControlledTermValue]%3Cexperimental_factor%200..1-++[Biosample],[TextValue]%3Cclimate_environment%200..1-++[Biosample],[TextValue]%3Cbiotic_relationship%200..1-++[Biosample],[TextValue]%3Cbiotic_regm%200..1-++[Biosample],[QuantityValue]%3Cair_temp_regm%200..1-++[Biosample],[QuantityValue]%3Csubsurface_depth2%200..1-++[Biosample],[QuantityValue]%3Csubsurface_depth%200..1-++[Biosample],[QuantityValue]%3Cdepth2%200..1-++[Biosample],[QuantityValue]%3Cwater_content%200..1-++[Biosample],[QuantityValue]%3Ctot_phosp%200..1-++[Biosample],[QuantityValue]%3Ctot_nitro_content%200..1-++[Biosample],[TextValue]%3Ctot_org_c_meth%200..1-++[Biosample],[QuantityValue]%3Ctot_org_carb%200..1-++[Biosample],[QuantityValue]%3Ctot_diss_nitro%200..1-++[Biosample],[QuantityValue]%3Ctot_depth_water_col%200..1-++[Biosample],[QuantityValue]%3Ctot_carb%200..1-++[Biosample],[TextValue]%3Ctidal_stage%200..1-++[Biosample],[TextValue]%3Ctillage%200..1-++[Biosample],[TextValue]%3Ctexture_meth%200..1-++[Biosample],[QuantityValue]%3Ctexture%200..1-++[Biosample],[QuantityValue]%3Ctemp%200..1-++[Biosample],[QuantityValue]%3Csulfide%200..1-++[Biosample],[QuantityValue]%3Csulfate%200..1-++[Biosample],[TextValue]%3Cstore_cond%200..1-++[Biosample],[TextValue]%3Csoil_type_meth%200..1-++[Biosample],[TextValue]%3Csoil_type%200..1-++[Biosample],[QuantityValue]%3Csodium%200..1-++[Biosample],[QuantityValue]%3Cslope_aspect%200..1-++[Biosample],[QuantityValue]%3Cslope_gradient%200..1-++[Biosample],[QuantityValue]%3Csize_frac_up%200..1-++[Biosample],[QuantityValue]%3Csize_frac_low%200..1-++[Biosample],[QuantityValue]%3Csieving%200..1-++[Biosample],[QuantityValue]%3Cseason_precpt%200..1-++[Biosample],[QuantityValue]%3Cseason_temp%200..1-++[Biosample],[QuantityValue]%3Csamp_vol_we_dna_ext%200..1-++[Biosample],[QuantityValue]%3Csamp_store_temp%200..1-++[Biosample],[TextValue]%3Csamp_store_loc%200..1-++[Biosample],[TextValue]%3Csamp_store_dur%200..1-++[Biosample],[ControlledTermValue]%3Csamp_mat_process%200..1-++[Biosample],[TextValue]%3Csamp_collect_device%200..1-++[Biosample],[TextValue]%3Csalinity_meth%200..1-++[Biosample],[QuantityValue]%3Csalinity%200..1-++[Biosample],[QuantityValue]%3Credox_potential%200..1-++[Biosample],[TextValue]%3Cprofile_position%200..1-++[Biosample],[TextValue]%3Cprevious_land_use_meth%200..1-++[Biosample],[TextValue]%3Cprevious_land_use%200..1-++[Biosample],[QuantityValue]%3Cpressure%200..1-++[Biosample],[QuantityValue]%3Cpotassium%200..1-++[Biosample],[TextValue]%3Cpool_dna_extracts%200..1-++[Biosample],[QuantityValue]%3Cphosplipid_fatt_acid%200..1-++[Biosample],[QuantityValue]%3Cphaeopigments%200..1-++[Biosample],[TextValue]%3Cph_meth%200..1-++[Biosample],[QuantityValue]%3Cph%200..1-++[Biosample],[QuantityValue]%3Cpetroleum_hydrocarb%200..1-++[Biosample],[TextValue]%3Cperturbation%200..1-++[Biosample],[QuantityValue]%3Cpart_org_carb%200..1-++[Biosample],[TextValue]%3Coxy_stat_samp%200..1-++[Biosample],[QuantityValue]%3Corganism_count%200..1-++[Biosample],[QuantityValue]%3Corg_nitro%200..1-++[Biosample],[QuantityValue]%3Corg_matter%200..1-++[Biosample],[QuantityValue]%3Cnitrite%200..1-++[Biosample],[QuantityValue]%3Cnitrate%200..1-++[Biosample],[QuantityValue]%3Cn_alkanes%200..1-++[Biosample],[QuantityValue]%3Cmisc_param%200..1-++[Biosample],[TextValue]%3Cmicrobial_biomass_meth%200..1-++[Biosample],[QuantityValue]%3Cmicrobial_biomass%200..1-++[Biosample],[QuantityValue]%3Cmean_peak_frict_vel%200..1-++[Biosample],[QuantityValue]%3Cmean_frict_vel%200..1-++[Biosample],[QuantityValue]%3Cmagnesium%200..1-++[Biosample],[TextValue]%3Clocal_class_meth%200..1-++[Biosample],[TextValue]%3Clocal_class%200..1-++[Biosample],[TextValue]%3Clink_climate_info%200..1-++[Biosample],[TextValue]%3Clink_class_info%200..1-++[Biosample],[TextValue]%3Clink_addit_analys%200..1-++[Biosample],[GeolocationValue]%3Clat_lon%200..1-++[Biosample],[TextValue]%3Chorizon_meth%200..1-++[Biosample],[TextValue]%3Chorizon%200..1-++[Biosample],[TextValue]%3Cheavy_metals_meth%200..1-++[Biosample],[QuantityValue]%3Cheavy_metals%200..1-++[Biosample],[QuantityValue]%3Cglucosidase_act%200..1-++[Biosample],[TextValue]%3Cgeo_loc_name%200..1-++[Biosample],[TimestampValue]%3Cflooding%200..1-++[Biosample],[TimestampValue]%3Cfire%200..1-++[Biosample],[TextValue]%3Cfao_class%200..1-++[Biosample],[TimestampValue]%3Cextreme_event%200..1-++[Biosample],[ControlledTermValue]%3Cenv_medium%201..1-++[Biosample],[ControlledTermValue]%3Cenv_local_scale%201..1-++[Biosample],[ControlledTermValue]%3Cenv_broad_scale%201..1-++[Biosample],[TextValue]%3Cenv_package%200..1-++[Biosample],[QuantityValue]%3Celev%200..1-++[Biosample],[TextValue]%3Cdrainage_class%200..1-++[Biosample],[QuantityValue]%3Cdiss_oxygen%200..1-++[Biosample],[QuantityValue]%3Cdiss_org_nitro%200..1-++[Biosample],[QuantityValue]%3Cdiss_org_carb%200..1-++[Biosample],[QuantityValue]%3Cdiss_inorg_phosp%200..1-++[Biosample],[QuantityValue]%3Cdiss_inorg_carb%200..1-++[Biosample],[QuantityValue]%3Cdiss_hydrogen%200..1-++[Biosample],[QuantityValue]%3Cdiss_carb_dioxide%200..1-++[Biosample],[QuantityValue]%3Cdepth%200..1-++[Biosample],[QuantityValue]%3Cdensity%200..1-++[Biosample],[TextValue]%3Ccrop_rotation%200..1-++[Biosample],[TextValue]%3Ccur_vegetation_meth%200..1-++[Biosample],[TextValue]%3Ccur_vegetation%200..1-++[Biosample],[TextValue]%3Ccur_land_use%200..1-++[Biosample],[TimestampValue]%3Ccollection_date%200..1-++[Biosample],[QuantityValue]%3Cchlorophyll%200..1-++[Biosample],[QuantityValue]%3Cchloride%200..1-++[Biosample],[ControlledTermValue]%3Cchem_administration%200..1-++[Biosample],[QuantityValue]%3Ccarb_nitro_ratio%200..1-++[Biosample],[QuantityValue]%3Ccalcium%200..1-++[Biosample],[QuantityValue]%3Cbromide%200..1-++[Biosample],[QuantityValue]%3Cbishomohopanol%200..1-++[Biosample],[QuantityValue]%3Cbacteria_carb_prod%200..1-++[Biosample],[QuantityValue]%3Cannual_temp%200..1-++[Biosample],[QuantityValue]%3Cannual_precpt%200..1-++[Biosample],[QuantityValue]%3Cammonium%200..1-++[Biosample],[QuantityValue]%3Caminopept_act%200..1-++[Biosample],[TextValue]%3Cal_sat_meth%200..1-++[Biosample],[QuantityValue]%3Cal_sat%200..1-++[Biosample],[QuantityValue]%3Calt%200..1-++[Biosample],[QuantityValue]%3Calkyl_diethers%200..1-++[Biosample],[TextValue]%3Calkalinity_method%200..1-++[Biosample],[QuantityValue]%3Calkalinity%200..1-++[Biosample],[QuantityValue]%3Cagrochem_addition%200..1-++[Biosample],[NamedThing]%3Cpart%20of%201..*-%20[Biosample],[BiosampleProcessing]-%20has%20input%200..*%3E[Biosample],[Database]++-%20biosample%20set%200..*%3E[Biosample],[OmicsProcessing]-%20has%20input(i)%201..*%3E[Biosample],[NamedThing]%5E-[Biosample]

**Comment by cmungall** [comment]
@turbomam is this still relevant?

**Comment by turbomam** [comment]
> @turbomam is this still relevant?

Yes, the web-based documentation page for NMDC biosample has a broken image.

What are our options as me move to gen-docs and mermaid? 
- Give an option for suppressing the diagram?
- Autosense when a diagram won't be useful or even feasible?
- _change the modeling_?

**Comment by turbomam** [comment]
see also:
- https://github.com/microbiomedata/NMDC_documentation/issues/10

**Comment by sujaypatil96** [comment]
We are not creating yUML diagrams anymore, so I think this issue can be closed.
