### ISSUE TITLE
Do some of the PyPI publishing GH action still use pip, not poetry?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#348]
I thought I saw some usages of pip just flash by, but I can't seem to find them in `.github/workflows`

**Comment by sujaypatil96** [comment]
Hm, none of our Actions use pip as far as I know. I checked the workflows and nothing there too, so I think this issue can be closed.

CC: @ssarrafan

**Comment by ssarrafan** [comment]
Closing!
