### ISSUE TITLE
Users shouldn't need to enter the NCBI BioProject Title in the submission portal

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#354]
The NCBI BioProject Title can be looked up from the NCBI BioProject Accession.

See https://github.com/microbiomedata/nmdc-schema/issues/288#issuecomment-1157704468

**Comment by mslarae13** [comment]
![Image](https://github.com/user-attachments/assets/6b5e6c51-383d-4568-8d11-a9c97a78f1a1)

Title is gone, only have Accession #. 
Resolved.
