### ISSUE TITLE
create enums for institutions like EMSL

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#357]
will probably require a changesheet for updating in mongodb

**Comment by turbomam** [comment]
Environmental Molecular Sciences Laboratory

**Comment by cmungall** [comment]
enums:
  Institution:
    permissible_values:
       Environmental Molecular Sciences Laboratory:
         meaning: https://ror.org/04rc0xn13

**Comment by ssarrafan** [comment]
@turbomam are you working on this in July?  Can I add this to the July board?

**Comment by cmungall** [comment]
Dupe with #352
