### ISSUE TITLE
Create list of needed identifiers and definitions

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#369]

**Comment by mslarae13** [comment]
Working doc for sorting our unique NMDC id shoulders : https://docs.google.com/spreadsheets/d/1HdY4PZSKJzmWsUIzgmsX6FxaS9k1Jxt-IppRkoyhtBA/edit?usp=sharing 

Working doc for types of identifiers needed: https://docs.google.com/spreadsheets/d/1e7hA0H4lkkHCNjYxMSkTR3BrYI3Jp-lJsnfOGyK28L8/edit?usp=sharing

**Comment by ssarrafan** [comment]
@mslarae13 moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by turbomam** [comment]
It's not enough to list something because it is needed.

Proposals for any new identifiers in the schema should include:
- to what class will the identifier apply?
- is the identifier required for any instance of the class above? or recommended, or optional?
- should the slot allow multiple identifier values, or just one?
- does it link to something else modeled by the schema, or does it link to something outside of the schema?
- a few examples of valid identifier values
- a few examples of invalid identifier values
- is it a subslot of an existing slot? (I can help determine that.)

**Comment by ssarrafan** [comment]
> It's not enough to list something because it is needed.
> 
> Proposals for any new identifiers in the schema should include:
> 
> * to what class will the identifier apply?
> * is the identifier required for any instance of the class above? or recommended, or optional?
> * should the slot allow multiple identifier values, or just one?
> * does it link to something else modeled by the schema, or does it link to something outside of the schema?
> * a few examples of valid identifier values
> * a few examples of invalid identifier values
> * is it a subslot of an existing slot? (I can help determine that.)

Can this criteria be a template for these types of identifier requests?

**Comment by ssarrafan** [comment]
Checked in with @turbomam and moving this to the squad sprint.  @mslarae13 let me know if you're not planning to work on this the rest of this month.

**Comment by dwinston** [comment]
my current thoughts on candidate typecodes for NMDC schema entities/classes:

sa - sample
st - study
saa - sample activity (e.g. sample prep) (range: sample)
p - party (e.g. instrument, person, software agent)
op - omics processing (workflow)
opa - omics processing (aka "data production"?) activity (domain: sample, range: data object)
do - data object
oaa - omics analysis activity (domain: data object. range: data object)

Note there are no separate mta, mga, etc. typecodes. These are all just `oaa`. For this squad, it's most important to assign study and (bio)sample codes while thinking about how they might fit in a larger scheme, without necessarily deciding on any other codes definitively at this time.

**Comment by ssarrafan** [comment]
@mslarae13 @sujaypatil96 Can this issue be closed today or by Tuesday?

**Comment by mslarae13** [comment]
What identifiers are needed has been curated. : https://lucid.app/lucidchart/811029cb-a93e-436a-a997-3faba459497c/edit?viewport_loc=-1802%2C-1249%2C4975%2C2700%2C0_0&invitationId=inv_46ca52cd-6253-4c5d-a913-e8d6df360a42# 

I'll now start working on getting the info into the schema.
