### ISSUE TITLE
Create 'shoulder' IDs for the different NMDC minted unique IDs and when/ where to use them

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#370]

**Comment by turbomam** [comment]
Make it clear which classes are intended to use which shoulders. May require
- a specification within the schema
- query methods in @dwinston's API
- ongoing monitoring

**Comment by ssarrafan** [comment]
@mslarae13 moving to Sept but let me know if you're not working on this for the next 2 weeks

**Comment by mslarae13** [comment]
Relates to https://github.com/orgs/microbiomedata/projects/34

**Comment by pkalita-lbl** [comment]
I'm going to close this issue as a duplicate of https://github.com/microbiomedata/issues/issues/4. This issue may be older, but the other one has more information and is part of the new identifiers squad's project.
