### ISSUE TITLE
Update schema identifiers accordingly

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#371]

**Comment by turbomam** [comment]
According to what?

**Comment by mslarae13** [comment]
@turbomam 
According to our decision on how to handle identifiers : https://github.com/microbiomedata/nmdc-schema/issues/330

**Comment by mslarae13** [comment]
Pushed an update to identifiers : https://github.com/microbiomedata/nmdc-schema/pull/491

**Comment by ssarrafan** [comment]
Moving to next sprint to allow for review. @mslarae13

**Comment by ssarrafan** [comment]
@mslarae13 has this been reviewed yet? Can we close this one?

**Comment by mslarae13** [comment]
Completed. https://github.com/microbiomedata/nmdc-schema/pull/491
