### ISSUE TITLE
Improve description for globally unique ID

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-schema#372]
ESS attendees reported being confused about how to fill in the globally unique ID column. Address the following and update the description accordingly.

- It should be clear that if they have an IGSN, that this can be used directly and should be compliant
- If they generate a UUID, it is not compliant with the required format. More guidance should be provided on how to make a UUID NMDC-compliant. e.g. add a prefix (which prefix? needs to be agreed upon)
- If they have an NCBI Accession Number - do they need to generate a UUID or can they just use the Accession? Not clear if this is globally unique -- and if it isn't what should be done to make it globally unique.
- Is the NMDC going to generate GUIDs such that users will no longer need to fill in this column in the future? 

Note: @mslarae13 to re-assign to @turbomam to update the description with the content has been determined.

**Comment by turbomam** [comment]
Honestly we could remove this column or just relax the requirements now that we are going to provide rigorous NMDC identifiers in the `id` slot.

In reality, there's no such thing as the "globally unique ID". It's just a re-titling of MIxS' [`source_mat_id`](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=178015749&range=24:24)

Before we had a policy regarding the mandatory use of an NMDC-minted identifier in the `id` slot, I thought this was a pretty good idea. But I would be conservative about dramatically overriding the semantics of a term we are borrowing form another source.

**Comment by turbomam** [comment]
What's more important: globally unique or resolvable?  We have talked some about adding some service-based validation to DataHarmoinzer. Nothing like that is in place yet, but this might be an interesting test case.

We could rename to column to "resolvable ID" and reject it if we can't validate against the services we trust.

**Comment by ssarrafan** [comment]
Based on discussion at Infrastructure sync meeting, adding to the August sprint

**Comment by mslarae13** [comment]
source_mat_id was titled globally unique ID for clarification on what is meant to go in this column. The value will match MIxS and JGI's source_mat_id values.

I think, for this variable (source_mat_id), globally unique is more important. Where as resolvable will be accomplished with 'id' which is the NMDC minted id. 

Discuss schema updates at Wednesday's (08-17) meeting.

**Comment by ssarrafan** [comment]
@mslarae13 moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by turbomam** [comment]
shouldn't **remove**: required by EMSL and people will have values 

wait until nmdc minted identifiers are auto-inserted

@turbomam remember we should add secondary keys to DH = LinkML unique key

**Comment by dwinston** [comment]
related resources:
- `ids` umbrella pattern for registered prefixes: https://api.openalex.org/works/W2098772291
- doi states of {draft,registered,findable}: https://support.datacite.org/docs/doi-states

**Comment by turbomam** [comment]
see also #328

**Comment by ssarrafan** [comment]
Checked in with @turbomam and moving this to the squad sprint.  @mslarae13 let me know if you're not planning to work on this the rest of this month.

**Comment by ssarrafan** [comment]
@mslarae13 Any update on this issue? Can this issue be closed today or by Tuesday?

**Comment by mslarae13** [comment]
See https://github.com/microbiomedata/sheets_and_friends/issues/157

This is done. @ssarrafan , @turbomam  should we make a new ticket for updating the portal?

**Comment by ssarrafan** [comment]
> See [microbiomedata/sheets_and_friends#157](https://github.com/microbiomedata/sheets_and_friends/issues/157)
> 
> This is done. @ssarrafan , @turbomam should we make a new ticket for updating the portal?

Great! @jeffbaumes let's discuss this when we meet later today.  
@mslarae13 I'll close this one. Thanks!
