### ISSUE TITLE
Make formatting guidelines for all temperature metadata terms consistent

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-schema#373]
![image](https://user-images.githubusercontent.com/7374085/182739995-ba68f092-87a6-4a3c-ab56-4a6d90cf1233.png)

Reported by ESS attendees:

All of these terms have slightly different requirements for valid values. Some require units, some do not. Please consolidate to use a single formatting guideline for all temperature terms. This is important for usability as it is confusing to sometimes provide only a numeric value, then in a different spot, a numeric value and unit. The validation rules for these terms will also need to be updated once a decision has been made on the format.

Note: @mslarae13 needs to work on this before re-assigning to @turbomam for the final update.

**Comment by turbomam** [comment]
What's the difference between the terms' formatting and the terms' validation?

**Comment by pvangay** [comment]
when I think of formatting guidance, I think of all of the text that is in the help text that pops up (after double clicking a header).

when I think of validation, I think of the actual implementation of how the value is validated when the user hits the "validate" button.

We've seen discrepancies with some terms (e.g. https://github.com/microbiomedata/sheets_and_friends/issues/140) so I wanted to make sure to distinguish them a bit.

**Comment by turbomam** [comment]
Thanks. The text that appears in the column headers is the slot `title`, at least within the [submission schema](https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/main/artifacts/nmdc_submission_schema.yaml).

The help screens provide
- the `title` (although DH calls it "Label")
- slot `name`
- `description`
- "Guidance"
  - `comments`
  - the regular expression `pattern` that is used for validation
  - "Pattern hint"s, which need some straightening out. I can elaborate if you want.
  - Indicator of whether the column requires unique values
  - Indicator of minimum and/or maximum values
  - `example`s

I might have forgotten something. I think Damion is working on this now, so it would be a good time to speak up if necessary.

**Comment by pvangay** [comment]
OH this is really helpful. Thanks @turbomam! I guess one question I have for the metadata team is whether we want to impose any internal requirements to always have content under at least one of the bullets listed under "Guidance". I flagged a bunch of terms that either had nothing under "Guidance" and/or nothing under "Example" here: https://github.com/microbiomedata/nmdc-schema/issues/382. But it's unclear if this is a self-imposed requirement that we want to abide by internally or not. If not - then perhaps #382 can just be ignored (sorry for making the assumption that these sections should be filled!)

**Comment by ssarrafan** [comment]
Based on discussion at Infrastructure sync meeting, adding to the August sprint

**Comment by mslarae13** [comment]
To discuss 08/17 @ metadata meeting

**Comment by ssarrafan** [comment]
@mslarae13 moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by mslarae13** [comment]
Mark updated the validation & that works. But we should still improve the guidelines 
@ssarrafan  can you make 1 ticket 'update guidelines & add examples for all submission portal slots' 
And tagg this one under it?

**Comment by ssarrafan** [comment]
> Mark updated the validation & that works. But we should still improve the guidelines @ssarrafan can you make 1 ticket 'update guidelines & add examples for all submission portal slots' And tagg this one under it?

What about this issue:  https://github.com/microbiomedata/nmdc-schema/issues/382

**Comment by mslarae13** [comment]
Exactly what I wanted! Thanks! Didn't know it existed. This should be able to be October sprint.

**Comment by ssarrafan** [comment]
> Exactly what I wanted! Thanks! Didn't know it existed. This should be able to be October sprint.

ok great so we can close this issue and I can adde #382 to October.
