### ISSUE TITLE
"history/extreme events" needs more context

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-schema#374]
Currently you can enter the date on which an extreme event occurred, but there is no where to explain what the actual extreme event was. ESS attendees noted that "history/extreme events" (which expects a date) should be accompanied by another term that provides more context on the extreme event itself.

This may require submitting a ticket to the GSC? Please discuss then address. @turbomam @cmungall

**Comment by turbomam** [comment]
Good one. There are a lot of MIxS terms like this that inefficiently address the need to identify noteworthy events and the dates on which they occurred. I'll dig up some more examples and make some suggestions.

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/nmdc-schema/pull/545

**Comment by mslarae13** [comment]
@ssarrafan  can you add this to the sprint that starts monday the 12th

**Comment by mslarae13** [comment]
This is basically done. PR approved and merged. Need to add "todo". WIll do that in a different branch

**Comment by turbomam** [comment]
Since the PR is merged, can we close this. Is there an issue for the addition of todos yet?
