### ISSUE TITLE
nitrogen flux modeling for bioscales

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#376]
[From NMDC Data Schema / Data Management Team Rolling Notes](1CDLw4zwD4Z_0dNHyT8nQGey6fDvVd0zQd4cDqG_ulqg)

How is the N flux collected? Does it match to 1:1 data point to biosample? 1:n data point:biosample

**Comment by ssarrafan** [comment]
@turbomam moving this to Sept but please let me know if you're not actively working on it for the next 2 weeks

**Comment by ssarrafan** [comment]
Removing this from the sprint and adding the backlog label after checking with Emiley.

**Comment by ssarrafan** [comment]
Over a year old. No updates. Closing issue. @turbomam let me know if you still plan to work on this.
