### ISSUE TITLE
Use changsesheet to get GOLD env paths for the 60 mCAFE biosamples into MongoDB

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#379]
From  [NMDC Data Schema / Data Management Team Rolling Notes](https://docs.google.com/document/d/1CDLw4zwD4Z_0dNHyT8nQGey6fDvVd0zQd4cDqG_ulqg/edit#)

see also #378

**Comment by ssarrafan** [comment]
@sujaypatil96 and @turbomam would you consider this done? Can we close this one?

**Comment by turbomam** [comment]
The GOLD paths are in there, but it didn't require a change sheet or a lookup table. Just the new biosample instantiator in hybrid mode.
