### ISSUE TITLE
whiteboard modeling project/study relationships

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#380]
from [NMDC Data Schema / Data Management Team Rolling Notes](https://docs.google.com/document/d/1CDLw4zwD4Z_0dNHyT8nQGey6fDvVd0zQd4cDqG_ulqg/edit#)

**Comment by turbomam** [comment]
see also #383

**Comment by ssarrafan** [comment]
@turbomam moving this to Sept but please let me know if you're not actively working on it for the next 2 weeks

**Comment by ssarrafan** [comment]
Discussed with @turbomam and moving to the backlog.

**Comment by aclum** [comment]
I can't tell what the request is for this ticket since it just links to the schema rolling meeting notes. I'm going close this since study modeling is being looked w/the current study page refresh squad. Please reopen if you remember what this was able.

**Comment by turbomam** [comment]
@aclum closign was a good idea. Could you please add a link to the place where you think work like this is continuing?

**Comment by aclum** [comment]
https://github.com/microbiomedata/issues/issues/342

**Comment by ssarrafan** [comment]
> [microbiomedata/issues#342](https://github.com/microbiomedata/issues/issues/342)

Moved 342 to the next sprint so will also move this issue to complete next week.
