### ISSUE TITLE
Update use of biosample identifier columns in MongoDB

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#381]
from [NMDC Data Schema / Data Management Team Rolling Note](https://docs.google.com/document/d/1CDLw4zwD4Z_0dNHyT8nQGey6fDvVd0zQd4cDqG_ulqg/edit#)s

- current `id` -> `source_mat_id`
- inject minted identifiers into `id`
- current `identifier` -> `samp_name`
- remove `identifier` from schema and MongoDB records

**Comment by ssarrafan** [comment]
@turbomam moving this to Sept but please let me know if you're not actively working on it for the next 2 weeks

**Comment by mslarae13** [comment]
Same comment as on ticket #328. We decided in a metadata meeting the identifier slot should be deprecated.

**Comment by ssarrafan** [comment]
Discussed with [@turbomam](https://github.com/turbomam) and moving to the backlog.

**Comment by turbomam** [comment]
A prototype for these identifier migrations is implemented in https://github.com/microbiomedata/nmdc-schema/blob/issue-486-data-to-7-0/src/schema/nmdc.yaml

It creates a new MongoDB database, which can be shared with @jeffbaumes Kitware and eventually loaded as a replacement  for the `nmdc` database in @dwinston's  production MongoDB.

**_WITH ONE EXCEPTION_**: I do not anticipate that the script linked above will migrate or validate either of these collections:

- functional_annotation_set
- genome_feature_set

The small "first N' sampling I have done so far suggests that those collections might not need any migration. In any case, they will have to be interleaved with the migrated dump I will be able to provide.
