### ISSUE TITLE
Add guidance and/or example text to soil template terms

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-schema#382]
Some terms were reported by ESS attendees. This is an exhaustive list of terms in the Soil-EMSL template on the submission portal that either are missing guidance text and/or example text.

**Missing guidance text _and_ example text:**
- [x] sample shipped amount
- [x] number technical replicate
- [x] history/extreme events
- [x] history/fire
- [x] history/flooding
- [x] filter method	
- [x] experimental factor- other	
- [x] non-microbial biomass	
- [x] non-microbial biomass method	
- [x] microbial biomass carbon	
- [x] microbial biomass carbon method	
- [x] microbial biomass nitrogen	
- [x] microbial biomass nitrogen method	
- [x] organic nitrogen method	
- [x] other treatments	
- [x] isotope exposure/addition	

**Missing example text:**
- [x] replicate number
- [x] slope aspect
- [x] extreme_unusual_properties/Al saturation
- [x] extreme_unusual_properties/Al saturation method	
- [x] mean annual precipitation	
- [x] current vegetation	
- [x] current vegetation method
- [x] extreme_unusual_properties/heavy metals method
- [ ] #584
- [ ] #678
- [ ] #679
- [ ] soil_taxonomic/local classification	(https://github.com/microbiomedata/nmdc-schema/issues/585)
- [ ] #585 
- [x] history/previous land use method	
- [x] history/previous land use	
- [x] mean seasonal precipitation	
- [x] slope gradient	
- [ ] #680
- [ ] soil texture method	
- [ ] soil type method (https://github.com/microbiomedata/nmdc-schema/issues/585)	
- [x] water content	
- [x] water content method	
- [x] pH method	
- [x] microbial biomass	
- [x] microbial biomass method	
- [x] total carbon	
- [x] total nitrogen content	
- [x] total nitrogen content method	
- [x] total organic carbon	
- [x] total organic carbon method	
- [x] salinity method	
- [x] composite design/sieving	
- [x] #586
- [x] gaseous environment	
- [x] watering regimen	

Note that @mslarae13 will need to help with content for all of these terms, then coordinate with @turbomam to update appropriately.
FYI @ssarrafan

**Comment by turbomam** [comment]
Wow! That's a lot!  Adding annotations to those slots will make the schema much better!

Many of those slots come from MIxS. Ideally any annotations that are prepared for them would go straight to the GSC. If there's a concern that the turn around time would be too slow, I recommend that @mslarae13 or any other contributors make a copy of the [MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=178015749) Google Sheets and enter their annotations there. It will be easy to do a diff between our version ans their version. If they decide to accept them, then it will already be in a suitable format. If they reject them or if the process starts dragging on too long, it will be easy to feed the annotations into [sheets-for-nmdc-submission-schema](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1136864036), the input for our submission portal schema.

Here's some [notes about the LinkML slots that currently appear in the DH help dialogs](https://github.com/microbiomedata/nmdc-schema/issues/373#issuecomment-1204651572), which include the catch-all "Guidance" section.

**Comment by mslarae13** [comment]
See also 
https://github.com/microbiomedata/nmdc-schema/issues/374

**Comment by ssarrafan** [comment]
Related to #https://github.com/microbiomedata/nmdc-schema/issues/373

**Comment by ssarrafan** [comment]
@mslarae13 do you want this issue in the next sprint?  Next sprint is very short due to the retreat.

**Comment by ssarrafan** [comment]
@mslarae13 I'm removing this one from the sprint until there is a plan to work on it.

**Comment by mslarae13** [comment]
@ssarrafan  can you add this to the sprint starting Monday?

**Comment by mslarae13** [comment]
I'm using "comments" in LinkML to capture what should be in "guidance" on the submission portal

**Comment by mslarae13** [comment]
Progress / commit tracking

Missing guidance text and example text:

- [ ] sample shipped amount
- [ ]  number technical replicate
- [ ]  history/extreme events
- [ ]  history/fire
- [ ]  history/flooding
- [ ]  filter method
- [ ]  experimental factor- other
- [ ]  non-microbial biomass
- [ ]  non-microbial biomass method
- [ ]  microbial biomass carbon
- [ ]  microbial biomass carbon method
- [ ]  microbial biomass nitrogen
- [ ]  microbial biomass nitrogen method
- [ ]  organic nitrogen method
- [ ]  other treatments
- [ ]  isotope exposure/addition

Missing example text:

- [ ] replicate number
- [ ]  slope aspect
- [ ]  extreme_unusual_properties/Al saturation
- [ ]  extreme_unusual_properties/Al saturation method
- [ ]  mean annual precipitation
- [ ]  current vegetation
- [ ]  current vegetation method
- [ ]  extreme_unusual_properties/heavy metals method
- [ ]  horizon method
- [ ]  link to classification information
- [ ]  link to climate information
- [ ]  soil_taxonomic/local classification
- [ ]  soil_taxonomic/local classification method
- [ ]  history/previous land use method
- [ ]  history/previous land use
- [ ]  mean seasonal precipitation
- [ ]  slope gradient
- [ ]  soil texture measurement
- [ ]  soil texture method
- [ ]  soil type method
- [ ]  water content
- [ ]  water content method
- [ ]  pH method
- [ ]  microbial biomass
- [ ]  microbial biomass method
- [ ]  total carbon
- [ ]  total nitrogen content
- [ ]  total nitrogen content method
- [ ]  total organic carbon
- [ ]  total organic carbon method
- [ ]  salinity method
- [ ]  composite design/sieving
- [ ]  climate environment
- [ ]  gaseous environment
- [ ]  watering regimen

**Comment by mslarae13** [comment]
Submit a GSC ticket for the following when PR approved

- [ ]  history/extreme events
- [ ]  history/fire
- [ ]  history/flooding

**Comment by mslarae13** [comment]
For experimental_factor_other , from Mark
Instead of "this is open text" I would recommend "This column (or field) accepts open-ended text about your sample. We recommend using key:value pairs. Then your keys will be considered for inclusion as future slots/terms in this data collection template."

then some examples could be

value: "sound: oink"
value: "flavor: orange; calories: 100"

**Comment by mslarae13** [comment]
@turbomam 
Do you know why horizon and horizon method are commented out in nmdc.yaml


and horizon is commented out of mixs.yam
https://github.com/microbiomedata/nmdc-schema/blob/c097bfdbf5feae5b1895deb3079f4d2b27e02edf/src/schema/mixs.yaml#L6437

**Comment by mslarae13** [comment]
Is adding an exampel where one does not exists count as changing the slot & it "no longer being the same IRI"? Per the conversation at the metadata sync : https://docs.google.com/document/d/1CDLw4zwD4Z_0dNHyT8nQGey6fDvVd0zQd4cDqG_ulqg/edit?usp=sharing

**Comment by mslarae13** [comment]
@ssarrafan overdue, please add to January 2023 sprint

**Comment by ssarrafan** [comment]
> @ssarrafan overdue, please add to January 2023 sprint

@mslarae13 Are these still in review status? I will move to the next sprint but let me know if it should go to the backlog instead.

**Comment by mslarae13** [comment]
PR has been merged. Any outstanding slots to update have individual issues assigned. Closing this one.
