### ISSUE TITLE
NMDC Schema update

### ISSUE THREAD

**Issue by StantonMartin** [microbiomedata/nmdc-schema#4]
The sediment package parameter tot_carb is not in nmdc.schema.json

**Comment by wdduncan** [comment]
@StantonMartin I add `tot_carb` as a slot to nmdc.biosample. I also regenerated the schema for you to use as testing. The schema is here: https://github.com/microbiomedata/nmdc-schema/blob/main/jsonschema/nmdc.schema.json

The repo is in a bit of flux right now, but the location of the nmdc schema is not going to change. You can use for it validating data.

cc @cmungall
