### ISSUE TITLE
nesting or relating slots in schema

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#402]
we have unique slots to capture things like 'GOLD sample identifiers' & ' INSDC bioproject identifiers'.

These need to be 'is_a' or linked / displayed and captured as an 'alternative identifier'

@turbomam

**Comment by turbomam** [comment]
@mslarae13 do these documentation pages show the right hierarchy?

- https://microbiomedata.github.io/nmdc-schema/gold_biosample_identifiers/
- https://microbiomedata.github.io/nmdc-schema/insdc_bioproject_identifiers/
