### ISSUE TITLE
GOLD 'ecosystem' slots at study level

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#403]
Why are the 5 GOLD ecosystem terms captured under study class? https://microbiomedata.github.io/nmdc-schema/Study/ 
Biosample makes sense.  https://microbiomedata.github.io/nmdc-schema/Biosample/ 
But with study is confusing to me.

Should these be deprecated?

* this might be a quick to close issue if I'm just misunderstanding something

@turbomam 
@emileyfadrosh 
@cmungall

**Comment by turbomam** [comment]
Hi, @mslarae13

Yes, it could be confusing. Even worse, nothing's in place to make sure that the biosample GOLD ecosystem paths are compatible with the study GOLD ecosystem paths  

There's some good discussion of this in https://github.com/microbiomedata/nmdc-schema/issues/10

**Comment by aclum** [comment]
@mslarae13  GOLD specifies these terms at the study level
see 
https://gold.jgi.doe.gov/study?id=Gs0161344

**Comment by mslarae13** [comment]
@aclum  so the term that is identified at the study level gets applied to all the biosamples?
Is that true for the lower levels?

Or can biosamples in a study differ from the study?

@turbomam  thanks, I don't think I saw that discussion... still seems weird to me. You can have a pretty wide variation among biosamples depending on your research questions within your study. If the study is assigned, and biosamples.. then that kinda makes sense to me. TO assign at only the study level seems weird.

**Comment by aclum** [comment]
BIosamples classification can be more specific that study. For example

for Gs0161344 we have 
Ecosystem | Environmental
-- | --
Ecosystem Category | Terrestrial
Ecosystem Type | Soil
Ecosystem Subtype | Unclassified
Specific Ecosystem | Unclassified
Ecosystem Path ID | 4212




The biosamples w/in the study have Ecosystem Subtype specified
ex Gb0356235

Ecosystem | Environmental
-- | --
Ecosystem Category | Terrestrial
Ecosystem Type | Soil
Ecosystem Subtype | Tundra
Specific Ecosystem | Unclassified
Ecosystem Path Id | 5950

**Comment by mslarae13** [comment]
Ok. in that case, I think this is fine then. Since we pull it from GOLD and it's at both biosample and study level
