### ISSUE TITLE
create more subslots of alternative_identifiers

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#409]
eg for IMG_taxon_identifier

also make sure there are validation patterns for all of these because the id prefixes attribute is currently "suggestion only"

**Comment by mslarae13** [comment]
Relates to #369 . 369 will inform what additional slots are needed.
Success for this ticket looks like
- slots to capture common alternate identifiers are created and added to the schema.
- all slots have clear descriptions, examples, and validation / syntax requirements
- Slots are clearly connected / the identifiers hierarchy is well laid out (example, a GOLD biosample identifier IS an alternate_identifier... but could also have alternate_identifiers that are less commonly used)
- Projects in the data portal / mongoDB are updated to correctly reflect the new ordering of alternative_identifiers & each alternative_identifier is in the correct slot (when source slots are greated, like INSDC).

**Comment by turbomam** [comment]
made slots for emsl and img biosample identifiers

this will be an ongoing task

**Comment by aclum** [comment]
this is marked done on the squad board so closing this issue.
