### ISSUE TITLE
Concrete identifiers action: intrinsic or linking externally

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#439]
We have lots of good issues and documents about identifiers.

I will try to help by making a diagram of their hierarchy.

Along with reviewing the existing hierarchy, I am requesting that we designate identifiers as 
- primary/required or secondary
- intrinsic (like my social security number refers to me) vs linking to something externally
  - you could say that my `employer_id` is ROR:02jbv0t02, where 'ROR': expands to https://ror.org/, for an expanded `employer_id` value of https://ror.org/02jbv0t02

Even though we might include an `employer_id` slot for a person class, it's really not an intrinsic identifier of the person.

**Comment by mslarae13** [comment]
@turbomam feel free to use the mural board for this diagram. (see slack)

When you say intrinsic or linking externally, do you mean generating a good description and use cases for each?

**Comment by mslarae13** [comment]
I think I made this diagram? In the lucid chart: https://lucid.app/lucidchart/811029cb-a93e-436a-a997-3faba459497c/edit?viewport_loc=435%2C-1109%2C1802%2C935%2C0_0&invitationId=inv_46ca52cd-6253-4c5d-a913-e8d6df360a42# 

Is that what you were looking for? LMK what I can add to satisfy this ticket

**Comment by turbomam** [comment]
OK, we already have the "external_database_identifiers" slot. We should just streamline that slots heirarchy.
