### ISSUE TITLE
remove mermaid diagrams until they are more useful

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#440]
more useful =
- showing class to class relationships
- not showing a multi-page box of slots for huge classes like Biosample

**Comment by sujaypatil96** [comment]
* The class to class relationships seems to be satisfied now?
* Not showing a huge box of all slots when the number of slots is too large hasn't been satisfied yet, and I'll work on it

**Comment by kheal** [comment]
Closing this.  Mermaid diagrams looking real nice on the documentation for the schema!
