### ISSUE TITLE
improve docs pages so that team members can get oriented

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#442]

**Comment by turbomam** [comment]
see also https://github.com/linkml/linkml/issues/938

**Comment by turbomam** [comment]
Sorry, @sujaypatil96 I have sent you details about this task but not in an organized way. Can you plese take responsibility for gathering whatever note you can find to make the issue more concrete?

**Comment by ssarrafan** [comment]
@sujaypatil96 is it safe to assume that this issue can be closed based on the check in earlier and your work on https://docs.google.com/document/d/1qnpD90FEnbj98FY3OH-PXRKyxhaFGvGalkuUL591D5I/edit#

**Comment by turbomam** [comment]
Sorry, I should have been more specific about the deliverables for this task. Let's determine what is complete and what will continue into the next sprint.

- [ ] all per-term pages should display all attributes of that term in an intuitive way
- [ ] LinkML source should be included
- [ ] both is_a and mixin hierarchy should be displayed with trees
- [ ] both inbound and outbound slot/class relationships should be displayed
  - [ ] if class C declares that it uses slot S (an inbound relationship), then the page for S should show that relationship
- [ ] the NMDC documentation pages, esp. the Jinja2 templates, should be maximally aligned with other LinkML documentation sites, like MIXS and the LinkML metamodel
  - [ ] we should have a plan to maintain that alignment

**Comment by ssarrafan** [comment]
Discussed at squad meeting and will move to the next sprint. @sujaypatil96 let me know if it would be helpful to break this up into multiple issues.

**Comment by sujaypatil96** [comment]
See: https://github.com/linkml/linkml/pull/990

**Comment by sujaypatil96** [comment]
Current status:

* NMDC Schema: all above checklists ticked
* MIxS Schema: all except fourth checkbox, see https://github.com/GenomicsStandardsConsortium/mixs/pull/509
* Propagated most changes, except fourth checkbox to linkml upstream

**Comment by turbomam** [comment]
@sujaypatil96 this was tagged as `small` and `high priority`

Do those need to be revised?

Please provide an update, preferably using [this comment's](https://github.com/microbiomedata/nmdc-schema/issues/442#issuecomment-1267268889) check-boxes

**Comment by ssarrafan** [comment]
Since there appears to be a few unchecked boxes I'll move this to the next sprint for completion.  @sujaypatil96 let me know if you don't plan to work on this during the next week or so.

**Comment by sujaypatil96** [comment]
Status check:

* make the jinja templates so that we don't have to explicitly add attribute rendering every time there's a new constraint added to an existing slot

**Comment by turbomam** [comment]
There was good progress on this issue for the immediate needs of NMDC identifiers documentation, but we have though of additional opportunities to improve documentation. @sujaypatil96 I think you can sloe this issue if you add some more in any repo of your choice.

**Comment by ssarrafan** [comment]
Great news! @sujaypatil96 I am closing this one per Mark's note above.
