### ISSUE TITLE
Totally omit a class' mermaid diagram if there are more than n slots

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#453]
Possible N = 60 (or whatever fits vertically on one average screen)

In the future, we might think about ways to show the structural part of the mermaid diagram without the slots, but just omitting diagrams with excessive slots is a good start.

**Comment by turbomam** [comment]
see also https://github.com/microbiomedata/nmdc-schema/pull/441

**Comment by turbomam** [comment]
see also:
- https://github.com/microbiomedata/NMDC_documentation/issues/10

**Comment by sujaypatil96** [comment]
In this issue we're saying that we should use one parameter, the total number of slots associated with a class to decide whether the Mermaid UML diagram should be rendered on a class documentation page or not.

I'm proposing that we add three more parameters to make this decision. They are:
* Number of edges between given class (in consideration) and `is_a` parents
* Number of edges between given class (in consideration) and `is_a` children
* Number of edges between given class (in consideration) and other classes that are linked/associated based on a slot

**Comment by sujaypatil96** [comment]
The above has been implemented in PR #1625 in `class_diagram.md.jinja2`
