### ISSUE TITLE
create command-line utility to retrieve jsonschema

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#46]
Provide a command-line utility to retrieve the jsonschema from the `nmdc-schema` pypi package.

cc @cmungall @dehays

**Comment by ssarrafan** [comment]
Adding backlog label. Needs to be reprioritized.

**Comment by cmungall** [comment]
can we close this?

**Comment by ssarrafan** [comment]
> can we close this?

Is it done @cmungall?  We had removed it from a sprint because Bill didn't have time to work on it. Happy to close if it's done or not needed.

**Comment by turbomam** [comment]
src/nmdc_schema/get_json_schema.py
