### ISSUE TITLE
annotate biosample_category_enum's permissible values

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#467]
@emileyfadrosh and @mslarae13 you can certainly delegate this task to other people. Let me know what I can do to help.

I have added a `biosample_category_enum` and the `permissible_values` we discussed this week.

Policy-wise, they **must** be reasonably annotated with some of the [slots assigned to PermissibleValues](https://linkml.io/linkml-model/docs/PermissibleValue/#slots). 

These would probably be good choices:
- [description](https://linkml.io/linkml-model/docs/description/)
- [title](https://linkml.io/linkml-model/docs/title/)
- [see_also](https://linkml.io/linkml-model/docs/see_also/) (range=**list** of URLs)

You could also assign one URL `meaning` or multiple URLs to `mappings`, but those should be URLs for semantic/ontological terms defined elsewhere. In other words, if you have a URL for a related homepage or a helpful page of documentation, that should go in `see_also`, **not** `meaning` or `mappings`

**Comment by emileyfadrosh** [comment]
I am closing this as I believe this is a very old ticket, and the relevant activities are captured in other tickets. Thanks and please reopen if you disagree and provide additional details. Thanks!

**Comment by turbomam** [comment]
Thanks for the curation @emileyfadrosh.

This task is not complete.

**Comment by turbomam** [comment]
I would say that including `SIP` as a permissible value here is really problematic. If we remove it, then the semantics of this enumeration is much clearer: some `Biosample`s (and maybe other class instances) can part of one of these 
- LTER
- SFA
- FICUS
- NEON

But a Biosamples can't be part of `SIP`. Also, the entry for SIP is totally unannounced.

Let's remove `SIP` from this list, express the `part_of` nature of the remaining values, and move `SIP` (with different semantics, including annotations) somewhere else.

**Comment by mslarae13** [comment]
I agree, @turbomam  ... I think we should decide if we want biosample_catagories to be general enough for any kind of "tag" you might put on a sample or if we want different types of tags.

SIP is more of a sample type / protocol tag

LTER is a research site (NEON kinda is too)

SFA, FICUS, and NEON are project / award types.

Do we want LOTS of tagging categories? Or one catch all?

**Comment by turbomam** [comment]
see also:
- #481

**Comment by emileyfadrosh** [comment]
Closing this issue, it's been over a year and it looks like other tickets have been created. Thanks!
