### ISSUE TITLE
Add an activity type for the raw data generation

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc-schema#469]
We would like to add some new activity that would correspond to the generation of the raw data.  This would give us a place to capture some critical values (e.g. insert size, basic stats, etc).  Let's use metaG as an example...

Right now the raw sequence data only appears as a `has_input` in the read QC.  This is complicated some of our efforts around automation and splitting up the workflows as more discrete subworkflows.  Having this activity would give us an anchor for some of these details.  It would also make it easier to deal with variations on the input.  For example if we want to allot for split paired-end libraries and interleaved.

One detail I'm not sure about is do we have one generic sequencing activity and then the type (e.g. metaT, metaG) is an attribute or do we want to have difference sequencing activities for each product type.

It would be good to have @emileyfadrosh weigh in here.

**Comment by kheal** [comment]
This has been resolved by the `DataGeneration` class and its subclasses on Berkeley fork.
