### ISSUE TITLE
Study title vs name

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#473]
Currently, the schema has the following slots
 - title
 - alternative_titles
 - alternative_names
 - name

I'm unsure how name and title are different.
Can someone (@sujaypatil96 , @turbomam , @pkalita-lbl ) provide me with some examples of what is currently captured in these slots in MongoDB? (There's no descriptions or examples in the schema)

Correction / completion of this ticket
1. Schema correctly captures how the above are different
  - If they aren't different, one of them is depreciated

**Comment by mslarae13** [comment]
Also. alternative vs alternate... don't care which but we should be consistent

**Comment by dwinston** [comment]
@mslarae13 see https://api.dev.microbiomedata.org/studies for JSON-schema-compliant representations of all 9 studies

**Comment by mslarae13** [comment]
Thanks @dwinston !

I don't see alternative titles or names in there anywhere. I assume we just haven't used it?
title vs name... name appears to be the GOLD study name and title is the study name that is represented on the NMDC data portal.

@emileyfadrosh Do we need to track GOLD study name? Or is just tracking the study ID good? (The GS number)

For alternative, because it appears these aren't used at all. I recommend we retire alternative_name... and keep alternative_title IF needed. @emileyfadrosh , @turbomam , thoughts?

**Comment by emileyfadrosh** [comment]
I would say tracking the GS number is good enough, not the full study name for GOLD. If we don't have alternative names, then we could probably retire as well. 

@mslarae13 @turbomam thoughts?

**Comment by ssarrafan** [comment]
Moving to next sprint to allow for review. @mslarae13

**Comment by ssarrafan** [comment]
@mslarae13 has this one been reviewed yet? Can it be closed?

**Comment by mslarae13** [comment]
I have an answer. See Emiley's response.
Retire name & alternative name. 
Title is displayed on NMDC data portal & should be kept. 
Name = GOLD, and just tracking GS in an alternate ID slot is sufficient. 

Do we need a new ticket for making this correction? Can we just use this one? 
@turbomam , thoughts?

**Comment by ssarrafan** [comment]
@mslarae13 @turbomam I'm moving this over so I can close this old sprint.

**Comment by ssarrafan** [comment]
@mslarae13 @turbomam I'm closing this issue. Please create a new issue to make the correction when you're ready to work on it.

**Comment by turbomam** [comment]
> I would say tracking the GS number is good enough, not the full study name for GOLD. If we don't have alternative names, then we could probably retire as well.
> 
> @mslarae13 @turbomam thoughts?

Yes, the nmdc-schema, as well as data collection and storage tools that adhere to it should emphasize storing IDs for studies, samples etc and leave retrieving the corresponding names/labels to another tool, like the Data Portal. 

Following up on 

> @mslarae13 @turbomam I'm closing this issue. Please create a new issue to make the correction when you're ready to work on it.

Yes, we should have an ongoing process or reconciling the classes and slots used in data storage systems like MongoDB against the classes and slots offered by the schema.
