### ISSUE TITLE
Montana's development environment should be able to run `make all` in the nmdc-schema repo

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#480]
@mslarae13 do you think this has be discussed anywhere else?

I want to make sure the work we do in support of the more visible Deinococcus tasks gets tracked.

**Comment by turbomam** [comment]
We have made a lot of progress thanks to @corilo and others.

To run the 3.2 -> 7.0 migration code, @mslarae13 would need ssh and database credentials for the production mongodb on SPIN, plus a local mongodb on her laptop. We may be able to skip that for now.

**Comment by ssarrafan** [comment]
@turbomam @mslarae13 is this done?  I thought I heard on a call that she was all set up now.
