### ISSUE TITLE
Add Napa Protocol `id` pattern to schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#493]
cc @dwinston @cmungall @sujaypatil96 @mslarae13 @scanon

**Comment by turbomam** [comment]
per-class `id` induced attributes report can be generated with `nmdc-schema/util/id_usage.py`

`id` `pattern`s haven't been asserted for any classes yet

Excerpt:

> INDUCED id ATTRIBUTE FOR Activity:
> name: id
> description: A unique identifier for a thing. Must be either a CURIE shorthand for
>   a URI or a complete URI
> from_schema: https://microbiomedata/schema/basic_slots
> multivalued: false
> identifier: true
> alias: id
> owner: Activity
> domain_of:
> - Biosample
> - Study
> - NamedThing
> - Activity
> range: string
> 
> 
> 
> CLASS Agent DOESN'T USE THE id SLOT
> 
> 
> CLASS AttributeValue DOESN'T USE THE id SLOT
> 
> 
> INDUCED id ATTRIBUTE FOR Biosample:
> name: id
> description: An NMDC assigned unique identifier for a biosample submitted to NMDC.
> from_schema: https://microbiomedata/schema/basic_slots
> multivalued: false
> identifier: true
> alias: id
> owner: Biosample
> domain_of:
> - Biosample
> - Study
> - NamedThing
> - Activity
> range: string
> required: true

**Comment by dwinston** [comment]
copying from @turbomam's NMDC slack post to faciliate extended discussion here:

abstraction:
```
prefix:typecode-authshoulder-blade(.version)?(_seqsuffix)?
```

regex:
```
^nmdc:[A-Za-z0-9]{1,6}-[A-Za-z0-9]{1,6}-[A-Za-z0-9]{1,6}(\.[A-Za-z0-9]{1,6})?(_.+)?$
```

**Comment by dwinston** [comment]
FYI I started a draft spec (just boilerplate for now) using https://respec.org/docs/ and put it in this repo as `docs/napa-protocol.html` ([snapshot](https://github.com/microbiomedata/nmdc-schema/blob/66b401ab30fd6e0110414813a20e879c29487c4f/docs/napa-protocol.html)), so visible as <https://w3id.org/nmdc/napa-protocol.html>. Will be good to have such a document to guide implementation.

**Comment by turbomam** [comment]
I love the railroad diagram and hope I won't forget about it. But it's time to close this generally satisfied issue.
