### ISSUE TITLE
Replace "An NMDC assigned unique identifier for a sample submitted to NMDC." description for `id` in `Study`

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#494]
@mslarae13 The GitHub "blame" view shows that you updated the description for `id` in class `Study` (in `src/schema/nmdc.yaml` to "An NMDC assigned unique identifier for a sample submitted to NMDC."

https://github.com/microbiomedata/nmdc-schema/blame/issue-493-napa-ids/src/schema/nmdc.yaml#L521

I think we should change that. Are you willing to do that, or should I? (Or we could do it together.)

**Comment by mslarae13** [comment]
@turbomam  I think you fixed this for me, right? If not, I recall a meeting where I said it was probably a novice accident. (Noob probs).

Does this still need fixed?

**Comment by turbomam** [comment]
No, I didn't fix that yet. Thanks for the reminder.
