### ISSUE TITLE
ValueError: : Unknown CURIE prefix: @base from RDF conversion

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#502]
```shell
poetry run linkml-convert \
		--output data_7.ttl	\
		--target-class Database \
		--schema src/schema/nmdc.yaml data_7.json
```

see also #500

**Comment by turbomam** [comment]
Not a problem if only `Study`s are instantiated

**Comment by turbomam** [comment]
RDF dumping works after adding the following to the `if collection_name == "data_object_set"` section of `util/migrate_7.py`:

```python
if ":" not in document['id']:
    logger.error(f"illegal document id: {document['id']}")
    document['id'] = f"bare:{document['id']}"
```

(Along with defining the `bare` prefix in `src/schema/nmdc.yaml`)

**Comment by aclum** [comment]
@turbomam  can this be closed? RDF conversion is working now.
