### ISSUE TITLE
Production NMDC MongoDB's `data_object_set collection` has illegally un-prefixed documents

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#503]
like `{id: '60e6fc9e49af89de1ba8999f'}`, as opposed to the legal`{id: 'emsl:output_448392'}`

@dwinston , do you know what person or software agent inserts into the `data_object_set` collection

**Comment by turbomam** [comment]
see also #502

**Comment by dwinston** [comment]
The deployed nmdc-runtime instance does insertions on behalf of users via its API, and currently such documents would be considered valid as the runtime uses only raw JSON Schema checking for validation and a DataObject.id need only be a string currently: https://github.com/microbiomedata/nmdc-schema/blob/v7.0.0/jsonschema/nmdc.schema.json#L1450

We should remedy this to require `id` be of a curie form.

**Comment by aclum** [comment]
This will be address with the reid squad so should be resolved by the end of the year.

**Comment by aclum** [comment]
Resolved by re-iding. There are no longer any data objects that don't have a prefix.
