### ISSUE TITLE
MongoDB repair vs Kitware ingest into Postgres

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#506]
From Mike Nagler, 2022-11-02:

> Hey Mark, thanks for updating the mongo dump. I'm still seeing some issues come up during ingest that I'm not sure are caused by more data integrity issues or if the ingest script needs to accommodate these situations.

> To start with, loading from omics_processing_set reveals 24 documents where has_input still contains a biosample ID prefixed with gold. I see no biosamples with a gold ID in mongo. The documents where this is true can be found with the mongo query: db.omics_processing_set.find({id: /gold:Gp02083.*/}). Additionally, there are some (21) documents where entries in the has_output array contain data_object IDs with no corresponding data_object in the data_object_set. An example is the omics_processing document with ID emsl:598849. The output data object with ID emsl:output_598849 does not appear to exist.

> Also, the ingest process is reporting lots of missing documents for metabolomics_analysis, metatranscriptome_activities, NOM_analysis, mags_activity, metaproteomic_analysis, and metagenome_assembly. Some are reporting missing data objects, but the majority of these broken links appear to be with omics_processing records. I can confirm that the number of ingeseted omics_processing records matches the number in the mongo dump you gave me (1927). For example, metabolomics_analysis with id nmdc:8969f454c3944f1eac9da499fb950a18 has a value emsl:646802 in the was_informed_by slot. The ingest script looks for a row in the omics_processing table for a matching ID, and fails to find one. I can also confirm that there is no such document in the omics_processing_set collection.

> There are about 500 of these "missing" records. Is that because I'm working with a subset of the total data, or is something else the issue here?

**Comment by turbomam** [comment]
Also dumped to RDF #502 for multi-collection querying and visualization.

**Comment by aclum** [comment]
Old enough that I'm assuming this was resolved.
