### ISSUE TITLE
additional optional attributes to be added to study

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-schema#51]
part of decomposition of #41 

To be added to study entity as optional attributes.  These are not currently available from GOLD studies and therefore cannot presently be populated from the GOLD -> NMDC ETL

- [x] study DOI
- [x] study websites
- [x] publication DOIs
- [x] proposal name
- [x] scientific objective

**Comment by wdduncan** [comment]
@dehays every `study` object has a `name` attribute. Is `proposal name` different than the study's name?

**Comment by wdduncan** [comment]
@dehays `study` already has a `doi` attribute:
```yaml
study:
    is_a: named thing
    in_subset: 
      - sample subset
    aliases: ['proposal', 'research proposal', 'research study', 'investigation']
    description: >-
      A study summarizes the overall goal of a research initiative and outlines the key objective of its underlying projects.  
    slots:
      - ecosystem
      - ecosystem_category
      - ecosystem_type
      - ecosystem_subtype
      - specific_ecosystem
      - principal investigator name
      - doi
```
But, the range of `doi` is an attribute value; e.g.:
```json
"doi":  { "has_raw_value": "10.25585/1487764" }
```
Do we need `doi` to be a list (i.e., multi-valued), or will a study only have one `doi`?

**Comment by dehays** [comment]
@wdduncan  On GOLD study name vs proposal name - I want to touch base with Emiley and Jeff with what we do here.  What I see is the the UI is using the proposal name [Stegen Study - notice the name displayed](https://data.microbiomedata.org/details/study/gold:Gs0114663) which is not something you are getting from GOLD (The name in the study entity is set to the GOLD study name, for example: "Groundwater microbial communities from the Columbia River, Washington, USA".  I think we are going to need to add another name - not sure proposal name should be the key, perhaps display_name.  But since it is not coming from GOLD it would need to be optional for the ETL to produce valid output.

I think a study would have a single DOI and as you point out, there is a slot for that.  Publication DOIs would need to be a list.

**Comment by wdduncan** [comment]
Thanks @dehays   
I'm a bit partial to naming the attribute `display name`. It seems to fit the purpose you describe.

What do you think @cmungall ?

**Comment by cmungall** [comment]
GOLD:

https://gold.jgi.doe.gov/study?id=Gs0114663

 * study name: E.g. _Groundwater microbial communities from the Columbia River, Washington, USA_
 * other names: E.g. _Microbial communities from the groundwater-surface water interaction zone near Columbia River, Washington, USA and their role in carbon and contaminant biogeochemistry_
 * description: E.g. _A metagenomic study to couple microbial communities to carbon and contaminant biogeochemistry in the groundwater-surface water interaction zone_
 * relevance: E.g. _Carbon cycle, Environmental, Bioremediation_

MIxS:

MIxS standardizes fields for samples not studies, but it doesn't follow normal form and does have repeated investigation variables such as project_name. project_name is underspecified, and if we look at existing values in INSDC they are all over the place. It ranges from "16S" to proper titles.

NCBI BioProject:

the study is broken into multiple projects 1 per sample, with identical metadata

https://www.ncbi.nlm.nih.gov//bioproject/PRJNA367315
...
https://www.ncbi.nlm.nih.gov//bioproject/PRJNA367318

Groundwater microbial communities from the Columbia River, Washington, USA - GW-RW S3_40_50 metagenome

Coupling Microbial Communities to Carbon and Contaminant Biogeochemistry in the Groundwater-Surface Water Interaction Zone

Relevance: Environmental

(Remediation and Carbon cycle seem to have been dropped)

NMDC:

https://data.microbiomedata.org/details/study/gold:Gs0114663

Coupling Microbial Communities to Carbon and Contaminant Biogeochemistry in the Groundwater-Surface Water Interaction Zone
Description A metagenomic study to couple microbial communities to carbon and contaminant biogeochemistry in the groundwater-surface water interaction zone

Scientific objective
To understand and predict the effects of variable groundwater-surface water mixing on microbial communities and, in turn, biogeochemical rates under the Subsurface Biogeochemical Research-Science Focus Area (SBR-SFA).

Not sure where objective is coming from, it's not in the schema or the json? Hardcoded in the UI?

My proposal:

 * study.title:
    * required, single-valued
    * SHOULD follow scientific norms for publication titles and should briefly communicate what was studied, possibly why
    * mappings:
        * exact: dcterms:title
        * exact?: gold:study.study_name
        * broad: mixs.project_name
 * study.description:
    * optional, single-valued
    * A rich free text description, roughly following norms for an abstract
    * mappings
        * dcterms:description
        * gold:study.description
 * study.alt_description:
    * optional, multi-valued
    * An alternative description
    * mappings:
        * dcterms:alternative
        * gold:study.other_names
 * study.objective:
    * optional, single-valued
    * the scientific objectives. Should correspond to scientific norms for objectives field in a structured abstract
    * mappings:
        * SIO:000337
* study.keywords
   * optional, multi-valued
   * A collection of index keywords. SHOULD come from controlled vocabularies, including MESH, ENVO
   * mappings:
       * dcterms.subject
       * broad: gold:study.relevance


TBD: should we have separate fields for doi, ark, etc, or just a generic citation field that takes a CURIE or PURL? My pref is the latter

**Comment by wdduncan** [comment]
I agree with @cmungall  that `title` addresses the need to distinguish between what we get out of GOLD and what the `study` is called from the perspective of a funding agency. 

A related issue to this is the long names we get out of gold for `biosamples`. I'm not so sure that `title` is the appropriate slot for shortening the GOLD biosample names, although we can use it for such a purpose. It might be better to have a `display name` slot, or perhaps we make use of `alternative description`.

We can also make use of an `other_names` slot, although I prefer to call it `alternative names` (this seems more consistent with `alternative identifier` and `alternative description`).

If we follow the suggestion of have a generic citation field to cover doi, ark, etc what do call it? `citations`? Also, do we need to create a `citation` object so that we specify if it is a doi etc.? We can do this, but I am unsure if the cost of doing so is worth the effort.

**Comment by wdduncan** [comment]
@dehays I've added the following slots to `nmdc:study`:

- title
- alternative titles
- alternative descriptions
- alternative names

I think/hope this should cover Kitwares needs for displaying the name of a study.

**Comment by wdduncan** [comment]
Update after metadata call:
There is a need to associate studies with websites. Should I add a `websites` slot, or make use of the existing `url` slot in `core.yaml`:
```yaml
url:
    is_a: attribute
    range: string
```

**Comment by wdduncan** [comment]
`publication DOIs` is simply names `publications`.
