### ISSUE TITLE
Add concept of sample grouping to NMDC schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#518]
In order to import data from the Bioscales project the schema needs to be updated to allow for the concept of sample groupings. Using Bioscales as an example, for the sequencing side of the project, there were three samples taken from the same tree so we want those be shown as related samples in the data portal.  For this to happen first the schema needs to be updated.

Example:
From tree name 'BESC-13-CL1_35_33' three samples from endopshere, rhizosphere, and soil were collected generating 3 GOLD Biosamples and 3 GOLD Bioprojects

[Gb0305833](https://gold.jgi.doe.gov/biosample?id=Gb0305833) [Gp0587733](https://gold.jgi.doe.gov/project?id=Gp0587733)
[Gb0291692](https://gold.jgi.doe.gov/biosample?id=Gb0291692) [Gp0566756](https://gold.jgi.doe.gov/project?id=Gp0566756)
[Gb0291582](https://gold.jgi.doe.gov/biosample?id=Gb0291582) [Gp0566632](https://gold.jgi.doe.gov/project?id=Gp0566632)

Bioscales is the highest priority dataset to have imported for GSP and @mslarae13  said this will also unblock import for other projects.

**Comment by turbomam** [comment]
This makes sense. It will require more explicit semantics, like a clearer label for the field and an explicit assertion of what classes are in the domain and range of this relationship.

**Comment by turbomam** [comment]
The Bioscales issue of relating samples that came from or around the same tree has been solved with `collected_from` -> some `FieldResearchSite`.
