### ISSUE TITLE
merge in migration script etc.

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#541]

**Comment by eecavanna** [comment]
Issue cleanup: I don't know what, specifically, this issue is referring to. It looks to me like it's done.

**Comment by kheal** [comment]
Closing this.  Several migration scripts are merged in and the migrations team have a good handle on the scripts and order in which they need to be run.

**Comment by eecavanna** [comment]
Thanks, @kheal. This ticket was opened before the migration squad started formalizing the migration process. I don't know what it referred to. Anyway, I am OK with it being closed.
