### ISSUE TITLE
support remote destination databases for schema migration

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#544]
I'm being vague here since this is a public repo

Create tunnels like this:

```
ssh \
    -i <KEY_PATH> 
    -L<LOCAL_PORT>:<MONGO_ADDRESS>:<REMOTE_PORT> <USER>@<LOGIN_ADDRESS> < \
    '/bin/bash -c "while [[ 1 ]]; do echo heartbeat; sleep 300; done"'
```

Then the redirected MongoDB will appear on `localhost:<LOCAL_PORT>`

the key can be obtained with NERSC's [sshproxy](https://www.nersc.gov/assets/Uploads/Using-sshproxy.pdf)

Mark had been running his destination MongoDB directly on localhost:27777

We now have two hosted MongoDBs: old (essentially prod) and new (essentially dev) MongoDB servers

The new one replaces the `nmdc-runtime-dev` portion of the old servers address with `nmdc-dev`

The general pattern has been to redirect the server's port 27017 to local 27027, but connectiosn to more MongoDBs will require more port forwarding!

Port|TCP|UDP|SCTP|DCCP|Description
-- | -- | -- | -- | -- | --
27000 | Unofficial |   |   |   | PowerBuilder SySAM license server
27000–27006 |   | Unofficial |   |   | id Software's QuakeWorld master server
27000–27009 | Yes | Yes |   |   | FlexNet Publisher's License server (from the range of default ports)
27000–27015 | No | Unofficial |   |   | Steam (game client traffic)[376]
27015 | No | Unofficial |   |   | GoldSrc and Source engine dedicated server port[376]
27015–27018 |   | Unofficial |   |   | Unturned, a survival game
27015–27030 | No | Unofficial |   |   | Steam (matchmaking and HLTV)[376]
Unofficial | Unofficial |   |   | Steam (downloads)[376]
27016 | Unofficial |   |   | Magicka and Space Engineers server port
27017 | Unofficial | No |   |   | **MongoDB** daemon process (mongod) and routing service (mongos)[377]
27031–27035 | No | Unofficial |   |   | Steam (In-Home Streaming)[376]
27036 | Unofficial | Unofficial |   |   | Steam (In-Home Streaming)[376]
27374 | Unofficial |   |   | Sub7 default.
27500–27900 |   | Unofficial |   |   | id Software's QuakeWorld
27888 |   | Unofficial |   |   | Kaillera server
27901–27910 |   | Unofficial |   |   | id Software's Quake II master server
27950 |   | Unofficial |   |   | OpenArena outgoing
27960–27969 |   | Unofficial |   |   | Activision's Enemy Territory and id Software's Quake III Arena, Quake III and Quake Live and some ioquake3 derived games, such as Urban Terror (OpenArena incoming)

**Comment by turbomam** [comment]
connection string:

```
mongodb://<USER>:<PW>@<HOST>:<PORT>/?authSource=admin&readPreference=primary&directConnection=true&ssl=false

**Comment by turbomam** [comment]
@eecavanna doesn't the migrator implemented in nmdc-schema connect to whatever MongoDBs it needs for source, staging, and target?

If so, I would close this issue.

**Comment by eecavanna** [comment]
Hi @turbomam, 

I'm in favor of this Issue being closed.

The transformation functions in the migrator classes in `nmdc-schema` don't connect to any databases at all. They just deal with Python dicts.

The database connection/usage happens at an external/higher level. In practice, it happens in a Python notebook in `nmdc-runtime`, which gets a document from the database, passes it through the transformation function(s), and puts the transformed version back into the database.
