### ISSUE TITLE
generate OWL output

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#57]
As part of makefile, generate OWL **artefact**.

cc @cmungall @turbomam

**Comment by turbomam** [comment]
On it. Should be good for visualizing issues about slot inheritance, like #402 and #410

@sujaypatil96 I'm going to put a free-standing OWL generation step in the Makefile. We should integrate that into the existing generation patterns in the Makefile, or maybe switching to gen-project could be part of an overall repo refactor like we were discussing yesterday.

**Comment by turbomam** [comment]
Start over after having closed messy PR 
- #425

**Comment by turbomam** [comment]
owl is now generated in the cookiecutter integration branch `issue-658-team-cookiecutter`
