### ISSUE TITLE
Use MIxS `samp_taxon_id` to model NCBI taxonomy ID from GOLD?

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#574]
Add a slot called `ncbi_taxon_id` to capture the host taxonomy ID as present in GOLD, and other sources possibly.

For example, let's look at `Gb0291745` on the GOLD website: https://gold.jgi.doe.gov/biosample?id=Gb0291745

Look under the Host Metadata section, and you'll see a value of 3689 associated with the host taxonomy ID.

We need a slot under the Biosample class to capture this information. In this issue, I'm proposing the addition of a slot called `ncbi_taxon_id` generally, and asserting its usage in the Biosample class using it's `slots` property.

**Comment by sujaypatil96** [comment]
Comments from discussion with @turbomam:

There is a slot in MIxS called [specific_host](https://genomicsstandardsconsortium.github.io/mixs/0000029/) already, which models the taxonomy name or id.

We have two approaches here:
* make changes to the `mixs.yaml` file in nmdc-schema repo, add in `specific_host` slot, import that into `Biosample` class in `nmdc.yaml` and constrain `specific_host` under the `slot_usage` for `Biosample`
* add a new slot in `nmdc.yaml` called `ncbi_taxon_id` which is inherited from `specific_host` using the `is_a` property, constrain the slot and then assert it on the `Biosample` class

**Comment by ssarrafan** [comment]
@sujaypatil96 is this something you're currently working on?  Can I add it to the sprint board for January?

**Comment by sujaypatil96** [comment]
Model this similar to ENVO terms. Followup with GSC to figure out why there are three similar terms for taxon id.

**Comment by sujaypatil96** [comment]
Following up on this, the three MIxS terms with confusing definitions are:
* specific_host: https://genomicsstandardsconsortium.github.io/mixs/0000029/ 
* host_taxid: https://genomicsstandardsconsortium.github.io/mixs/0000250/ 
* samp_taxon_id: https://genomicsstandardsconsortium.github.io/mixs/0001320/

**Comment by ssarrafan** [comment]
@sujaypatil96 I'll move this to the next sprint but let me know if you won't be actively working on it for the next couple of weeks

**Comment by sujaypatil96** [comment]
@ssarrafan yup, we plan to address this at the metadata call today.

**Comment by mslarae13** [comment]
> * samp_taxon_id

Agree, samp_taxon_id is the right slot. This is NOT collected by the user or in the submission portal, but I think that’s fine. This can just be a GOLD assigned field



> * specific_host: https://genomicsstandardsconsortium.github.io/mixs/0000029/
> * host_taxid:

These descriptions are more or less forward and reverse, so how they're different is unclear, but I think this is a different issue.

**Comment by turbomam** [comment]
Thanks for the notes, @mslarae13 

A couple of questions:

1. You're suggesting that there wouldn't be any column for `samp_taxon_id` in the Submission Portal. How would that relate to our vision of gathering sample metadata in bulk form external sources (like GOLD) and then loading it into the submission portal for a "data wrangler" to check?
2. what does "descriptions are more or less forward and reverse" mean?
3. Could the last two lines in your comment be summarized as below?

---

- NMDC will populate `samp_taxon_id` slots for `Biosample`s by composing the `ncbiTaxName` and `ncbiTaxId`. For the taxon identifier portion, MIxS implies a syntax of `^NCBI:txid[0-9]+` like 'NCBI:txid749906' but instead NMDC will follow the syntax used by the OBO foundry, `^ NCBITaxon:[0-9]+` like 'NCBITaxon:749906'
