### ISSUE TITLE
Update JGI Plate well description

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#580]
Currently, the description for plate well is 
"Required when 'plate' is selected for container type. Corner wells must be blank. For partial plates, fill by columns. Leave blank if the sample will be shipped in a tube."

Should be 

"Required when 'plate' is selected for container type. Corner wells must be blank. For partial plates, fill by columns. Provide "NA" if the sample will be shipped in a tube."

Completion involves updating the schema and merging the change into main.

**Comment by mslarae13** [comment]
@turbomam 
When the schema is updated, the submission portal schema updates, and an ingest (?) triggers the update to the submission portal. Right?

**Comment by ssarrafan** [comment]
@mslarae13 @turbomam is this issue being actively worked on?

**Comment by ssarrafan** [comment]
Haven't heard back so removing from sprint

**Comment by turbomam** [comment]
This is a reasonable issue, but 

> Required when 'plate' is selected for container type. Corner wells must be blank. For partial plates, fill by columns. Provide "NA" if the sample will be shipped in a tube.

isn't a description. We should create an actual description and capture this kind of knowledge in comments.

Blank entries are allowed now so I wouldn't recommend entering 'NA'. In fact, I don't think NA will validate.

There's a [DataHarmonizer issue](https://github.com/cidgoh/DataHarmonizer/issues/370) to address an implementation that won't require this workaround at all. But I don't think there's any development on that yet. I haven't created the necessary rule in the schema yet either.

**Comment by turbomam** [comment]
I'm starting to work on this now. You're talkinga bout slot `dna_cont_well`, right?

**Comment by turbomam** [comment]
@sujaypatil96 pointed out that the place that text appears in the Data Portal is in the `Guidance`, which sources its content from an element's `description` and `comments`!

**Comment by turbomam** [comment]
Comments and rules have been written to address this. Enforcement of the rules in DataHarmonizer has not been, but has been raised as an issue in the DataHarmonizer issue tracker.
