### ISSUE TITLE
Register EMSL project prefix on identifiers.org

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-schema#59]
I recommend registering `EMSL.project` as a prefix just in case the same 5 digit number is reused for other entities, e.g. metabolites.

It looks like the redirect should be to:

https://search.emsl.pnnl.gov/?project[0]=projects_$LocalID

E.g.

https://search.emsl.pnnl.gov/?project[0]=projects_51283

is this correct @SamuelPurvine

See https://microbiomedata.github.io/nmdc-schema/identifiers/

Note: once registered with identifiers.org it should percolate out to n2t, bioregistry, prefixcommons, ...

**Comment by SamuelPurvine** [comment]
Wow, I never saw that this was assigned to me, apologies! I'm fairly certain I do not have anything like the level of paygrade to register anything having to do with EMSL onto an external resource. Certainly I would need to work with @lamccue about this. I know when we discussed having someone at Kitware do this there was pretty strong pushback.

**Comment by turbomam** [comment]
https://bioregistry.io/registry/emsl.project

see also
- https://github.com/microbiomedata/nmdc-schema/issues/1139
