### ISSUE TITLE
test if biosmaple_set from gold_nmdc_pipeline.py passes 7.1.6 validation

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#590]
See https://github.com/microbiomedata/sample-annotator/blob/main/sample_annotator/clients/gold_nmdc_pipeline.py

**Comment by sujaypatil96** [comment]
Latest JSON output that can be generated after running the updated transformation script here: https://github.com/microbiomedata/sample-annotator/pull/113 does in fact pass v7.1.6 validation.

**Comment by turbomam** [comment]
> does in fact pass v7.1.6 validation

Unfortunately, the validation isn't catching cases in which the nmdc prefix has been used with GOLD local ids.

**Comment by aclum** [comment]
@sujaypatil96  can this be closed?
