### ISSUE TITLE
nmdc minted identifiers 'view level'

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#607]
NMDC minted identifiers will be applied across all nmdc-schema classes. Some identifiers will be 'user facing'. Which mean the user will see or intereact with the assigned identifiers. 

In some instances, assigned identifiers may never be seen by a user. We should add this context to the schema as well as when the various identifiers will be encountered.

See here for the typecodes that will be used in identifiers. 
 https://microbiomedata.github.io/nmdc-schema/typecode_table/ 

Criteria for completion
- [ ] Identify how to label identifiers / type codes as 'user facing'
- [ ] Identify and assign 'visibility' levels for the typecodes / identifiers. (for example, Biosample IDs will definitely be user facing, ChemicalEntity may not?)
- [ ] Update schema with this information.

**Comment by aclum** [comment]
@mslarae13 is this ticket still applicable? All nmdc minted identifiers are technically available via the API.

**Comment by mslarae13** [comment]
I don't even remember what this was referring to in specifics... so yes, I think we can close it.
