### ISSUE TITLE
update schema activity classes

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#609]
some classes in the schema are missing 'Activity' in their name. For example, "MetatranscriptomeAssembly"
Need to add this to be consistent with our names and typecodes

criteria for completion

- [ ] Identify which classes in the schema are miss names
- [ ] correct those classes in the schema and documentation & ensure typecodes follow the typecodes standard (add issue)

**Comment by kheal** [comment]
Closing this - it was decided to remove the Activity from the WorkflowExecution subclasses and that has been implemented on Berkeley fork.
