### ISSUE TITLE
typecode motivated changes to BiosampleProcessing alternative?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#617]
I am in the process of updating the typecode and `pattern` for `BiosampleProcessing`. Unsurprisingly, that lead to some failing tests.

> Schema validation errors were encountered.
  test/data/gold_project_test.json::$.omics_processing_set[0].id: 'gold:Gp0108335' does not match '^nmdc:bsmprc'
  test/data/gold_project_test.json::$.omics_processing_set[1].id: 'gold:Gp0108340' does not match '^nmdc:bsmprc'
  test/data/gold_project_test.json::$.omics_processing_set[2].id: 'gold:Gp0108341' does not match '^nmdc:bsmprc'

I could just overwrite those `id`s with strings like 'nmdc:bsmprc_1',  'nmdc:bsmprc_2', etc., but I thought it would be nice to retain the GOLD identifiers somewhere in the objects.

[BiosampleProcessing](https://microbiomedata.github.io/nmdc-schema/BiosampleProcessing/) does have an [alternative_identifiers](https://microbiomedata.github.io/nmdc-schema/alternative_identifiers/) slot, so I could put the GOLD identifiers there. 

Or should be follow the pattern we used with `Biosample` create a slot like gold_biosample_processing_identifier? Which would mix in [gold_identifiers](https://microbiomedata.github.io/nmdc-schema/gold_identifiers/) 

cc @cmungall @mslarae13 ... who else should weigh in on this?

**Comment by turbomam** [comment]
I did move the GOLD identifiers into [alternative_identifiers](https://microbiomedata.github.io/nmdc-schema/alternative_identifiers/) slots.

This issue will tie into the recent request for the NMDC schema to validate both legacy `id`s in MongoDB and the new patterns from the minter.

**Comment by mslarae13** [comment]
I think we can close / cancel this? Typecodes were worked on for monterey & biosampleProcessing is going away
