### ISSUE TITLE
update external_identifiers.yaml to support JGI metabolomics MASSIVE records

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#642]
Per Emiley for GSP we'd like to link the JGI metabolomics data to NMDC study page. JGI metabolomics raw data is summited to MASSIVE so we can expect to need to reference these a common external link. My suggestion is that external_identifiers.yaml be updated to allow for MASSIVE records. An example record from Bioscales
https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=83574f41458a4b259621d5c32a4d82f9

If it isn't too much additional work it would also be good to add functionally to link records at the biosample level (ie Gb0305843 is a biosample processed as part of this MASSIVE record). This is lower priority and can be broken into a separate ticket, I just thought it might be more efficient to support both at once.

If there are suggestions for supporting linking to these records without schema changes please let me know.

**Comment by turbomam** [comment]
I'd like to start in this order:
- Go back and constrain the patterns in external identifiers. For example, all GOLD external identifiers match "^GOLD:"
- Add a `massive_external_identifiers` slot requiring the pattern "^MASSIVE:"
  - I guess it would be good to formally define that the `prefix` 'MASSIVE' expands to '[https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=83574f41458a4b259621d5c32a4d82f9)'
  - assign the `massive_external_identifiers` to class `Biosample` (right?)
  - make valid and invalid sample data files

I don't think I understand the idea of linking records at the biosamaple level. I was going to assign the `massive_external_identifiers` to class `Biosample`, which already contains slots for GOLD identifiers. Do you think it would be better to assign XXX to a class that represents a metabolomics activity, like `MetabolomicsAnalysisActivity`?

**Comment by aclum** [comment]
Emiley's suggestion was to assign massive_external_identifiers to Study. The MASSIVE records are a collection of files and there isn't metadata at the sample level currently aside what is embedded in file names.

**Comment by turbomam** [comment]
> [https://identifiers.org/MASSIVE](https://identifiers.org/MASSIVE)

OK, thanks. That is how I implemented it. I'll be ready for some review in a day or tow.

**Comment by turbomam** [comment]
massive identifiers slot added to external identifiers YAML file, assigned to `Study`

using the prefix proposed by @aclum
