### ISSUE TITLE
Add missing  file_name_pattern to file type enums for metagenomes

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc-schema#703]
Add missing file_name_patterns to be able to map gold data to nmdc data objects.

**Comment by aclum** [comment]
@ssarrafan  I think this is the ticket we need to duplicate for metatranscriptomes.

**Comment by ssarrafan** [comment]
> 

@aclum thanks. @Michal-Babins I am you won't get to the metaT till next sprint. Is that correct?
