### ISSUE TITLE
Add missing file_name_pattern to file type enums for metatranscriptomes

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#708]
Add missing file_name_patterns to be able to map gold data to nmdc data objects. 
This is needed for the GROW study.

Similar to issue #703

**Comment by ssarrafan** [comment]
@aclum @Michal-Babins I added this to the next sprint, beginning Feb 13th but if you will be working on it sooner let me know or move it to the current sprint.  I also added it to the GROW squad board.

**Comment by aclum** [comment]
This is lower priority now, b/c of the schema freeze this won't be ready for GSP so doesn't need to be in the next sprint @ssarrafan

**Comment by ssarrafan** [comment]
Removing from sprint. Thanks @aclum

**Comment by ssarrafan** [comment]
@kaijli can you check to see if this is done and close the issue if it's done please?
@hubin-keio
