### ISSUE TITLE
addition to file_type_enum for NOM and metaB file types

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-schema#72]
modify the file_type_enum definition in nmdc.yml (https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml - line 376).  

Add 2 enum values with descriptions:

```
data_object_type: GC-MS Metabolomics Results
description: GC-MS-based metabolite assignment results table
```

```
data_object_type: Natural Organic Matter Results
description: FT-MS high resolution molecular formula assignment results table
```

**Comment by turbomam** [comment]
I added the two blocks into nmdc.yaml as is. Did not pass tests.

```
enums:
  file type enum:
    permissible_values:
      assembly_contigs.fna: 
        description: Final assembly contigs fasta.
.
.
.
      NOM:
        data object type: Natural Organic Matter Results
        description: FT-MS high resolution molecular formula assignment results table
      metaB:
        data object type: GC-MS Metabolomics Results
        description: GC-MS-based metabolite assignment results table
```

> ValueError:  Unknown argument: data object type = 'Natural Organic Matter Results'

**Comment by turbomam** [comment]
@dehays fixed in issue #83 / branch https://github.com/microbiomedata/nmdc-schema/tree/closes-%2372

```
enums:
  file type enum:
    permissible_values:
      assembly_contigs.fna: 
        description: Final assembly contigs fasta.
.
.
.
      GC-MS Metabolomics Results:
        GC-MS-based metabolite assignment results table
      Natural Organic Matter Results:
        FT-MS high resolution molecular formula assignment results table
```

**Where would the predicate/property `data object type` appear now? JSON data, or in the schema?**

**Comment by dehays** [comment]
@turbomam data_object_type will appear on instances of data object where data_object_type has the file_type_enum as its range.  Not sure why Bill called the property data_object_type rather than file_type following the enum naming.

**Comment by wdduncan** [comment]
It was called `data object type` b/c that was the original name that Chris gave it.

**Comment by wdduncan** [comment]
@dehays Do we need to implement this for the next sprint?

**Comment by dehays** [comment]
@wdduncan I am going to close this one.  The change would be to update the entire file type enum definition.  And before setting the range on data object type to the enum - we need to consider the mapping implementation that Donny used for data object type on the current data objects.
