### ISSUE TITLE
replace NMDC metadata downloads / https://github.com/microbiomedata/nmdc-runtime/#data-exports in README.md

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#739]
- [x] start by removing that link

@dwinston, what would you recommend as the best way or ways to download records from the NMDC metadata store? I use various APIs, but I think there was a desire to provide bulk downloads with a minimal number of clicks.

Is https://github.com/microbiomedata/nmdc-runtime/#data-exports up to date? In my recollection, that method required a chain of clicking links, examining API results, pasting another link into the browser, etc.

**Comment by dwinston** [comment]
you're talking about a way that doesn't require mongo credentials, right? I.e. something suitable for external users? Like a periodic archival dump for bulk download? Or are you wanting something near-real-time?

**Comment by turbomam** [comment]
If periodic dumps is easiest to implement, I think that's reasonable. 

Definitely should not require any database credentials, knowledge of submitting anything through a Swagger page, or interpreting JSON that explains how to construct some other access URL.

**Comment by turbomam** [comment]
In a few minutes, I will be pushing some suggestions about using the runtime API for paged collection download
