### ISSUE TITLE
run tests for invalid data

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#74]
For invalid datasets in `test/data`, add target to `makefile` to check that invalid data is confirmed to be invalid.

As a convention, prefix that name of the invalid dataset with `invalid_`; e.g., `invalid_study_test.json`.

cc @turbomam

**Comment by wdduncan** [comment]
See this stackoverflow article for pointers:

https://stackoverflow.com/questions/2188376/how-to-have-gnu-make-explicitly-test-for-failure

**Comment by turbomam** [comment]
in addition to prefixing the negative tests with "invalid_", can we also put them in an `invalid` subdirectory?

**Comment by wdduncan** [comment]
> in addition to prefixing the negative tests with "invalid_", can we also put them in an invalid subdirectory?
I'd prefer not.

**Comment by wdduncan** [comment]
Yes. That was going to be my approach.

**Comment by wdduncan** [comment]
@turbomam I think @sujaypatil96 fixed this :)

Closing ticket. Reopen if needed.
