### ISSUE TITLE
What is the ideal range for was_informed_by?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#761]
Following up on closed issue 
- https://github.com/microbiomedata/nmdc-schema/pull/92

**Comment by aclum** [comment]
with the current schema i believe was_informed_by is only populated with records of Class OmicsProcessing.

**Comment by kheal** [comment]
In Berkely branch `was_informed_by` has a constrained range of `DataGeneration` and is exclusively used on `WorkflowChain` class.
