### ISSUE TITLE
GitHub Publish Action not going through

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#793]
The GitHub publish to PyPI Action isn't going through for recent releases. The cause of the error seems to be many fold:
* Always be sure to include the `v` prefix in releases and tags in order to be consistent with previous releases [_not a reason for the Action to error out, but still good practice_]
* The current `pyproject.toml` file seems to have a version in there which is not compatible with PEP440 which is enforced by the `poetry-dynamic-versioning` plugin: https://github.com/microbiomedata/nmdc-schema/blob/main/pyproject.toml#L11

This is what the version looked like in the toml file after the cookiecutter restructure, but before the `v7.4.9` release: https://github.com/microbiomedata/nmdc-schema/blob/b79986a8f3386db47a5a4a34aa036cfb8eafb290/pyproject.toml#L11

I think switching back to `0.0.0` in the toml file should fix the problem.

**Comment by turbomam** [comment]
set `version` in `pyproject.toml` to "0.0.0"  (in main)
