### ISSUE TITLE
Do we keep GOLD add_date and mod_date?

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#8]
At present, I pull in the `add_date` and `mod_date` from the GOLD data tables. These tables pertain to when the record was added to the database, not when the sample was collected. 

Example biosample `add_date: 28-JUL-14 12.00.00.000000000 AM`.

Do we keep these or remove these?

cc @cmungall @dwinston @jbeezley @jeffbaumes @turbomam @dehays

**Comment by dehays** [comment]
1) I do not think they need to be displayed in the UI - particulary in their current context-less form.  2) The question of whether to include them at all depends on how much provenance we wish to retain, part of /nmdc-metadata#318 I think.

I could imagine that for each datum we'd want to have at least the source (GOLD in this case) and perhaps its add/update in that source.

**Comment by wdduncan** [comment]
@dehays great point! Yes, the `was generated by` slot can be used to point back to original record in the biosample table. This would be an ETL enhancement.

**Comment by wdduncan** [comment]
Adding @tbkreddy to the conversation.

**Comment by wdduncan** [comment]
We can also add information to the model that this information should not be displayed.

**Comment by emileyfadrosh** [comment]
Reviving this issue, and suggest to add information that this should not be displayed in the data portal. @wdduncan, sounds like this is an easy fix? Thanks.

**Comment by turbomam** [comment]
@wdduncan were you hoping I would help with this in some way? I don't know where the GOLD input lives and am not sure which repo contains the relevant code.

**Comment by dwinston** [comment]
FYI @turbomam the relevant code for gold translation is in the [nmdc-runtime/metadata-translation/](https://github.com/microbiomedata/nmdc-runtime/tree/39bab4c31624cc2af855fb511e480524166ac5bf/metadata-translation)  directory of the [microbiomedata/nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime) repo.

**Comment by dwinston** [comment]
But I think @wdduncan indicated that some annotation corresponding to "applications generally should not display this field" may be added to the LinkML model in this repo, unless I'm misunderstanding "add information to the model". So the metadata translation code needn't be touched. And then, going forward, the data portal can consult the model annotation for what not to display, rather than this being hard-coded in nmdc-server code.

**Comment by turbomam** [comment]
Thanks @dwinston . I'll wait to hear whether @wdduncan was thinking I should take any of this on.

**Comment by wdduncan** [comment]
Currently I do translate the `add_date` and `mod_date` fields from gold. I also convert the dates into ISO 8601 format. Can Kitware simply exclude them from the portal interface if we don't want them displayed?

**Comment by mslarae13** [comment]
@aclum is this still useful? do we need or use these fields? I think we do, for workflows.. but I think it's done?

**Comment by aclum** [comment]
mod_date is potentially useful for keeping track of which record should change if NMDC and GOLD records are get out of sync. I'd say if this isn't a problem we leave these fields as they are so just close this ticket as complete.

**Comment by TBKReddy** [comment]
Yes, I agree. Mod dates can help us in identifying updated records.
