### ISSUE TITLE
Prefix list curation

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#819]
- [x] We need the GOLD prefix to be uncommented since we are ingesting datasets from GOLD
  * GOLD: https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L45
- [x] https://unknown.to.linter.org/ links in commented prefixes need to be cleaned up
- [x] Remove commented prefixes that are not being used

**Comment by turbomam** [comment]
I agree.

The GOLD prefix is expanded to http://identifiers.org/gold/ in `src/schema/external_identifiers.yaml` and then inherited into nmdc.yaml anytime that root schema file is loaded with merging enabled. But maybe scattering prefix definition into different schema files isn't the best practice.  After resolving that decision, then we can remove all of the commented-out prefix definitions in nmdc.yaml

We also have sample data files that use the GOLD prefix and demonstrate the the schema recognizes it: https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Biosample-exhasutive.yaml

Which couldn't be converted to https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/output/Biosample-exhasutive.json if the GOLD prefix wasn't defined.

**But that may not be the proper expansion!**

https://bioregistry.io/registry/gold says 

| Name                    | Metaprefix  | URI                                            |
|-------------------------|-------------|------------------------------------------------|
| Genomes Online Database | gold        | https://gold.jgi.doe.gov/resolver?id=Gs0000008 |
| Bioregistry             | bioregistry | https://bioregistry.io/gold:Gs0000008          |
| Identifiers.org         | miriam      | https://identifiers.org/gold:Gs0000008         |

---

I have used https://unknown.to.linter.org/ as a placeholder expansion when I didn't know the official expansion. We should find official expansions for the examples below and more, or come up with a better placeholder strategy.

- ISA: https://unknown.to.linter.org/
- bare: https://unknown.to.linter.org/

Where can we find expansions for ISA and jgi? Apparently not in bioregistry.

General policy question: when to use all caps for prefixes vs lower case?

**Comment by turbomam** [comment]
Here are the prefixes we do have defined anywhere in src/schema:

- EFO: http://identifiers.org/efo/
- ISA: https://unknown.to.linter.org/
- NCIT: http://purl.obolibrary.org/obo/NCIT_
- OBI: http://purl.obolibrary.org/obo/OBI_
- bare: https://unknown.to.linter.org/
- linkml: https://w3id.org/linkml/
- nmdc: https://w3id.org/nmdc/
- nmdc_yaml: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/
- prov: http://www.w3.org/ns/prov#
- rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
- rdfs: http://www.w3.org/2000/01/rdf-schema#
- skos: http://www.w3.org/2004/02/skos/core#
- xsd: http://www.w3.org/2001/XMLSchema#
- jgi: https://unknown.to.linter.org/
- dcterms: http://purl.org/dc/terms/
- KEGG.COMPOUND: http://identifiers.org/kegg.compound/
- UniProtKB: https://identifiers.org/uniprot/
- biolink: https://w3id.org/biolink/vocab/
- gtpo: https://unknown.to.linter.org/
- qud: http://qudt.org/1.1/schema/qudt#
- schema: http://schema.org/
- sio: http://semanticscience.org/resource/SIO_
- wgs84: http://www.w3.org/2003/01/geo/wgs84_pos#
- shex: http://www.w3.org/ns/shex#
- GOLD: http://identifiers.org/gold/
- CHEBI: http://purl.obolibrary.org/obo/CHEBI_
- CHMO: http://purl.obolibrary.org/obo/CHMO_
- MIXS: https://w3id.org/mixs/
- COG: https://unknown.to.linter.org/
- EC: https://unknown.to.linter.org/
- GO: http://purl.obolibrary.org/obo/GO_
- KEGG.ORTHOLOGY: http://identifiers.org/kegg.orthology/
- KEGG.REACTION: http://identifiers.org/kegg.reaction/
- KEGG_PATHWAY: http://identifiers.org/kegg.pathway/
- MetaCyc: https://identifiers.org/metacyc.reaction/
- MetaNetX: https://unknown.to.linter.org/
- RHEA: http://identifiers.org/rhea/
- RetroRules: https://unknown.to.linter.org/
- SEED: http://identifiers.org/seed/

**Comment by turbomam** [comment]
tasks:
- decide in which YAML files to define prefixes
- find expansions for all of our prefixes and then assert them in the preferred YAML file(s)
- remove commented prefix declarations

**Comment by aclum** [comment]
@sujaypatil96  are the tasks you outlined compelte?

**Comment by sujaypatil96** [comment]
@turbomam could you remind which one of our schema files has the prefix expansion for gold/GOLD?

**Comment by turbomam** [comment]
```shell
egrep -r -i '^ +gold:' src/schema/
```

> `src/schema/external_identifiers.yaml:  gold: "https://bioregistry.io/gold:"`

----

- We need the GOLD prefix to be uncommented since we are ingesting datasets from GOLD
  - DONE
- https://unknown.to.linter.org/ links in commented prefixes need to be cleaned up
  - DONE. `https://unknown.to.linter.org/` is not asserted as the expansion of any prefix any more
  - I have kept the following prefix/expansion: ` generic: https://example.org/generic/`
- Remove commented prefixes that are not being used
  - DONE, with the exception of `AFO`, which will be removed in an upcoming PR.
