### ISSUE TITLE
`samp_taxon_id` and `host_taxid` need to be CURIEs

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#823]
* `samp_taxon_id` slot in schema: https://microbiomedata.github.io/nmdc-schema/samp_taxon_id/
  * This slot needs to be modelled as a CURIE since it is an identifier
  * Need to be modelled in a way such that the text portion of the samp_taxon_id and CURIE portion of it don't need to be parsed out of the raw string
    * Example: Gut Metagenome [NCBI:txid749906]
    * Gut Metagenome needs to be in a slot on some class that can model samp_taxon_id
    * NCBI:txid749906 needs to be in a slot with a range of uriorcurie on the same class
* `host_taxid` slot in schema: https://microbiomedata.github.io/nmdc-schema/host_taxid/
  * Currently a string, needs to be uriorcurie

**Comment by turbomam** [comment]
Can you say a little more about what MIxS seems to expect for these slots? 

Are you suggesting that `samp_taxon_id` be spit into two slots, one for the identifier and another for the label?

Please 
- open a  branch
- add the alternative modeling that you feel is needed
- add valid and invalid data that demonstrate your point
- assign me to the PR

Can you also please take responsibility for ensuring that the submission schema will capture data that will be conducive to reformatting as your have specified above?

We can discuss any of this whenever you wnat.

**Comment by turbomam** [comment]
See https://bioregistry.io/registry/ncbitaxon re preferred prefixes, although [OBO Foundry](https://obofoundry.org/ontology/ncbitaxon.html) uses the expansion http://purl.obolibrary.org/obo/NCBITaxon_

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606
