### ISSUE TITLE
update identifiers documentation 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#849]
I noticed the identifier endpoint is broken on this website https://microbiomedata.github.io/nmdc-schema/identifiers/, in the "IDs minted for use within NMDC" paragraph, api.dev should be api-dev in the link or it should link to the prod API. Also we should remove the paragraph titled "Reuse vs minting new IDs"

**Comment by ssarrafan** [comment]
Checked with Sujay and he said he can finish this by tomorrow so I'll leave it in this sprint.

**Comment by ssarrafan** [comment]
This doesn't look like it's updated yet.  I'll remove it from the sprint as unfinished. @aclum do you need this to be done by next sprint?  



![Image](https://user-images.githubusercontent.com/79225425/230683217-5db9f279-93b5-435e-a96f-be2b0a50e571.png)

**Comment by aclum** [comment]
I think the work is done pending a pull request review so we may as well finish this out next sprint so it doesn't linger.
