### ISSUE TITLE
RNA Plate position validation error

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#865]
A10 should validate for RNA plate position but it doesn't.
It looks like it should based on the regular expression?

See https://data.microbiomedata.org/submission/3f6d765d-18e2-4fb4-8209-456a3b9d1a86/samples 

DNA late position may also be wrong, I haven't checked it.
![Screen Shot 2023-04-13 at 5 28 46 PM](https://user-images.githubusercontent.com/44581429/231911427-edc9c213-cd0a-414d-b148-fac6652c05b8.png)

**Comment by mslarae13** [comment]
@turbomam made changes to NMDC and submission schema and sample data to address this.
The rules in NMDC schema are good, submission schema can import these rules.
Mark will check this in an example data file. 

DH doesn't understand rules. So nothing to connect that.

**Comment by pkalita-lbl** [comment]
Issue for implementing LinkML rules in DataHarmonizer: https://github.com/cidgoh/DataHarmonizer/issues/370

**Comment by turbomam** [comment]
The tube/plate/well rules work in terms of LinkML validation in both the nmdc-schema and the submission schema. The well/plate position columns are magenta/optional in the DataHarmonizer interface now.
