### ISSUE TITLE
clarify PyPI package release procedure

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#87]
I ran `make build-package` yesterday, noticed the version tag was weird (it had "2021.6.31" in it and "dev" and a long hash), so I set the version manually in setup.py to "2021.6.30", and after building ran `make deploy-pypi`. I notice that the deployed package doesn't facilitate

```python
import pkg_resources
pkg_resources.resource_filename("nmdc_schema", "nmdc.schema.json")
```

like before, so the package data wasn't included properly. The artifact is still present, which I can access via the following hack:

```python
from pathlib import Path

import nmdc_schema

Path(nmdc_schema.__path__[0]).joinpath("nmdc.schema.json")
```

@wdduncan Please draft a section of the README (or a section within the Makefile) that clarifies the release procedure, which will of course still be restricted to those with valid PyPI maintainer credentials.

**Comment by wdduncan** [comment]
It looks like you made some changes but didn't make a new release. Not sure I follow what is going on.

**Comment by wdduncan** [comment]
@dwinston @turbomam @cmungall   
I've added information to `MAINTAINERS.md` about how to maintain the schema and make a PyPI release.

Please review and let me know what is not clear. I will leave this ticket open while I wait for feedback.

**Comment by dwinston** [comment]
`MAINTAINERS.md` looks good to me, @wdduncan. Thanks!
