### ISSUE TITLE
Add 'M horizon' as to soil_horizon_enum

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#871]
Add `M horizon` to Enumeration soil_horizon_enum to be used for slot soil_horizon for Class Biosample in support of NEON and other studies.

The justification for this is that ENVO ontology supports `M horizon` as a term (ENVO:03600011) for soil horizon 

In [this branch](https://github.com/microbiomedata/nmdc-schema/tree/m_horizon) I've added an example valid data yaml file using this enum value

**Comment by aclum** [comment]
@pkalita-lbl  If we add an enum in the schema does something need to happen to mirror this in the submission schema or will the valid enums populate automatically?

**Comment by pkalita-lbl** [comment]
The workflow looks like this (for anything, not just enum permissible values):

1. Update the source files in `nmdc-schema`
2. Make a new release of `nmdc-schema` with your change (and possibly others). Write good release notes to help downstream users understand potential migration concerns when updating to this new version.
3. Over in `submission-schema` update the source files to pull from the newly released version of `nmdc-schema`.
4. Make a new release of `submission-schema` with this change (and possibly others). Write good release notes. The change is now in the submission schema. Are you also ready for it to show up in the submission portal? Then:
  4a. Over in `nmdc-server` update the `submission-schema` dependency to the latest version.

**Comment by aclum** [comment]
@dwinston  what happens in the API? If there are nmdc-schema version changes does the API automatically get update or changes are needed in nmdc-runtime?

**Comment by dwinston** [comment]
@aclum it doesn't automatically update. Yes, a `nmdc-schema` python package upgrade is needed in `nmdc-runtime`. The currently deployed version is displayed at the top of https://api.microbiomedata.org/docs (e.g. `nmdc-schema=7.4.15` as of now).

**Comment by mslarae13** [comment]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 


**RACI**

_Tag people in their roles_
- Responsible: @aclum 
- Accountable: @aclum 
- Consulted:
- Informed: @mslarae13

**Describe the the task?**
- [ ] Add M and O to soil_horizon enums

**Criteria for completion**
- M and O are available in the NMDC submission schema 
- M and O are accepted values for soil_horizon in the NMDC schema

**Estimate people time**
- 

**Completion Date (Goal)**
- June 2

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon isues**
-

**Comment by aclum** [comment]
@turbomam  I've scheduled some time for us to work on this on Monday 5/22

**Comment by turbomam** [comment]
'M horizon' has been added to the nmdc-schema. We could also add a comment about how it doesn't come from GSC. Maybe we could reorder the permissible values alphabetically or according to some other natural order.
