### ISSUE TITLE
Add MONet sampling slots

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-schema#875]
To accommodate MONet metadata submission via the NMDC submission portal, we need to add the following slots to the schema.  (3 new slots)

infiltration_1:
    description: Amount of time it takes to accomplish the first infiltration activity
    title: infiltration time 1
    examples:
      - value: 15 minutes
    multivalued: false

infiltration_2
    description: Amount of time it takes to accomplish the second infiltration activity
    title: infiltration time 2
    examples:
      - value: 15 minutes
    multivalued: false

infiltration_note:
    description: Any details, issues, or context needed to understand the infiltration activity
    title: infiltration notes
    examples:
      - value: Raining all day, infiltration unsuccessful
      - value: Infiltration too rapid to capture
    multivalued: false

bulk_elect_conductivity:
    description: Electrical conductivity is a measure of the bulk soil ability to carry electric current, which is mostly dictated by the chemistry of and amount of soil water. Provide the value output of the field instrument.
    examples:
      - value: 0.003 milli siemens per centimeter 
      - value: 0.003 mS/cm  
    multivalued: false

**Comment by mslarae13** [comment]
(non-squad activity)

**Comment by turbomam** [comment]
I apologize for forgetting about this.

These slots will require some remodeling. They appear to be in the schema/data hybrid notation and will need to be rewritten. We will also need to determine which class(es) can use them.

- is there really no information about an infiltration other than it's duration? and a note? I proposed creating an Infiltration class, with slots for duration, notes and additional future attributes.
- directives like "Provide the value output of the field instrument" are OK for a submission schema, but the nmdc-schema emphasizes purely descriptive `description`s, like "The measure of the bulk soil's ability to carry electric current." I would propose moving "mostly dictated by the chemistry of the soil and the amount of soil water" to a comment

**Comment by ssarrafan** [comment]
Adding to current sprint per Mark. Will be part of Metabolink squad work per Mark. 
FYI @anastasiyaprymolenna

**Comment by ssarrafan** [comment]
Marked as done on the Metabolink board so closing this issue.

**Comment by mslarae13** [comment]
These slots don't appear to be in the schema? That said, they were important for the submission portal for MONet submissions... and I think the decision is that's not happening now. So we do not need these MONet specific slots.
