### ISSUE TITLE
add `string_serialization: '{text < 20 characters}'` to rna_container_id

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#890]
Will make @brynnz22's  [SampleData-jgi_mt_data-exceeds-char-limit-rna_container_id.yaml](https://github.com/microbiomedata/submission-schema/blob/issue-99-plant-assoc/src/data/unexpected_pass/SampleData-jgi_mt_data-exceeds-char-limit-rna_container_id.yaml) in the submission schema invalid!

- eventually collapse the dna-specific and rna-specific slots in the JGI MG and MT modelling as much as possible. Will require changes to @sujaypatil96's user facility conversions scripts
- eventuality move content like `{text < 20 characters}` from `string_serialization` to `structured_pattern`

cc @pkalita-lbl @mslarae13

**Comment by kheal** [comment]
This has been implemented, closing issue
