### ISSUE TITLE
relationship between Activity and Process

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#896]
PROV vs OBI/BFO

**Comment by mslarae13** [comment]
Do we still need this issue? I feel like we settled this and are using Process?

**Comment by turbomam** [comment]
> Do we still need this issue? I feel like we settled this and are using Process?

Yes, the berkeley-schema-fy24 has a OBI-inspired PlannedProcess class but has eliminated the PROV-inspired Activity class
