### ISSUE TITLE
Provide regular expression values for slots' `patterns`

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-schema#9]
Need a list of regexs to check data.

**Comment by jbeezley** [comment]
We could bikeshed about regexes all day.  I think these are generally good compromises in terms of complexity and restrictiveness.  There are other sorts of strings we could pattern match as well, such as dates, attributes with units, etc. but I think these things are better left to the parsers doing the normalization.

DOI:
```
^10.\d{4,9}/[-._;()/:A-Za-z0-9]+$
```

URL:
```
^https?://(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?$
```

The following come from https://microbiomedata.github.io/nmdc-metadata/identifiers/:

KO term:
```
(?i)^KEGG.ORTHOLOGY:D\d{5}$
```
@jeffbaumes You had noted the desire to make this just `KO:`, but it is actually defined by an official CURIE prefix at https://registry.identifiers.org/registry/kegg.orthology.

ENVO term (all the terms I have in my database contain at least 7 digits):
```
(?i)^ENVO:\d{7,}$
```

ID's in general
```
^\w+:\S+$
```

One thing about the `(?i)` inline modifier used above... I'm not sure if the namespace is intended to be case insensitive or not.  If not, it should be removed.  If so, I will need to normalize the namespace during ingestion.

**Comment by jeffbaumes** [comment]
Thanks @jbeezley. Happy for it to be `KEGG.ORTHOLOGY`, as long as it's consistent.

**Comment by dehays** [comment]
wrt dates - JSON Schema has a date-time which validates to RFC 3339 - so I don't believe we need to apply our own regex to dates.  https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.1 (date-time has been in JSON Schema longer than this draft,  I think the date and time are added in JSON Schema 7)

**Comment by wdduncan** [comment]
Update:  
We are working on to implement this in LinkML. See tickets:
- https://github.com/linkml/linkml/issues/194
- https://github.com/linkml/linkml/issues/193

**Comment by turbomam** [comment]
This issue is closed by the presence of https://linkml.io/linkml-model/docs/pattern/ in the LinkML metamodel, although I do recommend more pattern bikeshedding!
