### ISSUE TITLE
model extraction process

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#906]
[Deliverable](https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680) this task is associated with

6

RACI

Responsible: @mslarae13 @turbomam @aclum 
Accountable: @aclum
Consulted: 
Informed:

Describe the task?

Using NEON as an example to model a [PlannedProcess](https://microbiomedata.github.io/nmdc-schema/PlannedProcess/) for extraction

slots (slot names are placeholders based on neon column headers):
inputs - id from Class Biosample
outputs - id from Class AnalyticalSample
laboratoryName
protocol_name
processedDate
sampleMass
nucleicAcidConcentration
nucleicAcidQuantMethod - enum of instrument names?
nucleicAcidPurity
nucleicAcidRange
qaqcStatus - enum of {Pass, Fail}

Work is being done in [this branch](https://github.com/microbiomedata/nmdc-schema/new/issue-906-dna_extraction) of nmdc-schema

Criteria for completion

A Class Extraction exists in a released version of the NMDC schema along with example valid data.

Completion Date (Goal)

June 16
Target Sprint Start & End Dates

Start: May 22
End: June 2

Tag Blocker/Contingent upon issues

**Comment by aclum** [comment]
@turbomam I've made example the following example data files
https://github.com/microbiomedata/nmdc-schema/blob/issue-906-dna_extraction/src/data/valid/Database-extraction_set-exhaustive.yaml
https://github.com/microbiomedata/nmdc-schema/blob/issue-906-dna_extraction/src/data/valid/Database-extraction_set-minimal.yaml
https://github.com/microbiomedata/nmdc-schema/blob/issue-906-dna_extraction/src/data/valid/Database-analytical_sample-minimal.yaml
https://github.com/microbiomedata/nmdc-schema/blob/issue-906-dna_extraction/src/data/valid/Database-analytical_sample-extract-exhaustive.yaml
I've also updated Class Database to include extraction_set and analytical_sample_set and processing_institution_enum.

What I need from you is 
- [ ] new Class for Extraction
- [ ] new slots for Class Extraction
- [ ] new slots AnalyticalSample
- [ ] new enumeration for the range of slot status for Class Extraction
- [ ] new enumeration for the range of slot detection_instrument for Class AnalyticalSample
- [ ] new enumeration for the range of slot extraction_type for Class Extraction

**Comment by ssarrafan** [comment]
Based on last comment moving to new sprint

**Comment by aclum** [comment]
enum for instrument_name to be handled in https://github.com/microbiomedata/issues/issues/162
