### ISSUE TITLE
YAML models for sample preparation metadata

### ISSUE THREAD

**Issue by anastasiyaprymolenna** [microbiomedata/nmdc-schema#907]
MONet metadata described in LinkML needs to be prepared for the nmdc-schema, the current metadata models are too complex and need to be distilled into the information able to be modeled in the NMDC while still being informative

**Comment by turbomam** [comment]
You're making great progress!

I can start giving feedback now if you'd like. There's opportunities to 
- improve the modeling some
- improve comments and descriptions
- standardize practices about what files get committed or not and what directories they should go into

**Comment by ssarrafan** [comment]
@anastasiyaprymolenna I see this is in progress on your squad board so I'm adding to the current sprint. Let me know if you're not planning to work on it this sprint.  Thanks.

**Comment by ssarrafan** [comment]
@anastasiyaprymolenna what's the status of this issue?  Doesn't appear to be active

**Comment by anastasiyaprymolenna** [comment]
SampleOperations are being moved to be defined as PlannedProcess

**Comment by ssarrafan** [comment]
@anastasiyaprymolenna with the change to PlannedProcess can this issue be closed?

**Comment by ssarrafan** [comment]
@anastasiyaprymolenna let me know if this should be closed or removed from the sprint. Thanks.

**Comment by ssarrafan** [comment]
still in progress, right @anastasiyaprymolenna ?

**Comment by ssarrafan** [comment]
This is still in progress. 8 am Friday meetings set up to discuss.  Will keep it open.

**Comment by ssarrafan** [comment]
@anastasiyaprymolenna I'm adding backlog label and removing from sprint. Let me know if this is still active.  Thanks!
