### ISSUE TITLE
model library preparation 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-schema#908]
[Deliverable](https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680) this task is associated with

6

RACI

Responsible: @mslarae13 @turbomam @aclum
Accountable: @turbomam 
Consulted:
Informed:

Describe the task?

Using NEON as an example to model library preparation
- [x] generate example valid data
- [x] new Class LibraryPreparation
- [x] slot updates as needed
- [x] enumeration updates as needed
- [x] updates to Class Database for library_preparation_set

Work is being done in [this branch](https://github.com/microbiomedata/nmdc-schema/tree/issue-908-library_construction) of nmdc-schema

Criteria for completion

A Class LibraryPreparation exists in a released version of the NMDC schema along with example valid data.

Completion Date (Goal)

June 16
Target Sprint Start & End Dates

Start: May 22
End: June 2

Tag Blocker/Contingent upon issues

**Comment by turbomam** [comment]
it seems like we have some conflicts between whether this topic should be called library **construction** or library **preparation**

either is fine with me, but we should be consistent in the terms used in the schema and the terms we use in our discussions

**Comment by aclum** [comment]
As discussed at the squad meeting today we are using 'library preparation' in line with OBI ontology.

**Comment by aclum** [comment]
@turbomam is there a reason https://microbiomedata.github.io/nmdc-schema/LIBRARYTYPEENUM/ is all caps instead of camelcase like the other enums?

**Comment by aclum** [comment]
Last thing here is to update the date slots. example valid data 
https://github.com/microbiomedata/nmdc-schema/blob/issue-917-neon-story/src/data/valid/Database-neon-story.yaml

**Comment by ssarrafan** [comment]
One checkbox left, will move to new sprint to complete

**Comment by aclum** [comment]
The last slot that I wanted for Class LibraryPreparation isn't urgent for ESA so I made a separate issue, https://github.com/microbiomedata/nmdc-schema/issues/1000, so we can close this one.
