### ISSUE TITLE
In what ways does the casing of GOLD vs gold matter?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#913]
@aclum pointed out that there are case mismatches between the way GOLD is represented in the schema (slot patterns, for example), data, primary resources (like at lest one GOLD API may require inputs to be in a particular case), and third party resolvers

----

Bioregistry has a https://bioregistry.io/registry/gold page

identifiers.org has a https://registry.identifiers.org/registry/gold page

https://bioregistry.io/gold:Gs0110115 and https://identifiers.org/gold:Gs0000008 resolve to https://gold.jgi.doe.gov/study?id=Gs0110115

----

The public GOLD API home is here: https://gold-ws.jgi.doe.gov/

I can log in with my JGI credentials and use the swagger interface at https://gold-ws.jgi.doe.gov/swagger-ui/index.html

The following link, with a local id and not GOLD prefix works: https://gold-ws.jgi.doe.gov/api/v1/studies?studyGoldId=Gs0110115 

There is also some separate API that specifically allows NMDC users to retrieve GOLD information

@sujaypatil96 can you please provide information bout which GOLD API you use? Does it require queries to include the GOLD prefix? In what case should GOLD/gold be written?

**Comment by turbomam** [comment]
```shell
grep -R gold src/schema/*
```

> src/schema/basic_slots.yaml:      For example, when extracting study information for GOLD, the GOLD system has assigned a name/label.
> src/schema/external_identifiers.yaml:  GOLD: http://identifiers.org/gold/
> src/schema/external_identifiers.yaml:  gold_identifiers:
> src/schema/external_identifiers.yaml:      - https://gold.jgi.doe.gov/
> src/schema/external_identifiers.yaml:  gold_study_identifiers:
> src/schema/external_identifiers.yaml:      - gold_identifiers
> src/schema/external_identifiers.yaml:    pattern: "^GOLD:Gs[0-9]+$"
> src/schema/external_identifiers.yaml:    description: identifiers for corresponding project(s) in GOLD
> src/schema/external_identifiers.yaml:      - value: https://identifiers.org/gold:Gs0110115
> src/schema/external_identifiers.yaml:      - https://gold.jgi.doe.gov/studies
> src/schema/external_identifiers.yaml:    title: GOLD Study Identifiers
> src/schema/external_identifiers.yaml:  gold_biosample_identifiers:
> src/schema/external_identifiers.yaml:      - gold_identifiers
> src/schema/external_identifiers.yaml:    pattern: "^GOLD:Gb[0-9]+$"
> src/schema/external_identifiers.yaml:    description: identifiers for corresponding sample in GOLD
> src/schema/external_identifiers.yaml:      - value: https://identifiers.org/gold:Gb0312930
> src/schema/external_identifiers.yaml:  gold_sequencing_project_identifiers:
> src/schema/external_identifiers.yaml:      - gold_identifiers
> src/schema/external_identifiers.yaml:    pattern: "^GOLD:Gp[0-9]+$"
> src/schema/external_identifiers.yaml:    description: identifiers for corresponding sequencing project in GOLD
> src/schema/external_identifiers.yaml:      - value: https://identifiers.org/gold:Gp0108335
> src/schema/external_identifiers.yaml:  gold_analysis_project_identifiers:
> src/schema/external_identifiers.yaml:      - gold_identifiers
> src/schema/external_identifiers.yaml:    pattern: "^GOLD:Ga[0-9]+$"
> src/schema/external_identifiers.yaml:    description: identifiers for corresponding analysis project in GOLD
> src/schema/external_identifiers.yaml:      - value: https://identifiers.org/gold:Ga0526289
> src/schema/external_identifiers.yaml:      - in INSDC this is a run but it corresponds to a GOLD analysis
> src/schema/nmdc.yaml:  #  GOLD: http://identifiers.org/gold/
> src/schema/nmdc.yaml:      - "might correspond to GOLD's identifier on a page like https://gold.jgi.doe.gov/biosample?id=Gb0305833"
> src/schema/nmdc.yaml:      - removed previous id_prefixes value of GOLD, since we are now using pattern-based id validation
> src/schema/nmdc.yaml:      - removed id_prefixes value of GOLD, since we are now using pattern-based id validation
> src/schema/nmdc.yaml:      - could add GOLD and EBI's biosample definitions to the alt_descriptions?
> src/schema/nmdc.yaml:      - removed previous id_prefixes value of GOLD, since we are now using pattern-based id validation
> src/schema/nmdc.yaml:      - gold_biosample_identifiers
> src/schema/nmdc.yaml:      ## GOLD path fields
> src/schema/nmdc.yaml:      ## GOLD specific fields
> src/schema/nmdc.yaml:      gold_biosample_identifiers:
> src/schema/nmdc.yaml:        description: Unique identifier for a biosample submitted to GOLD that matches the NMDC submitted biosample
> src/schema/nmdc.yaml:        comments: This is the ID provided by GOLD that starts with 'GB'
> src/schema/nmdc.yaml:          display_hint: Provide the GOLD biosample IDs associated with this biosample.
> src/schema/nmdc.yaml:      - gold_study_identifiers
> src/schema/nmdc.yaml:      - "sample GOLD link https://identifiers.org/gold:Gs0110115"
> src/schema/nmdc.yaml:      - "GOLD, insdc.srs and mgnify are reasonable prefixes for alternative study identifiers, but no longer for the Study.id"
> src/schema/nmdc.yaml:      - The ID prefix for objects coming from GOLD will be gold:Gp
> src/schema/nmdc.yaml:      - gold_sequencing_project_identifiers
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_structural_annotation.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_structural_annotation_stats.json'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_functional_annotation.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_imgap.info'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_proteins.faa'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_ec.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_ko.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_pairedMapped.sam.gz'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_assembly.contigs.fasta'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_pairedMapped_sorted.bam.cov'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_contig_names_mapping.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_tigrfam.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_crt.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_genemark.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_prodigal.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_trna.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_rfam_misc_bind_misc_feature_regulatory.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_rfam.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_rfam_ncrna_tmrna.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_ko_ec.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_product_names.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_gene_phylogeny.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_gene_phylogeny.tsv'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_cog.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_cath_funfam.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_supfam.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_smart.gff'
> src/schema/nmdc.yaml:          file_name_pattern: '[GOLD-AP]_pfam.gff'
> src/schema/nmdc.yaml:  ## GOLD PATHS
> src/schema/nmdc.yaml:  gold_path_field:
> src/schema/nmdc.yaml:      This is a grouping for any of the gold path fields
> src/schema/nmdc.yaml:    is_a: gold_path_field
> src/schema/nmdc.yaml:      Ecosystem is in position 1/5 in a GOLD path.
> src/schema/nmdc.yaml:      of organisms in a given environment. The GOLD Ecosystem at the top of the five-level
> src/schema/nmdc.yaml:    see_also: https://gold.jgi.doe.gov/help
> src/schema/nmdc.yaml:    is_a: gold_path_field
> src/schema/nmdc.yaml:      is isolated. Ecosystem category is in position 2/5 in a GOLD path.
> src/schema/nmdc.yaml:    see_also: https://gold.jgi.doe.gov/help
> src/schema/nmdc.yaml:    is_a: gold_path_field
> src/schema/nmdc.yaml:      type is in position 3/5 in a GOLD path.
> src/schema/nmdc.yaml:    see_also: https://gold.jgi.doe.gov/help
> src/schema/nmdc.yaml:    is_a: gold_path_field
> src/schema/nmdc.yaml:      into more distinct subtypes. Ecosystem subtype is in position 4/5 in a GOLD
> src/schema/nmdc.yaml:    see_also: https://gold.jgi.doe.gov/help
> src/schema/nmdc.yaml:    is_a: gold_path_field
> src/schema/nmdc.yaml:      Specific ecosystem is in position 5/5 in a GOLD path.
> src/schema/nmdc.yaml:    see_also: https://gold.jgi.doe.gov/help
> src/schema/nmdc.yaml:    description: A unique id representing the GOLD classifers associated with a sample.
> src/schema/nmdc.yaml:      - "maps to gold:salinity"
> src/schema/sample_prep.yaml:#  GOLD: http://identifiers.org/gold/
> src/schema/workflow_execution_activity.yaml:      - gold_analysis_project_identifiers
> src/schema/workflow_execution_activity.yaml:      - gold_analysis_project_identifiers

**Comment by turbomam** [comment]
```shell
grep -i -R gold src/data/*
```

> src/data/invalid/Database-Biosample-invalid_range.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gb0101224
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gs0128849
> src/data/invalid/Database-Biosample-invalid_range.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gb0101225
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gs0128849
> src/data/invalid/Database-Biosample-invalid_range.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gb0101226
> src/data/invalid/Database-Biosample-invalid_range.yaml:      - gold:Gs0128849
> src/data/invalid/Biosample-invalid_fire.yaml:  - gold:Gs0110115
> src/data/invalid/Database-biosamples-lat_lon-with-GLV-missing-longitude.yaml:      - gold:Gs0110115
> src/data/invalid/Database-invalid-studies.yaml:    id: gold:Gs0110115
> src/data/invalid/Database-invalid-studies.yaml:  - id: gold:Gs0110132
> src/data/invalid/Database-invalid-studies.yaml:  - id: gold:Gs0112340
> src/data/invalid/Database-biosamples-rna-in-plate-invalid-well-val.yaml:      - gold:Gs0110115
> src/data/invalid/Database-biosamples-dna-in-tube-with-well-value.yaml:      - gold:Gs0110115
> src/data/invalid/Database-biosample_mismatch_regex.yaml:  - gold_biosample_identifiers:
> src/data/invalid/Database-biosample_mismatch_regex.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_mismatch_regex.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_mismatch_regex.yaml:      - gold:Gb0101225
> src/data/invalid/Database-biosample_mismatch_regex.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_mismatch_regex.yaml:  - gold_biosample_identifiers:
> src/data/invalid/Database-biosample_mismatch_regex.yaml:      - gold:Gs0128849
> src/data/invalid/Biosample-missing-id.yaml:  - gold:Gs0110115
> src/data/invalid/Database-biosamples-rna-in-plate-no-well-val.yaml:      - gold:Gs0110115
> src/data/invalid/OmicsProcessing-invalid-omics-type.yaml:  - gold:Gp0108335
> src/data/invalid/OmicsProcessing-invalid-omics-type.yaml:  - gold:Gb0108335
> src/data/invalid/OmicsProcessing-invalid-omics-type.yaml:  - gold:Gs0112340
> src/data/invalid/Database-biosamples-lat_lon-with-GLV-missing-latitude.yaml:      - gold:Gs0110115
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gb0101224
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gb0101225
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gb0101225
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gb0101226
> src/data/invalid/Database-biosample_single_multi_value_mixup.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosamples-dna-in-bucket.yaml:      - gold:Gs0110115
> src/data/invalid/Database-biosample_undeclared_slot.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gb0101224
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_undeclared_slot.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gb0101225
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosample_undeclared_slot.yaml:    gold_biosample_identifiers:
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gb0101226
> src/data/invalid/Database-biosample_undeclared_slot.yaml:      - gold:Gs0128849
> src/data/invalid/Database-biosamples-rna-in-tube-with-well-value.yaml:      - gold:Gs0110115
> src/data/invalid/Biosample-incomplete_napa_id.yaml:gold_biosample_identifiers:
> src/data/invalid/Biosample-incomplete_napa_id.yaml:  - gold:Gb0101224
> src/data/invalid/Biosample-incomplete_napa_id.yaml:  - gold:Gs0110115
> src/data/invalid/Database-biosamples-dna-in-plate-invalid-well-val.yaml:      - gold:Gs0110115
> src/data/invalid/MetagenomeSequencingActivity-no_parthood.yaml:was_informed_by: gold:Gp0213371
> src/data/invalid/Database-biosamples-rna-in-bucket.yaml:      - gold:Gs0110115
> src/data/invalid/MetagenomeSequencingActivity-bad_id.yaml:was_informed_by: gold:Gp0213371
> src/data/invalid/Biosample-non_boolean_embargo.yaml:  - gold:Gs0110115
> src/data/invalid/Database-biosamples-dna-in-plate-no-well-val.yaml:      - gold:Gs0110115
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gp0108335
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gb0108335
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gs0112340
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gp0108340
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gb0108340
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gs0112340
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gp0108341
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gb0108341
> src/data/invalid/Database-invalid-omics-processing.yaml:      - gold:Gs0112340
> src/data/invalid/OmicsProcessing-no-id.yaml:  - gold:Gp0108335
> src/data/invalid/OmicsProcessing-no-id.yaml:  - gold:Gb0108335
> src/data/invalid/OmicsProcessing-no-id.yaml:  - gold:Gs0112340
> src/data/invalid/Biosample-invalid-embargoed.yaml:  - gold:Gs0110115
> src/data/valid/Database-biosamples-1.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-1.yaml:      - GOLD:Gb0101224
> src/data/valid/Database-biosamples-1.yaml:      - gold:Gs0110115
> src/data/valid/Database-biosamples-1.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-1.yaml:      - GOLD:Gb0101224
> src/data/valid/Database-biosamples-1.yaml:      - gold:Gs0110115
> src/data/valid/Database-biosamples-1.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-1.yaml:      - GOLD:Gb0101225
> src/data/valid/Database-biosamples-1.yaml:      - gold:Gs0110115
> src/data/valid/Database-biosamples-1.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-1.yaml:      - GOLD:Gb0101226
> src/data/valid/Database-biosamples-1.yaml:      - gold:Gs0110115
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0305833
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0291692
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0291582
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0305834
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0291693
> src/data/valid/Database-biosamples-sites.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-biosamples-sites.yaml:      - GOLD:Gb0291583
> src/data/valid/Database-mags-activities.yaml:    was_informed_by: gold:Gp0115663
> src/data/valid/Database-mags-activities.yaml:    was_informed_by: gold:Gp0115664
> src/data/valid/Study-exhaustive.yaml:gold_study_identifiers:
> src/data/valid/Study-exhaustive.yaml:  - GOLD:Gs12345
> src/data/valid/Study-exhaustive.yaml:  - GOLD:Gs90909
> src/data/valid/Database-biosamples-rna-in-tube.yaml:      - gold:Gs0110115
> src/data/valid/Database-multiple-paths.yaml:      - gold:Gs0110115
> src/data/valid/Database-multiple-paths.yaml:      - gold:Gs0110115
> src/data/valid/Database-multiple-paths.yaml:      - gold:Gp0108335
> src/data/valid/Database-multiple-paths.yaml:      - gold:Gb0108335
> src/data/valid/Database-multiple-paths.yaml:      - gold:Gs0112340
> src/data/valid/Database-metagenome-assembly.yaml:    was_informed_by: gold:Gp0061273
> src/data/valid/Database-metagenome-assembly.yaml:    was_informed_by: gold:Gp0061274
> src/data/valid/Database-metagenome-assembly.yaml:    was_informed_by: gold:Gp0061275
> src/data/valid/Database-omics-processings.yaml:      - gold:Gp0108335
> src/data/valid/Database-omics-processings.yaml:      - gold:Gb0108335
> src/data/valid/Database-omics-processings.yaml:      - gold:Gs0112340
> src/data/valid/Database-omics-processings.yaml:      - gold:Gp0108340
> src/data/valid/Database-omics-processings.yaml:      - gold:Gb0108340
> src/data/valid/Database-omics-processings.yaml:      - gold:Gs0112340
> src/data/valid/Database-omics-processings.yaml:      - gold:Gp0108341
> src/data/valid/Database-omics-processings.yaml:      - gold:Gb0108341
> src/data/valid/Database-omics-processings.yaml:      - gold:Gs0112340
> src/data/valid/Database-biosamples-rna-in-plate-valid-well-val.yaml:      - gold:Gs0110115
> src/data/valid/DataObject-1.yaml:description: Metagenome Contig Coverage Stats for gold:Gp0061273
> src/data/valid/Biosample-soil_horizon.yaml:  - gold:Gs0110115
> src/data/valid/ReadQcAnalysisActivity-1.yaml:was_informed_by: "gold:Gp0061273"
> src/data/valid/Database-biosamples-minimal.yaml:      - gold:Gs0110115
> src/data/valid/Biosample-exhasutive.yaml:gold_biosample_identifiers:
> src/data/valid/Biosample-exhasutive.yaml:  - GOLD:Gb123456789
> src/data/valid/Biosample-exhasutive.yaml:  - GOLD:Gb90909090
> src/data/valid/DataObject-2.yaml:description: Assembled scaffold fasta for gold:Gp0061273
> src/data/valid/Biosample-embargoed.yaml:  - gold:Gs0110115
> src/data/valid/Database-with-MetagenomeSequencingActivity.yaml:    was_informed_by: gold:Gp0213371
> src/data/valid/Biosample-minimal-2.yaml:  - gold:Gs0110115
> src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml:gold_biosample_identifiers:
> src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml:  - GOLD:Gb123456789
> src/data/valid/Biosample-exhaustive-issue-796-bye-yq-for-7-4-10.yaml:  - GOLD:Gb90909090
> src/data/valid/OmicsProcessing-1.yaml:  - gold:Gp0108335
> src/data/valid/OmicsProcessing-1.yaml:  - gold:Gb0108335
> src/data/valid/OmicsProcessing-1.yaml:  - gold:Gs0112340
> src/data/valid/Database-study-set-with-gnps-id.yaml:    gold_study_identifiers:
> src/data/valid/Database-study-set-with-gnps-id.yaml:      - GOLD:Gs0128849
> src/data/valid/DataObject-3.yaml:description: Metagenome Contig Coverage Stats for gold:Gp0061273
> src/data/valid/Database-nmdc-example.yaml:    gold_study_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0128849
> src/data/valid/Database-nmdc-example.yaml:    gold_study_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0130354
> src/data/valid/Database-nmdc-example.yaml:    gold_study_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0134277
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gp0225767
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0157174
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0130354
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gp0208560
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0150408
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0128849
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gp0306221
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0188037
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0134277
> src/data/valid/Database-nmdc-example.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0150408
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0128849
> src/data/valid/Database-nmdc-example.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0157174
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0128849
> src/data/valid/Database-nmdc-example.yaml:    gold_biosample_identifiers:
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gb0188037
> src/data/valid/Database-nmdc-example.yaml:      - GOLD:Gs0128849
> src/data/valid/Biosample-with-fire.yaml:  - gold:Gs0110115
> src/data/valid/Biosample-minimal.yaml:  - gold:Gs0110115
> src/data/valid/MetagenomeSequencingActivity-from-metagenome_seequencing_activity_json.yaml:was_informed_by: gold:Gp0213371
> src/data/valid/Database-biosamples-dna-in-tube.yaml:      - gold:Gs0110115
> src/data/valid/Database-biosamples-dna-in-plate-valid-well-val.yaml:      - gold:Gs0110115
>

**Comment by aclum** [comment]
@turbomam i think we can close this, all the gold prefixes are lowercase now.
