### ISSUE TITLE
has_input and has_inputs are both multivalued !?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#923]
- https://microbiomedata.github.io/nmdc-schema/has_input/
- https://microbiomedata.github.io/nmdc-schema/has_inputs/

**Comment by turbomam** [comment]
@aclum this applies to at least one of the issues we're working on in support of NEON right now. When I remember which one it is, I will link it :-)

**Comment by turbomam** [comment]
probably the library preparation issue

**Comment by turbomam** [comment]
Ack, it's the same for has_output ad has_outputs!

**Comment by aclum** [comment]
We were talking specifically about pooling where there should only be 1 output.
https://microbiomedata.github.io/nmdc-schema/Pooling/

This is enforced with cardinality but consider updating `has_outputs` to `has_output` for Class `Pooling` 
https://microbiomedata.github.io/nmdc-schema/Pooling/

**Comment by turbomam** [comment]
see also:
- #917
