### ISSUE TITLE
work on enum and permissible value names/texts

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#931]
- match the case expected by the linter, https://linkml.io/linkml/schemas/linter.html#standard-naming
- don't use any characters that are illegal in URLs or require excessive escaping: https://docs.microfocus.com/OMi/10.62/Content/OMi/ExtGuide/ExtApps/URL_encoding.htm

**Comment by Shalsh23** [comment]
Adding more context given by @turbomam in slack discussion:

This concerns enums  in all YAML files in `src/schema`, including `src/schema/portal`, but not including `src/schema/mixs.yaml`.

1. According to https://linkml.io/linkml/schemas/linter.html#standard-naming, the names/keys of the enums should be PascalCase/UpperCamelCase. `YesNoEnum` in `src/schema/nmdc.yaml` meets that standard, but the nearby `biosample_category_enum` doesn’t.
2. We should also to look for opportunities to consolidate enums with the same or virtually identical `permissible_values` . That requires a little more creativity or discretion. If you do find two enums with essentially the same permissible_values, then you could look for slots that use the to-be-deprecated enum in their range and switch it to the to-be-retained enum. The delete the definition of the to-be-deprecated enum.
3. If you pursue the second task above, you may see that there are lots of opportunities for consolidating enums in mixs.yaml, but I and a few other people from the Genomics Standards Consortium are working on totally regenerating the MIxS schema.
