### ISSUE TITLE
New NEON process classes should have start and end dates.

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#937]
Are they going to be real date values, or date strings? @pkalita-lbl is working on better support for real date and time objects within DataHarmonizer, but that won't be released for a while. 

Are end users going to enter instances of these processes in DataHarmonizer? If not, we could start using real dates now. Although that has some incompatibility with LinkML's SQL DDL conversion.

**Comment by aclum** [comment]
It would be useful if at some point in the future users could enter their own data in DataHarmonizer. For example, JGI users send extracted RNA and DNA so they may what to record. To some extend this is already happening in the overloading of Class Biosample (ie [dna_isolate_meth](https://microbiomedata.github.io/nmdc-schema/dna_isolate_meth/)

**Comment by aclum** [comment]
cc @mslarae13

**Comment by turbomam** [comment]
@aclum thanks for the update. Can you please give an example of how users can't enter their own data into DataHarmonizer? I thought that's exactly what they are doing in our DataPortal.

Are you saying that there are some new or implicit classes for which DataHarmonizer templates are required?

**Comment by turbomam** [comment]
Some existing date slots

Check ranges. See work @pkalita-lbl is doing on date format handling in DataHarmonizer.

slots with 'inc' in their names are about an incubation.

- add_date (about JGI records being added to a database?)
- collection_date
- collection_date_inc
- completion_date (no annotations. not associated with any class?)
- date_created (for nmdc-schema Database class)
- date_last_rain
- extraction_date **replace**
- iw_bt_date_well
- mod_date (about JGI records being added to a database?)
- processed_date **replace** (for LibraryPreparation class)
- prod_start_date
- start_date_inc

**Comment by turbomam** [comment]
@aclum and @mslarae13 are either `start_date` or `end_date` required for `LibraryPreparation` or `Extraction`?

**Comment by aclum** [comment]
@turbomam Not everything we are capturing with these new process classes is currently captured in DataHarmonizer. So DataHarmonizer templates aren't required currently but we'd want to add them at some point so people could provide more information about how their samples were processed. That work would get separate tickets when that is ready to be worked on for the submission portal. 
No, I don't think we should require `start_date` or `end_date` for `LibraryPreparation`, `Extraction`, or `Pooling`.
