### ISSUE TITLE
Semantics for AssociatedResearchers tab on Sample Metadata template?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#94]
This is one component of issue microbiomedata/nmdc-metadata#375

I have no idea how to reflect this kind of data in the NMDC schema.

Field | Sample value
-- | --
Name | Pajau Vangay
email | pvangay@lbl.gov
ORCiD | 0000-0002-9231-0692
Role- CRediT | Project   administration

**Comment by wdduncan** [comment]
Moving issue to `nmdc-schema` repo.

Question: Do we want a hierarchy of researchers? E.g.

researcher
  - investigator
    - co-investigator
    - principle investigator
 - other kinds of researchers?

In my experience, this would be sufficient:

investigator
    - co-investigator
    - principle investigator

but I don't know if this works in the environmental domain.

cc @cmungall

**Comment by turbomam** [comment]
investigator
- co-investigator
- principal investigator

is fine with me, but the NMDC Sample Metadata Template also captures a CRediT term relating the co-investigator to the study.

For now, I've modeled it as a list of dicts, as below.

Note that I've also used an undefined "email_address" slot.

```
{ 'id': 'GOLD:Gs01971387',
 'type': 'Study',
 'principal_investigator': {'has raw value': 'Montana Smith',
                            'orcid': '0000-0002-8683-0050'},
 'co-investigators': [{'credit': 'Project administration',
                             'co-investigator': {'email_address': 'pvangay@lbl.gov',
                                        'has_raw_value': 'Pajau Vangay',
                                        'orcid': '0000-0002-9231-0692'}}]
}
```

**Comment by turbomam** [comment]
https://microbiomedata.github.io/nmdc-schema/CreditAssociation/
