### ISSUE TITLE
should Biosample.slot_usage.slot_usage include range: Study?

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-schema#940]
https://github.com/microbiomedata/nmdc-schema/blob/96d79193d5c38283e025dcb979e5c092c6345ed3/src/schema/nmdc.yaml#L1074

**Comment by turbomam** [comment]
Do you mean the `range` for `part_of`, when used in class `Biosample`, should be `Study`?

I would agree with that.

**Comment by dwinston** [comment]
Yes, that’s what I mean.
