### ISSUE TITLE
instrument_name_enum

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#984]

**Comment by turbomam** [comment]
see also `used`

**Comment by mslarae13** [comment]
Enum exists. need to populate permissible values for both vendor and model

Two separate enums of Insrument class

@corilo and @SamuelPurvine will work on and help with this

**Comment by mslarae13** [comment]
Class:Instrument

Has Model and Vendor enums

Need to capture the EXACT instrument
(Example: I have 3 FTICR-MS ... I need to know that this data is from FTICR.. but ALSO this data set is from FTICR-A and this is from FTICR-B)

Consider re-adding instrument_name or need a way to capture exact instrument that is minimally disruptive when new instruments are used / data is provided from new instruments ... but is not error prone... string means it's easy for people to say instrument A is instrument 1. but they're the same

**Comment by kheal** [comment]
This has been refactored to use the `Instrument` class.  See https://github.com/microbiomedata/berkeley-schema-fy24/pull/38.
