### ISSUE TITLE
MongoDB data repair and schema loosening. DON'T FORGET TO RESOTRE THE `id`'s `strucutred_patterns` like 'syntax: "{id_nmdc_prefix}:'...

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#987]
Moved some previously invalid example data files due to permanent or temporary schema changes. For example

- date slots that had the datetime range removed and only undergo pattern validation
- `id`s, which had their structured patterns commented out in this branch but should be kept in main/all releases

```
renamed:    src/data/invalid/Database-nom_analysis_activity_set-invalid-string-ended_at_time.yaml -> src/data/uncertain/Database-nom_analysis_activity_set-invalid-string-ended_at_time.yaml
renamed:    src/data/invalid/Database-nom_analysis_activity_set-non-string-ended_at_time.yaml -> src/data/uncertain/Database-nom_analysis_activity_set-non-string-ended_at_time.yaml
renamed:    src/data/invalid/MetagenomeSequencingActivity-bad_id.yaml -> src/data/uncertain/MetagenomeSequencingActivity-bad_id.yaml
```

**Goal**: it should be possible to move all example data files in `src/data/uncertain/` and `src/data/unexpected_pass/` into either `src/data/valid/` or `src/data/invalid`. That may require changes to the data, to the nmdc-schema, or to LinkML.

**Comment by turbomam** [comment]
Added the following targets to `project.Makefile`
- local/mongodb-collection-report.txt
- local/selected_mongodb_contents.json
- dump-validate-report-convert-mongodb
- mongodb-cleanup
- local/selected_mongodb_contents_jsonschema_check.txt
- linkml-validate-mongodb
- local/selected_mongodb_contents.yaml
- local/selected_mongodb_contents.ttl

**Comment by turbomam** [comment]
Removed `id`'s `structured_pattern`s on several classes in src/schema/core.yaml. For lenience with legacy `id`s in MongoDB. Should be reintroduced for production/main/release.

Added a pattern for `id` in `PlannedProcess`
 
```
slot_usage:
   id:
     pattern: '^[a-zA-Z0-9][a-zA-Z0-9_\.]+:[a-zA-Z0-9_][a-zA-Z0-9_\-\/\.]*$'
```

**Comment by turbomam** [comment]
Loosened `pattern`s in src/schema/external_identifiers.yaml

old: pattern: '^[a-zA-Z0-9][a-zA-Z0-9_\.]+:[a-zA-Z0-9_][a-zA-Z0-9_\/\.]*$'

new: pattern: '^[a-zA-Z0-9][a-zA-Z0-9_\.]+:[a-zA-Z0-9_][a-zA-Z0-9_\-\/\.]*$'

renamed  `external identifier` type to `external_identifier`

**Comment by turbomam** [comment]
Removed id's structured_patterns on several classes in src/schema/prov.yaml. For lenience with legacy ids in MongoDB. Should be reintroduced for production/main/release.

changed range of  `started_at_time` and `ended_at_time` from `datetime` to (implicit?) `string`.

**Comment by turbomam** [comment]
Removed id's structured_patterns on several classes in `src/schema/sample_prep.yaml`. For lenience with legacy ids in MongoDB. Should be reintroduced for production/main/release.

**Comment by turbomam** [comment]
Removed `id`'s `structured_pattern`s on several classes in `src/schema/workflow_execution_activity.yaml`. For lenience with legacy ids in MongoDB. Should be reintroduced for production/main/release.

**Comment by aclum** [comment]
Is this complete?
