### ISSUE TITLE
S4G3 - Review and test GOLD API for NMDC

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-schema#99]
Will turn into issue if the API is ready for testing and assign to Bill per discussions with David H.

**Comment by ssarrafan** [comment]
@wdduncan we should be getting an update on Thursday on this API.  I'm not sure when it will be available for you to review but I'm adding it to August just in case. 

@elishawc 
@dehays

**Comment by ssarrafan** [comment]
@wdduncan @emileyfadrosh since Reddy did his presentation does the API still need to be reviewed by Bill?  Or should this ticket be closed and a new one opened to address the GOLD API issue?

**Comment by emileyfadrosh** [comment]
This ticket can be closed as this has been discussed over email. @ssarrafan I will follow up separately with a set of follow-on tasks, thanks!

**Comment by emileyfadrosh** [comment]
I reviewed the new GOLD API for the NMDC (details [here](https://github.com/microbiomedata/nmdc-schema/issues/99)) and have requested ~50 additional fields of relevance that will be needed going forward. This additional list of fields is attached here. Thanks!
[IMG-API-fields-8-17-2021.txt](https://github.com/microbiomedata/nmdc-schema/files/7002954/IMG-API-fields-8-17-2021.txt)

**Comment by ssarrafan** [comment]
@emileyfadrosh and @wdduncan I'm adding the backlog label to this. Let me know if it should be moved to the September sprint instead.

**Comment by ssarrafan** [comment]
After discussing with @emileyfadrosh and email with @wdduncan I'm adding this issue to the September sprint and removing the backlog label.

**Comment by cmungall** [comment]
How is this different from #136 ?

**Comment by ssarrafan** [comment]
Closing this as it's the same as #136
