### ISSUE TITLE
Sample Operations Slot descriptions

### ISSUE THREAD

**Issue by anastasiyaprymolenna** [microbiomedata/nmdc-schema#998]
Sample Operations need standard slot descriptions according to existing nmdc schema slots
defining terms could be done by ourselves or leveraging NIST approved definitions (https://www.nist.gov/bioscience/nist-bioeconomy-lexicon)

**Comment by turbomam** [comment]
Is 'Sample Operations' a leaf class, or does it have subclasses?  What's it's official slot name in the branch you and @JamesTessmer are working in?

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/nmdc-schema/blob/issue-907-metabolink/linkml/SampleOperations.yaml

to add slot descriptions, reference : https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/prov.yaml
